import type { PlacementItemDef } from "../types";
import { item, talk } from "./shared";

/** Listening: a short recording (Piper TTS from the script) and one question. The script is shown only in the review sheet. */
export const listeningItems: PlacementItemDef[] = [
  item("LISTENING", "A1", 1, "What is the man's name?", ["David", "Daniel", "Dennis", "Davis"], 0, "He spells it: D-A-V-I-D.", { script: talk("Woman: Hello. What's your name?", "Man: My name is David. D-A-V-I-D.") }),
  item("LISTENING", "A1", 2, "How much is the T-shirt?", ["$20", "$12", "$2", "$15"], 1, "\"It's twelve dollars.\"", { script: talk("Man: Excuse me, how much is this T-shirt?", "Woman: It's twelve dollars.") }),
  item("LISTENING", "A1", 3, "What time does the bus leave?", ["7:00", "6:30", "7:30", "7:15"], 2, "\"At half past seven\" is 7:30.", { script: talk("Woman: What time does the bus leave?", "Man: At half past seven.") }),
  item("LISTENING", "A1", 4, "Where is the bag?", ["On the bed", "In the kitchen", "Behind the door", "Under the bed"], 3, "\"It's under your bed.\"", { script: talk("Boy: Mum, where's my bag?", "Woman: It's under your bed.") }),

  item("LISTENING", "A2", 1, "Why can't the man go to the cinema tonight?", ["He has to finish his homework.", "He doesn't like films.", "He has no money.", "He is going with other friends."], 0, "\"I have to finish my homework.\"", { script: talk("Woman: Are you coming to the cinema tonight?", "Man: I'd love to, but I have to finish my homework. What about tomorrow?") }),
  item("LISTENING", "A2", 2, "When is the new appointment?", ["Tuesday at three o'clock", "Thursday at three o'clock", "Thursday at two o'clock", "Tuesday at one o'clock"], 1, "He moves it from Tuesday to Thursday; three o'clock is free.", { script: talk("Man: Good morning. I'd like to change my appointment from Tuesday to Thursday, please.", "Woman: Thursday at three o'clock is free. Is that OK?", "Man: Perfect, thanks.") }),
  item("LISTENING", "A2", 3, "Where is the train station?", ["Next to the bank", "Behind the park", "Opposite the park", "On the right after the bank"], 2, "\"The station is opposite the park.\"", { script: talk("Woman: Excuse me, how do I get to the train station?", "Man: Go straight on, then turn left at the bank. The station is opposite the park.") }),
  item("LISTENING", "A2", 4, "What has changed?", ["The time", "The destination", "The price", "The platform"], 3, "The train leaves from platform four, not two.", { script: "Attention, please. The eleven fifteen train to Hanoi will leave from platform four, not platform two. We are sorry for the change." }),

  item("LISTENING", "B1", 1, "What was disappointing about the holiday?", ["The rain stopped them doing a long walk.", "The scenery", "The hotel", "The long journey"], 0, "It rained almost every day, so they couldn't do the walk.", { script: talk("Man: How was your holiday in Sa Pa?", "Woman: The scenery was amazing, but it rained almost every day, so we couldn't do the long walk we'd planned.") }),
  item("LISTENING", "B1", 2, "What advice does the man give?", ["Buy a car instead", "Check how far it goes on one charge", "Only use it for long trips", "Buy the cheapest one"], 1, "\"Check how far it goes on one charge.\"", { script: talk("Woman: I'm thinking of buying an electric scooter.", "Man: They're great for short trips, but check how far it goes on one charge. Mine only does about twenty kilometres.") }),
  item("LISTENING", "B1", 3, "What are visitors asked not to do?", ["Take photos", "Visit the cloakroom", "Use flash in the painting galleries", "Bring small bags"], 2, "Photos are allowed, but not flash in the painting galleries.", { script: "Welcome to the museum. Before you start, please leave large bags at the cloakroom on your right. Photos are allowed, but please don't use flash in the painting galleries." }),
  item("LISTENING", "B1", 4, "What will the woman do first?", ["Apply for the job now", "Move to France", "Ask for a different job", "Take a French course"], 3, "She will take a course first and apply next year.", { script: talk("Man: Did you apply for the marketing job?", "Woman: I was going to, but it says you need to speak French, so I've decided to take a course first and apply next year.") }),

  item("LISTENING", "B2", 1, "Why has the deadline changed?", ["The client has asked for more data.", "The survey was lost.", "The man is ill.", "Friday is a holiday."], 0, "The client asked for extra data, so the deadline moved.", { script: talk("Woman: The report's due on Friday, isn't it?", "Man: It was, but the client has asked for extra data, so the deadline's been pushed back a week. Mind you, that means we'll need to run the survey again.") }),
  item("LISTENING", "B2", 2, "What do the researchers point out?", ["Walking must be done in the morning.", "The study shows a link, not that walking causes better sleep.", "Only young adults took part.", "Walking for longer is harmful."], 1, "They stress it shows a link rather than proving cause.", { script: "Researchers following two thousand adults found that those who walked for at least twenty minutes a day slept better, whatever time of day they exercised. However, the researchers stress that the study shows a link, rather than proving that walking causes better sleep." }),
  item("LISTENING", "B2", 3, "Why did the woman refuse the promotion?", ["The salary was too low.", "She didn't like the climate in Singapore.", "She wants to stay close to her parents.", "She is planning to retire."], 2, "With her parents getting older, she'd rather stay close by.", { script: talk("Man: I hear you turned down the promotion.", "Woman: I did. The salary was better, but it would have meant moving to Singapore, and with my parents getting older, I'd rather stay close by.") }),
  item("LISTENING", "B2", 4, "What does the man suggest?", ["Booking the largest room now", "Cancelling the conference", "Inviting more speakers", "Waiting until the speakers confirm"], 3, "\"I'd hold off\" until the speakers confirm.", { script: talk("Woman: Shall we book the conference venue now?", "Man: I'd hold off. Two of the speakers haven't confirmed yet, and if they drop out, we might only need a smaller room.") }),

  item("LISTENING", "C1", 1, "What point does the speaker make?", ["Bilingual children's total vocabulary is similar to other children's.", "Bilingual children learn to speak much later.", "Monolingual children know more words.", "Children should learn one language first."], 0, "Counting both languages, their vocabulary is comparable.", { script: "It's often said that bilingual children are slower to start speaking. In fact, when you count the words they know in both languages together, their vocabulary is typically comparable to that of children who speak only one language." }),
  item("LISTENING", "C1", 2, "What is the woman's attitude to the proposal?", ["She rejects it completely.", "She supports the idea but doubts how it would be funded.", "She wants to cut the training budget.", "She thinks it is too cheap."], 1, "\"In principle, yes\", but she can't see how to fund it.", { script: talk("Man: So, are you backing Linh's proposal?", "Woman: In principle, yes. I just can't see how we'd fund it without cutting the training budget, and that's a price I'm not sure I'm willing to pay.") }),
  item("LISTENING", "C1", 3, "What does the speaker find most significant?", ["The low cost", "The fast construction", "The sensors that monitor the structure", "The shape of the bridge"], 2, "\"What's really caught engineers' attention is the sensors.\"", { script: "The bridge was completed on time and under budget, which is remarkable in itself. But what's really caught engineers' attention is the sensors built into its structure, which report stress levels in real time and could change the way bridges are maintained." }),
  item("LISTENING", "C1", 4, "What does the man imply about the software?", ["It is excellent.", "Planning now takes longer.", "Nobody uses it.", "The time it saves is lost fixing its mistakes."], 3, "People spend so long fixing its mistakes that there is no overall gain.", { script: talk("Woman: Did the new scheduling software save any time?", "Man: On paper, yes: planning takes half as long. But people spend so long fixing its mistakes that I doubt we're any better off overall.") }),

  item("LISTENING", "C2", 1, "What is the speaker's view of the exhibition's lavish style?", ["It is intentional and part of the message.", "It hides a lack of content.", "It is too expensive.", "It copies luxury brands without comment."], 0, "The lavish presentation \"is itself the commentary\".", { script: "Critics have been quick to label the exhibition a triumph of style over substance. I'd argue that's rather missing the point: the lavish presentation is itself the commentary, a deliberate parody of the luxury brands the artist is dissecting." }),
  item("LISTENING", "C2", 2, "How does the woman feel about the new strategy?", ["It has clearly failed.", "It is too early to judge it.", "It is a great success.", "It should be stopped now."], 1, "She stops short of calling it a failure: \"It's early days.\"", { script: talk("Man: Well, the figures are hardly a ringing endorsement of the new strategy.", "Woman: No, though I'd stop short of calling it a failure. It's early days, and half the stores only switched over last month.") }),
  item("LISTENING", "C2", 3, "What idea is the speaker challenging?", ["That religious texts were important", "That the press was invented earlier", "That printing quickly spread knowledge to everyone", "That cities had low literacy"], 2, "The received wisdom that printing democratised knowledge overnight.", { script: "The received wisdom is that the printing press democratised knowledge overnight. The reality was messier: for decades, printers favoured profitable religious and legal texts, and literacy rates barely moved outside the cities." }),
  item("LISTENING", "C2", 4, "What is the man suggesting?", ["The merger will be blocked.", "The senior team strongly supports the merger.", "The merger will happen very slowly.", "Many senior staff may leave after the merger."], 3, "Half the senior team are \"quietly updating their CVs\".", { script: talk("Woman: You don't think the merger will go through?", "Man: Oh, it'll go through. The question is whether anyone will still be around to run it once the dust settles. Half the senior team are already quietly updating their CVs.") })
];
