import type { PlacementItemDef } from "../types";
import { item } from "./shared";

/** Reading: one short text and one question; texts grow longer and more implicit with the level. */
export const readingItems: PlacementItemDef[] = [
  item("READING", "A1", 1, "How does Lan go to school?", ["By bike", "By bus", "On foot", "By car"], 0, "\"I go to school by bike.\"", { passage: "Hi, I'm Lan. I live in Hue with my mother and two brothers. I go to school by bike. After school, I play badminton with my friends." }),
  item("READING", "A1", 2, "When can you visit the library?", ["On Saturday morning", "On Tuesday at 10 a.m.", "On Sunday afternoon", "On Friday at 7 p.m."], 1, "Open Monday to Friday, 8 a.m. to 6 p.m.", { passage: "CITY LIBRARY\nOpen Monday to Friday, 8 a.m. to 6 p.m.\nClosed on Saturday and Sunday." }),
  item("READING", "A1", 3, "Who is making the cake?", ["Tom", "Tom's friends", "Tom's dad", "Tom's mum"], 2, "\"His dad is making a big chocolate cake.\"", { passage: "Tom's birthday is on Sunday. He wants a party at home. His dad is making a big chocolate cake, and his friends are bringing pizza." }),
  item("READING", "A1", 4, "Why does Mum send this message?", ["She is lost.", "She wants Mai to cook dinner.", "She needs money.", "She wants to know what to buy."], 3, "She asks whether they need milk or eggs.", { passage: "Mai, I'm at the supermarket. Do we need milk or eggs? Please call me. — Mum" }),

  item("READING", "A2", 1, "What is the main purpose of the email?", ["To explain why she will be absent", "To book a doctor's appointment", "To ask for a new job", "To invite Mr Hall to a meeting"], 0, "She says she can't come to work because of an appointment.", { passage: "Dear Mr Hall,\nI'm sorry, but I can't come to work tomorrow. I have a doctor's appointment at 10 a.m. I will be back in the office on Thursday.\nBest wishes,\nNga" }),
  item("READING", "A2", 2, "What do you get for $80?", ["Only the bike", "A bike, a lock and a helmet", "A bike and a phone", "Two bikes"], 1, "\"The price includes a lock and a helmet.\"", { passage: "Bike for sale. Only one year old, red, in very good condition. $80. The price includes a lock and a helmet. Call Minh after 6 p.m." }),
  item("READING", "A2", 3, "What was good about Hoa's summer job?", ["She finished work early.", "The work was easy.", "She practised her English.", "She lived next to the café."], 2, "She improved her English by talking with tourists.", { passage: "Last summer, Hoa worked in a café by the beach. The work was hard, and she often finished at midnight, but she made many new friends and improved her English by talking to tourists." }),
  item("READING", "A2", 4, "What must everyone do before swimming?", ["Bring an adult", "Eat something", "Buy a drink", "Take a shower"], 3, "\"Please shower before swimming\" applies to everyone; the adult rule is only for children.", { passage: "SWIMMING POOL RULES\nChildren under 10 must be with an adult.\nPlease shower before swimming.\nNo food or drinks in the pool area." }),

  item("READING", "B1", 1, "What problem do some home workers mention?", ["They find it hard to stop working in the evening.", "Their journey takes too long.", "Their office is too small.", "They do not have enough work."], 0, "Their home has become their office, so they find it harder to stop.", { passage: "Many people think working from home saves time, and it often does: there is no journey to the office. However, some workers say they find it harder to stop working in the evening, because their home has become their office." }),
  item("READING", "B1", 2, "What did the reviewer NOT like?", ["The food", "The slow service", "The prices", "The location"], 1, "\"The only problem is the service: we waited 40 minutes.\"", { passage: "The Green Bowl is a new vegetarian restaurant in the city centre. The food is fresh and tasty, and the prices are reasonable. The only problem is the service: we waited 40 minutes for our main course." }),
  item("READING", "B1", 3, "Why was Viet asked to give another presentation?", ["He wanted more practice.", "His manager was ill.", "His first presentation went very well.", "Nobody else wanted to do it."], 2, "The presentation went so well that he was asked to give another.", { passage: "Viet had always been afraid of speaking in public. When his manager asked him to present the project, he nearly said no. Instead, he practised every evening for a week, and the presentation went so well that he was asked to give another one." }),
  item("READING", "B1", 4, "What should visitors bring to use the app?", ["A printed guide", "A tablet from the museum", "Money for the download", "Their own headphones"], 3, "The app is free, but visitors need their own headphones.", { passage: "The museum's new app lets visitors listen to information about each painting in six languages. It is free to download, but visitors need to bring their own headphones." }),

  item("READING", "B2", 1, "What do the critics say?", ["The idea may not work in every type of job.", "Office staff are not productive.", "Workers do not need more rest.", "Hospitals should close one day a week."], 0, "Critics point out that hospitals and shops cannot simply close.", { passage: "Supporters of a four-day working week argue that staff become more productive when they have more time to rest. Critics accept that this may be true in offices, but point out that hospitals and shops cannot simply close for an extra day." }),
  item("READING", "B2", 2, "According to the text, why has traffic got worse?", ["Bus fares have risen sharply.", "The bus network has not grown with the population.", "Residents dislike buses.", "The roads are too narrow."], 1, "The population doubled but the bus network hardly changed, so people drive.", { passage: "Although the town's population has doubled in twenty years, its bus network has hardly changed. As a result, many residents who could use public transport choose to drive, which in turn has made the traffic worse." }),
  item("READING", "B2", 3, "What is the writer's main point?", ["Recycling plastic is impossible.", "Plastic should be recycled more times.", "Using less plastic matters more than recycling it.", "Recycling is the best solution to plastic waste."], 2, "\"Reducing how much we use … is therefore far more effective.\"", { passage: "It is tempting to see recycling as the solution to plastic waste. Yet only a small share of the plastic produced is ever recycled, and much of it can be recycled only once or twice. Reducing how much we use in the first place is therefore far more effective." }),
  item("READING", "B2", 4, "How was the managers' concern solved?", ["Meetings were cancelled.", "Flexible hours were stopped.", "Managers held meetings in the evening.", "Teams agreed on hours when everyone is available."], 3, "Teams agreed on a few 'core hours' each day.", { passage: "When the company introduced flexible hours, managers feared that meetings would be impossible to organise. In practice, teams agreed on a few 'core hours' each day when everyone is available, and the problem largely disappeared." }),

  item("READING", "C1", 1, "What concern does the passage raise?", ["Short, frequent contact may replace deeper conversation.", "People now have fewer friends online.", "Social media makes contact harder.", "Researchers disagree about friendship."], 0, "Brief exchanges may replace the deeper conversations friendships depend on.", { passage: "Few would dispute that social media has made it easier to stay in touch. What is less often acknowledged is how it has changed the nature of those contacts: frequent but brief exchanges may, some researchers suggest, gradually replace the deeper conversations on which close friendships depend." }),
  item("READING", "C1", 2, "What does the writer suggest about the museum's decision?", ["It was forced on the museum by the media.", "It had been under discussion long before the campaign.", "It was made reluctantly.", "It was kept secret from the country of origin."], 1, "Talks had begun several years before the campaign drew attention.", { passage: "The museum's decision to return the statue was not, as some commentators claimed, a reluctant response to public pressure. Internal documents show that talks with the statue's country of origin had begun several years before the campaign attracted media attention." }),
  item("READING", "C1", 3, "What assumption does the passage refer to?", ["That city dwellers dislike banks", "That mobile phones are expensive", "That remote areas are the last to adopt new technology", "That villages have many bank branches"], 2, "Remote villages \"were long assumed to be the last to benefit\".", { passage: "Remote villages were long assumed to be the last to benefit from new technology. Mobile banking has turned that assumption on its head: in several countries, people without access to a bank branch adopted phone payments faster than city dwellers who already had bank accounts." }),
  item("READING", "C1", 4, "What is the defenders' argument?", ["Tests make teaching more varied.", "Teachers should ignore exams.", "Tests should be removed from schools.", "A common test is needed to identify failing schools."], 3, "Without a common measure it is impossible to identify failing schools.", { passage: "Critics of standardised testing argue that it narrows the curriculum, as teachers understandably focus on what will be examined. Defenders counter that without a common measure it becomes impossible to identify schools that are failing their students." }),

  item("READING", "C2", 1, "How does the writer view the digressions in the later novels?", ["As a deliberate way of representing memory", "As evidence of a lack of discipline", "As a sign of self-indulgence", "As a return to chronological storytelling"], 0, "The digressions \"assemble into a portrait of memory itself\".", { passage: "The novelist's later work has been dismissed as self-indulgent, yet such criticism arguably misreads her intentions. The apparent digressions, far from being lapses of discipline, gradually assemble into a portrait of memory itself: fragmentary, recursive and stubbornly resistant to chronology." }),
  item("READING", "C2", 2, "What do critics infer from the policy makers' silence?", ["That emissions were not reduced", "That they accept the policy was costly for poorer households", "That the policy was cheap to run", "That the critics had misunderstood the policy"], 1, "The silence is read as a \"tacit admission\" about the burden on low-income households.", { passage: "That the policy reduced emissions is beyond dispute; whether it did so at an acceptable cost is another matter entirely. Its architects have been curiously reticent about the burden placed on low-income households, a silence that critics are quick to interpret as tacit admission." }),
  item("READING", "C2", 3, "What is the writer's main criticism?", ["Cities collect too little data.", "Technical experts should make political decisions.", "Choices about data are presented as neutral when they are not.", "Smart cities are impossible to build."], 2, "Choosing what to measure is a political judgement \"masquerading\" as a technical one.", { passage: "Much of the enthusiasm for 'smart cities' rests on the premise that more data inevitably yields better decisions. Yet data, however abundant, does not interpret itself; the choices about what to measure, and what to ignore, are themselves political judgements masquerading as technical ones." }),
  item("READING", "C2", 4, "What unintended effect of digitisation does the writer point out?", ["Fewer people could access the archive.", "The original documents were damaged.", "The cataloguers lost their jobs.", "The online collection repeated old judgements about what mattered."], 3, "Only 'significant' documents were scanned, reproducing the cataloguers' hierarchies.", { passage: "The archive's digitisation was hailed as democratising access to history. Less remarked upon was the fact that only documents deemed 'significant' were scanned, so the online collection inadvertently reproduced the very hierarchies of the original cataloguers." })
];
