import { lq, type LessonDef } from "../types";

const C1 = "Skills for advanced users";
const C2 = "Skills for expert users";

const tip = (body: string) => ({ kind: "text" as const, heading: "Listening tip", body });
const before = (body: string) => ({ kind: "text" as const, heading: "Before you read", body });

/** More C1–C2 listening and reading lessons (English 4 Free original). */
export const moreSkillsC: LessonDef[] = [
  {
    key: "more:c1:listening-ai-panel", batch: "lessons", level: "C1", unit: C1, slug: "listening-a-panel-on-ai-in-the-classroom", title: "Listen: a panel on AI in the classroom", skill: "LISTENING", minutes: 19,
    blocks: [
      tip("In panel discussions, speakers often partly agree before disagreeing ('I take the point, but…'). Track each speaker's position, and notice when someone changes or refines their view during the discussion."),
      { kind: "listening", heading: "Panel discussion: should students use AI tools?", voices: { Chair: "male", Hanh: "female", Marcus: "male" }, script: "Chair: Our question tonight: should schools allow students to use AI writing tools? Ms Hanh, you're a secondary school teacher.\nHanh: I'd say yes, with conditions. Banning these tools simply drives their use underground. Students use them anyway, just without guidance. I'd rather teach them to use AI the way we once taught them to use search engines: critically.\nChair: Marcus, you run a tutoring company.\nMarcus: I take the point about guidance, but I'm more cautious. Writing isn't only a way of showing what you know; it's how you work out what you think. If a tool produces a fluent paragraph in seconds, students may skip the thinking altogether.\nHanh: That's a fair concern, and it's why I change the tasks rather than the rules. If students hand in only a final essay, AI can do most of it. If they also submit their notes, an outline and a short reflection on how they revised, the thinking becomes visible.\nMarcus: That's more convincing than a blanket permission, I'll admit. My worry is the students who aren't confident yet. For them, the temptation to let the tool do everything is strongest.\nChair: So where do you both land?\nMarcus: Allow it for older students, with assessment designed around the process. For beginners, I'd still limit it.\nHanh: I can live with that. Though I'd add that teachers need training too — most of us are learning this at the same time as our students." },
      { kind: "practice", instruction: "Listen and choose the best answer.", questions: [
        lq("Why does Hanh oppose banning AI tools?", ["Bans push students to use them without guidance.", "AI tools are always accurate.", "Students prefer search engines."], 0, "Banning these tools simply drives their use underground."),
        lq("What is Marcus's main concern?", ["AI tools are too expensive.", "Students may skip the thinking that writing involves.", "Teachers will lose their jobs."], 1, "Writing is how you work out what you think… students may skip the thinking."),
        lq("How does Hanh respond to Marcus's concern?", ["She changes the tasks so the process is visible.", "She bans essays completely.", "She says the concern is wrong."], 0, "Notes, an outline and a reflection make the thinking visible."),
        lq("What does 'That's more convincing than a blanket permission' show about Marcus?", ["He rejects Hanh's view entirely.", "He partly accepts Hanh's approach.", "He has stopped listening."], 1, "He concedes that her approach is more convincing."),
        lq("Which students worry Marcus most?", ["Older students", "Students who are not yet confident", "Students who write slowly"], 1, "My worry is the students who aren't confident yet."),
        lq("What do the speakers agree on by the end?", ["AI should be banned for everyone.", "Older students may use AI with process-based assessment.", "Teachers need no training."], 1, "Allow it for older students… Hanh: I can live with that.")
      ] }
    ]
  },
  {
    key: "more:c1:listening-coral-reefs", batch: "lessons", level: "C1", unit: C1, slug: "listening-a-lecture-on-coral-reefs", title: "Listen: a lecture on coral reefs", skill: "LISTENING", minutes: 19,
    blocks: [
      tip("Academic lectures move from definition to cause to consequence. Listen for cause-and-effect language: 'as a result', 'this triggers', 'which in turn'. Writing short arrows (→) in your notes makes the chain of causes easy to review."),
      { kind: "listening", heading: "Lecture: why coral reefs turn white", voices: { Lecturer: "male" }, script: "Lecturer: Let's start with something that surprises many people: corals are animals, not plants. A coral reef is built by colonies of tiny animals called polyps, which produce a hard skeleton of calcium carbonate.\nMost reef-building corals live in partnership with microscopic algae that live inside their tissue. The algae use sunlight to make food, and they share much of it with the coral. In return, the coral provides shelter. The algae also give corals much of their colour.\nNow, this partnership is sensitive to temperature. When the water stays even a degree or two warmer than usual for several weeks, the relationship breaks down. The coral expels the algae, and as a result it loses its colour — revealing the white skeleton underneath. This is what we call coral bleaching.\nA bleached coral is not necessarily dead. If temperatures return to normal fairly quickly, the algae can return and the coral can recover. But if the heat lasts too long, the coral starves, which in turn affects the whole reef community.\nAnd that community is remarkable. Reefs cover a tiny fraction of the ocean floor, yet a large share of marine species depend on them at some stage of their lives. They also protect coastlines from waves and support fishing and tourism for millions of people.\nSo when we talk about protecting reefs, we are talking about water temperature first of all, but also about reducing pollution and overfishing, which make it harder for reefs to recover between heat events." },
      { kind: "practice", instruction: "Listen and choose the best answer.", questions: [
        lq("What surprising fact does the lecturer begin with?", ["Corals are animals.", "Corals live in fresh water.", "Corals are a type of algae."], 0, "Corals are animals, not plants."),
        lq("What do the algae provide for the coral?", ["Shelter", "Food made using sunlight", "A hard skeleton"], 1, "The algae use sunlight to make food and share it with the coral."),
        lq("What triggers coral bleaching?", ["Water that stays warmer than usual for weeks", "Very cold water for one day", "Too much sunlight at night"], 0, "Even a degree or two warmer for several weeks."),
        lq("Why does a bleached coral look white?", ["It has died immediately.", "It has expelled the algae, revealing its skeleton.", "It is covered in salt."], 1, "The coral expels the algae… revealing the white skeleton."),
        lq("Under what condition can a bleached coral recover?", ["If temperatures return to normal fairly quickly", "If more fish arrive", "If the reef is moved"], 0, "If temperatures return to normal fairly quickly, the algae can return."),
        lq("Why does the lecturer mention pollution and overfishing?", ["They are the main cause of bleaching.", "They make it harder for reefs to recover.", "They help reefs grow faster."], 1, "They make it harder for reefs to recover between heat events.")
      ] }
    ]
  },
  {
    key: "more:c1:reading-street-food", batch: "lessons", level: "C1", unit: C1, slug: "reading-the-economics-of-street-food", title: "Read: the economics of street food", skill: "READING", minutes: 19,
    blocks: [
      before("C1 articles often combine description with analysis. As you read, separate what the writer reports (facts, examples) from what the writer interprets (claims about causes and consequences)."),
      { kind: "text", heading: "Article", body: "To a visitor, a street-food stall may look like the simplest business imaginable: a cart, a stove, a few plastic stools. Look more closely, however, and you find an economic model of considerable sophistication.\n\nConsider costs. A stall pays little or no rent, has almost no equipment to depreciate and often relies on family labour. This allows prices that restaurants cannot match. But low costs are only half the story. Successful vendors specialise ruthlessly. A stall that sells only one dish — a single kind of noodle soup, say — can buy ingredients in bulk, prepare them in advance and serve a customer in under a minute. Specialisation turns a tiny kitchen into a remarkably efficient production line.\n\nLocation and timing complete the model. Vendors cluster where customers already are: outside schools at lunchtime, near offices in the early morning, along busy streets in the evening. Some stalls operate for only three or four hours a day, yet sell more in that time than a restaurant does all afternoon. Reputation, built through daily repeat customers, does the work that advertising does for larger businesses.\n\nThe model has its vulnerabilities. Vendors rarely have savings, insurance or legal security, and a change in city regulations can remove their livelihood overnight. Rising rents in central districts push stalls further out, away from their customers. And as cities modernise, there is a temptation to treat street food as untidy — something to be cleared away rather than supported.\n\nThat would be a mistake. Street food provides affordable meals for millions of workers, employs people with few other options and gives cities much of their character. The challenge for policymakers is to make stalls safer and more secure without destroying the low costs and flexibility that make them work." },
      { kind: "practice", instruction: "Read the article and choose the best answer.", questions: [
        lq("What is the writer's main claim in paragraph 1?", ["Street-food stalls are simple businesses.", "Street-food stalls have a sophisticated economic model.", "Visitors dislike street food."], 1, "You find an economic model of considerable sophistication."),
        lq("According to paragraph 2, why does specialisation matter?", ["It makes the stall look attractive.", "It allows bulk buying, advance preparation and very fast service.", "It increases rent."], 1, "Buy in bulk, prepare in advance, serve in under a minute."),
        lq("What replaces advertising for vendors?", ["Social media", "Reputation built through repeat customers", "Low prices alone"], 1, "Reputation… does the work that advertising does."),
        lq("Which is described as a vulnerability of the model?", ["Too many customers", "Lack of savings, insurance and legal security", "High equipment costs"], 1, "Vendors rarely have savings, insurance or legal security."),
        lq("What attitude does the writer criticise in paragraph 4?", ["Treating street food as untidy and clearing it away", "Supporting vendors with training", "Eating street food every day"], 0, "A temptation to treat street food as untidy — something to be cleared away."),
        lq("What does the writer think policymakers should do?", ["Ban street stalls in central areas", "Improve safety and security without destroying low costs and flexibility", "Move all vendors into restaurants"], 1, "Make stalls safer and more secure without destroying the low costs…")
      ] }
    ]
  },
  {
    key: "more:c1:reading-trusting-strangers", batch: "lessons", level: "C1", unit: C1, slug: "reading-why-we-trust-strangers-online", title: "Read: why we trust strangers online", skill: "READING", minutes: 19,
    blocks: [
      before("Watch for the writer's use of contrast to build an argument: an apparent paradox is introduced, explained, and then complicated. Ask yourself what the writer finally recommends."),
      { kind: "text", heading: "Article", body: "We teach children not to talk to strangers. Yet as adults, we routinely sleep in strangers' homes, get into strangers' cars and buy second-hand phones from people we will never meet. Online platforms have made trust between strangers so ordinary that we rarely notice how strange it is.\n\nThe main mechanism is reputation. Ratings and reviews turn a stranger into someone with a visible history. A host with hundreds of positive reviews is no longer entirely unknown; their past behaviour becomes a guide to the future. Platforms reinforce this with verification — confirmed phone numbers, identity checks, photos — and with payment systems that hold money until both sides are satisfied.\n\nThe system works surprisingly well, but it has weaknesses that are easy to overlook. Ratings tend to cluster at the top of the scale, partly because people feel awkward giving a low score to someone they have met. When almost everyone has four or five stars, the stars stop telling us very much. Reviews can also be bought or written by friends, and new sellers with no history struggle to compete, however good their service may be.\n\nThere is a subtler cost as well. Reputation systems encourage people to behave well, but also to behave cautiously: hosts may refuse guests who seem slightly unusual, and drivers may avoid areas with a poor reputation. Trust built on ratings can quietly reproduce the very prejudices that strangers once faced in person.\n\nNone of this means we should abandon reviews. It means reading them as evidence rather than verdicts: looking at the written comments, not just the score; paying attention to how recent and specific they are; and remembering that a short history is not the same as a bad one." },
      { kind: "practice", instruction: "Read the article and choose the best answer.", questions: [
        lq("What paradox does the first paragraph describe?", ["Children trust strangers more than adults do.", "We teach children to avoid strangers but trust strangers online as adults.", "Strangers never use online platforms."], 1, "We teach children not to talk to strangers. Yet as adults…"),
        lq("How do ratings change our view of a stranger?", ["They give the stranger a visible history.", "They make the stranger anonymous.", "They replace payment."], 0, "Ratings and reviews turn a stranger into someone with a visible history."),
        lq("Why do ratings become less useful?", ["Most ratings cluster at four or five stars.", "Nobody writes reviews.", "Ratings are deleted every month."], 0, "When almost everyone has four or five stars, the stars stop telling us much."),
        lq("Who is disadvantaged by reputation systems, according to paragraph 3?", ["New sellers with no history", "Sellers with many reviews", "Platform owners"], 0, "New sellers with no history struggle to compete."),
        lq("What is the 'subtler cost' in paragraph 4?", ["Higher prices", "Rating systems can reproduce prejudice", "Slower payments"], 1, "Trust built on ratings can quietly reproduce the very prejudices…"),
        lq("What does the writer recommend?", ["Ignoring all reviews", "Reading reviews as evidence rather than verdicts", "Only trusting five-star ratings"], 1, "Reading them as evidence rather than verdicts.")
      ] }
    ]
  },
  {
    key: "more:c2:listening-translation-seminar", batch: "lessons", level: "C2", unit: C2, slug: "listening-a-seminar-on-literary-translation", title: "Listen: a seminar on literary translation", skill: "LISTENING", minutes: 20,
    blocks: [
      tip("At C2, speakers often make their point through examples and implication rather than direct statements. After each example, ask: what general claim is this example supporting?"),
      { kind: "listening", heading: "Seminar: what is a faithful translation?", voices: { Professor: "female", Student: "male" }, script: "Professor: Let's return to the word 'faithful'. When we say a translation is faithful, faithful to what, exactly?\nStudent: To the original text, surely. To what the author actually wrote.\nProfessor: To the words, then? Suppose a novel contains a pun — a joke that depends on a word having two meanings. Translate the words faithfully and the joke vanishes. The reader of the translation is left with a sentence that makes no sense.\nStudent: So the translator invents a different joke?\nProfessor: Often, yes. And in doing so, they are unfaithful to the words precisely in order to be faithful to the effect. The same tension appears with forms of address. Vietnamese marks the relationship between speakers in almost every sentence — older brother, younger sister, uncle. English has 'you'. A translator into English must decide how much of that social texture to carry over, and how.\nStudent: But then isn't the translator becoming an author?\nProfessor: To a degree, inevitably. The question is whether they acknowledge it. The most dangerous translations are not the obviously free ones, but the ones that claim a neutrality they cannot possibly have.\nStudent: So you'd rather a translator added notes, explained their choices?\nProfessor: In some contexts. Though a novel full of footnotes is rarely a pleasure to read. Perhaps the honest position is this: every translation is an interpretation, and a good one is an interpretation that has thought carefully about what it is giving up." },
      { kind: "practice", instruction: "Listen and choose the best answer.", questions: [
        lq("What does the pun example show?", ["Word-for-word translation can lose the original effect.", "Puns are impossible in English.", "Translators should never change anything."], 0, "Translate the words faithfully and the joke vanishes."),
        lq("According to the professor, a translator may be unfaithful to the words in order to…", ["save time", "be faithful to the effect", "make the text longer"], 1, "Unfaithful to the words precisely in order to be faithful to the effect."),
        lq("Why does the professor mention Vietnamese forms of address?", ["To show that English is more polite", "To illustrate social meaning that English does not mark grammatically", "To criticise Vietnamese grammar"], 1, "Vietnamese marks relationships; English has 'you'."),
        lq("Which translations does the professor consider most dangerous?", ["Obviously free translations", "Translations that claim a neutrality they cannot have", "Translations with footnotes"], 1, "The ones that claim a neutrality they cannot possibly have."),
        lq("What is her attitude to footnotes?", ["Always essential", "Useful in some contexts but can spoil a novel", "Completely unacceptable"], 1, "In some contexts. Though a novel full of footnotes is rarely a pleasure."),
        lq("What is the professor's final position?", ["A good translation is perfectly neutral.", "Every translation is an interpretation that should consider what it loses.", "Translation should be avoided."], 1, "A good one has thought carefully about what it is giving up.")
      ] }
    ]
  },
  {
    key: "more:c2:listening-collective-memory", batch: "lessons", level: "C2", unit: C2, slug: "listening-a-talk-on-collective-memory", title: "Listen: a talk on collective memory", skill: "LISTENING", minutes: 20,
    blocks: [
      tip("Talks on abstract ideas usually define a term, give a concrete case, and then draw out implications. Note the definition precisely — later questions often test whether you understood its limits."),
      { kind: "listening", heading: "Talk: how places remember", voices: { Speaker: "male" }, script: "Speaker: The term 'collective memory' is usually traced to the sociologist Maurice Halbwachs, writing in the 1920s. His insight was that memory is not only something that happens inside individual heads. What we remember, and how, is shaped by the groups we belong to — families, communities, nations.\nCities are one of the clearest places to see this at work. A street name, a statue, a preserved building: each is a decision about what should be remembered. Just as revealing are the things that disappear. When an old market is demolished to make way for a shopping centre, the city does not only lose a building; it loses a place where certain stories were told and certain habits practised.\nIt's tempting to think of this as a simple battle between preservation and progress. I'd argue that's too crude. Cities that try to freeze themselves in the past risk becoming museums — beautiful, perhaps, but no longer lived in. Memory that cannot change is closer to embalming than remembering.\nThe more interesting question is who gets to decide. Official memory — the plaques and monuments — tends to record the achievements of the powerful. Unofficial memory survives in other ways: in the names locals still use for places that have been renamed, in recipes, in the routes people walk out of habit.\nSo perhaps the task is not to choose between keeping and changing, but to make sure that when a city changes, the people whose memories are attached to a place have a say in what happens to it." },
      { kind: "practice", instruction: "Listen and choose the best answer.", questions: [
        lq("What was Halbwachs's key insight, according to the speaker?", ["Memory is shaped by the groups we belong to.", "Individuals cannot remember anything.", "Cities have no memory."], 0, "What we remember… is shaped by the groups we belong to."),
        lq("Why does the speaker mention a demolished market?", ["To show that a city loses stories and habits, not just buildings", "To argue that markets are unhygienic", "To praise shopping centres"], 0, "It loses a place where certain stories were told and habits practised."),
        lq("What does the speaker think of 'preservation versus progress'?", ["It is the right way to frame the issue.", "It is too crude a framing.", "Progress should always win."], 1, "I'd argue that's too crude."),
        lq("What does the comparison with 'embalming' suggest?", ["Unchanging memory is lifeless.", "Memory should be expensive.", "Museums should be closed."], 0, "Memory that cannot change is closer to embalming than remembering."),
        lq("Where does unofficial memory survive?", ["Only in monuments", "In old place names, recipes and habitual routes", "In government records"], 1, "In the names locals still use… in recipes, in the routes people walk."),
        lq("What does the speaker finally propose?", ["Banning all new buildings", "Giving people attached to a place a say in how it changes", "Building more statues"], 1, "People whose memories are attached to a place should have a say.")
      ] }
    ]
  },
  {
    key: "more:c2:reading-boredom", batch: "lessons", level: "C2", unit: C2, slug: "reading-in-defence-of-boredom", title: "Read: in defence of boredom", skill: "READING", minutes: 20,
    blocks: [
      before("This essay argues against a common assumption. Track how the writer anticipates objections and limits the claim. The conclusion is carefully qualified — notice exactly what is and is not being recommended."),
      { kind: "text", heading: "Essay", body: "Of all the unpleasant states of mind, boredom has the worst reputation and perhaps the least deserved. We treat it as a problem to be solved instantly, and modern life has obliged: no queue, bus ride or moment of waiting need ever be empty again while there is a phone in our pocket.\n\nYet boredom may be less an absence than a signal. It tells us that our current activity is not engaging us and prompts us to look for something that will. Some psychologists have suggested that this restlessness can push the mind towards daydreaming, and that daydreaming, in turn, is where unexpected connections are often made. It is no accident that so many people report having their best ideas in the shower or on a walk — situations dull enough to let the mind wander.\n\nThe objection is obvious: much boredom is simply unproductive misery, and nobody is helped by being told that a tedious job is secretly good for them. That is true, and the argument here is narrower. It concerns the short, low-stakes boredom of waiting and idleness — precisely the kind we now eliminate most automatically.\n\nWhat is lost when every gap is filled? Not, perhaps, creativity alone, but a certain ownership of attention. A mind that is constantly supplied with stimulation never has to decide what it finds interesting. Its curiosity is managed for it, by feeds designed to hold it as long as possible.\n\nNone of this amounts to a case for throwing away our devices, still less for romanticising dullness. It is a case for occasionally declining the instant cure: for letting a few minutes of waiting remain empty, and seeing what the mind does with them when nobody else is choosing." },
      { kind: "practice", instruction: "Read the essay and choose the best answer.", questions: [
        lq("How does the writer describe boredom's reputation?", ["Deserved", "The worst of unpleasant states, and perhaps the least deserved", "Mostly positive"], 1, "Boredom has the worst reputation and perhaps the least deserved."),
        lq("In paragraph 2, boredom is presented as…", ["a signal that prompts us to look for engagement", "a sign of illness", "a waste of time with no function"], 0, "Boredom may be less an absence than a signal."),
        lq("Why does the writer mention ideas in the shower?", ["To show that dull situations can let the mind wander productively", "To recommend longer showers", "To criticise daydreaming"], 0, "Situations dull enough to let the mind wander."),
        lq("How does the writer limit the argument in paragraph 3?", ["By focusing only on short, low-stakes boredom", "By rejecting all forms of boredom", "By praising tedious jobs"], 0, "It concerns the short, low-stakes boredom of waiting and idleness."),
        lq("What does 'ownership of attention' refer to?", ["Deciding for yourself what you find interesting", "Owning many devices", "Paying for apps"], 0, "A mind constantly stimulated never has to decide what it finds interesting."),
        lq("What does the writer finally recommend?", ["Throwing away devices", "Occasionally letting short waits stay empty", "Romanticising dullness"], 1, "Occasionally declining the instant cure.")
      ] }
    ]
  },
  {
    key: "more:c2:reading-measurement", batch: "lessons", level: "C2", unit: C2, slug: "reading-the-limits-of-measurement", title: "Read: the limits of measurement", skill: "READING", minutes: 21,
    blocks: [
      before("The writer uses a well-known principle and then extends it. Identify the principle, the examples used to illustrate it, and the writer's own contribution to the argument."),
      { kind: "text", heading: "Essay", body: "Modern organisations run on numbers. Schools are judged by exam results, hospitals by waiting times, employees by targets met. The appeal is easy to understand: numbers are clear, comparable and apparently objective. Yet anyone who has worked inside such a system knows the uneasy feeling that what is being counted is not quite what matters.\n\nThe problem has a name. It is often called Goodhart's law, after the economist Charles Goodhart, and is commonly summarised as: when a measure becomes a target, it ceases to be a good measure. A number that once reflected something useful starts to be pursued for its own sake, and behaviour bends around it. A hospital told to reduce waiting times may achieve this by changing when the clock starts. A school judged on pass rates may steer weaker students away from difficult subjects. The figures improve; the reality they were meant to capture may not.\n\nIt would be easy to conclude that measurement is the enemy. That conclusion is too comfortable. Without measurement, organisations fall back on impression and reputation, which are no less open to manipulation and considerably less open to scrutiny. The question is not whether to measure, but how to measure without being captured by the measure.\n\nSeveral principles suggest themselves. Use several indicators rather than one, so that gaming any single number becomes harder. Treat numbers as prompts for questions rather than as verdicts. Change targets from time to time, before behaviour has fully adapted to them. Above all, keep talking to the people being measured, who usually know far better than any dashboard where the figures and the reality have parted company.\n\nMeasurement, in other words, is a tool for judgement, not a substitute for it. Organisations get into trouble not when they count, but when they forget why they started counting." },
      { kind: "practice", instruction: "Read the essay and choose the best answer.", questions: [
        lq("What principle does the writer introduce in paragraph 2?", ["When a measure becomes a target, it ceases to be a good measure.", "More data always leads to better decisions.", "Numbers are never objective."], 0, "Commonly summarised as: when a measure becomes a target…"),
        lq("What does the hospital example illustrate?", ["Improving a figure without improving the reality", "Hospitals have no waiting times", "Doctors dislike numbers"], 0, "Changing when the clock starts improves the figure, not the reality."),
        lq("Why does the writer reject abandoning measurement?", ["Impression and reputation are no less open to manipulation and harder to scrutinise.", "Measurement is free.", "Everyone likes targets."], 0, "Without measurement, organisations fall back on impression and reputation…"),
        lq("Which is one of the principles the writer suggests?", ["Rely on a single indicator", "Treat numbers as prompts for questions", "Never change targets"], 1, "Treat numbers as prompts for questions rather than as verdicts."),
        lq("According to the writer, who usually knows where figures and reality differ?", ["The people being measured", "Software designers", "Senior managers only"], 0, "The people being measured, who usually know far better than any dashboard."),
        lq("Which statement best summarises the conclusion?", ["Organisations should stop counting.", "Measurement should support judgement, not replace it.", "Dashboards are always accurate."], 1, "Measurement is a tool for judgement, not a substitute for it.")
      ] }
    ]
  }
];
