import { lq, type LessonDef } from "../types";

const C1 = "Skills for advanced users";
const C2 = "Skills for expert users";

export const skillsC: LessonDef[] = [
  {
    key: "skills:c1:reading-earworms", batch: "lessons", level: "C1", unit: C1, slug: "reading-why-songs-get-stuck", title: "Read: why songs get stuck in our heads", skill: "READING", minutes: 18,
    blocks: [
      { kind: "text", heading: "Before you read", body: "At C1, you need to follow the development of an argument and recognise how a writer qualifies claims. As you read, underline words that show certainty (clearly, shows) and caution (may, appears, some)." },
      { kind: "text", heading: "Article", body: "Almost everyone has experienced it: a few bars of a song repeat in the mind for hours, sometimes long after the music has stopped. Researchers call these involuntary musical memories 'earworms', and although they are usually harmless, they offer a revealing glimpse into how memory works.\n\nSurveys suggest that around nine in ten people experience an earworm at least once a week. The songs involved tend to share certain features: a simple, repetitive melody, an unusual interval that makes the tune distinctive, and a fast-to-moderate tempo. Crucially, most earworms are only a short fragment — often the chorus — rather than a complete song. One explanation is that the brain replays an 'unfinished' pattern in an attempt to complete it, much as we keep thinking about a task we have left half done.\n\nContext matters as much as the music itself. Earworms appear more often when people are tired or stressed, and during low-demand activities such as showering or walking. Recent exposure is the strongest trigger, but so are associations: seeing a particular word or place can revive a song linked to it.\n\nInterestingly, trying to suppress an earworm can make it return more often, a pattern observed with other unwanted thoughts. Researchers have tested several remedies. Chewing gum appears to reduce the problem, perhaps because it interferes with the 'inner voice' used to rehearse sounds. Another approach is to listen to the whole song, giving the brain the ending it seems to be searching for. Neither method works for everyone, but both are more effective than simply trying not to think about the tune." },
      { kind: "practice", instruction: "Read the article and choose the best answer.", questions: [
        lq("Why does the writer say earworms offer 'a revealing glimpse'?", ["They show how memory works.", "They are a sign of illness.", "They improve musical ability."], 0, "They offer a revealing glimpse into how memory works."),
        lq("Which feature is typical of an earworm?", ["A complete, slow song", "A short, repetitive fragment", "A song with no chorus"], 1, "Most earworms are only a short fragment, often the chorus."),
        lq("What does the 'unfinished pattern' explanation compare earworms to?", ["Dreams we remember", "Songs we dislike", "Tasks left half done"], 2, "Much as we keep thinking about a task we have left half done."),
        lq("According to the text, what is the strongest trigger?", ["Stress", "Recent exposure to the song", "Showering"], 1, "Recent exposure is the strongest trigger."),
        lq("What happens when people try to suppress an earworm?", ["It may come back more often.", "It disappears immediately.", "It becomes a different song."], 0, "Trying to suppress it can make it return more often."),
        lq("How does the writer present the remedies?", ["As guaranteed cures", "As useless", "As helpful for some people but not all"], 2, "Neither method works for everyone, but both are more effective…")
      ] }
    ]
  },
  {
    key: "skills:c1:listening-interview", batch: "lessons", level: "C1", unit: C1, slug: "listening-radio-interview-gig-work", title: "Listen: a radio interview on gig work", skill: "LISTENING", minutes: 18,
    blocks: [
      { kind: "text", heading: "Listening tip", body: "At C1 you need to identify attitude as well as facts. Notice how speakers soften criticism ('to be fair', 'that said') and how they signal a change of direction ('the flip side is…')." },
      { kind: "listening", heading: "Radio interview: the gig economy", voices: { Presenter: "male", "Dr Adeyemi": "female" }, script: "Presenter: My guest today is Dr Ruth Adeyemi, who researches work and technology. Dr Adeyemi, delivery riders and ride-hailing drivers are everywhere now. Is this a good way to earn a living?\nDr Adeyemi: It depends on who you ask and why they're doing it. For students or people who want a second income, the flexibility is genuinely valuable. You choose your hours, and you can stop when you like.\nPresenter: But?\nDr Adeyemi: The flip side is that the flexibility often runs one way. The app decides how much each job pays, and those rates can change overnight. Riders rarely have sick pay or insurance, so a minor accident can mean a week without income.\nPresenter: The companies say they're simply providing a platform.\nDr Adeyemi: To be fair, they have created a huge number of jobs very quickly, and some have introduced accident insurance after pressure from workers. That said, calling someone independent while controlling their prices and ratings is, I think, a contradiction.\nPresenter: What would you change?\nDr Adeyemi: I'd start with transparency — riders should know in advance how pay is calculated. And a basic safety net, funded partly by the platforms, would make a big difference without destroying the flexibility people value." },
      { kind: "practice", instruction: "Listen and choose the best answer.", questions: [
        lq("According to Dr Adeyemi, who benefits most from gig work's flexibility?", ["Full-time workers with families", "Students and people wanting a second income", "Company managers"], 1, "For students or people who want a second income, the flexibility is valuable."),
        lq("What does she mean by 'the flexibility often runs one way'?", ["The app can change pay rates, not the worker.", "Workers can only drive in one direction.", "Workers choose everything."], 0, "The app decides how much each job pays."),
        lq("What does she concede with 'To be fair'?", ["The platforms pay very well.", "The platforms have created many jobs quickly.", "Riders do not need insurance."], 1, "To be fair, they have created a huge number of jobs very quickly."),
        lq("What contradiction does she point out?", ["Workers are called independent but have their prices controlled.", "Riders work at night but sleep during the day.", "Apps are free but expensive."], 0, "Calling someone independent while controlling their prices…"),
        lq("What is the first change she would make?", ["Ban delivery apps", "Raise all prices", "Make pay calculation transparent"], 2, "I'd start with transparency."),
        lq("What is her overall attitude?", ["Completely positive", "Critical but balanced", "Completely negative"], 1, "She recognises benefits but argues for reforms.")
      ] }
    ]
  },
  {
    key: "skills:c1:speaking-data", batch: "lessons", level: "C1", unit: C1, slug: "speaking-presenting-data-clearly", title: "Speak: presenting data clearly", skill: "SPEAKING", minutes: 17,
    blocks: [
      { kind: "text", heading: "Useful language", body: "Introducing: This chart shows… / What stands out here is…\nDescribing change: rose steadily, fell sharply, levelled off, peaked at, a slight dip.\nComparing: roughly twice as many, a far higher proportion, slightly fewer than.\nInterpreting with caution: This may reflect… / One possible explanation is… / It's worth bearing in mind that…\nSignposting: Turning to…, If we look at…, To sum up…\n\nTip: don't read every number. Pick the two or three figures that support your main message." },
      { kind: "listening", heading: "Model mini-presentation", voices: { Presenter: "female" }, script: "Presenter: This chart shows how our library members borrowed books and e-books between 2021 and 2025.\nWhat stands out here is the growth in e-books, which rose steadily from around eight thousand loans to just over twenty thousand — roughly two and a half times as many.\nPrint loans, by contrast, fell sharply in 2022, then levelled off at about fifteen thousand a year.\nOne possible explanation is the new reading app we launched in 2022, although it's worth bearing in mind that the building was also closed for repairs that year.\nTo sum up, e-books are now our main format, but print borrowing has remained surprisingly stable." },
      { kind: "practice", instruction: "Choose the best answer.", questions: [
        lq("What happened to e-book loans?", ["They rose steadily.", "They fell sharply.", "They stayed the same."], 0, "E-books rose steadily from about 8,000 to just over 20,000."),
        lq("Why does the speaker mention the building repairs?", ["To blame the staff", "To show caution in explaining the drop", "To advertise the library"], 1, "It's worth bearing in mind… offers another possible cause."),
        lq("Which phrase describes stopping changing?", ["peaked at", "levelled off", "rose steadily"], 1, "Levelled off = stayed at a similar level."),
        lq("Which phrase interprets data cautiously?", ["This proves that…", "Obviously, …", "One possible explanation is…"], 2, "It presents an explanation as a possibility."),
        lq("'Roughly two and a half times as many' is a way to…", ["compare quantities", "introduce a chart", "end a talk"], 0, "It compares the size of two figures."),
        lq("According to the tip, what should presenters do?", ["Read out every number", "Choose the key figures that support the message", "Avoid using charts"], 1, "Pick the two or three figures that support your main message.")
      ] }
    ]
  },
  {
    key: "skills:c1:writing-proposal", batch: "lessons", level: "C1", unit: C1, slug: "writing-a-proposal", title: "Write: a proposal", skill: "WRITING", minutes: 20,
    blocks: [
      { kind: "text", heading: "Model proposal (extract)", body: "Proposal: Reducing single-use plastic in the school canteen\n\nPurpose\nThe aim of this proposal is to outline practical measures to cut single-use plastic in the canteen by at least half within one school year.\n\nCurrent situation\nAt present, around 600 plastic cups and 400 plastic bags are thrown away every day. Students have indicated in a recent survey that they would support change, provided that it does not increase prices.\n\nRecommendations\nFirstly, it is recommended that the canteen replace plastic cups with washable ones, funded by a small deposit that is returned when the cup is brought back. Secondly, students could be encouraged to bring their own containers through a modest discount on meals.\n\nConclusion\nIf implemented, these measures would reduce waste considerably at minimal cost, while involving students directly in the solution." },
      { kind: "text", heading: "Features of a proposal", body: "• Clear headings (Purpose, Current situation, Recommendations, Conclusion).\n• A formal, impersonal tone: it is recommended that…, students could be encouraged to…\n• Specific, practical suggestions supported by evidence.\n• A forward-looking conclusion: If implemented, these measures would…\n\nUseful language: The aim of this proposal is to… / At present, … / I would strongly recommend… / This would enable… / In the long term, …" },
      { kind: "practice", instruction: "Choose the best answer.", questions: [
        lq("What is the main aim of the proposal?", ["To close the canteen", "To cut single-use plastic by at least half", "To raise food prices"], 1, "The aim is to cut single-use plastic by at least half within one year."),
        lq("What condition did students give in the survey?", ["That prices do not increase", "That the canteen opens earlier", "That cups are free"], 0, "…provided that it does not increase prices."),
        lq("Which sentence has the most appropriate tone for a proposal?", ["You guys should stop using plastic!", "It is recommended that the canteen introduce washable cups.", "Plastic is really bad, right?"], 1, "Formal and impersonal: it is recommended that…"),
        lq("How would the washable cups be funded?", ["By the government", "By a returnable deposit", "By raising meal prices"], 1, "Funded by a small deposit that is returned."),
        lq("Which heading would best replace 'Current situation'?", ["Background", "Thank you", "My feelings"], 0, "Background describes the present situation."),
        lq("What does the conclusion do?", ["It introduces a new problem.", "It summarises the expected benefits.", "It lists the survey questions."], 1, "It states what the measures would achieve.")
      ] }
    ]
  },
  {
    key: "skills:c2:reading-choice", batch: "lessons", level: "C2", unit: C2, slug: "reading-the-cost-of-endless-choice", title: "Read: the cost of endless choice", skill: "READING", minutes: 20,
    blocks: [
      { kind: "text", heading: "Before you read", body: "C2 texts often argue indirectly. Pay attention to how the writer positions other views (concession, irony, rhetorical questions) and what the writer ultimately endorses." },
      { kind: "text", heading: "Essay", body: "It has become an article of faith in consumer societies that more choice is always better. A supermarket with forty kinds of yoghurt, a streaming service with thousands of films, a dating app with seemingly endless profiles — each is presented as an expansion of freedom. Yet anyone who has spent twenty minutes scrolling without watching anything may suspect that abundance carries a hidden price.\n\nThe case against endless choice is not that choice is bad, but that its benefits diminish while its costs accumulate. Comparing options demands time and attention, and each option we reject becomes a small 'what if'. The more alternatives there are, the easier it is to imagine that one of them would have been better — a thought that quietly erodes satisfaction with what we did choose. Paradoxically, then, we may feel less content with a good decision made from fifty options than with the same decision made from five.\n\nIt would be naive, however, to conclude that we should simply return to scarcity. For people with specific needs — dietary restrictions, a rare interest, a limited budget — wide choice is not a luxury but a necessity. The problem lies less in the number of options than in the absence of structure. Well-designed defaults, trusted recommendations and clear categories allow people to benefit from variety without being overwhelmed by it.\n\nPerhaps the real lesson is personal rather than commercial. Deciding in advance what is 'good enough' — and then stopping the search — is not a failure of ambition. It may be the most effective way to enjoy the abundance that modern life offers." },
      { kind: "practice", instruction: "Read the essay and choose the best answer.", questions: [
        lq("What is the 'article of faith' mentioned in the first paragraph?", ["The belief that more choice is always better", "The belief that supermarkets are too big", "The belief that streaming is free"], 0, "It has become an article of faith… that more choice is always better."),
        lq("According to paragraph 2, why can more options reduce satisfaction?", ["Products become more expensive.", "It becomes easier to imagine that another option was better.", "Shops close earlier."], 1, "The more alternatives, the easier it is to imagine one would have been better."),
        lq("How does paragraph 3 relate to paragraph 2?", ["It repeats the same argument.", "It qualifies the argument by recognising when choice is necessary.", "It gives a personal story."], 1, "It would be naive… wide choice is a necessity for some people."),
        lq("Where does the writer locate the real problem?", ["In the number of options", "In high prices", "In the absence of structure"], 2, "The problem lies less in the number of options than in the absence of structure."),
        lq("What does the writer recommend at a personal level?", ["Deciding what is 'good enough' and stopping the search", "Avoiding supermarkets", "Always choosing the cheapest option"], 0, "Deciding in advance what is 'good enough' — and then stopping the search."),
        lq("The word 'erodes' in paragraph 2 is closest in meaning to…", ["gradually weakens", "suddenly destroys", "clearly increases"], 0, "To erode = to reduce gradually.")
      ] }
    ]
  },
  {
    key: "skills:c2:listening-debate", batch: "lessons", level: "C2", unit: C2, slug: "listening-debate-on-heritage", title: "Listen: a debate on heritage and development", skill: "LISTENING", minutes: 20,
    blocks: [
      { kind: "text", heading: "Listening tip", body: "In debates, speakers often appear to agree before disagreeing ('I take the point, but…'). Track each speaker's actual position and the evidence they use, and notice irony or understatement." },
      { kind: "listening", heading: "Debate: should old buildings make way for new housing?", voices: { Chair: "female", Kevin: "male", Mai: "female" }, script: "Chair: Tonight's question: should cities protect old buildings even when housing is urgently needed? Kevin, you're an urban planner.\nKevin: Thank you. Let me be clear: I'm not against heritage. But when families are paying half their income in rent, preserving every nineteenth-century warehouse is a luxury we can't afford. A single protected site can block hundreds of homes.\nChair: Mai, you work in conservation.\nMai: I take the point about rents, and it's a serious one. But the choice is rarely as stark as 'warehouse or homes'. Many old buildings can be converted into housing — often more cheaply than people assume, and with a far lower carbon cost than demolition and rebuilding.\nKevin: In some cases, certainly. Conversion works well for sturdy warehouses. It's rather less convenient for a small, crumbling shophouse on a site that could hold forty flats.\nMai: Which is why we don't argue for protecting everything. We argue for deciding carefully, with the community, rather than letting whoever buys the land decide overnight.\nChair: So you'd both accept some demolition?\nKevin: Of course.\nMai: Reluctantly — and with a much better process than we have now." },
      { kind: "practice", instruction: "Listen and choose the best answer.", questions: [
        lq("What is Kevin's main concern?", ["The cost of housing", "The beauty of old buildings", "Traffic congestion"], 0, "Families paying half their income in rent."),
        lq("What does Mai mean by 'the choice is rarely as stark' as that?", ["It is usually a simple either-or decision.", "There are often options between keeping and demolishing.", "The choice is always obvious."], 1, "Old buildings can often be converted into housing."),
        lq("What advantage of conversion does Mai mention?", ["It is always faster.", "It produces more flats.", "It has a lower carbon cost than rebuilding."], 2, "A far lower carbon cost than demolition and rebuilding."),
        lq("Kevin's phrase 'rather less convenient' is an example of…", ["understatement", "exaggeration", "a rhetorical question"], 0, "He means it is much harder, but says it mildly."),
        lq("What does Mai want most?", ["To protect every old building", "A careful decision-making process involving the community", "To stop all new housing"], 1, "We argue for deciding carefully, with the community."),
        lq("How do both speakers respond to the chair's final question?", ["Both reject demolition completely.", "Both accept some demolition, Mai reluctantly.", "Neither answers."], 1, "Kevin: Of course. Mai: Reluctantly.")
      ] }
    ]
  },
  {
    key: "skills:c2:speaking-persuasion", batch: "lessons", level: "C2", unit: C2, slug: "speaking-persuasive-techniques", title: "Speak: persuasive techniques", skill: "SPEAKING", minutes: 18,
    blocks: [
      { kind: "text", heading: "Useful techniques", body: "• Rule of three: We need a plan that is fair, affordable and realistic.\n• Anticipating objections: Some will say this is too expensive. In fact, …\n• Concession then counter: Admittedly, it will take time. But the alternative is…\n• Rhetorical question: Can we really afford to wait another ten years?\n• Concrete example over abstraction: Instead of 'many people', say 'three out of four residents we surveyed'.\n• Measured emphasis: What matters most is… / The key point is…\n\nAt C2, persuasion should sound confident but not aggressive; precise evidence persuades more than volume." },
      { kind: "listening", heading: "Model speech (extract)", voices: { Speaker: "male" }, script: "Speaker: Some will say that a car-free city centre is a nice idea for a sunny weekend and nothing more. I understand that concern. Admittedly, change on this scale is inconvenient at first. But consider what we have now: three out of four residents we surveyed said the traffic makes them avoid the centre altogether. Shops are losing customers, the air is unhealthy, and our streets are designed for vehicles rather than people.\nSo what are we asking for? A centre that is cleaner, safer and busier — busier with people, not cars. Can we really afford to keep a system that drives away the very people our businesses depend on?" },
      { kind: "practice", instruction: "Choose the best answer.", questions: [
        lq("Which technique does the speaker use first?", ["Anticipating an objection", "Telling a joke", "Listing statistics without comment"], 0, "Some will say that… anticipates an objection."),
        lq("'Cleaner, safer and busier' is an example of…", ["a rhetorical question", "the rule of three", "a concession"], 1, "Three parallel adjectives: the rule of three."),
        lq("Why does the speaker mention 'three out of four residents'?", ["To give concrete evidence", "To criticise residents", "To change the topic"], 0, "A specific figure is more persuasive than 'many people'."),
        lq("Which sentence from the speech is a rhetorical question?", ["I understand that concern.", "Can we really afford to keep a system that drives away the very people our businesses depend on?", "Shops are losing customers."], 1, "The speaker does not expect an answer; the question makes the listener agree."),
        lq("'Admittedly, change on this scale is inconvenient at first.' What is this?", ["A concession", "A conclusion", "An insult"], 0, "It admits a weakness before countering it."),
        lq("According to the tips, what persuades more at C2?", ["Speaking loudly", "Precise evidence", "Repeating the same point"], 1, "Precise evidence persuades more than volume.")
      ] }
    ]
  },
  {
    key: "skills:c2:writing-summary", batch: "lessons", level: "C2", unit: C2, slug: "writing-summary-and-paraphrase", title: "Write: summary and paraphrase", skill: "WRITING", minutes: 20,
    blocks: [
      { kind: "text", heading: "Source paragraph", body: "\"Although online courses have made education accessible to millions who could never attend a university campus, completion rates remain strikingly low; fewer than one in ten learners who enrol in a free course typically finish it. Researchers attribute this not to the difficulty of the material but to the absence of the social commitments — classmates, deadlines, a teacher who notices when you are missing — that keep students on track in traditional settings.\"" },
      { kind: "text", heading: "Model summary (one sentence)", body: "While free online courses have widened access to education, very few learners complete them, largely because they lack the social structures that motivate students in conventional classes.\n\nHow it was done:\n• Kept only the main idea and the key reason; removed examples (classmates, deadlines…).\n• Changed the vocabulary: accessible to millions → widened access; strikingly low → very few; absence of → lack.\n• Changed the grammar: Although… → While…; attribute this to… → largely because…\n• Kept the meaning accurate: the reason is social structure, not difficulty." },
      { kind: "practice", instruction: "Choose the best answer.", questions: [
        lq("Which is the most accurate paraphrase of 'completion rates remain strikingly low'?", ["Very few learners finish.", "Most learners finish quickly.", "The courses are strikingly difficult."], 0, "Low completion = few people finish."),
        lq("According to the source, why do learners drop out?", ["The material is too difficult.", "They lack social commitments that keep them on track.", "The courses are too expensive."], 1, "Researchers attribute this… to the absence of social commitments."),
        lq("Which detail should a one-sentence summary leave out?", ["The main contrast (access vs completion)", "The key reason (lack of social structure)", "The list of examples: classmates, deadlines, a teacher"], 2, "Examples are usually removed in a short summary."),
        lq("Which paraphrase changes the meaning incorrectly?", ["Online learners often lack the support of classmates.", "Online courses fail because the content is too hard.", "Few people who start free courses complete them."], 1, "The source says the problem is not the difficulty of the material."),
        lq("What is the best synonym for 'attribute … to' in this context?", ["explain as caused by", "give as a gift", "argue against"], 0, "Attribute A to B = say that B causes A."),
        lq("Which technique is NOT good paraphrasing?", ["Changing word forms and structure", "Keeping key technical terms when there is no synonym", "Replacing words one by one while keeping the original sentence structure"], 2, "Word-by-word replacement keeps the source's structure and risks plagiarism.")
      ] }
    ]
  }
];
