CREATE TYPE "content_status" AS ENUM ('DRAFT', 'REVIEW', 'APPROVED', 'PUBLISHED', 'ARCHIVED');
CREATE TYPE "exam_type" AS ENUM ('TOEIC', 'IELTS');
CREATE TYPE "attempt_status" AS ENUM ('IN_PROGRESS', 'SUBMITTED', 'EXPIRED');

CREATE TABLE "content_batches" ("id" uuid PRIMARY KEY, "source" text NOT NULL, "license" varchar(255) NOT NULL, "author" varchar(255), "generated_by" varchar(255), "reviewed_by" varchar(255), "imported_at" timestamptz NOT NULL, "version" varchar(64) NOT NULL, "status" content_status NOT NULL DEFAULT 'DRAFT');
CREATE TABLE "exams" ("id" uuid PRIMARY KEY, "slug" varchar(128) NOT NULL UNIQUE, "title" varchar(255) NOT NULL, "type" exam_type NOT NULL, "duration_seconds" integer NOT NULL, "status" content_status NOT NULL DEFAULT 'DRAFT', "content_batch_id" uuid REFERENCES "content_batches"("id"), "created_at" timestamptz NOT NULL DEFAULT now(), "updated_at" timestamptz NOT NULL DEFAULT now());
CREATE TABLE "exam_parts" ("id" uuid PRIMARY KEY, "exam_id" uuid NOT NULL REFERENCES "exams"("id") ON DELETE CASCADE, "part_number" integer NOT NULL, "title" varchar(255) NOT NULL, "sort_order" integer NOT NULL, "instructions" text, "duration_seconds" integer);
CREATE TABLE "questions" ("id" uuid PRIMARY KEY, "exam_part_id" uuid NOT NULL REFERENCES "exam_parts"("id") ON DELETE CASCADE, "schema_version" integer NOT NULL, "type" varchar(64) NOT NULL, "content" jsonb NOT NULL, "answer" jsonb NOT NULL, "explanation" text, "tags" jsonb NOT NULL, "status" content_status NOT NULL DEFAULT 'DRAFT', "content_batch_id" uuid REFERENCES "content_batches"("id"), "created_at" timestamptz NOT NULL DEFAULT now(), "updated_at" timestamptz NOT NULL DEFAULT now());
CREATE TABLE "attempts" ("id" uuid PRIMARY KEY, "exam_id" uuid NOT NULL REFERENCES "exams"("id"), "user_id" uuid, "guest_id" uuid, "status" attempt_status NOT NULL DEFAULT 'IN_PROGRESS', "started_at" timestamptz NOT NULL, "submitted_at" timestamptz, "raw_score" integer, "total_questions" integer NOT NULL, "created_at" timestamptz NOT NULL DEFAULT now(), "updated_at" timestamptz NOT NULL DEFAULT now());
CREATE TABLE "attempt_answers" ("attempt_id" uuid NOT NULL REFERENCES "attempts"("id") ON DELETE CASCADE, "question_id" uuid NOT NULL REFERENCES "questions"("id"), "selected_option_id" varchar(128) NOT NULL, "updated_at" timestamptz NOT NULL DEFAULT now(), PRIMARY KEY("attempt_id", "question_id"));
