ALTER TABLE "exams" ADD COLUMN "mode" varchar(24) NOT NULL DEFAULT 'PRACTICE';
ALTER TABLE "exams" ADD COLUMN "metadata" jsonb NOT NULL DEFAULT '{}'::jsonb;
ALTER TABLE "exam_parts" ADD COLUMN "skill" varchar(16);
ALTER TABLE "exam_parts" ADD COLUMN "metadata" jsonb NOT NULL DEFAULT '{}'::jsonb;
CREATE TABLE "passages" ("id" uuid PRIMARY KEY, "exam_part_id" uuid NOT NULL REFERENCES "exam_parts"("id") ON DELETE CASCADE, "title" varchar(255), "content" text NOT NULL, "sort_order" integer NOT NULL DEFAULT 1, "metadata" jsonb NOT NULL DEFAULT '{}'::jsonb);
ALTER TABLE "questions" ADD COLUMN "passage_id" uuid REFERENCES "passages"("id") ON DELETE SET NULL;
ALTER TABLE "questions" ADD COLUMN "group_key" varchar(128);
ALTER TABLE "attempts" ADD COLUMN "expires_at" timestamptz;
ALTER TABLE "writing_submissions" ADD COLUMN "prompt_id" varchar(128) NOT NULL DEFAULT 'general-writing';
ALTER TABLE "writing_submissions" ADD COLUMN "word_count" integer NOT NULL DEFAULT 0;
ALTER TABLE "writing_submissions" ADD COLUMN "updated_at" timestamptz NOT NULL DEFAULT now();
CREATE TABLE "writing_revisions" ("id" uuid PRIMARY KEY, "submission_id" uuid NOT NULL REFERENCES "writing_submissions"("id") ON DELETE CASCADE, "text" text NOT NULL, "word_count" integer NOT NULL, "created_at" timestamptz NOT NULL DEFAULT now());
ALTER TABLE "speaking_sessions" ADD COLUMN "prompt_id" varchar(128) NOT NULL DEFAULT 'general-speaking';
ALTER TABLE "speaking_sessions" ADD COLUMN "prompt" text NOT NULL DEFAULT 'Speak about the topic.';
ALTER TABLE "speaking_turns" ADD COLUMN "duration_ms" integer;
ALTER TABLE "progress_events" ADD COLUMN "source_type" varchar(64);
ALTER TABLE "progress_events" ADD COLUMN "source_id" varchar(128);
ALTER TABLE "progress_events" ADD COLUMN "idempotency_key" varchar(255);
CREATE UNIQUE INDEX "progress_events_idempotency_idx" ON "progress_events"("idempotency_key");
CREATE INDEX "passages_part_idx" ON "passages"("exam_part_id", "sort_order");
CREATE INDEX "attempts_owner_status_idx" ON "attempts"("user_id", "guest_id", "status");
CREATE INDEX "writing_submissions_owner_updated_idx" ON "writing_submissions"("user_id", "guest_id", "updated_at");
CREATE INDEX "speaking_sessions_owner_created_idx" ON "speaking_sessions"("user_id", "guest_id", "created_at");
