import { heard, mcq, type ExamPartDef } from "../types";
import { graphic, photo } from "./media";

const P1 = "Look at the picture and listen to the four statements. Choose the statement that best describes the picture.";
const P2 = "Listen to the question or statement and the three responses. Choose the best response.";
const statements = (lines: [string, string, string, string]) => `Narrator: Look at the picture.\n(A) ${lines[0]}\n(B) ${lines[1]}\n(C) ${lines[2]}\n(D) ${lines[3]}`;
const exchange = (first: "Woman" | "Man", question: string, answers: [string, string, string]) => `${first}: ${question}\n${first === "Woman" ? "Man" : "Woman"}: (A) ${answers[0]}\n(B) ${answers[1]}\n(C) ${answers[2]}`;

export const mock1Part1: ExamPartDef = {
  partNumber: 1, title: "Photographs", skill: "LISTENING", instructions: "For each question, look at the photograph and listen to four statements. Choose the statement that best describes what you see. The statements are not printed and are heard only once.",
  groups: [{ questions: [
    heard(P1, statements(["She's closing the window.", "She's typing on a laptop.", "She's carrying a bench.", "She's painting a brick wall."]), 4, "B", "(B) She's typing on a laptop. The window is not being closed, and she is not carrying or painting anything.", { image: photo("laptop-bench", "Photograph for question 1") }),
    heard(P1, statements(["She's washing a pot in the sink.", "She's cutting vegetables on a board.", "She's stirring food in a large pot.", "She's opening an oven door."]), 4, "C", "(C) She's stirring food in a large pot with a wooden paddle.", { image: photo("stirring-pot", "Photograph for question 2") }),
    heard(P1, statements(["A train is stopped beside a platform.", "Passengers are boarding a bus.", "The platform is crowded with travelers.", "A man is sitting on a bench."]), 4, "A", "(A) A train is stopped beside a platform. Only a few people are walking on the platform.", { image: photo("metro-platform", "Photograph for question 3") }),
    heard(P1, statements(["The workers are sitting down for lunch.", "A road is being painted.", "A truck is being unloaded.", "Some workers are wearing hard hats."]), 4, "D", "(D) Some workers are wearing hard hats while they cut and lay paving stones.", { image: photo("road-workers", "Photograph for question 4") }),
    heard(P1, statements(["Fishermen are unloading their catch.", "Some boats are tied up at a pier.", "People are swimming near the boats.", "A boat is being lifted out of the water."]), 4, "B", "(B) Some boats are tied up at a pier. No people are visible.", { image: photo("fishing-boats", "Photograph for question 5") }),
    heard(P1, statements(["A man is fishing from a boat.", "Diners are standing in a line.", "A man is holding a plate of food.", "Some chairs are stacked against a wall."]), 4, "C", "(C) A man is holding a plate of food near the outdoor tables.", { image: photo("waiter-terrace", "Photograph for question 6") })
  ] }]
};

export const mock1Part2: ExamPartDef = {
  partNumber: 2, title: "Question–response", skill: "LISTENING", instructions: "You will hear a question or statement and three responses. Choose the best response. Nothing is printed except the answer letters.",
  groups: [{ questions: [
    heard(P2, exchange("Woman", "When does the quarterly meeting start?", ["In the main conference room.", "At nine thirty, I think.", "Yes, it was very productive."]), 3, "B", "A 'when' question needs a time: At nine thirty."),
    heard(P2, exchange("Man", "Where can I find the printer paper?", ["In the cabinet next to the copier.", "Yes, I printed it this morning.", "About two hundred pages."]), 3, "A", "A 'where' question needs a place: in the cabinet."),
    heard(P2, exchange("Woman", "Who's leading the training session tomorrow?", ["It's in Room 4.", "Mostly new employees.", "Ms. Tanaka from human resources."]), 3, "C", "A 'who' question needs a person: Ms. Tanaka."),
    heard(P2, exchange("Man", "Why was the delivery delayed?", ["The truck had engine trouble.", "To the warehouse on Pine Street.", "Please sign here."]), 3, "A", "A 'why' question needs a reason: engine trouble."),
    heard(P2, exchange("Woman", "Would you like me to book a taxi for you?", ["The station is very busy.", "Thanks, but I'll take the train.", "I've already read that book."]), 3, "B", "The reply politely declines the offer. (C) repeats the word book with a different meaning."),
    heard(P2, exchange("Man", "How long will the renovation take?", ["About three weeks.", "The lobby and the stairs.", "It's very long."]), 3, "A", "How long asks for a duration: about three weeks."),
    heard(P2, exchange("Woman", "Isn't the product launch next Monday?", ["Lunch is at noon.", "It's been moved to Wednesday.", "Yes, I launched it."]), 3, "B", "The reply corrects the information. (A) uses the similar-sounding word lunch."),
    heard(P2, exchange("Man", "Have you sent the invoice to the client?", ["An invoice number.", "She sent a nice card.", "I'll do it right after lunch."]), 3, "C", "The speaker hasn't sent it yet but says when she will."),
    heard(P2, exchange("Woman", "Which hotel are the conference guests staying at?", ["The one across from the convention center.", "For three nights.", "They're guessing."]), 3, "A", "Which hotel → the one across from the convention center."),
    heard(P2, exchange("Man", "Could you help me move these boxes?", ["The boxing match was great.", "Sure, where do they go?", "I moved last year."]), 3, "B", "The reply accepts the request and asks a follow-up question."),
    heard(P2, exchange("Woman", "The elevator is out of order again.", ["I ordered it yesterday.", "On the fifth floor.", "We'll have to take the stairs, then."]), 3, "C", "A logical reaction to the statement. (A) repeats order with a different meaning."),
    heard(P2, exchange("Man", "Do you prefer the blue design or the green one?", ["The green one looks more modern.", "Yes, I prefer it.", "He designed the logo."]), 3, "A", "A choice question is answered by choosing one option, not by yes or no."),
    heard(P2, exchange("Woman", "How much does the annual membership cost?", ["Every year in January.", "It's two hundred dollars.", "Many members."]), 3, "B", "How much asks for a price."),
    heard(P2, exchange("Man", "When will the new manager arrive?", ["She manages the Tokyo office.", "By bus from the airport.", "Not until next month."]), 3, "C", "When → not until next month."),
    heard(P2, exchange("Woman", "Why don't we order lunch for the team?", ["That's a good idea.", "In alphabetical order.", "Because it's closed."]), 3, "A", "Why don't we…? is a suggestion, so the best reply accepts it."),
    heard(P2, exchange("Man", "Where did you put the signed contracts?", ["Yes, they're signed.", "In the top drawer of my desk.", "A three-year contract."]), 3, "B", "Where → in the top drawer."),
    heard(P2, exchange("Woman", "Shouldn't we confirm the reservation first?", ["The reservoir is full.", "Six people, please.", "I already called them this morning."]), 3, "C", "The reply shows the reservation is already confirmed."),
    heard(P2, exchange("Man", "Who approved the budget for the event?", ["The finance director did.", "About five thousand dollars.", "It was an eventful day."]), 3, "A", "Who → the finance director."),
    heard(P2, exchange("Woman", "Can you send me the slides before the presentation?", ["The playground has two slides.", "I'll email them in a few minutes.", "It was presented well."]), 3, "B", "The reply agrees to the request."),
    heard(P2, exchange("Man", "How often do you back up the computer files?", ["At the back of the office.", "Several files.", "Every Friday afternoon."]), 3, "C", "How often asks for frequency."),
    heard(P2, exchange("Woman", "The client wants to reschedule our call.", ["What time works for her?", "I called him yesterday.", "On schedule."]), 3, "A", "A natural follow-up is to ask for a new time."),
    heard(P2, exchange("Man", "Are you taking the early flight or the late one?", ["It was a long flight.", "The early one, so I can rest.", "Yes, I'm taking it."]), 3, "B", "A choice question: the early one."),
    heard(P2, exchange("Woman", "What did you think of the new software?", ["It's much faster than the old one.", "I think it's on the desk.", "Software engineers."]), 3, "A", "The question asks for an opinion."),
    heard(P2, exchange("Man", "Why is the office so cold today?", ["I'll have a cold drink.", "Since last Tuesday.", "The heating system is being repaired."]), 3, "C", "The reply gives a reason."),
    heard(P2, exchange("Woman", "Let's review the report together this afternoon.", ["I'm free after three.", "A very good review.", "He reported it."]), 3, "A", "The reply accepts the suggestion and offers a time.")
  ] }]
};

const Q = (prompt: string, options: [string, string, string, string], correct: "A" | "B" | "C" | "D", explanation: string) => mcq(prompt, options, correct, explanation);

export const mock1Part3: ExamPartDef = {
  partNumber: 3, title: "Conversations", skill: "LISTENING", instructions: "You will hear conversations between two or three people. Read the questions, then listen and choose the best answer to each question. Each conversation is heard once.",
  groups: [
    { title: "Questions 32–34", listening: { voices: { Woman: "female", Man: "male" }, script: "Woman: Hi, Martin. The toner cartridges we ordered last week still haven't arrived, and the printer on our floor is almost empty.\nMan: I know. I called the supplier this morning. They said their warehouse was closed for two days because of the storm, so everything is running late.\nWoman: Did they say when we can expect them?\nMan: Thursday at the earliest. In the meantime, you could use the printer in the design department. They just got a new one.\nWoman: Good idea. I'll let the rest of the team know." }, questions: [
      Q("What problem does the woman mention?", ["A printer is broken.", "An order has not arrived.", "A meeting was cancelled.", "A bill is incorrect."], "B", "The toner cartridges they ordered still haven't arrived."),
      Q("Why was the delivery delayed?", ["The supplier was short of staff.", "The address was wrong.", "The order was lost.", "A warehouse was closed because of a storm."], "D", "Their warehouse was closed for two days because of the storm."),
      Q("What does the man suggest?", ["Ordering from a different company", "Using a printer in another department", "Printing documents at home", "Calling the supplier again"], "B", "You could use the printer in the design department.")
    ] },
    { title: "Questions 35–37", listening: { voices: { Man: "male", Woman: "female" }, script: "Man: Good afternoon, Harbor Grill. How can I help you?\nWoman: Hello. I'd like to reserve a table for eight people this Friday at seven. It's a dinner with some clients, so we'd prefer somewhere quiet.\nMan: Let me check. We're fully booked at seven, but our private room is available from seven thirty.\nWoman: The private room would be perfect. Is there an extra charge?\nMan: There's a twenty-dollar service fee, but you'd have the room to yourselves all evening.\nWoman: That's fine. Please book it under the name Chen." }, questions: [
      Q("Where does the man most likely work?", ["At a hotel", "At a travel agency", "At a restaurant", "At a catering company"], "C", "He answers the phone: Harbor Grill, and takes a table reservation."),
      Q("Why does the woman want a quiet place?", ["She is meeting clients.", "She is celebrating a birthday.", "She has a headache.", "She wants to watch a game."], "A", "It's a dinner with some clients."),
      Q("What does the man say about the private room?", ["It must be booked a week ahead.", "It holds only six people.", "It closes at nine.", "It has an additional fee."], "D", "There's a twenty-dollar service fee.")
    ] },
    { title: "Questions 38–40", listening: { voices: { Woman: "female", Man: "male" }, script: "Woman: Excuse me, I'm Priya Nair. I'm starting in the marketing department today, but my ID card doesn't open the main door.\nMan: Welcome, Ms. Nair. New cards usually take a day to activate. I can give you a visitor pass for today.\nWoman: Thank you. Do I need to do anything else?\nMan: Just fill in this form with your emergency contact details. Once it's done, security will activate your card by tomorrow morning.\nWoman: No problem. I'll bring it back before lunch." }, questions: [
      Q("Who most likely is the woman?", ["A security guard", "A new employee", "A visiting client", "A delivery driver"], "B", "She is starting in the marketing department today."),
      Q("What will the man give the woman?", ["A new laptop", "A parking permit", "A visitor pass", "A department map"], "C", "I can give you a visitor pass for today."),
      Q("What does the woman agree to do?", ["Return a form before lunch", "Call her manager", "Come back tomorrow morning", "Take a photo for her card"], "A", "I'll bring it back before lunch.")
    ] },
    { title: "Questions 41–43", listening: { voices: { Man: "male", Woman: "female", "Second man": "male" }, script: "Man: Thanks for coming, both of you. The trade fair is in three weeks, and we still need to decide who will run the product demonstrations.\nWoman: I can do the morning sessions. I've presented the new tablet to clients several times already.\nSecond man: And I'll take the afternoons. But we should have a backup device. Last year one of our demo units stopped working on the first day.\nMan: Good point. I'll ask the warehouse to send two extra tablets with the display materials.\nWoman: Also, could we print some brochures in Spanish? Many visitors come from Latin America.\nMan: I'll check the budget, but it should be possible." }, questions: [
      Q("What are the speakers mainly discussing?", ["Hiring new staff", "Repairing a device", "Choosing a hotel", "Preparing for a trade fair"], "D", "They plan who will run the demonstrations at the trade fair."),
      Q("What happened last year?", ["A demonstration unit stopped working.", "The fair was cancelled.", "Brochures arrived late.", "Few visitors attended."], "A", "Last year one of our demo units stopped working on the first day."),
      Q("What does the woman request?", ["A larger booth", "Extra tablets", "Brochures in another language", "A later start time"], "C", "Could we print some brochures in Spanish?")
    ] },
    { title: "Questions 44–46", listening: { voices: { Woman: "female", Man: "male" }, script: "Woman: Hi, this is Sara Lopez in apartment 12B. The sink in my kitchen has been leaking since last night.\nMan: I'm sorry to hear that. Our plumber is working in another building this morning, but he can come at around two o'clock. Will someone be home?\nWoman: I'll be at work, but you can use the spare key. I left it with the building manager.\nMan: All right. In the meantime, you might want to turn off the water valve under the sink.\nWoman: I already did that. Thanks." }, questions: [
      Q("Why is the woman calling?", ["To pay her rent", "To report a leak", "To request a new key", "To complain about noise"], "B", "The sink in my kitchen has been leaking."),
      Q("When will the plumber visit?", ["This morning", "Around noon", "Tomorrow", "At about two o'clock"], "D", "He can come at around two o'clock."),
      Q("What does the woman say she has already done?", ["Called a plumber", "Turned off the water", "Left work early", "Bought a new sink"], "B", "The man suggests turning off the valve; she says: I already did that.")
    ] },
    { title: "Questions 47–49", listening: { voices: { Man: "male", Woman: "female" }, script: "Man: Kate, have you booked your flights for the conference in Singapore yet?\nWoman: Not yet. The finance team hasn't approved the travel budget.\nMan: Really? Conference registration closes on Friday. If we wait much longer, the early-bird discount will end too.\nWoman: I know. I'll send the finance director a reminder today and copy you on the email.\nMan: Thanks. And if they approve it, let's book the same hotel as last year. It's right next to the venue." }, questions: [
      Q("Where will the conference be held?", ["In Bangkok", "In Seoul", "In Singapore", "In Sydney"], "C", "The conference in Singapore."),
      Q("Why is the man concerned?", ["The hotel is fully booked.", "A deadline is approaching.", "The flight was cancelled.", "The venue has changed."], "B", "Registration closes on Friday, and the early-bird discount will end."),
      Q("What will the woman do today?", ["Send a reminder email", "Book a hotel", "Register for the conference", "Meet the finance director"], "A", "I'll send the finance director a reminder today.")
    ] },
    { title: "Questions 50–52", listening: { voices: { Woman: "female", Man: "male" }, script: "Woman: Excuse me, I'm looking for a book called Designing Small Gardens. The website says you have it in stock.\nMan: Let me check the system. It says we have one copy, but it's not on the shelf. Someone may have put it in the wrong section.\nWoman: Oh. I really need it for a class that starts on Monday.\nMan: If I can't find it today, I can order one from our other store. It would arrive on Saturday.\nWoman: That works. Here's my phone number. Please call me when it's ready." }, questions: [
      Q("What does the woman want to buy?", ["A gardening tool", "A plant", "A class ticket", "A book"], "D", "She is looking for a book called Designing Small Gardens."),
      Q("What problem does the man mention?", ["The website is not working.", "The item is not where it should be.", "The price has increased.", "The store is closing early."], "B", "It's not on the shelf; someone may have put it in the wrong section."),
      Q("What does the woman give the man?", ["A receipt", "A credit card", "Her phone number", "A shopping list"], "C", "Here's my phone number.")
    ] },
    { title: "Questions 53–55", listening: { voices: { Man: "male", Woman: "female" }, script: "Man: Hi, I'm interested in joining the fitness center. Do you offer any discounts?\nWoman: Yes, we do. If you sign up for a full year, the first month is free. And if your company is one of our corporate partners, you get fifteen percent off.\nMan: I work at Brightline Engineering. Are they a partner?\nWoman: Let me see. Yes, they are. You'll just need to show your employee ID.\nMan: Great. I left it in my car. I'll go and get it now." }, questions: [
      Q("What is the man interested in?", ["Getting a job", "Repairing his car", "Buying equipment", "Joining a fitness center"], "D", "I'm interested in joining the fitness center."),
      Q("What discount do employees of corporate partners receive?", ["Ten percent off", "Fifteen percent off", "One free month", "Free parking"], "B", "You get fifteen percent off. The free month is for a one-year sign-up."),
      Q("What will the man do next?", ["Call his company", "Pay for a full year", "Get his ID from his car", "Fill out a form"], "C", "I left it in my car. I'll go and get it now.")
    ] },
    { title: "Questions 56–58", listening: { voices: { Woman: "female", Man: "male", "Second woman": "female" }, script: "Woman: So the movers are coming on Saturday. Is everyone's equipment packed?\nMan: Almost. The IT team still needs to disconnect the servers, but they'll do that on Friday evening.\nSecond woman: What about the files in the storage room? There are about fifty boxes.\nWoman: The moving company said they'd take those as well, but we need to label each box with the new room number.\nMan: I can print the labels this afternoon.\nSecond woman: Great. I'll start labeling them tomorrow morning." }, questions: [
      Q("When will the office move take place?", ["On Friday", "On Saturday", "On Sunday", "Tomorrow morning"], "B", "The movers are coming on Saturday."),
      Q("What will the IT team do on Friday evening?", ["Disconnect the servers", "Pack the files", "Print labels", "Order new computers"], "A", "They'll disconnect the servers on Friday evening."),
      Q("What does the man offer to do?", ["Move the boxes", "Call the moving company", "Clean the storage room", "Print labels"], "D", "I can print the labels this afternoon.")
    ] },
    { title: "Questions 59–61", listening: { voices: { Man: "male", Woman: "female" }, script: "Man: Hello, I bought a coffee maker from your online store last week, and it arrived with a crack in the glass jug.\nWoman: I'm very sorry about that. Do you have your order number?\nMan: Yes, it's 4-7-7-2-1.\nWoman: Thank you. I can send you a replacement jug right away, or, if you prefer, you can return the whole machine for a full refund.\nMan: I'll take the replacement jug. The machine itself works fine.\nWoman: No problem. It should reach you within three business days." }, questions: [
      Q("What is the problem with the product?", ["It is the wrong color.", "It stopped working.", "Part of it is cracked.", "It arrived late."], "C", "It arrived with a crack in the glass jug."),
      Q("What does the woman ask for?", ["A photograph", "An order number", "A delivery address", "A credit card number"], "B", "Do you have your order number?"),
      Q("What will the man receive?", ["A replacement part", "A full refund", "A new coffee maker", "A discount code"], "A", "He chooses the replacement jug.")
    ] },
    { title: "Questions 62–64", image: graphic({ name: "westfield-directory", title: "Westfield Tower directory", columns: ["Floor", "Company"], rows: [["2", "Apex Accounting"], ["3", "Lumen Design Studio"], ["4", "Harper & Cole Law"], ["5", "Nova Health Clinic"]] }), listening: { voices: { Woman: "female", Man: "male" }, script: "Woman: Hi, I have a two o'clock appointment, but I'm not sure which floor to go to.\nMan: Which company are you visiting?\nWoman: It's a design studio. I'm interviewing for a graphic designer position.\nMan: Ah, yes. The elevators are just behind you, but the one on the left is being serviced today, so please use the one on the right.\nWoman: Thanks. Should I sign in first?\nMan: Yes, please write your name here, and I'll print you a visitor badge." }, questions: [
      Q("Why is the woman visiting the building?", ["To see a doctor", "To deliver a package", "To attend a job interview", "To meet a lawyer"], "C", "I'm interviewing for a graphic designer position."),
      Q("Look at the graphic. Which floor will the woman go to?", ["Floor 2", "Floor 3", "Floor 4", "Floor 5"], "B", "She is visiting a design studio; Lumen Design Studio is on floor 3."),
      Q("What does the man say about one of the elevators?", ["It is very slow.", "It needs a key card.", "It only goes to the lobby.", "It is being serviced."], "D", "The one on the left is being serviced today.")
    ] },
    { title: "Questions 65–67", image: graphic({ name: "quickprint-prices", title: "QuickPrint price list (per 100 copies)", columns: ["Service", "Price"], rows: [["Black and white", "$8"], ["Color, one side", "$25"], ["Color, double-sided", "$40"], ["Poster size", "$60"]] }), listening: { voices: { Man: "male", Woman: "female" }, script: "Man: Hi, I need to print flyers for our store's grand opening. About three hundred copies.\nWoman: Sure. Would you like them in color or black and white?\nMan: Color, definitely. And printed on one side only. The back will be blank.\nWoman: No problem. When do you need them?\nMan: By Thursday morning, if possible. The opening is on Thursday afternoon.\nWoman: We can have them ready by Wednesday evening." }, questions: [
      Q("What is the man preparing for?", ["A trade fair", "A store opening", "A retirement party", "A sports event"], "B", "Flyers for our store's grand opening."),
      Q("Look at the graphic. How much will the man pay per 100 copies?", ["$8", "$25", "$40", "$60"], "B", "Color, printed on one side only: $25 per 100 copies."),
      Q("When will the flyers be ready?", ["Thursday morning", "Thursday afternoon", "Friday", "Wednesday evening"], "D", "We can have them ready by Wednesday evening.")
    ] },
    { title: "Questions 68–70", image: graphic({ name: "central-departures", title: "Central Station departures", columns: ["Train", "Destination", "Departs", "Platform"], rows: [["R12", "Riverside", "10:05", "3"], ["E7", "Airport", "10:20", "5"], ["R14", "Riverside", "10:35", "3"], ["E9", "Airport", "10:50", "5"]] }), listening: { voices: { Woman: "female", Man: "male" }, script: "Woman: Excuse me, is this the right platform for the airport train?\nMan: Yes, the airport trains leave from here. But the next one was just cancelled. There's a problem with the signals.\nWoman: Oh no. My flight leaves at one o'clock. Will the one after that still run?\nMan: As far as I know, yes. You'll have plenty of time if you take it.\nWoman: Thanks. I'll get a coffee while I wait." }, questions: [
      Q("Where most likely are the speakers?", ["At an airport", "At a train station", "On a bus", "In a hotel"], "B", "They talk about the platform and airport trains."),
      Q("Why was a train cancelled?", ["Bad weather", "A shortage of staff", "A signal problem", "Track repairs"], "C", "There's a problem with the signals."),
      Q("Look at the graphic. What time will the woman's train leave?", ["10:05", "10:20", "10:35", "10:50"], "D", "The next airport train (10:20) was cancelled, so she will take the following one at 10:50.")
    ] }
  ]
};

export const mock1Part4: ExamPartDef = {
  partNumber: 4, title: "Short talks", skill: "LISTENING", instructions: "You will hear short talks given by a single speaker. Read the questions, then listen and choose the best answer to each question. Each talk is heard once.",
  groups: [
    { title: "Questions 71–73", listening: { voices: { Speaker: "female" }, script: "Speaker: Hello, this message is for Mr. Daniel Ortiz. This is Anna from Brightsmile Dental Clinic. I'm calling about your check-up appointment on Tuesday at ten a.m. Unfortunately, Dr. Mehta will be at a training course that day, so we need to move your appointment. We have openings on Wednesday at nine or Thursday at three. Please call us back at 555-0142 to let us know which time you prefer. Also, as you are a new patient, please arrive fifteen minutes early to complete some forms. Thank you." }, questions: [
      Q("Why is the speaker calling?", ["To confirm a payment", "To reschedule an appointment", "To advertise a service", "To cancel a training course"], "B", "We need to move your appointment."),
      Q("Why is Dr. Mehta unavailable on Tuesday?", ["She is on vacation.", "She is sick.", "She will attend a training course.", "She is moving to a new clinic."], "C", "Dr. Mehta will be at a training course that day."),
      Q("What is the listener asked to do?", ["Arrive early to fill out forms", "Bring his insurance card", "Pay a deposit", "Visit the clinic website"], "A", "Please arrive fifteen minutes early to complete some forms.")
    ] },
    { title: "Questions 74–76", listening: { voices: { Speaker: "male" }, script: "Speaker: Attention, passengers on Pacific Airways flight 382 to Vancouver. Please note that this flight will now depart from Gate 27 instead of Gate 14. The new gate is in Terminal B, about a ten-minute walk from here, so we recommend that you start moving now. Boarding will begin at four fifteen. Passengers traveling with small children or needing extra assistance are invited to board first. We apologize for any inconvenience, and thank you for flying with Pacific Airways." }, questions: [
      Q("Where is the announcement being made?", ["At a train station", "At a bus terminal", "At a ferry port", "At an airport"], "D", "It is for passengers on a flight and mentions gates and terminals."),
      Q("What has changed?", ["The departure gate", "The destination", "The departure date", "The airline"], "A", "The flight will now depart from Gate 27 instead of Gate 14."),
      Q("Who is invited to board first?", ["Business-class passengers", "Passengers with small children", "Airline employees", "Passengers without luggage"], "B", "Passengers traveling with small children or needing extra assistance board first.")
    ] },
    { title: "Questions 77–79", listening: { voices: { Speaker: "female" }, script: "Speaker: Good morning, this is Lisa Park with your seven thirty traffic update. Drivers heading downtown on Route 9 should expect delays of up to twenty minutes because of roadwork near the Maple Avenue exit. Two lanes are closed until Friday. If possible, take the Riverside Expressway instead. Meanwhile, the city has announced that the new bus lane on Fifth Street will open next Monday, which officials hope will reduce traffic in the city center. I'll be back with another update in half an hour." }, questions: [
      Q("What is causing delays on Route 9?", ["An accident", "Bad weather", "Roadwork", "A parade"], "C", "Delays because of roadwork near the Maple Avenue exit."),
      Q("What does the speaker recommend?", ["Using a different road", "Leaving home earlier", "Taking the train", "Working from home"], "A", "If possible, take the Riverside Expressway instead."),
      Q("What will happen next Monday?", ["Route 9 will reopen.", "A new bus lane will open.", "Parking fees will increase.", "A bridge will close."], "B", "The new bus lane on Fifth Street will open next Monday.")
    ] },
    { title: "Questions 80–82", listening: { voices: { Speaker: "male" }, script: "Speaker: Before we start today's meeting, I want to talk about the new expense system. From the first of next month, all travel and meal expenses must be submitted through the online app instead of on paper forms. The app lets you take a photo of your receipt, so you won't need to keep the originals. Payments should also be faster, usually within five working days. On Thursday afternoon, Mei from the finance team will run a short training session in Room 204. I strongly recommend attending, especially if you travel often." }, questions: [
      Q("What is the speaker mainly discussing?", ["A new way to submit expenses", "A change in travel destinations", "A budget cut", "A new meal policy"], "A", "All expenses must be submitted through the online app."),
      Q("According to the speaker, what is one advantage of the new system?", ["Employees can travel more.", "Receipts are no longer needed at all.", "Payments will be faster.", "Meals will be free."], "C", "Payments should also be faster, usually within five working days."),
      Q("What will happen on Thursday afternoon?", ["The app will be updated.", "A training session will be held.", "Paper forms will be collected.", "The finance team will move offices."], "B", "Mei will run a short training session in Room 204.")
    ] },
    { title: "Questions 83–85", listening: { voices: { Speaker: "female" }, script: "Speaker: Is your home office ready for the new year? This weekend only, Carlton Furniture is holding its biggest sale of the season. Get thirty percent off all desks and office chairs, and forty percent off selected bookshelves. Every purchase over five hundred dollars comes with free delivery and assembly. Not sure what fits your space? Bring a photo and the measurements of your room, and our designers will help you plan it at no extra cost. Carlton Furniture, on Oak Street, open from nine to nine, Saturday and Sunday." }, questions: [
      Q("What is being advertised?", ["A furniture sale", "An interior design course", "A new office building", "A moving service"], "A", "Carlton Furniture is holding its biggest sale of the season."),
      Q("What do customers receive with purchases over $500?", ["A free chair", "An extra discount", "A gift card", "Free delivery and assembly"], "D", "Every purchase over five hundred dollars comes with free delivery and assembly."),
      Q("Why should customers bring a photo of their room?", ["To enter a contest", "To get help planning their space", "To receive a refund", "To join a membership program"], "B", "Our designers will help you plan it at no extra cost.")
    ] },
    { title: "Questions 86–88", listening: { voices: { Speaker: "male" }, script: "Speaker: Welcome to the Maritime History Museum. My name is Tom, and I'll be your guide for the next hour. We'll begin in the harbor gallery, where you can see models of the ships that traded in this port two hundred years ago. After that, we'll visit the lighthouse exhibit on the second floor. Please note that photography is allowed everywhere except in the map room, because bright flashes can damage the old paper. At the end of the tour, you're welcome to visit our gift shop, where tour guests receive ten percent off." }, questions: [
      Q("Who most likely is the speaker?", ["A ship captain", "A museum guide", "A shop assistant", "A photographer"], "B", "I'll be your guide for the next hour."),
      Q("Why is photography not allowed in the map room?", ["The room is too dark.", "The maps are for sale.", "Flashes can damage old paper.", "The room is closed today."], "C", "Bright flashes can damage the old paper."),
      Q("What do tour guests receive?", ["A free map", "A discount at the gift shop", "A ticket for a boat trip", "A lighthouse model"], "B", "Tour guests receive ten percent off at the gift shop.")
    ] },
    { title: "Questions 89–91", listening: { voices: { Speaker: "female" }, script: "Speaker: In business news, the electric bicycle maker Voltway has announced that it will open a new factory just outside the city next spring. The company says the plant will create around four hundred jobs, most of them in manufacturing and quality control. Voltway chose the location because of its access to the port, which will make it easier to export bicycles overseas. The mayor welcomed the decision, saying it will help the region become a center for green technology. Construction is scheduled to begin in March." }, questions: [
      Q("What does Voltway produce?", ["Electric bicycles", "Solar panels", "Delivery vans", "Batteries for phones"], "A", "The electric bicycle maker Voltway."),
      Q("Why did the company choose the location?", ["Land was cheap.", "It has access to the port.", "The mayor offered funding.", "It is close to a university."], "B", "Because of its access to the port, which makes exporting easier."),
      Q("When will construction begin?", ["In January", "In March", "Next summer", "Next spring"], "B", "Construction is scheduled to begin in March.")
    ] },
    { title: "Questions 92–94", listening: { voices: { Speaker: "male" }, script: "Speaker: Thank you all for coming this evening to celebrate Margaret Ellis, who is retiring after twenty-five years with our company. Margaret joined us as a sales assistant and went on to lead our international sales team, opening offices in three new countries. Many of you know her as the person who started our mentoring program, which has helped more than a hundred new employees. Margaret, we'll miss your energy and your advice. Now, before we have dinner, I'd like to invite you up to say a few words." }, questions: [
      Q("What is the purpose of the event?", ["To welcome a new employee", "To celebrate a retirement", "To open a new office", "To announce an award winner"], "B", "To celebrate Margaret Ellis, who is retiring."),
      Q("What did Margaret start at the company?", ["A mentoring program", "A sales conference", "An online store", "A training center abroad"], "A", "She started our mentoring program."),
      Q("What will most likely happen next?", ["Dinner will be served.", "A video will be shown.", "Margaret will give a speech.", "Guests will leave."], "C", "I'd like to invite you up to say a few words.")
    ] },
    { title: "Questions 95–97", image: graphic({ name: "weekend-forecast", title: "Weekend forecast", columns: ["Day", "Weather", "High"], rows: [["Friday", "Sunny", "27°C"], ["Saturday", "Heavy rain", "22°C"], ["Sunday", "Cloudy", "24°C"], ["Monday", "Sunny", "28°C"]] }), listening: { voices: { Speaker: "female" }, script: "Speaker: Hi everyone, it's Grace from the events committee. I'm calling about our company picnic at Lakeside Park. As you know, it was planned for Saturday, but the forecast shows heavy rain that day, so we've decided to move it to the next day. The weather won't be perfect, but at least it should stay dry. Lunch will still be provided, and the park's covered picnic area is reserved from eleven. Please remember to bring your own chairs if you'd like to sit by the lake. See you there!" }, questions: [
      Q("What event is the speaker discussing?", ["A product launch", "A company picnic", "A sports competition", "A training course"], "B", "Our company picnic at Lakeside Park."),
      Q("Look at the graphic. What will the weather be like on the day of the event?", ["Sunny", "Heavy rain", "Cloudy", "Windy"], "C", "The picnic moves from Saturday to the next day, Sunday, which is cloudy."),
      Q("What are listeners asked to bring?", ["Their own chairs", "Food to share", "Umbrellas", "Sports equipment"], "A", "Please remember to bring your own chairs.")
    ] },
    { title: "Questions 98–100", image: graphic({ name: "conference-schedule", title: "Retail Innovation Conference — Day 1", columns: ["Time", "Session", "Room"], rows: [["9:00", "Opening keynote", "Hall A"], ["10:30", "Online sales trends", "Room 2"], ["1:00", "Customer data and privacy", "Room 5"], ["3:00", "Designing better stores", "Room 3"]] }), listening: { voices: { Speaker: "male" }, script: "Speaker: Good morning and welcome to the Retail Innovation Conference. Before the opening keynote begins, I have one announcement. The speaker for the session on customer data and privacy has been delayed by a flight problem. Her session will now start two hours later than planned, in the same room. We apologize for the change. Also, lunch will be served in the main lobby at twelve. Wi-Fi details are printed on the back of your name badges." }, questions: [
      Q("Why was a session rescheduled?", ["The room was double-booked.", "A speaker was delayed by a flight problem.", "The equipment was not working.", "Few people registered."], "B", "The speaker has been delayed by a flight problem."),
      Q("Look at the graphic. What time will the rescheduled session start?", ["9:00", "10:30", "1:00", "3:00"], "D", "Customer data and privacy was at 1:00; two hours later is 3:00."),
      Q("Where can listeners find the Wi-Fi details?", ["On the back of their name badges", "In the main lobby", "On the conference website", "At the registration desk"], "A", "Wi-Fi details are printed on the back of your name badges.")
    ] }
  ]
};
