import { mcq, type ExamPartDef } from "../types";

const R = (prompt: string, options: [string, string, string, string], correct: "A" | "B" | "C" | "D", explanation: string) => mcq(prompt, options, correct, explanation);
const POSITIONS: [string, string, string, string] = ["[1]", "[2]", "[3]", "[4]"];
const insert = (sentence: string, correct: "A" | "B" | "C" | "D", explanation: string) => R(`In which of the positions marked [1], [2], [3], and [4] does the following sentence best belong? "${sentence}"`, POSITIONS, correct, explanation);

export const mock1Part7: ExamPartDef = {
  partNumber: 7, title: "Reading comprehension", skill: "READING", instructions: "Read a selection of texts, such as notices, e-mails, articles and chats. Each text or set of texts is followed by questions. Choose the best answer to each question.",
  groups: [
    { title: "Questions 147–148 refer to the following notice.", passage: "NOTICE TO ALL TENANTS — HARBORVIEW OFFICE PARK\n\nThe north parking lot will be resurfaced on Saturday, October 12, and Sunday, October 13. No vehicles may be parked there from 6 P.M. on Friday until 7 A.M. on Monday. Any vehicle left in the lot will be towed at the owner's expense.\n\nDuring the work, tenants may park in the south lot or in the public garage on Bay Street, where Harborview parking permits will be accepted free of charge.", questions: [
      R("What is the purpose of the notice?", ["To announce the opening of a new garage", "To inform tenants about temporary parking restrictions", "To explain an increase in parking fees", "To request volunteers for a cleanup"], "B", "The north lot will be closed for resurfacing over the weekend."),
      R("What is stated about the public garage on Bay Street?", ["It will be closed on Sunday.", "It is only for visitors.", "It will accept Harborview permits for free.", "It opens at 7 A.M. on Monday."], "C", "Harborview parking permits will be accepted free of charge.")
    ] },
    { title: "Questions 149–150 refer to the following advertisement.", passage: "LINGUA BRIDGE LANGUAGE CENTER\n\nNeed English, Japanese, or Korean for your career? Our evening courses are designed for busy professionals.\n\n• Small classes of no more than eight students\n• Business-focused lessons: meetings, presentations, e-mails\n• Classes on Tuesdays and Thursdays, 6:30–8:30 P.M.\n\nSign up before August 20 and receive a free placement test and course book. Companies that enroll three or more employees receive 15 percent off the total fee.\n\nVisit linguabridge.example.com or call 555-0163.", questions: [
      R("Who is the advertisement mainly intended for?", ["University students", "Working professionals", "Young children", "Tourists"], "B", "Evening courses designed for busy professionals."),
      R("What will people who sign up before August 20 receive?", ["A discount of 15 percent", "A free trial class", "A placement test and a course book", "A certificate"], "C", "Sign up before August 20 and receive a free placement test and course book.")
    ] },
    { title: "Questions 151–152 refer to the following text-message chain.", passage: "Diego Alvarez [9:12 A.M.]: Hi Mia, the client from Lindgren Foods just called. They want to move our 2 P.M. meeting to 11 A.M.\nMia Chen [9:14 A.M.]: That's tight. I still need to update the sales figures in the presentation.\nDiego Alvarez [9:15 A.M.]: I can do the charts if you send me the numbers.\nMia Chen [9:16 A.M.]: You're a lifesaver. Sending them now.\nDiego Alvarez [9:17 A.M.]: Got them. I'll have the slides ready by 10:30.", questions: [
      R("Why did Mr. Alvarez contact Ms. Chen?", ["A meeting time has changed.", "A client has cancelled an order.", "The sales figures are incorrect.", "A presentation was lost."], "A", "The client wants to move the meeting from 2 P.M. to 11 A.M."),
      R("At 9:16 A.M., what does Ms. Chen most likely mean when she writes, \"You're a lifesaver\"?", ["She is worried about her health.", "She is grateful for Mr. Alvarez's help.", "She wants to cancel the meeting.", "She thinks the charts are wrong."], "B", "Mr. Alvarez offers to make the charts, and she thanks him.")
    ] },
    { title: "Questions 153–155 refer to the following e-mail.", passage: "To: Rahul Mehta\nFrom: Olivia Grant, Human Resources, Castell Engineering\nSubject: Job offer\n\nDear Mr. Mehta,\n\nThank you for meeting with our team last week. I am pleased to offer you the position of project coordinator in our Denver office, starting on Monday, May 5.\n\nAs discussed, the position includes a starting salary of $62,000 per year, health insurance, and twenty days of paid vacation. You will spend your first two weeks in training at our headquarters in Chicago; your travel and hotel costs will be covered by the company.\n\nPlease confirm whether you accept this offer by April 18. If you have any questions, you can reach me directly at 555-0119.\n\nSincerely,\nOlivia Grant", questions: [
      R("What is the main purpose of the e-mail?", ["To schedule an interview", "To offer Mr. Mehta a job", "To explain a change in salary", "To request travel receipts"], "B", "I am pleased to offer you the position of project coordinator."),
      R("Where will Mr. Mehta spend his first two weeks?", ["In Denver", "In Chicago", "At a hotel in Denver", "At a client's office"], "B", "Your first two weeks in training at our headquarters in Chicago."),
      R("What is Mr. Mehta asked to do by April 18?", ["Complete a training course", "Send his travel plans", "Confirm whether he accepts the offer", "Call the Chicago office"], "C", "Please confirm whether you accept this offer by April 18.")
    ] },
    { title: "Questions 156–158 refer to the following article.", passage: "Local Bakery Rises to the Occasion\n\nWhen Sophie Laurent opened Crumb & Co. in a tiny shop on Elm Street six years ago, she baked everything herself before sunrise. — [1] — Today, the bakery employs fourteen people and supplies bread to nine cafés across the city.\n\nNext month, Crumb & Co. will move to a larger building on Market Square that includes a seating area for forty customers. — [2] — Ms. Laurent says the new space will also allow her to offer baking classes on weekends.\n\n\"Our customers kept asking where they could sit and enjoy their coffee,\" she explained. — [3] — The Elm Street shop will remain open as a takeaway counter.\n\nThe new location will open on June 2. — [4] — The first fifty customers will receive a free loaf of the bakery's famous sourdough.", questions: [
      R("What is the article mainly about?", ["A bakery that is expanding", "A new café chain", "A cooking competition", "A shop that is closing"], "A", "Crumb & Co. is moving to a larger building while keeping its original shop."),
      R("What is NOT mentioned as a feature of the new location?", ["A seating area", "Weekend baking classes", "A larger space", "A delivery service"], "D", "Seating, weekend classes and more space are mentioned; delivery is not."),
      insert("Finally, we will be able to give them that.", "C", "It follows the quotation about customers wanting somewhere to sit.")
    ] },
    { title: "Questions 159–161 refer to the following memo.", passage: "MEMO\nTo: All sales staff\nFrom: Paulo Ferreira, Finance Director\nDate: February 3\nSubject: Updated travel policy\n\nEffective March 1, the following changes will apply to business travel:\n\n1. Flights of less than four hours must be booked in economy class.\n2. Hotel costs will be reimbursed up to $180 per night, instead of the current $150.\n3. Employees must book all travel through our online portal at least ten days in advance, except in urgent cases approved by a department head.\n\nThese changes are intended to control costs while reflecting the higher hotel prices in many cities. Please direct any questions to the finance team.", questions: [
      R("What is the purpose of the memo?", ["To announce a sales competition", "To describe changes to a travel policy", "To introduce a new finance director", "To cancel upcoming business trips"], "B", "It lists changes that apply to business travel."),
      R("What is indicated about hotel reimbursement?", ["It will be reduced.", "It will increase to $180 per night.", "It will no longer be offered.", "It depends on the length of the flight."], "B", "Up to $180 per night, instead of the current $150."),
      R("When may employees book travel less than ten days in advance?", ["When the flight is under four hours", "When the trip is urgent and approved by a department head", "When they travel in economy class", "When they use the online portal"], "B", "Except in urgent cases approved by a department head.")
    ] },
    { title: "Questions 162–164 refer to the following online review.", passage: "Riverside Inn — ★★★★☆\nReviewed by K. Tanaka\n\nI stayed at the Riverside Inn for three nights while attending a conference. The location is excellent: the convention center is a five-minute walk away, and there are plenty of restaurants nearby. My room was clean and quiet, and the staff at the front desk were extremely helpful when I needed to print documents late at night.\n\nMy only complaint is breakfast. It was included in the price, but the choice was limited, and by 8:30 most of the hot dishes had run out. Next time I will probably eat at one of the cafés on the riverfront instead. Overall, I would still recommend this hotel to business travelers.", questions: [
      R("Why did Mr. Tanaka stay at the Riverside Inn?", ["He was on vacation.", "He was attending a conference.", "He was visiting relatives.", "He was looking for a new apartment."], "B", "While attending a conference."),
      R("What did Mr. Tanaka like about the hotel?", ["Its breakfast", "Its swimming pool", "Its helpful staff", "Its low prices"], "C", "The staff were extremely helpful when he needed to print documents."),
      R("What problem does Mr. Tanaka mention?", ["His room was noisy.", "Breakfast food ran out early.", "The hotel was far from the convention center.", "He was charged for breakfast."], "B", "By 8:30 most of the hot dishes had run out.")
    ] },
    { title: "Questions 165–167 refer to the following Web page.", passage: "Northbrook Science Museum — Membership\n\nBecome a member and enjoy the museum all year round!\n\nIndividual — $45 per year: unlimited free entry for one adult; 10% off in the museum shop.\nFamily — $110 per year: unlimited free entry for two adults and up to three children; 10% off in the museum shop; one free guest pass per visit.\nPatron — $250 per year: all Family benefits, plus invitations to exhibition previews and a behind-the-scenes tour of our laboratories.\n\nMemberships can be purchased online or at the ticket desk. Members who renew before their membership expires receive one additional month free.", questions: [
      R("What benefit is included in all memberships?", ["A free guest pass", "A discount in the museum shop", "A behind-the-scenes tour", "Exhibition previews"], "B", "10% off in the museum shop is listed for every level (Patron includes all Family benefits)."),
      R("How much does a membership for two adults and two children cost?", ["$45", "$90", "$110", "$250"], "C", "The Family membership covers two adults and up to three children for $110."),
      R("How can members receive an extra free month?", ["By buying online", "By renewing before their membership expires", "By bringing a guest", "By joining a laboratory tour"], "B", "Members who renew before their membership expires receive one additional month free.")
    ] },
    { title: "Questions 168–171 refer to the following online chat discussion.", passage: "Laura Kim [2:03 P.M.]: Hi team, quick update on the Delgado Hotel website. The client approved the design, but they want the online booking page to go live by the end of next week instead of next month.\nOmar Haddad [2:05 P.M.]: That's a big change. The payment system hasn't been tested yet.\nLaura Kim [2:06 P.M.]: I know. Omar, how long would testing take?\nOmar Haddad [2:07 P.M.]: At least three days if nothing goes wrong.\nGrace Liu [2:08 P.M.]: I can help with testing on Monday and Tuesday. The photo gallery is finished, so I have time.\nLaura Kim [2:09 P.M.]: Great. Then let's aim for Thursday. I'll tell the client the booking page will be ready, but the restaurant menu page may follow a week later.\nOmar Haddad [2:10 P.M.]: That sounds realistic.", questions: [
      R("What does the client want?", ["A new website design", "An earlier launch of the booking page", "A lower price", "A different payment system"], "B", "They want the booking page to go live by the end of next week instead of next month."),
      R("What is Mr. Haddad concerned about?", ["The photo gallery is incomplete.", "The payment system has not been tested.", "The client has not approved the design.", "The team is too large."], "B", "The payment system hasn't been tested yet."),
      R("Why is Ms. Liu able to help?", ["She has finished her part of the project.", "She designed the payment system.", "She is the client's manager.", "She is on vacation next week."], "A", "The photo gallery is finished, so I have time."),
      R("At 2:10 P.M., what does Mr. Haddad mean when he writes, \"That sounds realistic\"?", ["He thinks the plan is achievable.", "He wants to change the design.", "He disagrees with Ms. Kim.", "He will contact the client himself."], "A", "He agrees that aiming for Thursday, with the menu page later, is possible.")
    ] },
    { title: "Questions 172–175 refer to the following article.", passage: "Working From Anywhere, Together\n\nWhen software company Brightloop allowed its 300 employees to work from home permanently in 2023, managers worried that teams would lose contact with each other. — [1] — Instead, the company says, productivity has stayed the same while staff turnover has fallen by nearly half.\n\nThe key, according to chief operating officer Naomi Brandt, is that remote does not mean alone. Every team meets in person for two days each quarter, and the company pays for travel and accommodation. — [2] — Brightloop also gives each employee an annual allowance of $1,000 to improve their home office or to rent a desk in a shared workspace.\n\nNot every experiment has worked. An attempt to hold all meetings in a virtual reality app was abandoned after a month. — [3] — \"People found the headsets uncomfortable, and the novelty wore off quickly,\" Ms. Brandt admitted.\n\nThe company now plans to publish its internal guidelines so that other businesses can learn from its experience. — [4] —", questions: [
      R("What is the article mainly about?", ["A company's approach to remote work", "The launch of a new software product", "The rising cost of office space", "A virtual reality company"], "A", "It describes how Brightloop manages permanent remote work."),
      R("According to the article, what has happened since 2023?", ["Productivity has fallen sharply.", "Staff turnover has decreased.", "The company has hired 300 people.", "Employees have returned to the office."], "B", "Staff turnover has fallen by nearly half."),
      R("What does Brightloop provide each employee every year?", ["A virtual reality headset", "A company car", "An allowance for a home office or shared workspace", "Two extra days of vacation"], "C", "An annual allowance of $1,000 to improve their home office or rent a desk."),
      insert("These gatherings are used for planning and team-building rather than routine work.", "B", "It follows the sentence about teams meeting in person each quarter.")
    ] },
    { title: "Questions 176–180 refer to the following advertisement and e-mail.", passage: "Text 1 — Advertisement\n\nSMALL BUSINESS GROWTH SUMMIT\nJuly 15–16, Grandview Convention Center\n\nJoin more than 800 entrepreneurs for two days of practical workshops on marketing, finance, and hiring.\n\nRegistration fees:\n• Full two-day pass: $240 ($199 if you register by June 15)\n• One-day pass: $140\n• Groups of five or more: 20% off full passes\n\nAll passes include lunch and access to the exhibition hall. Workshop seats are limited and are assigned in the order that registrations are received.\n\nText 2 — E-mail\n\nTo: registration@growthsummit.example.com\nFrom: Hye-jin Park, Park & Sons Stationery\nDate: June 20\nSubject: Registration question\n\nHello,\n\nI would like to register for both days of the summit. I tried to use the early registration price on your Web site, but it was not accepted. Is there any way I could still receive the discount? Also, I am especially interested in the workshop on hiring, which I understand is on the second day. Could you tell me if seats are still available?\n\nThank you,\nHye-jin Park", questions: [
      R("What is indicated about the summit?", ["It lasts one week.", "Lunch is included in all passes.", "It is only for large companies.", "Workshop seats are unlimited."], "B", "All passes include lunch and access to the exhibition hall."),
      R("How many people are expected to attend?", ["About 200", "About 500", "More than 800", "More than 2,000"], "C", "Join more than 800 entrepreneurs."),
      R("Why was Ms. Park unable to get the lower price?", ["She registered after the deadline.", "She chose a one-day pass.", "She did not register as part of a group.", "The Web site was closed."], "A", "The early price ($199) required registration by June 15; she wrote on June 20."),
      R("How much will Ms. Park most likely pay?", ["$140", "$199", "$240", "$280"], "C", "She wants both days and missed the early deadline: $240."),
      R("What does Ms. Park want to know?", ["Whether seats remain for a specific workshop", "Where the convention center is", "Whether she can bring her sons", "When the exhibition hall opens"], "A", "Could you tell me if seats are still available (for the hiring workshop)?")
    ] },
    { title: "Questions 181–185 refer to the following job posting and e-mail.", passage: "Text 1 — Job posting\n\nMARLOWE OUTDOOR GEAR — Store Supervisor (Westgate Mall branch)\n\nWe are looking for an experienced supervisor to lead a team of twelve sales associates.\n\nRequirements:\n• At least two years of experience supervising staff in a retail store\n• Ability to work weekends and some evenings\n• Knowledge of camping or hiking equipment is an advantage\n\nThe successful candidate will manage schedules, train new staff, and monitor stock levels. To apply, send your résumé and a cover letter to jobs@marlowe.example.com by May 10. Interviews will take place during the week of May 17.\n\nText 2 — E-mail\n\nTo: jobs@marlowe.example.com\nFrom: Tomás Rivera\nDate: May 6\nSubject: Store Supervisor application\n\nDear Hiring Manager,\n\nPlease find attached my résumé and cover letter for the Store Supervisor position at your Westgate Mall branch. For the past three years, I have supervised a team of eight at a sporting goods store, where I also designed a new training program for part-time staff. I am a keen hiker and have led weekend hiking groups for our local club since 2019.\n\nI should mention that I will be away at a family event from May 16 to May 18, but I am available at any other time.\n\nBest regards,\nTomás Rivera", questions: [
      R("What is one responsibility of the store supervisor?", ["Designing store layouts", "Managing staff schedules", "Buying equipment from suppliers", "Organizing hiking trips"], "B", "The candidate will manage schedules, train new staff, and monitor stock levels."),
      R("What is suggested about Mr. Rivera?", ["He has more supervisory experience than required.", "He has never worked in retail.", "He prefers to work only on weekdays.", "He currently works for Marlowe."], "A", "He has supervised staff for three years; the posting requires at least two."),
      R("What qualification does Mr. Rivera have that the posting describes as an advantage?", ["A university degree", "Knowledge of hiking", "Experience in a large mall", "The ability to speak several languages"], "B", "He is a keen hiker; knowledge of camping or hiking equipment is an advantage."),
      R("In the e-mail, the word \"keen\" in paragraph 1, line 3, is closest in meaning to", ["sharp", "enthusiastic", "careful", "early"], "B", "A keen hiker = an enthusiastic hiker."),
      R("What might be a problem for Mr. Rivera's application?", ["He applied after the deadline.", "He may not be available on some interview days.", "He did not include a résumé.", "He cannot work weekends."], "B", "He is away May 16–18, during the interview week of May 17.")
    ] },
    { title: "Questions 186–190 refer to the following Web page, order form, and e-mail.", passage: "Text 1 — Web page\n\nGREEN TABLE CATERING — Office Lunch Menu\nSandwich platter (serves 10): $85\nSalad bowl (serves 8): $60\nHot pasta tray (serves 12): $110\nFruit platter (serves 10): $45\nFree delivery for orders over $200 within the city. Orders must be placed at least 48 hours in advance.\n\nText 2 — Order form\n\nCustomer: Lena Novak, Pellan Architects\nDelivery date: Thursday, September 12, 12:00 P.M.\nItems: 2 sandwich platters, 1 salad bowl, 1 fruit platter\nSpecial instructions: Please label any dishes that contain nuts.\n\nText 3 — E-mail\n\nTo: orders@greentable.example.com\nFrom: Lena Novak\nDate: September 12\nSubject: Today's delivery\n\nHello,\n\nOur lunch arrived on time, and everyone enjoyed the food. However, we were charged a delivery fee of $15, even though our order qualified for free delivery. Also, one of the salads contained walnuts but was not labeled, and a colleague with an allergy nearly ate it. Please make sure this does not happen again, and refund the delivery fee to our account.\n\nThank you,\nLena Novak", questions: [
      R("According to the Web page, what is required for all orders?", ["A minimum of ten people", "Payment by credit card", "Ordering at least 48 hours in advance", "Pickup from the restaurant"], "C", "Orders must be placed at least 48 hours in advance."),
      R("What is the total cost of the food Ms. Novak ordered?", ["$190", "$230", "$275", "$320"], "C", "2 × $85 + $60 + $45 = $275."),
      R("Why does Ms. Novak believe the delivery should have been free?", ["The order was over $200.", "The delivery was late.", "Her company has a contract.", "The office is outside the city."], "A", "Free delivery for orders over $200; her order was $275."),
      R("What problem with the food does Ms. Novak mention?", ["It was cold.", "A dish was not labeled as containing nuts.", "An item was missing.", "The portions were too small."], "B", "A salad contained walnuts but was not labeled."),
      R("What does Ms. Novak request?", ["A replacement lunch", "A refund of the delivery fee", "A discount on her next order", "A new delivery time"], "B", "Refund the delivery fee to our account.")
    ] },
    { title: "Questions 191–195 refer to the following schedule, e-mail, and text message.", passage: "Text 1 — Schedule\n\nCITY ARTS CENTER — Autumn Photography Workshops (Saturdays)\nOctober 5 — Portrait Lighting — Studio A — Instructor: Ben Okafor\nOctober 12 — Street Photography — meet at the main entrance — Instructor: Ana Sousa\nOctober 19 — Editing Basics — Computer Lab — Instructor: Ben Okafor\nOctober 26 — Night Photography — Rooftop Terrace — Instructor: Ana Sousa\nAll workshops run from 10:00 A.M. to 1:00 P.M., except Night Photography (7:00–10:00 P.M.). $35 per workshop; $120 for all four.\n\nText 2 — E-mail\n\nTo: workshops@cityarts.example.com\nFrom: Priya Das\nDate: September 28\n\nHello,\n\nI have paid for all four photography workshops. Unfortunately, I will be out of town on October 12. Would it be possible to receive a partial refund for that session, or to attend the same workshop next season instead?\n\nBest,\nPriya Das\n\nText 3 — Text message\n\nFrom: City Arts Center\nTo: Priya Das\nDate: October 24\n\nReminder: This Saturday's workshop starts at 7:00 P.M. on the rooftop terrace. Please bring a tripod. In case of rain, the workshop will move to Studio A.", questions: [
      R("Which workshop will Ms. Das miss?", ["Portrait Lighting", "Street Photography", "Editing Basics", "Night Photography"], "B", "She will be out of town on October 12: Street Photography."),
      R("How much did Ms. Das pay?", ["$35", "$105", "$120", "$140"], "C", "She paid for all four workshops: $120."),
      R("Who teaches the workshop Ms. Das will miss?", ["Ben Okafor", "Ana Sousa", "Priya Das", "The schedule does not say"], "B", "Street Photography is taught by Ana Sousa."),
      R("What is the text message about?", ["Night Photography", "Portrait Lighting", "Editing Basics", "Street Photography"], "A", "The Saturday after October 24 is October 26 — Night Photography on the rooftop, starting at 7 P.M."),
      R("What will happen if it rains?", ["The workshop will be cancelled.", "The workshop will move indoors.", "Participants will receive a refund.", "The workshop will start later."], "B", "In case of rain, the workshop will move to Studio A.")
    ] },
    { title: "Questions 196–200 refer to the following notice, registration page, and e-mail.", passage: "Text 1 — Notice\n\nMAPLEWOOD 10K CHARITY RUN — Sunday, May 18\nAll proceeds support the Maplewood Children's Hospital.\nStart: Maplewood Park, 8:00 A.M. (5K walkers start at 8:30 A.M.)\nRegistration closes on May 10. Every registered participant receives a T-shirt. Runners who raise more than $300 in donations also receive a medal.\n\nText 2 — Registration page\n\nName: Daniel Osei\nEvent: 10K run\nT-shirt size: Large\nFundraising goal: $500\nTeam: Riverside Bank Runners (8 members)\nRegistration date: May 6\n\nText 3 — E-mail\n\nTo: Riverside Bank Runners\nFrom: Daniel Osei\nDate: May 19\nSubject: Thank you!\n\nHi everyone,\n\nWhat a morning! All eight of us finished the race, and together we raised $3,200 for the hospital — more than any other team. I personally collected $420, so I'm now the proud owner of a medal. The organizers told me that our team photo will appear in the Maplewood Gazette next week. Thanks again for your energy, and see you at next year's run!\n\nDaniel", questions: [
      R("Who benefits from the event?", ["A children's hospital", "Riverside Bank", "Maplewood Park", "The Maplewood Gazette"], "A", "All proceeds support the Maplewood Children's Hospital."),
      R("What time did Mr. Osei most likely start the race?", ["7:30 A.M.", "8:00 A.M.", "8:30 A.M.", "9:00 A.M."], "B", "He ran the 10K; runners start at 8:00 (5K walkers at 8:30)."),
      R("What is true about Mr. Osei's fundraising?", ["He reached his goal.", "He raised less than his goal.", "He raised more than his team.", "He did not raise any money."], "B", "His goal was $500, but he collected $420."),
      R("Why did Mr. Osei receive a medal?", ["He finished first.", "He raised more than $300.", "He registered early.", "His team had eight members."], "B", "Runners who raise more than $300 receive a medal; he raised $420."),
      R("What is suggested about the Riverside Bank Runners?", ["They raised the most money of any team.", "Some members did not finish.", "They registered after May 10.", "They will organize next year's run."], "A", "Together we raised $3,200 — more than any other team.")
    ] }
  ]
};
