import { heard, mcq, type ExamDef } from "../types";
import { graphic, photo } from "./media";

const P1 = "Look at the picture and listen to the four statements. Choose the statement that best describes the picture.";
const P2 = "Listen to the question or statement and the three responses. Choose the best response.";
const statements = (lines: [string, string, string, string]) => `Narrator: Look at the picture.\n(A) ${lines[0]}\n(B) ${lines[1]}\n(C) ${lines[2]}\n(D) ${lines[3]}`;
const exchange = (first: "Woman" | "Man", question: string, answers: [string, string, string]) => `${first}: ${question}\n${first === "Woman" ? "Man" : "Woman"}: (A) ${answers[0]}\n(B) ${answers[1]}\n(C) ${answers[2]}`;
const Q = (prompt: string, options: [string, string, string, string], correct: "A" | "B" | "C" | "D", explanation: string) => mcq(prompt, options, correct, explanation);
const practice = (part: number, title: string, minutes: number, parts: ExamDef["parts"]): ExamDef => ({ key: `toeic:practice:${part}`, batch: "toeic", slug: `toeic-part-${part}-practice`, title: `TOEIC Part ${part} practice: ${title}`, type: "TOEIC", mode: "PRACTICE", durationSeconds: minutes * 60, parts });

export const toeicPractice: ExamDef[] = [
  practice(1, "Photographs", 8, [{ partNumber: 1, title: "Photographs", skill: "LISTENING", instructions: "Look at each photograph and listen to four statements. Choose the statement that best describes the picture. In practice mode you can play each recording twice.", groups: [{ questions: [
    heard(P1, statements(["Fruit is being picked from trees.", "Fruit has been arranged in boxes.", "A vendor is weighing some grapes.", "Customers are paying for fruit."]), 4, "B", "(B) Fruit has been arranged in boxes. There are no people in the picture.", { image: photo("fruit-display", "Photograph for question 1") }),
    heard(P1, statements(["Some bicycles are parked in racks.", "People are riding bicycles on the road.", "A bicycle is being repaired.", "A car is being washed."]), 4, "A", "(A) Some bicycles are parked in racks on the pavement.", { image: photo("bicycle-racks", "Photograph for question 2") }),
    heard(P1, statements(["Workers are carrying boxes.", "The shelves are empty.", "Boxes and files have been stored on shelves.", "A ladder is leaning against a shelf."]), 4, "C", "(C) Boxes and files have been stored on the shelves. No workers or ladders are visible.", { image: photo("storage-shelves", "Photograph for question 3") }),
    heard(P1, statements(["Someone is folding a newspaper.", "Someone is buying a newspaper at a kiosk.", "Someone is lying on the grass.", "Someone is holding a newspaper open."]), 4, "D", "(D) The person is holding a newspaper open while sitting on a bench.", { image: photo("newspaper-bench", "Photograph for question 4") }),
    heard(P1, statements(["Travelers are checking in at a counter.", "Two men are walking through a passageway.", "A suitcase is being loaded onto a plane.", "The men are sitting in a waiting area."]), 4, "B", "(B) Two men with backpacks are walking through a covered passageway.", { image: photo("airport-walkway", "Photograph for question 5") }),
    heard(P1, statements(["A man is writing on a whiteboard.", "The chairs are stacked in a corner.", "Some people are seated at desks.", "People are leaving the room."]), 4, "C", "(C) Some people are seated at desks in a meeting room.", { image: photo("training-room", "Photograph for question 6") })
  ] }] }]),

  practice(2, "Question–response", 10, [{ partNumber: 2, title: "Question–response", skill: "LISTENING", instructions: "Listen to a question or statement and three responses. Choose the best response. In practice mode you can play each recording twice.", groups: [{ questions: [
    heard(P2, exchange("Man", "What time does the bank open on Saturdays?", ["At nine o'clock.", "On Main Street.", "Yes, I opened an account."]), 3, "A", "What time → a time."),
    heard(P2, exchange("Woman", "Who should I give this package to?", ["It's very heavy.", "Leave it with the receptionist.", "By express mail."]), 3, "B", "Who → a person (the receptionist)."),
    heard(P2, exchange("Man", "Didn't you order more envelopes last week?", ["They're in the post office.", "Several letters.", "Yes, but they haven't arrived yet."]), 3, "C", "The reply confirms and adds new information."),
    heard(P2, exchange("Woman", "Where's the nearest subway station?", ["Two blocks down this street.", "Every ten minutes.", "It's a new station."]), 3, "A", "Where → a location."),
    heard(P2, exchange("Man", "Would you prefer to meet in the morning or the afternoon?", ["Yes, I'd like to meet.", "The afternoon suits me better.", "About an hour."]), 3, "B", "A choice question is answered with one option."),
    heard(P2, exchange("Woman", "The new photocopier is really fast.", ["I'll make ten copies.", "The coffee is hot.", "Yes, it saves us a lot of time."]), 3, "C", "The reply agrees and adds a comment."),
    heard(P2, exchange("Man", "Why did Ms. Lopez leave early today?", ["She had a dentist appointment.", "At four thirty.", "She left it on the desk."]), 3, "A", "Why → a reason."),
    heard(P2, exchange("Woman", "How many people signed up for the workshop?", ["Next Tuesday.", "Around thirty so far.", "In the training room."]), 3, "B", "How many → a number."),
    heard(P2, exchange("Man", "Could you check these figures before I send the report?", ["It was a very good report.", "I sent it yesterday.", "Sure, give me ten minutes."]), 3, "C", "The reply accepts the request."),
    heard(P2, exchange("Woman", "Has the client approved the new logo?", ["Not yet, she's still reviewing it.", "A red and blue logo.", "The client is in Paris."]), 3, "A", "The reply answers the yes/no question with extra detail.")
  ] }] }]),

  practice(3, "Conversations", 10, [{ partNumber: 3, title: "Conversations", skill: "LISTENING", instructions: "Read the questions, then listen to each conversation and answer. In practice mode you can play each conversation twice.", groups: [
    { title: "Questions 1–3", listening: { voices: { Man: "male", Woman: "female" }, script: "Man: Hi, Rachel. Are you still planning to drive to the client meeting in Springfield tomorrow?\nWoman: I was, but my car is at the garage until Friday. I'm thinking about taking the train instead.\nMan: I'm driving there anyway. Why don't you come with me? I'm leaving at eight.\nWoman: That would be great, thanks. I'll meet you in the parking garage.\nMan: Perfect. And could you bring the printed contracts? I don't have them." }, questions: [
      Q("Why can't the woman drive her car?", ["It is being repaired.", "She lent it to a colleague.", "She doesn't have a license.", "The roads are closed."], "A", "My car is at the garage until Friday."),
      Q("What does the man offer to do?", ["Buy her a train ticket", "Give her a ride", "Call the client", "Reschedule the meeting"], "B", "Why don't you come with me?"),
      Q("What does the man ask the woman to bring?", ["Her laptop", "Some coffee", "The printed contracts", "A map"], "C", "Could you bring the printed contracts?")
    ] },
    { title: "Questions 4–6", listening: { voices: { Woman: "female", Man: "male" }, script: "Woman: Good morning, Crestview Apartments leasing office. How can I help?\nMan: Hi, I saw your advertisement for a two-bedroom apartment. Is it still available?\nWoman: Yes, it is. It's on the sixth floor and has a balcony overlooking the park.\nMan: That sounds nice. Are pets allowed? I have a small dog.\nWoman: Small pets are fine, but there's a one-time cleaning fee of two hundred dollars.\nMan: OK. Could I see the apartment this afternoon?\nWoman: Sure. How about four o'clock?" }, questions: [
      Q("What is the man calling about?", ["A job advertisement", "An apartment for rent", "A parking space", "A pet store"], "B", "I saw your advertisement for a two-bedroom apartment."),
      Q("What does the woman say about pets?", ["They are not allowed.", "Only cats are allowed.", "An extra fee is charged.", "They must stay on the balcony."], "C", "Small pets are fine, but there's a one-time cleaning fee."),
      Q("What will the man most likely do at four o'clock?", ["Sign a contract", "Pay a deposit", "Move in", "Visit the apartment"], "D", "Could I see the apartment this afternoon? — How about four o'clock?")
    ] },
    { title: "Questions 7–9", image: graphic({ name: "practice-staff-roster", title: "Help desk roster — next week", columns: ["Day", "Staff member"], rows: [["Monday", "Carlos"], ["Tuesday", "Aiko"], ["Wednesday", "Carlos"], ["Thursday", "Priya"], ["Friday", "Aiko"]] }), listening: { voices: { Woman: "female", Man: "male" }, script: "Woman: Carlos, I've just seen next week's help desk roster. You're down for Monday and Wednesday, right?\nMan: Yes, but I have a dental appointment on Wednesday morning. I was hoping to swap days with someone.\nWoman: I'm not on the roster at all next week, so I can cover for you on Wednesday.\nMan: Really? Thanks, Sofia. Then I'll take one of your days the following week.\nWoman: Deal. Just remember to update the online roster so the manager knows." }, questions: [
      Q("Why does the man want to change his schedule?", ["He has a dental appointment.", "He is going on vacation.", "He has a training session.", "He is moving to another office."], "A", "I have a dental appointment on Wednesday morning."),
      Q("Look at the graphic. Which day will the woman work at the help desk?", ["Monday", "Wednesday", "Thursday", "Friday"], "B", "She covers for Carlos on Wednesday."),
      Q("What does the woman remind the man to do?", ["Call the dentist", "Tell the customers", "Work late on Monday", "Update the online roster"], "D", "Remember to update the online roster.")
    ] }
  ] }]),

  practice(4, "Short talks", 10, [{ partNumber: 4, title: "Short talks", skill: "LISTENING", instructions: "Read the questions, then listen to each talk and answer. In practice mode you can play each talk twice.", groups: [
    { title: "Questions 1–3", listening: { voices: { Speaker: "female" }, script: "Speaker: Hello, this is Mei Lin from Sunrise Travel returning your call about the Kyoto tour package. The tour you asked about in April is fully booked, but we have places on the May tour, which follows the same itinerary. The price is slightly lower, too: one thousand four hundred dollars instead of one thousand five hundred. If you'd like to reserve a place, please call me back before Friday, as the May tour is also filling up quickly. My number is 555-0178." }, questions: [
      Q("Why is the speaker calling?", ["To confirm a hotel reservation", "To respond to an inquiry about a tour", "To cancel a flight", "To advertise a new travel agency"], "B", "Returning your call about the Kyoto tour package."),
      Q("What is mentioned about the May tour?", ["It costs less than the April tour.", "It visits different places.", "It is fully booked.", "It lasts longer."], "A", "The price is slightly lower: $1,400 instead of $1,500."),
      Q("Why should the listener call back before Friday?", ["The office closes on Friday.", "The price will increase.", "The tour is filling up quickly.", "The speaker will be on vacation."], "C", "The May tour is also filling up quickly.")
    ] },
    { title: "Questions 4–6", listening: { voices: { Speaker: "male" }, script: "Speaker: Good afternoon, shoppers. Thank you for visiting Westfield Supermarket. For the next thirty minutes, all fresh bread in our bakery section is half price. And don't forget our new self-checkout machines near the main entrance. They accept both cards and mobile payments, so you can finish your shopping more quickly. Finally, a reminder that the store will close early today, at six P.M., because of the holiday tomorrow." }, questions: [
      Q("Where is the announcement being made?", ["In a bakery", "In a supermarket", "In a bank", "In a shopping mall parking lot"], "B", "Thank you for visiting Westfield Supermarket."),
      Q("What is on sale for the next thirty minutes?", ["Fresh fruit", "Mobile phones", "Holiday gifts", "Bread"], "D", "All fresh bread in our bakery section is half price."),
      Q("Why will the store close early today?", ["There is a holiday tomorrow.", "New machines are being installed.", "The bakery is being cleaned.", "There is a staff meeting."], "A", "The store will close early because of the holiday tomorrow.")
    ] },
    { title: "Questions 7–9", image: graphic({ name: "practice-tour-stops", title: "City walking tour", columns: ["Stop", "Place", "Time"], rows: [["1", "Old Town Hall", "10:00"], ["2", "Riverside Market", "10:45"], ["3", "Cathedral Square", "11:30"], ["4", "Botanical Garden", "12:15"]] }), listening: { voices: { Speaker: "female" }, script: "Speaker: Good morning, everyone, and welcome to our city walking tour. Before we start, one quick change. The Riverside Market is closed today for a private event, so we'll skip that stop and go straight to our third stop instead. We'll have lunch at the final stop, where there's a lovely café by the greenhouse. Please stay close to the group, and if you have any questions, just raise your hand." }, questions: [
      Q("What change does the speaker announce?", ["The tour will start later.", "Lunch has been cancelled.", "The tour will end early.", "One stop will be skipped."], "D", "We'll skip the Riverside Market."),
      Q("Look at the graphic. Where will the group go after the Old Town Hall?", ["Riverside Market", "Cathedral Square", "Botanical Garden", "Back to the start"], "B", "They skip stop 2 and go straight to the third stop, Cathedral Square."),
      Q("Where will the group have lunch?", ["At the Old Town Hall", "At a market stall", "At a café in the Botanical Garden", "At a restaurant near the cathedral"], "C", "Lunch at the final stop, a café by the greenhouse (the Botanical Garden).")
    ] }
  ] }]),

  practice(5, "Incomplete sentences", 12, [{ partNumber: 5, title: "Incomplete sentences", skill: "READING", instructions: "Choose the word or phrase that best completes each sentence.", groups: [{ questions: [
    Q("The board of directors ___ the proposal at its next meeting.", ["reviewed", "will review", "reviewing", "has reviewing"], "B", "Next meeting = future: will review."),
    Q("Ms. Duval is ___ qualified for the position of finance manager.", ["high", "higher", "highly", "height"], "C", "An adverb modifies the adjective qualified: highly."),
    Q("Please send the updated price list ___ all our regional distributors.", ["to", "at", "for", "with"], "A", "Send something to someone."),
    Q("The company's profits rose ___ after the new product was launched.", ["sharp", "sharply", "sharpness", "sharper"], "B", "An adverb describes how profits rose."),
    Q("Visitors must wear safety glasses ___ they are in the production area.", ["during", "while", "until", "despite"], "B", "While + clause (they are in…)."),
    Q("The training manual has been ___ into five languages.", ["translate", "translating", "translation", "translated"], "D", "Passive: has been + past participle."),
    Q("We have received ___ complaints about the new delivery schedule.", ["much", "a few", "a little", "every"], "B", "Complaints is plural and countable: a few."),
    Q("The seminar was so popular that the organizers had to add a ___ session.", ["second", "twice", "double", "two"], "A", "An ordinal adjective before the noun: a second session."),
    Q("Mr. Owens asked his assistant to ___ the meeting room for Thursday afternoon.", ["reserve", "reservation", "reserved", "reserving"], "A", "Ask someone to + base verb."),
    Q("The flight was delayed ___ heavy fog at the airport.", ["because", "since", "due to", "although"], "C", "Due to + noun phrase."),
    Q("Each of the candidates ___ an interview scheduled for next week.", ["have", "has", "having", "are having"], "B", "Each of + plural noun takes a singular verb: has."),
    Q("The new software is ___ easier to use than the previous version.", ["very", "much", "most", "too"], "B", "Much + comparative."),
    Q("Employees ___ wish to attend the conference should inform their manager by Friday.", ["which", "whose", "who", "whom"], "C", "People as the subject: who."),
    Q("The warehouse will be closed ___ Monday because of the national holiday.", ["in", "at", "on", "for"], "C", "On + a day of the week."),
    Q("Customer satisfaction has improved ___ since we extended our opening hours.", ["notice", "noticeable", "noticeably", "noticed"], "C", "An adverb modifies improved.")
  ] }] }]),

  practice(6, "Text completion", 10, [{ partNumber: 6, title: "Text completion", skill: "READING", instructions: "Read each text and choose the best word, phrase or sentence for each blank.", groups: [
    { title: "Questions 1–4 refer to the following e-mail.", passage: "To: Jonas Weber\nFrom: Claire Dubois\nSubject: Your order #2291\n\nDear Mr. Weber,\n\nThank you for your recent order of office chairs. Unfortunately, the model you selected is temporarily out of stock. We ___(1)___ a new shipment from the manufacturer on March 14.\n\n___(2)___ If you prefer not to wait, we can offer you a similar model at the same price. Alternatively, you may cancel your order and receive a full ___(3)___.\n\nPlease let us know which option you prefer. We apologize for the ___(4)___.\n\nSincerely,\nClaire Dubois\nCustomer Service", questions: [
      mcq("(1)", ["expected", "are expecting", "have expected", "expecting"], "B", "A planned future arrival: are expecting."),
      mcq("(2)", ["Your chairs will then be delivered within three days.", "We no longer sell office chairs.", "The manufacturer has closed.", "Your payment was declined."], "A", "It explains what happens after the shipment arrives; the others contradict the e-mail."),
      mcq("(3)", ["refund", "refunded", "refundable", "refunding"], "A", "A noun after a full: refund."),
      mcq("(4)", ["inconvenient", "inconvenience", "inconveniently", "convenience"], "B", "A noun after the: inconvenience.")
    ] },
    { title: "Questions 5–8 refer to the following notice.", passage: "ATTENTION: GREENWAY BUILDING RESIDENTS\n\nThe main water supply to the building will be ___(5)___ off on Wednesday, July 9, from 9 A.M. to 1 P.M. so that workers can replace an old pipe in the basement.\n\nDuring this time, taps and toilets will not work. ___(6)___ We recommend that residents store some water in advance.\n\nWe understand that this may cause difficulties, especially for families with small children. ___(7)___, we have scheduled the work for a weekday morning, when most residents are at work or school.\n\nThank you for your ___(8)___.\n\nGreenway Property Management", questions: [
      mcq("(5)", ["turn", "turning", "turned", "turns"], "C", "Passive: will be turned off."),
      mcq("(6)", ["Bottled water will be available in the lobby.", "The building will be painted next month.", "Residents may use the gym as usual.", "The pipe was replaced last year."], "A", "It helps residents cope with the lack of water; the others are unrelated or contradictory."),
      mcq("(7)", ["Instead", "For this reason", "In contrast", "Otherwise"], "B", "The timing was chosen because of the difficulty: For this reason. The other linkers do not connect the two sentences logically."),
      mcq("(8)", ["understand", "understanding", "understood", "understandable"], "B", "A noun after your: understanding.")
    ] }
  ] }]),

  practice(7, "Reading comprehension", 20, [{ partNumber: 7, title: "Reading comprehension", skill: "READING", instructions: "Read each text or set of texts and answer the questions.", groups: [
    { title: "Questions 1–2 refer to the following text message.", passage: "From: Harbor Dental Clinic\nTo: 555-0126\n\nHi Ms. Yamada, this is a reminder of your appointment with Dr. Russo on Thursday, June 6, at 3:30 P.M. Please arrive ten minutes early and bring your insurance card. Reply C to confirm or call 555-0190 to reschedule.", questions: [
      Q("What is the purpose of the message?", ["To remind a patient of an appointment", "To advertise a new clinic", "To request a payment", "To announce a change of dentist"], "A", "This is a reminder of your appointment."),
      Q("What is Ms. Yamada asked to bring?", ["A payment receipt", "Her insurance card", "A letter from her doctor", "A photo ID"], "B", "Bring your insurance card.")
    ] },
    { title: "Questions 3–5 refer to the following e-mail.", passage: "To: All Kestrel Logistics staff\nFrom: IT Department\nSubject: System upgrade this weekend\n\nOn Saturday, November 9, from 8 A.M. to 6 P.M., we will upgrade the company's e-mail and file-sharing systems. During this time, you will not be able to access your e-mail or shared folders.\n\nBefore you leave on Friday, please save any files you are working on and log out of all programs. On Monday morning, you will be asked to create a new password when you first sign in. The new password must contain at least twelve characters.\n\nIf you experience any problems after the upgrade, contact the help desk at extension 4400.", questions: [
      Q("What is the e-mail mainly about?", ["A new office opening", "A planned system upgrade", "A change in working hours", "A security problem"], "B", "We will upgrade the company's e-mail and file-sharing systems."),
      Q("What are employees asked to do before leaving on Friday?", ["Create a new password", "Contact the help desk", "Save their files and log out", "Take their computers home"], "C", "Save any files you are working on and log out of all programs."),
      Q("What will happen on Monday morning?", ["Employees will create new passwords.", "The office will open late.", "The help desk will be closed.", "New computers will be delivered."], "A", "You will be asked to create a new password when you first sign in.")
    ] },
    { title: "Questions 6–9 refer to the following article.", passage: "Riverside Cinema Reopens After Renovation\n\nAfter eight months of work, the Riverside Cinema on Canal Street reopened last Friday. — [1] — The 1950s building now has comfortable reclining seats, a modern sound system, and a small café serving local coffee and pastries.\n\nOwner Martin Hale said the renovation cost more than expected because workers discovered problems with the roof. — [2] — \"We wanted to keep the building's original character,\" he explained, \"so we restored the old ceiling paintings instead of covering them.\"\n\nThe cinema will show both new releases and classic films. — [3] — On the first Sunday of every month, tickets for classic films will cost only five dollars.\n\nThe opening weekend was a success, with most screenings sold out. — [4] —", questions: [
      Q("What is the article mainly about?", ["The reopening of a cinema", "A new film festival", "A famous film director", "The construction of a new café"], "A", "The Riverside Cinema reopened after renovation."),
      Q("Why did the renovation cost more than expected?", ["The owner added a café.", "Problems were found with the roof.", "The seats were imported.", "The work took two years."], "B", "Workers discovered problems with the roof."),
      Q("What is indicated about classic films?", ["They will no longer be shown.", "Tickets are cheaper on the first Sunday of each month.", "They are shown only in the café.", "They are always sold out."], "B", "Tickets for classic films cost only five dollars on the first Sunday of every month."),
      Q("In which of the positions marked [1], [2], [3], and [4] does the following sentence best belong? \"It was the first time the cinema had closed since it opened in 1952.\"", ["[1]", "[2]", "[3]", "[4]"], "A", "It follows the sentence about reopening after eight months of work.")
    ] },
    { title: "Questions 10–14 refer to the following advertisement and e-mail.", passage: "Text 1 — Advertisement\n\nBRIGHTON BIKE RENTALS\nExplore the coast on two wheels!\nCity bike: $15 per day\nElectric bike: $35 per day\nTandem (two riders): $40 per day\nHelmets and locks are included free of charge. Rent for three days or more and get the third day free. Open daily 8 A.M.–7 P.M., next to the ferry terminal.\n\nText 2 — E-mail\n\nTo: info@brightonbikes.example.com\nFrom: Julia Moreau\nDate: August 2\n\nHello,\n\nMy husband and I will be visiting Brighton from August 14 to 16 and would like to rent two electric bikes for all three days. Could you tell me whether we need to book in advance? Also, our ferry arrives at 7:30 P.M. on the 13th. Would it be possible to pick up the bikes that evening?\n\nThank you,\nJulia Moreau", questions: [
      Q("What is included in every rental?", ["A map of the coast", "Helmets and locks", "A ferry ticket", "Insurance"], "B", "Helmets and locks are included free of charge."),
      Q("Where is Brighton Bike Rentals located?", ["At the train station", "Next to the ferry terminal", "On the beach", "In a hotel"], "B", "Next to the ferry terminal."),
      Q("How much will Ms. Moreau most likely pay for the rental?", ["$105", "$140", "$210", "$70"], "B", "Two electric bikes × $35 × 2 paid days (the third day is free) = $140."),
      Q("Why might Ms. Moreau be unable to pick up the bikes on August 13?", ["The shop closes before her ferry arrives.", "The electric bikes are sold out.", "The shop is closed on weekdays.", "She has not paid a deposit."], "A", "The shop closes at 7 P.M., but her ferry arrives at 7:30 P.M."),
      Q("What does Ms. Moreau ask about?", ["Whether she needs to book in advance", "Whether children can ride", "The price of a tandem", "Guided tours of the coast"], "A", "Could you tell me whether we need to book in advance?")
    ] }
  ] }])
];
