"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { type FormEvent, useMemo, useState } from "react";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import type { AdminCopy } from "@/lib/admin-copy";
import type { AdminEditorData } from "@/modules/content-management/repository";

type Builder = "lesson" | "exam" | "library";
type Notice = { kind: "success" | "error"; text: string } | null;
const fieldClass = "mt-1 w-full rounded-ui border border-line bg-canvas px-3 py-2 text-sm outline-none focus:border-brand";
const labelClass = "block text-sm font-bold";

const labels = {
  vi: {
    workspaceTitle: "Trình biên tập nội dung", help: "Soạn bằng biểu mẫu, chọn dữ liệu liên quan từ danh sách và xem trước trước khi xuất bản. CMS tự chuẩn hóa dữ liệu; không cần JSON hoặc sao chép UUID.",
    lesson: "Lesson Builder", exam: "Exam Builder", library: "Media & từ vựng", lessonFlow: "Lô nguồn → Khóa học/chủ đề → Bài học → Khối nội dung → Xem trước → Publish", examFlow: "Lô nguồn → Đề → Part/section → Passage/media → Câu hỏi → Kiểm tra → Publish",
    sourceTitle: "1. Khai báo nguồn nội dung", sourceHelp: "Mỗi tài liệu hoặc bộ nội dung phải có nguồn và giấy phép trước khi publish.", source: "Nguồn hoặc URL tham chiếu", license: "Giấy phép / quyền sử dụng", author: "Tác giả (không bắt buộc)", version: "Phiên bản", createBatch: "Tạo lô nháp",
    courseTitle: "2. Tạo khóa học và chủ đề", courseHelp: "Khóa học được khởi tạo cùng chủ đề đầu tiên. Chọn lô nội dung từ danh sách.", title: "Tiêu đề", slug: "Đường dẫn", description: "Mô tả", level: "Trình độ CEFR", unit: "Tên chủ đề", batch: "Lô nội dung", createCourse: "Tạo khóa học",
    lessonTitle: "3. Tạo bài học", lessonHelp: "Chọn chủ đề và lô nội dung. Không cần nhập ID.", selectUnit: "Chọn chủ đề", skill: "Kỹ năng", minutes: "Thời lượng (phút)", createLesson: "Tạo bài học",
    blocksTitle: "4. Soạn khối nội dung", blocksHelp: "Thêm từng khối theo thứ tự hiển thị. Câu luyện tập được chấm ở server khi learner nộp bài.", selectLesson: "Chọn bài học", blockType: "Loại khối", heading: "Tiêu đề / hướng dẫn", body: "Nội dung", order: "Thứ tự", addBlock: "Thêm khối", transcript: "Transcript", sourceLabel: "Nhãn nguồn audio", browserSpeech: "Văn bản đọc mẫu trên trình duyệt", selectMedia: "Audio đã tải lên", practiceQuestion: "Câu hỏi luyện tập", option: "Lựa chọn", correct: "Đáp án đúng", explanation: "Giải thích", addPractice: "Thêm câu luyện tập",
    previewTitle: "5. Xem trước và publish", previewHelp: "Preview dùng đúng learner renderer. Trước khi publish, đưa lô nội dung từ DRAFT → REVIEW → APPROVED → PUBLISHED bằng các nút workflow bên dưới.", preview: "Xem trước", publish: "Publish bài học", learner: "Mở như learner",
    mediaTitle: "Tải audio hoặc ảnh", mediaHelp: "Audio dùng cho Listening. File local đi qua Media abstraction để sau này thay bằng R2 mà không đổi lesson.", upload: "Tải file lên", vocabularyTitle: "Thêm từ vựng", word: "Từ", partOfSpeech: "Từ loại", ipa: "IPA", meaning: "Nghĩa", example: "Ví dụ", tags: "Nhãn, cách nhau bằng dấu phẩy", saveVocabulary: "Lưu từ vựng",
    examTitle: "1. Tạo đề và part đầu tiên", examHelp: "Sau khi tạo đề, thêm các part/section, passage và câu hỏi từ các form bên dưới.", examType: "Kỳ thi", mode: "Chế độ", duration: "Thời lượng (giây)", partNumber: "Số part/section", partTitle: "Tên part/section", createExam: "Tạo đề nháp", addPartTitle: "2. Thêm part / section", selectExam: "Chọn đề", instructions: "Hướng dẫn người học", addPart: "Thêm part", passageTitle: "3. Thêm passage / transcript", selectPart: "Chọn part", passageName: "Tiêu đề passage", addPassage: "Thêm passage", questionTitle: "4. Thêm câu hỏi MCQ", questionHelp: "Đáp án được lưu riêng tại server, không được gửi cho learner trước khi submit.", selectPassage: "Passage (không bắt buộc)", addQuestion: "Thêm câu hỏi", publishExamTitle: "5. Publish đề", publishExamHelp: "Mỗi part cần ít nhất một câu hỏi và lô nội dung phải ở trạng thái PUBLISHED.", publishExam: "Publish đề", openExam: "Mở đề đã publish",
    noBatch: "Hãy tạo lô nội dung trước.", noUnit: "Hãy tạo khóa học/chủ đề trước.", noLesson: "Hãy tạo bài học trước.", noExam: "Hãy tạo đề nháp trước.", choose: "— Chọn —", all: "Chung", saving: "Đang lưu…", failed: "Không thể hoàn tất thao tác.",
    richText: "Văn bản", grammar: "Ngữ pháp", pronunciation: "Phát âm", listening: "Audio / Listening", practice: "Câu luyện tập",
    batchDone: "Đã tạo lô nội dung ở trạng thái DRAFT.", courseDone: "Đã tạo khóa học và chủ đề đầu tiên.", lessonDone: "Đã tạo bài học nháp. Hãy thêm các khối nội dung.", blockDone: "Đã thêm khối nội dung.", lessonPublished: "Đã publish bài học. Learner có thể mở ngay.", mediaDone: "Đã tải file lên. Làm mới trang rồi chọn file trong khối Audio / Listening.", vocabDone: "Đã lưu từ vựng nháp.", examDone: "Đã tạo đề nháp và part đầu tiên.", partDone: "Đã thêm part/section.", passageDone: "Đã thêm passage.", questionDone: "Đã thêm câu hỏi. Đáp án vẫn được giữ ở server.", examPublished: "Đã publish đề."
  },
  en: {
    workspaceTitle: "Content authoring workspace", help: "Author with forms, select related data from lists, and preview before publishing. The CMS normalizes the data for you; no JSON or UUID copying is needed.",
    lesson: "Lesson Builder", exam: "Exam Builder", library: "Media & vocabulary", lessonFlow: "Source batch → Course/unit → Lesson → Content blocks → Preview → Publish", examFlow: "Source batch → Exam → Part/section → Passage/media → Questions → Validate → Publish",
    sourceTitle: "1. Register the content source", sourceHelp: "Every document or content set needs a source and usage licence before publication.", source: "Source or reference URL", license: "Licence / usage rights", author: "Author (optional)", version: "Version", createBatch: "Create draft batch",
    courseTitle: "2. Create a course and unit", courseHelp: "A course starts with its first unit. Select a content batch from the list.", title: "Title", slug: "URL slug", description: "Description", level: "CEFR level", unit: "Unit title", batch: "Content batch", createCourse: "Create course",
    lessonTitle: "3. Create a lesson", lessonHelp: "Choose a unit and a content batch. You never need to enter an ID.", selectUnit: "Choose unit", skill: "Skill", minutes: "Estimated minutes", createLesson: "Create lesson",
    blocksTitle: "4. Author lesson blocks", blocksHelp: "Add blocks in display order. Practice questions are scored on the server when a learner submits.", selectLesson: "Choose lesson", blockType: "Block type", heading: "Heading / instruction", body: "Content", order: "Order", addBlock: "Add block", transcript: "Transcript", sourceLabel: "Audio source label", browserSpeech: "Browser sample speech text", selectMedia: "Uploaded audio", practiceQuestion: "Practice question", option: "Option", correct: "Correct answer", explanation: "Explanation", addPractice: "Add practice question",
    previewTitle: "5. Preview and publish", previewHelp: "Preview uses the learner renderer. Before publishing, move the source batch from DRAFT → REVIEW → APPROVED → PUBLISHED with the workflow controls below.", preview: "Preview", publish: "Publish lesson", learner: "Open as learner",
    mediaTitle: "Upload audio or image", mediaHelp: "Audio supports Listening. Local files go through the Media abstraction so R2 can replace it later without changing lessons.", upload: "Upload file", vocabularyTitle: "Add vocabulary", word: "Word", partOfSpeech: "Part of speech", ipa: "IPA", meaning: "Meaning", example: "Example", tags: "Tags, separated by commas", saveVocabulary: "Save vocabulary",
    examTitle: "1. Create an exam and first part", examHelp: "After creating an exam, add parts/sections, passages and questions with the forms below.", examType: "Exam", mode: "Mode", duration: "Duration (seconds)", partNumber: "Part/section number", partTitle: "Part/section title", createExam: "Create draft exam", addPartTitle: "2. Add part / section", selectExam: "Choose exam", instructions: "Learner instructions", addPart: "Add part", passageTitle: "3. Add passage / transcript", selectPart: "Choose part", passageName: "Passage title", addPassage: "Add passage", questionTitle: "4. Add MCQ questions", questionHelp: "Answer keys are stored on the server and are never sent to learners before submission.", selectPassage: "Passage (optional)", addQuestion: "Add question", publishExamTitle: "5. Publish exam", publishExamHelp: "Every part needs at least one question and the content batch must be PUBLISHED.", publishExam: "Publish exam", openExam: "Open published exam",
    noBatch: "Create a content batch first.", noUnit: "Create a course/unit first.", noLesson: "Create a lesson first.", noExam: "Create a draft exam first.", choose: "— Choose —", all: "General", saving: "Saving…", failed: "The operation could not be completed.",
    richText: "Text", grammar: "Grammar", pronunciation: "Pronunciation", listening: "Audio / Listening", practice: "Practice question",
    batchDone: "Draft content batch created.", courseDone: "Course and first unit created.", lessonDone: "Draft lesson created. Add its content blocks next.", blockDone: "Content block added.", lessonPublished: "Lesson published. Learners can open it now.", mediaDone: "File uploaded. Refresh and select it in an Audio / Listening block.", vocabDone: "Draft vocabulary saved.", examDone: "Draft exam and first part created.", partDone: "Part/section added.", passageDone: "Passage added.", questionDone: "Question added. The answer key remains on the server.", examPublished: "Exam published."
  }
} as const;
type Text = (typeof labels)["vi"];

function Field({ label, name, required = true, type = "text", defaultValue }: { label: string; name: string; required?: boolean; type?: string; defaultValue?: string | number }) { return <label className={labelClass}>{label}<input className={fieldClass} name={name} type={type} required={required} defaultValue={defaultValue} /></label>; }
function Area({ label, name, required = true }: { label: string; name: string; required?: boolean }) { return <label className={`${labelClass} md:col-span-2`}>{label}<textarea className={`${fieldClass} min-h-28`} name={name} required={required} /></label>; }
function Select({ label, name, children, required = true, value, onChange }: { label: string; name: string; children: React.ReactNode; required?: boolean; value?: string; onChange?: (value: string) => void }) { return <label className={labelClass}>{label}<select className={fieldClass} name={name} required={required} value={value} onChange={(event) => onChange?.(event.target.value)}>{children}</select></label>; }
function Submit({ label, pending }: { label: string; pending: boolean }) { return <div className="md:col-span-2"><Button type="submit" disabled={pending}>{pending ? "…" : label}</Button></div>; }
function Empty({ text }: { text: string }) { return <p className="rounded-ui bg-band p-4 text-sm text-muted md:col-span-2">{text}</p>; }
function BuilderCard({ title, help, children }: { title: string; help: string; children: React.ReactNode }) { return <Card><h3 className="font-serif text-2xl font-bold">{title}</h3><p className="mt-2 max-w-3xl text-sm leading-6 text-muted">{help}</p><div className="mt-6">{children}</div></Card>; }
function batchLabel(batch: AdminEditorData["batches"][number]) { return `${batch.source} · ${batch.version} · ${batch.status}`; }

export function AdminContentOperations({ copy, data }: { copy: AdminCopy; data: AdminEditorData }) {
  const t = labels[copy.locale] as Text;
  const router = useRouter(); const [builder, setBuilder] = useState<Builder>("lesson"); const [notice, setNotice] = useState<Notice>(null); const [pending, setPending] = useState<string | null>(null);
  async function request(operation: string, payload: Record<string, unknown>, message: string) { setPending(operation); setNotice(null); try { const response = await fetch("/api/admin/operations", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ operation, payload }) }); const body = await response.json() as { error?: string }; if (!response.ok) throw new Error(body.error ?? t.failed); setNotice({ kind: "success", text: message }); router.refresh(); return true; } catch (error) { setNotice({ kind: "error", text: error instanceof Error ? error.message : t.failed }); return false; } finally { setPending(null); } }
  async function upload(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setPending("media"); setNotice(null); try { const response = await fetch("/api/admin/media/local", { method: "POST", body: new FormData(event.currentTarget) }); const body = await response.json() as { error?: string }; if (!response.ok) throw new Error(body.error ?? t.failed); setNotice({ kind: "success", text: t.mediaDone }); router.refresh(); } catch (error) { setNotice({ kind: "error", text: error instanceof Error ? error.message : t.failed }); } finally { setPending(null); } }
  return <section className="mt-10"><Card><h2 className="font-serif text-3xl font-bold">{t.workspaceTitle}</h2><p className="mt-3 max-w-4xl leading-7 text-muted">{t.help}</p><div className="mt-6 flex flex-wrap gap-2">{(["lesson", "exam", "library"] as Builder[]).map((item) => <Button key={item} variant={builder === item ? "primary" : "secondary"} className="min-h-9 px-4" onClick={() => { setBuilder(item); setNotice(null); }}>{t[item]}</Button>)}</div>{notice && <p className={`mt-5 rounded-ui p-4 text-sm font-semibold ${notice.kind === "success" ? "bg-emerald-50 text-emerald-950" : "bg-red-50 text-red-800"}`} role="status">{notice.text}</p>}</Card>{builder === "lesson" && <LessonBuilder t={t} data={data} request={request} pending={pending} />}{builder === "exam" && <ExamBuilder t={t} data={data} request={request} pending={pending} />}{builder === "library" && <LibraryBuilder t={t} data={data} request={request} upload={upload} pending={pending} />}</section>;
}

function LessonBuilder({ t, data, request, pending }: { t: Text; data: AdminEditorData; request: (operation: string, payload: Record<string, unknown>, message: string) => Promise<boolean>; pending: string | null }) {
  const [blockType, setBlockType] = useState("RICH_TEXT"); const [lessonId, setLessonId] = useState(data.lessons.find((item) => item.status === "DRAFT")?.id ?? data.lessons[0]?.id ?? ""); const batches = data.batches.filter((item) => item.status !== "ARCHIVED"); const lesson = data.lessons.find((item) => item.id === lessonId);
  const form = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); return new FormData(event.currentTarget); };
  const draftLessons = data.lessons.filter((item) => item.status === "DRAFT");
  return <div className="mt-6 space-y-6"><p className="rounded-ui bg-brand-soft p-4 text-sm font-bold text-brand">{t.lessonFlow}</p>
    <BuilderCard title={t.sourceTitle} help={t.sourceHelp}><form className="grid gap-4 md:grid-cols-2" onSubmit={(event) => { const f = form(event); void request("batch", { source: String(f.get("source") ?? "").trim(), license: String(f.get("license") ?? "").trim(), author: String(f.get("author") ?? "").trim() || undefined, version: String(f.get("version") ?? "").trim() }, t.batchDone); }}><Field label={t.source} name="source" /><Field label={t.license} name="license" /><Field label={t.author} name="author" required={false} /><Field label={t.version} name="version" defaultValue="1" /><Submit label={t.createBatch} pending={pending === "batch"} /></form></BuilderCard>
    <BuilderCard title={t.courseTitle} help={t.courseHelp}><form className="grid gap-4 md:grid-cols-2" onSubmit={(event) => { const f = form(event); void request("course", { contentBatchId: f.get("contentBatchId"), title: String(f.get("title") ?? "").trim(), slug: String(f.get("slug") ?? "").trim(), description: String(f.get("description") ?? "").trim(), cefrLevel: f.get("cefrLevel"), unitTitle: String(f.get("unitTitle") ?? "").trim() }, t.courseDone); }}>{batches.length ? <><Select label={t.batch} name="contentBatchId">{batches.map((item) => <option key={item.id} value={item.id}>{batchLabel(item)}</option>)}</Select><Field label={t.title} name="title" /><Field label={t.slug} name="slug" /><Field label={t.description} name="description" required={false} /><Select label={t.level} name="cefrLevel">{["A1", "A2", "B1", "B2", "C1", "C2"].map((item) => <option key={item}>{item}</option>)}</Select><Field label={t.unit} name="unitTitle" /><Submit label={t.createCourse} pending={pending === "course"} /></> : <Empty text={t.noBatch} />}</form></BuilderCard>
    <BuilderCard title={t.lessonTitle} help={t.lessonHelp}><form className="grid gap-4 md:grid-cols-2" onSubmit={(event) => { const f = form(event); void request("lesson", { unitId: f.get("unitId"), contentBatchId: f.get("contentBatchId"), title: String(f.get("title") ?? "").trim(), slug: String(f.get("slug") ?? "").trim(), skill: f.get("skill"), estimatedMinutes: Number(f.get("estimatedMinutes")) }, t.lessonDone); }}>{data.units.length && batches.length ? <><Select label={t.selectUnit} name="unitId">{data.units.map((item) => <option key={item.id} value={item.id}>{item.courseTitle} · {item.level} · {item.title}</option>)}</Select><Select label={t.batch} name="contentBatchId">{batches.map((item) => <option key={item.id} value={item.id}>{batchLabel(item)}</option>)}</Select><Field label={t.title} name="title" /><Field label={t.slug} name="slug" /><Select label={t.skill} name="skill">{["LISTENING", "SPEAKING", "READING", "WRITING"].map((item) => <option key={item}>{item}</option>)}</Select><Field label={t.minutes} name="estimatedMinutes" type="number" defaultValue={10} /><Submit label={t.createLesson} pending={pending === "lesson"} /></> : <Empty text={data.units.length ? t.noBatch : t.noUnit} />}</form></BuilderCard>
    <BuilderCard title={t.blocksTitle} help={t.blocksHelp}><form className="grid gap-4 md:grid-cols-2" onSubmit={(event) => { const f = form(event); const base = { lessonId: f.get("lessonId"), type: blockType, sortOrder: Number(f.get("sortOrder")), schemaVersion: 1 }; if (blockType === "QUESTION_SET") { const options = ["a", "b", "c", "d"].map((id) => ({ id, text: String(f.get(`option-${id}`) ?? "").trim() })).filter((item) => item.text); void request("lessonBlock", { ...base, content: { instruction: String(f.get("heading") ?? "").trim(), questions: [{ id: crypto.randomUUID(), prompt: String(f.get("question") ?? "").trim(), options, correctOptionId: f.get("correctOptionId"), explanation: String(f.get("explanation") ?? "").trim() }] } }, t.blockDone); return; } if (blockType === "MEDIA") { void request("lessonBlock", { ...base, content: { heading: String(f.get("heading") ?? "").trim(), transcript: String(f.get("body") ?? "").trim(), playbackText: String(f.get("playbackText") ?? "").trim() || undefined, mediaId: String(f.get("mediaId") ?? "") || undefined, sourceLabel: String(f.get("sourceLabel") ?? "").trim() } }, t.blockDone); return; } void request("lessonBlock", { ...base, content: { heading: String(f.get("heading") ?? "").trim(), body: String(f.get("body") ?? "").trim() } }, t.blockDone); }}>{draftLessons.length ? <><Select label={t.selectLesson} name="lessonId" value={lessonId} onChange={setLessonId}>{draftLessons.map((item) => <option key={item.id} value={item.id}>{item.level} · {item.title}</option>)}</Select><Select label={t.blockType} name="blockType" value={blockType} onChange={setBlockType}>{[["RICH_TEXT", t.richText], ["GRAMMAR", t.grammar], ["PRONUNCIATION", t.pronunciation], ["MEDIA", t.listening], ["QUESTION_SET", t.practice]].map(([id, label]) => <option key={id} value={id}>{label}</option>)}</Select><Field label={t.order} name="sortOrder" type="number" defaultValue={1} /><BlockFields t={t} type={blockType} media={data.media.filter((item) => item.status === "READY" && item.kind === "AUDIO")} /><Submit label={blockType === "QUESTION_SET" ? t.addPractice : t.addBlock} pending={pending === "lessonBlock"} /></> : <Empty text={t.noLesson} />}</form></BuilderCard>
    <BuilderCard title={t.previewTitle} help={t.previewHelp}><div className="grid gap-4 md:grid-cols-2">{data.lessons.length ? <><Select label={t.selectLesson} name="publishedLesson" value={lessonId} onChange={setLessonId}><option value="">{t.choose}</option>{data.lessons.map((item) => <option key={item.id} value={item.id}>{item.level} · {item.title} · {item.status}</option>)}</Select><div className="flex flex-wrap items-end gap-3"><Link className={`inline-flex ${lessonId ? "" : "pointer-events-none opacity-50"}`} href={lessonId ? `/admin/preview/lesson/${lessonId}` : "/admin"}><Button>{t.preview}</Button></Link><Button disabled={!lessonId || pending === "publishLesson"} onClick={() => lessonId && void request("publishLesson", { lessonId }, t.lessonPublished)}>{pending === "publishLesson" ? t.saving : t.publish}</Button>{lesson?.status === "PUBLISHED" && <Link className="inline-flex" href={`/learn/${lesson.level.toLowerCase()}/${lesson.slug}`}><Button variant="secondary">{t.learner}</Button></Link>}</div></> : <Empty text={t.noLesson} />}</div></BuilderCard>
  </div>;
}

function BlockFields({ t, type, media }: { t: Text; type: string; media: AdminEditorData["media"] }) { if (type === "QUESTION_SET") return <><Area label={t.heading} name="heading" /><Area label={t.practiceQuestion} name="question" />{["a", "b", "c", "d"].map((item, index) => <Field key={item} label={`${t.option} ${item.toUpperCase()}`} name={`option-${item}`} required={index < 2} />)}<Select label={t.correct} name="correctOptionId">{["a", "b", "c", "d"].map((item) => <option key={item}>{item}</option>)}</Select><Area label={t.explanation} name="explanation" /></>; if (type === "MEDIA") return <><Field label={t.heading} name="heading" /><Area label={t.transcript} name="body" /><Select label={t.selectMedia} name="mediaId" required={false}><option value="">{t.choose}</option>{media.map((item) => <option key={item.id} value={item.id}>{item.kind} · {item.contentType}</option>)}</Select><Field label={t.browserSpeech} name="playbackText" required={false} /><Field label={t.sourceLabel} name="sourceLabel" /><p className="text-xs text-muted md:col-span-2">Audio file or browser speech text is required.</p></>; return <><Field label={t.heading} name="heading" /><Area label={t.body} name="body" /></>; }

function ExamBuilder({ t, data, request, pending }: { t: Text; data: AdminEditorData; request: (operation: string, payload: Record<string, unknown>, message: string) => Promise<boolean>; pending: string | null }) {
  const batches = data.batches.filter((item) => item.status !== "ARCHIVED"); const draftExams = data.exams.filter((item) => item.status === "DRAFT"); const [examId, setExamId] = useState(draftExams[0]?.id ?? ""); const parts = useMemo(() => data.examParts.filter((item) => !examId || item.examId === examId), [data.examParts, examId]); const form = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); return new FormData(event.currentTarget); };
  return <div className="mt-6 space-y-6"><p className="rounded-ui bg-brand-soft p-4 text-sm font-bold text-brand">{t.examFlow}</p>
    <BuilderCard title={t.examTitle} help={t.examHelp}><form className="grid gap-4 md:grid-cols-2" onSubmit={(event) => { const f = form(event); void request("exam", { contentBatchId: f.get("contentBatchId"), title: String(f.get("title") ?? "").trim(), slug: String(f.get("slug") ?? "").trim(), type: f.get("type"), mode: f.get("mode"), durationSeconds: Number(f.get("durationSeconds")), partNumber: Number(f.get("partNumber")), partTitle: String(f.get("partTitle") ?? "").trim(), skill: f.get("skill") }, t.examDone); }}>{batches.length ? <><Select label={t.batch} name="contentBatchId">{batches.map((item) => <option key={item.id} value={item.id}>{batchLabel(item)}</option>)}</Select><Field label={t.title} name="title" /><Field label={t.slug} name="slug" /><Select label={t.examType} name="type"><option>TOEIC</option><option>IELTS</option></Select><Select label={t.mode} name="mode"><option>PRACTICE</option><option>MINI_TEST</option><option>FULL_MOCK</option></Select><Field label={t.duration} name="durationSeconds" type="number" defaultValue={1800} /><Field label={t.partNumber} name="partNumber" type="number" defaultValue={1} /><Field label={t.partTitle} name="partTitle" /><Select label={t.skill} name="skill"><option>LISTENING</option><option>READING</option></Select><Submit label={t.createExam} pending={pending === "exam"} /></> : <Empty text={t.noBatch} />}</form></BuilderCard>
    <BuilderCard title={t.addPartTitle} help={t.examHelp}><form className="grid gap-4 md:grid-cols-2" onSubmit={(event) => { const f = form(event); void request("examPart", { examId: f.get("examId"), partNumber: Number(f.get("partNumber")), title: String(f.get("title") ?? "").trim(), skill: f.get("skill"), instructions: String(f.get("instructions") ?? "").trim() || undefined, durationSeconds: Number(f.get("durationSeconds")) || undefined }, t.partDone); }}>{draftExams.length ? <><Select label={t.selectExam} name="examId" value={examId} onChange={setExamId}>{draftExams.map((item) => <option key={item.id} value={item.id}>{item.type} · {item.title}</option>)}</Select><Field label={t.partNumber} name="partNumber" type="number" defaultValue={parts.length + 1} /><Field label={t.partTitle} name="title" /><Select label={t.skill} name="skill"><option>LISTENING</option><option>READING</option></Select><Area label={t.instructions} name="instructions" required={false} /><Field label={t.duration} name="durationSeconds" type="number" required={false} /><Submit label={t.addPart} pending={pending === "examPart"} /></> : <Empty text={t.noExam} />}</form></BuilderCard>
    <BuilderCard title={t.passageTitle} help={t.examHelp}><form className="grid gap-4 md:grid-cols-2" onSubmit={(event) => { const f = form(event); void request("passage", { examPartId: f.get("examPartId"), title: String(f.get("title") ?? "").trim(), content: String(f.get("content") ?? "").trim(), sortOrder: Number(f.get("sortOrder")) }, t.passageDone); }}>{data.examParts.length ? <><Select label={t.selectPart} name="examPartId">{data.examParts.map((item) => <option key={item.id} value={item.id}>{item.examTitle} · {item.partNumber} · {item.title}</option>)}</Select><Field label={t.passageName} name="title" /><Area label={t.body} name="content" /><Field label={t.order} name="sortOrder" type="number" defaultValue={1} /><Submit label={t.addPassage} pending={pending === "passage"} /></> : <Empty text={t.noExam} />}</form></BuilderCard>
    <BuilderCard title={t.questionTitle} help={t.questionHelp}><form className="grid gap-4 md:grid-cols-2" onSubmit={(event) => { const f = form(event); const options = ["a", "b", "c", "d"].map((id) => ({ id, text: String(f.get(`option-${id}`) ?? "").trim() })).filter((item) => item.text); void request("question", { examPartId: f.get("examPartId"), passageId: String(f.get("passageId") ?? "") || undefined, prompt: String(f.get("prompt") ?? "").trim(), options, correctOptionId: f.get("correctOptionId"), explanation: String(f.get("explanation") ?? "").trim(), tags: String(f.get("tags") ?? "").split(",").map((item) => item.trim()).filter(Boolean) }, t.questionDone); }}>{data.examParts.length ? <><Select label={t.selectPart} name="examPartId">{data.examParts.map((item) => <option key={item.id} value={item.id}>{item.examTitle} · {item.partNumber} · {item.title}</option>)}</Select><Select label={t.selectPassage} name="passageId" required={false}><option value="">{t.choose}</option>{data.passages.map((item) => <option key={item.id} value={item.id}>{item.title ?? t.all}</option>)}</Select><Area label={t.practiceQuestion} name="prompt" />{["a", "b", "c", "d"].map((item, index) => <Field key={item} label={`${t.option} ${item.toUpperCase()}`} name={`option-${item}`} required={index < 2} />)}<Select label={t.correct} name="correctOptionId">{["a", "b", "c", "d"].map((item) => <option key={item}>{item}</option>)}</Select><Field label={t.tags} name="tags" required={false} /><Area label={t.explanation} name="explanation" /><Submit label={t.addQuestion} pending={pending === "question"} /></> : <Empty text={t.noExam} />}</form></BuilderCard>
    <BuilderCard title={t.publishExamTitle} help={t.publishExamHelp}><div className="flex flex-wrap items-end gap-3">{data.exams.length ? <><Select label={t.selectExam} name="publishExamId" value={examId} onChange={setExamId}>{data.exams.map((item) => <option key={item.id} value={item.id}>{item.type} · {item.title} · {item.status}</option>)}</Select><Button disabled={!examId || pending === "publishExam"} onClick={() => examId && void request("publishExam", { examId }, t.examPublished)}>{pending === "publishExam" ? t.saving : t.publishExam}</Button>{data.exams.find((item) => item.id === examId)?.status === "PUBLISHED" && <Link href={`/exams/${data.exams.find((item) => item.id === examId)?.slug}`}><Button variant="secondary">{t.openExam}</Button></Link>}</> : <Empty text={t.noExam} />}</div></BuilderCard>
  </div>;
}

function LibraryBuilder({ t, data, request, upload, pending }: { t: Text; data: AdminEditorData; request: (operation: string, payload: Record<string, unknown>, message: string) => Promise<boolean>; upload: (event: FormEvent<HTMLFormElement>) => Promise<void>; pending: string | null }) { const batches = data.batches.filter((item) => item.status !== "ARCHIVED"); return <div className="mt-6 grid gap-6 lg:grid-cols-2"><BuilderCard title={t.mediaTitle} help={t.mediaHelp}><form className="grid gap-4" onSubmit={upload}><label className={labelClass}>{t.mediaTitle}<input className={fieldClass} name="file" type="file" accept="audio/mpeg,audio/wav,audio/ogg,image/png,image/jpeg,image/webp" required /></label><Submit label={t.upload} pending={pending === "media"} /></form></BuilderCard><BuilderCard title={t.vocabularyTitle} help={t.help}><form className="grid gap-4 md:grid-cols-2" onSubmit={(event) => { event.preventDefault(); const f = new FormData(event.currentTarget); void request("vocabulary", { contentBatchId: f.get("contentBatchId"), headword: String(f.get("headword") ?? "").trim(), partOfSpeech: String(f.get("partOfSpeech") ?? "").trim(), cefrLevel: f.get("cefrLevel"), ipa: String(f.get("ipa") ?? "").trim() || undefined, meaning: String(f.get("meaning") ?? "").trim(), example: String(f.get("example") ?? "").trim(), tags: String(f.get("tags") ?? "").split(",").map((item) => item.trim()).filter(Boolean) }, t.vocabDone); }}>{batches.length ? <><Select label={t.batch} name="contentBatchId">{batches.map((item) => <option key={item.id} value={item.id}>{batchLabel(item)}</option>)}</Select><Field label={t.word} name="headword" /><Field label={t.partOfSpeech} name="partOfSpeech" /><Select label={t.level} name="cefrLevel">{["A1", "A2", "B1", "B2", "C1", "C2"].map((item) => <option key={item}>{item}</option>)}</Select><Field label={t.ipa} name="ipa" required={false} /><Field label={t.meaning} name="meaning" /><Field label={t.example} name="example" /><Field label={t.tags} name="tags" required={false} /><Submit label={t.saveVocabulary} pending={pending === "vocabulary"} /></> : <Empty text={t.noBatch} />}</form></BuilderCard></div>; }
