"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { type FormEvent, useState } from "react";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import type { ContentImportSummary } from "@/modules/content-management/content-importer";

const field = "mt-1 w-full rounded-ui border border-line bg-canvas px-3 py-2 text-sm outline-none focus:border-brand";
const text = {
  vi: { title: "Content Importer", intro: "Tải file nguồn vào vùng nháp. Importer chỉ trích xuất và tạo nội dung DRAFT; bạn vẫn phải kiểm tra, preview và publish qua workflow.", file: "File nguồn", target: "Mục tiêu import", source: "Nguồn hoặc URL tham chiếu", license: "Giấy phép / quyền sử dụng", author: "Tác giả (không bắt buộc)", version: "Phiên bản", upload: "Tải lên và trích xuất", uploading: "Đang trích xuất…", formats: "Hỗ trợ .xlsx, .csv, .docx và .pdf; tối đa 20 MB.", exam: "Đề thi / question bank", lesson: "Bài học từ Word/PDF", staged: "Bản nháp import", review: "Map và duyệt", failed: "Không thể tải hoặc trích xuất file." },
  en: { title: "Content Importer", intro: "Upload a source file into staging. The importer only extracts and creates DRAFT content; you still review, preview and publish through the workflow.", file: "Source file", target: "Import target", source: "Source or reference URL", license: "Licence / usage rights", author: "Author (optional)", version: "Version", upload: "Upload and extract", uploading: "Extracting…", formats: "Supports .xlsx, .csv, .docx and .pdf up to 20 MB.", exam: "Exam / question bank", lesson: "Lesson from Word/PDF", staged: "Staged imports", review: "Map and review", failed: "The file could not be uploaded or extracted." }
} as const;

export function ContentImporter({ locale, imports }: { locale: "vi" | "en"; imports: ContentImportSummary[] }) {
  const t = text[locale]; const router = useRouter(); const [pending, setPending] = useState(false); const [error, setError] = useState<string>();
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setPending(true); setError(undefined); try { const response = await fetch("/api/admin/imports", { method: "POST", body: new FormData(event.currentTarget) }); const body = await response.json() as { id?: string; error?: string }; if (!response.ok || !body.id) throw new Error(body.error ?? t.failed); router.push(`/admin/imports/${body.id}`); router.refresh(); } catch (reason) { setError(reason instanceof Error ? reason.message : t.failed); } finally { setPending(false); } }
  return <div className="mt-8 grid gap-8 lg:grid-cols-[minmax(0,1fr)_minmax(20rem,0.7fr)]"><Card><h2 className="font-serif text-3xl font-bold">{t.title}</h2><p className="mt-3 leading-7 text-muted">{t.intro}</p><p className="mt-3 text-sm font-semibold text-brand">{t.formats}</p><form className="mt-7 grid gap-4 md:grid-cols-2" onSubmit={submit}><label className="block text-sm font-bold md:col-span-2">{t.file}<input className={field} name="file" type="file" accept=".xlsx,.csv,.docx,.pdf,application/pdf,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,application/vnd.openxmlformats-officedocument.wordprocessingml.document,text/csv" required /></label><label className="block text-sm font-bold">{t.target}<select className={field} name="targetType"><option value="EXAM">{t.exam}</option><option value="LESSON">{t.lesson}</option></select></label><label className="block text-sm font-bold">{t.version}<input className={field} name="version" defaultValue="1" required /></label><label className="block text-sm font-bold md:col-span-2">{t.source}<input className={field} name="source" placeholder="https://… or internal source record" required /></label><label className="block text-sm font-bold">{t.license}<input className={field} name="license" placeholder="Original content / CC BY…" required /></label><label className="block text-sm font-bold">{t.author}<input className={field} name="author" /></label><div className="md:col-span-2"><Button type="submit" disabled={pending}>{pending ? t.uploading : t.upload}</Button></div></form>{error && <p className="mt-5 rounded-ui bg-red-50 p-4 text-sm font-semibold text-red-800" role="alert">{error}</p>}</Card><Card><h2 className="font-serif text-2xl font-bold">{t.staged}</h2><div className="mt-5 space-y-3">{imports.length ? imports.slice().reverse().map((item) => <Link className="block rounded-ui border border-line p-4 transition hover:border-brand" key={item.id} href={`/admin/imports/${item.id}`}><p className="font-bold">{item.fileName}</p><p className="mt-1 text-sm text-muted">{item.fileType} · {item.targetType} · {item.status}</p><p className="mt-3 text-sm font-bold text-brand">{t.review} →</p></Link>) : <p className="text-sm text-muted">{locale === "vi" ? "Chưa có file nào trong vùng nháp." : "No staged files yet."}</p>}</div></Card></div>;
}
