"use client";

import { useState } from "react";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { LocalListeningPlayer } from "@/components/local-listening-player";
import type { LearnerLessonBlock } from "@/modules/lessons/repository";

type Props = { lessonId: string; blocks: LearnerLessonBlock[]; locale: "vi" | "en" };
type Result = { rawScore: number; totalQuestions: number; alreadyCompleted: boolean; questions: Array<{ questionId: string; correct: boolean; correctOptionId: string; explanation: string }> };
const copy = { vi: { practice: "Luyện tập", submit: "Hoàn thành bài học", submitting: "Đang lưu kết quả…", completed: "Đã lưu hoàn thành", score: "Kết quả", correct: "đúng", retry: "Bạn có thể làm lại để cải thiện điểm; tiến độ hoàn thành vẫn được giữ.", failed: "Không thể lưu kết quả. Hãy thử lại.", choose: "Chọn một đáp án cho mỗi câu trước khi nộp.", correctAnswer: "Đáp án đúng", viewProgress: "Xem tiến độ" }, en: { practice: "Practice", submit: "Complete lesson", submitting: "Saving result…", completed: "Completion saved", score: "Score", correct: "correct", retry: "You can try again to improve your score; your completion stays saved.", failed: "Could not save the result. Please try again.", choose: "Choose an answer for every question before submitting.", correctAnswer: "Correct answer", viewProgress: "View progress" } } as const;

export function LessonRunner({ lessonId, blocks, locale }: Props) {
  const text = copy[locale]; const questionBlocks = blocks.filter((block): block is Extract<LearnerLessonBlock, { type: "QUESTION_SET" }> => block.type === "QUESTION_SET"); const allQuestions = questionBlocks.flatMap((block) => block.content.questions); const [answers, setAnswers] = useState<Record<string, string>>({}); const [pending, setPending] = useState(false); const [error, setError] = useState<string | null>(null); const [result, setResult] = useState<Result | null>(null);
  async function submit() { if (allQuestions.some((question) => !answers[question.id])) { setError(text.choose); return; } setPending(true); setError(null); try { const response = await fetch(`/api/lessons/${lessonId}/complete`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ answers: allQuestions.map((question) => ({ questionId: question.id, selectedOptionId: answers[question.id] })) }) }); const body = await response.json() as Result & { error?: string }; if (!response.ok) throw new Error(body.error ?? text.failed); setResult(body); } catch (submitError) { setError(submitError instanceof Error ? submitError.message : text.failed); } finally { setPending(false); } }
  return <div className="mt-10 space-y-6">{blocks.filter((block): block is Extract<LearnerLessonBlock, { type: "RICH_TEXT" }> => block.type === "RICH_TEXT").map((block) => <Card key={block.id}><h2 className="font-serif text-2xl font-bold">{block.content.heading}</h2><p className="mt-4 whitespace-pre-line leading-7 text-muted">{block.content.body}</p></Card>)}{blocks.filter((block): block is Extract<LearnerLessonBlock, { type: "MEDIA" }> => block.type === "MEDIA").map((block) => <LocalListeningPlayer key={block.id} {...block.content} locale={locale} />)}{questionBlocks.map((block) => <Card key={block.id}><p className="text-sm font-bold text-brand">{text.practice}</p><p className="mt-3 leading-7 text-muted">{block.content.instruction}</p><div className="mt-7 space-y-8">{block.content.questions.map((question, index) => { const review = result?.questions.find((item) => item.questionId === question.id); return <fieldset key={question.id}><legend className="font-bold">{index + 1}. {question.prompt}</legend><div className="mt-4 grid gap-3">{question.options.map((option) => <label key={option.id} className="flex cursor-pointer items-center gap-3 rounded-ui border border-line p-4 has-[:checked]:border-brand has-[:checked]:bg-brand-soft"><input type="radio" name={question.id} value={option.id} checked={answers[question.id] === option.id} disabled={Boolean(result)} onChange={() => setAnswers((current) => ({ ...current, [question.id]: option.id }))} /><span>{option.text}</span></label>)}</div>{review && <div className={`mt-4 rounded-ui p-4 text-sm ${review.correct ? "bg-emerald-50 text-emerald-900" : "bg-amber-50 text-amber-950"}`}><p className="font-bold">{review.correct ? "✓" : "!"} {review.correct ? text.correct : text.correctAnswer}: {question.options.find((option) => option.id === review.correctOptionId)?.text}</p><p className="mt-2 leading-6">{review.explanation}</p></div>}</fieldset>; })}</div></Card>)}{allQuestions.length > 0 && !result && <Button disabled={pending} onClick={submit}>{pending ? text.submitting : text.submit}</Button>}{error && <p className="text-sm text-red-700" role="alert">{error}</p>}{result && <Card className="border-brand bg-brand-soft"><p className="font-bold text-brand">{text.completed}</p><h2 className="mt-2 font-serif text-3xl font-bold">{text.score}: {result.rawScore}/{result.totalQuestions} {text.correct}</h2><p className="mt-3 text-sm leading-6 text-muted">{text.retry}</p><Link className="mt-5 inline-flex" href="/dashboard"><Button>{text.viewProgress}</Button></Link></Card>}</div>;
}
