import { randomUUID } from "crypto";
import { desc, eq } from "drizzle-orm";
import type { LearnerRef } from "@/modules/learners/types";
import { createDatabase } from "@/db/client";
import { progressEvents } from "@/db/schema";
import type { ProgressEvent, ProgressEventType } from "./progress";
type NewProgressEvent = Omit<ProgressEvent, "id" | "occurredAt" | "sourceType" | "sourceId" | "idempotencyKey"> & { sourceType?: string | null; sourceId?: string | null; idempotencyKey?: string | null; occurredAt?: Date };
export async function appendProgressEvent(input: NewProgressEvent) { const db = createDatabase(); if (!db) return null; const event: ProgressEvent = { ...input, id: randomUUID(), sourceType: input.sourceType ?? null, sourceId: input.sourceId ?? null, idempotencyKey: input.idempotencyKey ?? null, occurredAt: input.occurredAt ?? new Date() }; const inserted = await db.insert(progressEvents).values({ id: event.id, learnerId: event.learnerId, type: event.type, skill: event.skill, sourceType: event.sourceType, sourceId: event.sourceId, idempotencyKey: event.idempotencyKey, metadata: event.metadata, occurredAt: event.occurredAt }).onConflictDoNothing().returning({ id: progressEvents.id }); return inserted.length ? event : null; }
export async function listProgressEvents(learner: LearnerRef): Promise<ProgressEvent[]> { const db = createDatabase(); if (!db) return []; const rows = await db.select().from(progressEvents).where(eq(progressEvents.learnerId, learner.learnerId)).orderBy(desc(progressEvents.occurredAt)).limit(500); return rows.map((row) => ({ ...row, type: row.type as ProgressEventType, skill: row.skill as ProgressEvent["skill"], sourceType: row.sourceType, sourceId: row.sourceId, idempotencyKey: row.idempotencyKey, metadata: row.metadata as Record<string, unknown> })); }
