import { existsSync } from "node:fs";
import { resolve } from "node:path";
import { drizzle } from "drizzle-orm/postgres-js";
import postgres from "postgres";
import { localExamFixtures } from "../../content/seed/local-exam-pack";
import { contentBatches, examParts, exams, passages, questions } from "../../apps/web/src/db/schema";
const batchId = "90000000-0000-4000-8000-000000000001";
for (const envFile of [resolve(process.cwd(), "apps/web/.env.local"), resolve(process.cwd(), ".env")]) if (existsSync(envFile)) process.loadEnvFile(envFile);
if (!process.env.DATABASE_URL) throw new Error("DATABASE_URL is required");
const client = postgres(process.env.DATABASE_URL, { prepare: false }); const db = drizzle(client);
async function seed() { await db.transaction(async (tx) => { await tx.insert(contentBatches).values({ id: batchId, source: "https://english4free.local/content/local-exam-pack-v1", license: "English 4 Free original content", author: "English 4 Free", reviewedBy: "English 4 Free", importedAt: new Date("2026-09-21T00:00:00.000Z"), version: "1", status: "PUBLISHED" }).onConflictDoUpdate({ target: contentBatches.id, set: { status: "PUBLISHED" } }); for (const exam of localExamFixtures) { await tx.insert(exams).values({ id: exam.id, slug: exam.slug, title: exam.title, type: exam.type, mode: exam.mode, durationSeconds: exam.durationSeconds, metadata: { originalDemo: true }, status: "PUBLISHED", contentBatchId: batchId }).onConflictDoUpdate({ target: exams.id, set: { title: exam.title, mode: exam.mode, durationSeconds: exam.durationSeconds, status: "PUBLISHED", updatedAt: new Date() } }); for (const [index, part] of exam.parts.entries()) { await tx.insert(examParts).values({ id: part.id, examId: exam.id, partNumber: part.partNumber, title: part.title, sortOrder: index + 1, instructions: part.instructions, skill: part.skill, metadata: part.metadata }).onConflictDoUpdate({ target: examParts.id, set: { title: part.title, instructions: part.instructions, skill: part.skill, metadata: part.metadata } }); if (part.passage) await tx.insert(passages).values({ id: part.passage.id, examPartId: part.id, title: part.passage.title, content: part.passage.content, sortOrder: 1 }).onConflictDoUpdate({ target: passages.id, set: { title: part.passage.title, content: part.passage.content } }); await tx.insert(questions).values({ id: part.question.id, examPartId: part.id, passageId: part.passage?.id, schemaVersion: 1, type: "MCQ", content: { prompt: part.question.prompt, options: part.question.options }, answer: { correctOptionId: part.question.correctOptionId }, explanation: part.question.explanation, tags: [exam.type.toLowerCase(), `part-${part.partNumber}`, exam.mode.toLowerCase()], status: "PUBLISHED", contentBatchId: batchId }).onConflictDoUpdate({ target: questions.id, set: { passageId: part.passage?.id, content: { prompt: part.question.prompt, options: part.question.options }, answer: { correctOptionId: part.question.correctOptionId }, explanation: part.question.explanation, status: "PUBLISHED", updatedAt: new Date() } }); } } }); }
seed().then(() => console.log("Seeded shared TOEIC/IELTS exam fixtures.")).catch((error: unknown) => { console.error(error instanceof Error ? error.message : error); process.exitCode = 1; }).finally(() => client.end());
