export const LOCAL_CONTENT_BATCH_ID = "c6eec55d-8c58-49a9-9c06-c0a149305b14";

type Question = { id: string; prompt: string; options: { id: string; text: string }[]; correctOptionId: string; explanation: string };
type Block = { id: string; type: "RICH_TEXT" | "MEDIA" | "QUESTION_SET"; sortOrder: number; content: Record<string, unknown> };
export type DemoLesson = { courseId: string; levelId: string; unitId: string; lessonId: string; courseSlug: string; level: "A1" | "A2" | "B1" | "B2" | "C1" | "C2"; courseTitle: string; unitTitle: string; slug: string; title: string; skill: "LISTENING" | "SPEAKING" | "READING" | "WRITING"; estimatedMinutes: number; blocks: Block[] };

const question = (id: string, prompt: string, options: [string, string, string], correctOptionId: string, explanation: string): Question => ({ id, prompt, options: options.map((text, index) => ({ id: ["a", "b", "c"][index], text })), correctOptionId, explanation });

export const localDemoLessons: DemoLesson[] = [
  { courseId: "3db5bfb2-5bb0-41ba-bb8d-e3063a1ad4e8", levelId: "5b8db10b-a9db-4d11-93c4-226a53fefbab", unitId: "8bb10b3e-3f18-4c83-8f66-aa1dc52ca1ee", lessonId: "a2a87e74-5ddb-4a11-8764-9b620031a5d9", courseSlug: "a1-foundations", level: "A1", courseTitle: "A1 Foundations", unitTitle: "Getting started", slug: "introduce-yourself", title: "Introduce yourself", skill: "SPEAKING", estimatedMinutes: 10, blocks: [
    { id: "78bcce79-031c-4f26-9b6b-6c8bcbe7597f", type: "RICH_TEXT", sortOrder: 1, content: { heading: "Say hello", body: "When you meet someone, you can say:\n\nHello. I’m Mai. Nice to meet you.\n\nUse “I’m” before your name. It is the short form of “I am”." } },
    { id: "e8350c39-40b1-4c8b-81e1-793b93df8bbb", type: "RICH_TEXT", sortOrder: 2, content: { heading: "Useful language", body: "• Hello. / Hi.\n• I’m [your name].\n• My name is [your name].\n• Nice to meet you.\n• Nice to meet you, too." } },
    { id: "d80c4dc3-8049-44d2-bfa1-78ec2c0d0427", type: "QUESTION_SET", sortOrder: 3, content: { instruction: "Choose the best answer.", questions: [question("f40d445d-9f99-4cac-8c10-bf3e1652b1a9", "Which sentence is a natural way to introduce yourself?", ["I am Mai. Nice to meet you.", "I Mai nice.", "My is Mai."], "a", "Use “I am + name” or “I’m + name” when you introduce yourself."), question("5fc5822f-465c-4a3a-bdb0-7e7a3f054b7b", "Complete the sentence: “___ name is Nam.”", ["My", "I", "Me"], "a", "“My” is a possessive adjective. We say “My name is …”.") ] } }
  ] },
  { courseId: "5a9f8e47-6c4e-4d83-92d6-427ae4b6a526", levelId: "b1c63b3f-71da-4d0f-9f67-4ad44b0f018d", unitId: "7fdbaf85-86db-453e-9eb6-73d1bd4a4769", lessonId: "8d93bbc4-6e77-49dc-a867-a32d5d634723", courseSlug: "a2-everyday", level: "A2", courseTitle: "A2 Everyday English", unitTitle: "Making plans", slug: "plans", title: "Make a simple plan", skill: "WRITING", estimatedMinutes: 12, blocks: [
    { id: "9d4d68e1-7f7e-4652-9f08-781a0fc69c1a", type: "RICH_TEXT", sortOrder: 1, content: { heading: "Grammar: be going to", body: "Use be going to for a plan you have already decided.\n\nI’m going to visit my aunt on Saturday.\nThey’re going to cook dinner tonight.\n\nForm: subject + am/is/are + going to + base verb." } },
    { id: "73e7e9e5-45eb-432d-9295-ec6d06c2cb1f", type: "QUESTION_SET", sortOrder: 2, content: { instruction: "Choose the sentence with the correct plan form.", questions: [question("5c3d782e-0fe6-47a2-b22f-503f3cb49991", "Which sentence is correct?", ["I going to study tonight.", "I am going to study tonight.", "I am go to study tonight."], "b", "After I, use am: “I am going to study.”"), question("b9f8bb2a-13c6-46b2-b0d5-a8014cf0af43", "Complete: “They ___ going to play football.”", ["is", "are", "be"], "b", "With they, use are: “They are going to …”.") ] } }
  ] },
  { courseId: "642a5a26-5190-4482-8dce-0f9a31845780", levelId: "5c2ec3b1-ee54-4fc9-b887-b915b7b6dc8f", unitId: "6e0c3e1f-aa44-47a5-bff1-7bb3cca45a6f", lessonId: "6eac35cd-00b4-4a2d-8f6a-5be6e970ed71", courseSlug: "b1-independent", level: "B1", courseTitle: "B1 Independent English", unitTitle: "Community voices", slug: "opinions", title: "A library for everyone", skill: "READING", estimatedMinutes: 15, blocks: [
    { id: "d090e4e6-3a83-4bd6-abcb-d94536a1c783", type: "RICH_TEXT", sortOrder: 1, content: { heading: "Reading passage", body: "The town library used to be quiet after school. Last year, it started a free homework club and a weekly book discussion. Now students, parents, and older residents visit the building for different reasons.\n\nLinh, a university student, volunteers on Tuesdays. She says the club helps younger learners ask questions without feeling embarrassed. The library manager plans to add a small collection of easy English books next month." } },
    { id: "4af1f2be-0c99-419f-9fca-c1b8211b90c9", type: "QUESTION_SET", sortOrder: 2, content: { instruction: "Read the passage and choose the best answer.", questions: [question("11111111-0aa1-4a62-86ec-d8aa3be27955", "Why does Linh volunteer?", ["She sells English books.", "She supports younger learners.", "She manages the library."], "b", "Linh says the club helps younger learners ask questions."), question("22222222-0aa1-4a62-86ec-d8aa3be27955", "What is planned for next month?", ["A homework fee.", "A new sports club.", "Easy English books."], "c", "The manager plans to add easy English books.") ] } }
  ] },
  { courseId: "0b2cba7c-5e25-4816-9eec-b9fb960f224a", levelId: "45140a81-3778-4796-a8a0-81a90a93c5b9", unitId: "336a0962-b7fc-4a34-831a-8f91b1d4ad46", lessonId: "5d4bcb71-a2d8-45ac-94d0-6c3caf750ee5", courseSlug: "b2-confident", level: "B2", courseTitle: "B2 Confident English", unitTitle: "Clear arguments", slug: "arguments", title: "Build a clear argument", skill: "WRITING", estimatedMinutes: 16, blocks: [
    { id: "0a4e47bb-732a-4f79-a2e9-3fb77909e5ba", type: "RICH_TEXT", sortOrder: 1, content: { heading: "Grammar: linking ideas", body: "A clear argument often has a claim, a reason, and an example.\n\nUse however to contrast two ideas. Use therefore to show a result. Use for example to introduce evidence.\n\nExample: Public transport can be crowded. However, it reduces traffic in city centres." } },
    { id: "f00d446c-28c8-4b93-a1af-9f3a7c94eb31", type: "QUESTION_SET", sortOrder: 2, content: { instruction: "Choose the best linking word.", questions: [question("33333333-0aa1-4a62-86ec-d8aa3be27955", "The train was delayed; ___, we arrived late.", ["therefore", "however", "for example"], "a", "Therefore introduces a result."), question("44444444-0aa1-4a62-86ec-d8aa3be27955", "Online lessons are flexible. ___, some learners miss face-to-face discussion.", ["Therefore", "However", "For example"], "b", "However introduces a contrast.") ] } }
  ] },
  { courseId: "a2d59c63-0b9f-4a37-87fe-f6fdd4d83610", levelId: "a0de2c78-c7dd-49b0-9939-992ab5f3ef51", unitId: "81042764-cc89-44d6-aaed-bd38e862cc34", lessonId: "78328da9-ed3f-474e-91e3-5097b7b15947", courseSlug: "c1-flexible", level: "C1", courseTitle: "C1 Flexible English", unitTitle: "Workplace communication", slug: "nuance", title: "Hear the nuance", skill: "LISTENING", estimatedMinutes: 15, blocks: [
    { id: "57366f52-9b9c-4e7e-b443-f0f3d6d8b5ed", type: "RICH_TEXT", sortOrder: 1, content: { heading: "Listening strategy", body: "Before you listen, identify the speaker’s purpose. Notice softening language such as “might”, “perhaps”, and “it would be useful”. It can make feedback sound constructive rather than negative." } },
    { id: "66e6e7c0-dc72-4723-8c37-093a0dc38f03", type: "MEDIA", sortOrder: 2, content: { heading: "Team feedback", playbackText: "Your draft is clear and the examples are relevant. It might be useful to explain the final recommendation in more detail, so that readers understand what action you want them to take.", transcript: "Your draft is clear and the examples are relevant. It might be useful to explain the final recommendation in more detail, so that readers understand what action you want them to take.", sourceLabel: "Original English 4 Free script · demo audio generated with neural text-to-speech (see public/demo-media/README.md)." } },
    { id: "94f1a8f0-2f4b-408b-823f-09e5e994d54b", type: "QUESTION_SET", sortOrder: 3, content: { instruction: "Listen, then choose the best answer.", questions: [question("55555555-0aa1-4a62-86ec-d8aa3be27955", "What does the speaker want improved?", ["The examples", "The final recommendation", "The draft length"], "b", "The speaker asks for more detail in the final recommendation."), question("66666666-0aa1-4a62-86ec-d8aa3be27955", "Why does the speaker use “might be useful”?", ["To make the feedback less direct", "To cancel the meeting", "To praise the writer’s grammar"], "a", "This softening phrase makes a suggestion sound constructive.") ] } }
  ] },
  { courseId: "c6ec5a74-20e2-4676-8d5e-11fa7d2d75d9", levelId: "c30e279d-6e5f-40bb-afdf-4a4b6e7d20fe", unitId: "45534dc3-0f8a-427f-bd52-4e516bb0956c", lessonId: "aa4e6e38-239c-4c1f-bac1-b1cddc2e204b", courseSlug: "c2-mastery", level: "C2", courseTitle: "C2 Language Mastery", unitTitle: "Precise communication", slug: "precision", title: "Interpret precise language", skill: "LISTENING", estimatedMinutes: 18, blocks: [
    { id: "c3cb4f48-5550-44f4-a6e9-fa4a9deaa81d", type: "RICH_TEXT", sortOrder: 1, content: { heading: "Listening strategy", body: "At C2, listen for qualification: a speaker may agree with an idea while limiting how strongly they support it. Words such as broadly, provided that, and in principle are important signals." } },
    { id: "4ca34df4-6304-4e49-a0f1-68f8a177b5e7", type: "MEDIA", sortOrder: 2, content: { heading: "A qualified opinion", playbackText: "I broadly support the proposal, provided that the pilot is evaluated independently. In principle, a shorter process could help applicants, but we should not assume that speed alone will improve the quality of decisions.", transcript: "I broadly support the proposal, provided that the pilot is evaluated independently. In principle, a shorter process could help applicants, but we should not assume that speed alone will improve the quality of decisions.", sourceLabel: "Original English 4 Free script · demo audio generated with neural text-to-speech (see public/demo-media/README.md)." } },
    { id: "f99258d8-5276-458c-bf5a-d2b7c28c92b3", type: "QUESTION_SET", sortOrder: 3, content: { instruction: "Listen for the speaker’s qualification.", questions: [question("77777777-0aa1-4a62-86ec-d8aa3be27955", "What condition does the speaker set?", ["The pilot must be evaluated independently.", "Applicants must pay less.", "The process must be longer."], "a", "Support is conditional on independent evaluation."), question("88888888-0aa1-4a62-86ec-d8aa3be27955", "What does the speaker question?", ["Whether the proposal is shorter", "Whether speed alone improves decisions", "Whether applicants exist"], "b", "The speaker does not assume speed alone improves decision quality.") ] } }
  ] }
];

export const localDemoVocabulary = [
  ["hello", "interjection", "A1", "/həˈləʊ/", "xin chào", "Hello, I’m Linh.", ["greetings"]], ["name", "noun", "A1", "/neɪm/", "tên", "My name is An.", ["identity"]], ["meet", "verb", "A1", "/miːt/", "gặp", "Nice to meet you.", ["greetings"]],
  ["plan", "noun", "A2", "/plæn/", "kế hoạch", "Our plan is simple.", ["daily-life"]], ["visit", "verb", "A2", "/ˈvɪzɪt/", "thăm", "I’m going to visit my aunt.", ["daily-life"]], ["tonight", "adverb", "A2", "/təˈnaɪt/", "tối nay", "We are cooking tonight.", ["time"]],
  ["volunteer", "verb", "B1", "/ˌvɒlənˈtɪə/", "tình nguyện", "She volunteers on Tuesdays.", ["community"]], ["resident", "noun", "B1", "/ˈrezɪdənt/", "cư dân", "Older residents use the library.", ["community"]], ["embarrassed", "adjective", "B1", "/ɪmˈbærəst/", "ngại ngùng", "He felt embarrassed to ask.", ["feelings"]],
  ["therefore", "adverb", "B2", "/ˈðeəfɔː/", "vì vậy", "The road was closed; therefore, we walked.", ["linking"]], ["however", "adverb", "B2", "/haʊˈevə/", "tuy nhiên", "However, the idea needs evidence.", ["linking"]], ["evidence", "noun", "B2", "/ˈevɪdəns/", "bằng chứng", "Give an example as evidence.", ["argument"]],
  ["constructive", "adjective", "C1", "/kənˈstrʌktɪv/", "mang tính xây dựng", "Her feedback was constructive.", ["work"]], ["recommendation", "noun", "C1", "/ˌrekəmenˈdeɪʃn/", "đề xuất", "The report includes a recommendation.", ["work"]], ["relevant", "adjective", "C1", "/ˈreləvənt/", "liên quan", "Use relevant examples.", ["work"]],
  ["broadly", "adverb", "C2", "/ˈbrɔːdli/", "nhìn chung", "I broadly agree with the idea.", ["nuance"]], ["provided that", "phrase", "C2", "/prəˈvaɪdɪd ðæt/", "với điều kiện là", "We can proceed provided that we test it.", ["nuance"]], ["independently", "adverb", "C2", "/ˌɪndɪˈpendəntli/", "một cách độc lập", "The pilot was evaluated independently.", ["nuance"]]
] as const;
