export type ExamMode = "PRACTICE" | "MINI_TEST" | "FULL_MOCK";
type PartFixture = { id: string; partNumber: number; title: string; skill: "LISTENING" | "READING"; instructions: string; metadata: Record<string, unknown>; passage?: { id: string; title: string; content: string }; question: { id: string; prompt: string; options: { id: string; text: string }[]; correctOptionId: string; explanation: string } };
export type ExamFixture = { id: string; slug: string; title: string; type: "TOEIC" | "IELTS"; mode: ExamMode; durationSeconds: number; parts: PartFixture[] };
const uuid = (value: number) => `90000000-0000-4000-8000-${value.toString(16).padStart(12, "0")}`;
const options = (correct: string, wrong1: string, wrong2: string) => [{ id: "a", text: correct }, { id: "b", text: wrong1 }, { id: "c", text: wrong2 }];
const toeicPart = (partNumber: number, offset: number): PartFixture => {
  const listening = partNumber <= 4; const definitions: Record<number, { title: string; prompt: string; correct: string; wrong1: string; wrong2: string; passage?: string; audio?: string }> = {
    1: { title: "Photographs", prompt: "Which statement best describes the demo scene?", correct: "A person is arranging books on a shelf.", wrong1: "The shelves are being removed.", wrong2: "Several people are waiting outside.", audio: "Look at the scene. A person is arranging books on a shelf." },
    2: { title: "Question–response", prompt: "Where will the workshop take place?", correct: "In the second-floor meeting room.", wrong1: "At three o’clock.", wrong2: "Yes, I enjoyed it.", audio: "Where will the workshop take place? In the second-floor meeting room." },
    3: { title: "Conversations", prompt: "What will the speakers do next?", correct: "Check the updated schedule.", wrong1: "Cancel the event.", wrong2: "Order new computers.", audio: "The meeting time has changed. Let us check the updated schedule before we email the team." },
    4: { title: "Short talks", prompt: "What is the purpose of the announcement?", correct: "To explain a temporary entrance change.", wrong1: "To advertise a new restaurant.", wrong2: "To announce a job opening.", audio: "The main entrance is closed today for maintenance. Please use the east entrance beside the café." },
    5: { title: "Incomplete sentences", prompt: "The report must be submitted ___ Friday.", correct: "by", wrong1: "during", wrong2: "among" },
    6: { title: "Text completion", prompt: "Which word best completes the notice?", correct: "available", wrong1: "availability", wrong2: "availably", passage: "The new training guide is now ___ on the staff portal. Please read it before Monday." },
    7: { title: "Reading comprehension", prompt: "Why did Mina write the message?", correct: "To confirm a delivery time.", wrong1: "To request a refund.", wrong2: "To apply for a position.", passage: "Hello Alex, the replacement chairs will arrive between 9 and 11 tomorrow. Please confirm that someone can open the storage room. Thanks, Mina." }
  }; const item = definitions[partNumber];
  return { id: uuid(offset), partNumber, title: item.title, skill: listening ? "LISTENING" : "READING", instructions: listening ? "Listen once and choose the best answer." : "Read and choose the best answer.", metadata: listening ? { playbackText: item.audio, playbackLimit: 1, mediaKind: "BROWSER_TTS" } : {}, passage: item.passage ? { id: uuid(offset + 100), title: `${item.title} passage`, content: item.passage } : undefined, question: { id: uuid(offset + 200), prompt: item.prompt, options: options(item.correct, item.wrong1, item.wrong2), correctOptionId: "a", explanation: `The best answer is “${item.correct}”.` } };
};
const makeToeic = (idValue: number, slug: string, title: string, mode: ExamMode, parts: number[], durationSeconds: number): ExamFixture => ({ id: uuid(idValue), slug, title, type: "TOEIC", mode, durationSeconds, parts: parts.map((part, index) => toeicPart(part, idValue + 10 + index)) });
const practices = Array.from({ length: 7 }, (_, index) => makeToeic(1000 + index * 30, `toeic-part-${index + 1}-demo`, `TOEIC Part ${index + 1} Demo`, "PRACTICE", [index + 1], 300));
const ieltsListening: ExamFixture = { id: uuid(2000), slug: "ielts-listening-demo", title: "IELTS Listening Demo", type: "IELTS", mode: "PRACTICE", durationSeconds: 480, parts: [{ id: uuid(2001), partNumber: 1, title: "Community event", skill: "LISTENING", instructions: "Listen and choose the best answer.", metadata: { playbackText: "The community garden workshop starts at ten thirty on Saturday morning. Please bring a hat and a bottle of water.", playbackLimit: 2, mediaKind: "BROWSER_TTS" }, question: { id: uuid(2002), prompt: "What should participants bring?", options: options("A hat and water.", "A laptop.", "Gardening tools only."), correctOptionId: "a", explanation: "The announcement asks for a hat and a bottle of water." } }] };
const ieltsReading: ExamFixture = { id: uuid(2100), slug: "ielts-reading-demo", title: "IELTS Reading Demo", type: "IELTS", mode: "PRACTICE", durationSeconds: 600, parts: [{ id: uuid(2101), partNumber: 1, title: "Urban trees", skill: "READING", instructions: "Read the passage and choose the best answer.", metadata: {}, passage: { id: uuid(2102), title: "Urban trees", content: "Trees can lower surface temperatures in cities by providing shade. Their benefits depend on species, location, water availability, and long-term maintenance." }, question: { id: uuid(2103), prompt: "What does the passage say affects the benefits of urban trees?", options: options("Several planning and maintenance factors.", "Only the age of a city.", "The number of nearby cars."), correctOptionId: "a", explanation: "The passage lists species, location, water, and maintenance." } }] };
export const localExamFixtures: ExamFixture[] = [...practices, makeToeic(1500, "toeic-mini-demo", "TOEIC Mini Test", "MINI_TEST", [1, 2, 5, 7], 900), makeToeic(1700, "toeic-full-demo", "TOEIC Full-format Demo", "FULL_MOCK", [1, 2, 3, 4, 5, 6, 7], 1800), ieltsListening, ieltsReading];
