import { choose, gap, match, mcq, type ExamDef } from "../types";

const C = (prompt: string, options: [string, string, string], correct: "A" | "B" | "C", explanation: string) => mcq(prompt, options, correct, explanation);

export const ieltsListening2: ExamDef = {
  key: "ielts:listening-2", batch: "ielts", slug: "ielts-listening-test-2", title: "IELTS Listening Test 2", type: "IELTS", mode: "PRACTICE", durationSeconds: 40 * 60,
  parts: [
    {
      partNumber: 1, title: "Section 1 · Joining a sports centre", skill: "LISTENING", instructions: "You will hear a conversation at a sports centre. Complete the form and notes. Write NO MORE THAN TWO WORDS AND/OR A NUMBER for each answer.",
      groups: [{ title: "Questions 1–10", listening: { voices: { Receptionist: "male", Sofia: "female" }, script: "Receptionist: Good afternoon, Parkside Sports Centre. How can I help?\nSofia: Hi. I'd like to become a member, please.\nReceptionist: Great. Can I take your name?\nSofia: Sofia Hartley. That's H-A-R-T-L-E-Y.\nReceptionist: Thank you. And your date of birth?\nSofia: The nineteenth of July, nineteen ninety-six.\nReceptionist: Lovely. Now, we have three types of membership. The standard one covers the gym and the pool. The off-peak one is the same but only before four o'clock on weekdays. And the premium membership adds all the fitness classes.\nSofia: I work during the day, so off-peak is no good. I'd like to do some classes, so I'll take premium.\nReceptionist: Premium is thirty-eight pounds a month. Would you like to pay monthly or for the whole year?\nSofia: How much is the year?\nReceptionist: Four hundred and twenty pounds, which works out cheaper.\nSofia: I'll pay monthly for now, thanks.\nReceptionist: No problem. And when would you like to start?\nSofia: Next Monday, if possible. That's the third of March.\nReceptionist: That's fine. Now, a few things you need to know. Before you use the gym, you have to book an induction session with a trainer. They last about forty-five minutes.\nSofia: Okay. Do I need to bring anything?\nReceptionist: Just a towel and a padlock for the lockers. And for the pool, swimming caps are required.\nSofia: Right. Is there a car park?\nReceptionist: Yes, at the back. It's free for members, but you need to register your car's number plate here at reception.\nSofia: And can I bring a friend sometimes?\nReceptionist: Premium members get four guest passes a year. After that, guests pay seven pounds fifty a visit.\nSofia: Perfect. One more thing — the yoga classes. Are they very busy?\nReceptionist: The evening ones fill up quickly, so book them online. You can reserve a place up to seven days in advance." }, questions: [
        gap("Parkside Sports Centre — Membership form\nName: Sofia ___\nDate of birth: ___ July 1996\nType of membership: ___\nPayment: £___ per month\nStart date: ___ March", [["Hartley"], ["19", "19th", "nineteenth"], ["premium"], ["38", "thirty-eight"], ["3", "3rd", "third"]], "Hartley is spelled out; 19 July; premium (off-peak doesn't suit her); £38 a month; Monday 3 March.", 2),
        gap("Notes\nBefore using the gym, book an ___ session.\nBring a towel and a ___ for the lockers.\nIn the pool, swimming ___ must be worn.\nTo park free, register your number plate at ___.\nYoga places can be reserved up to ___ days in advance.", [["induction"], ["padlock"], ["caps"], ["reception"], ["7", "seven"]], "Induction session; a padlock; swimming caps; register at reception; up to seven days in advance.", 2)
      ] }]
    },
    {
      partNumber: 2, title: "Section 2 · A guided walk through the old town", skill: "LISTENING", instructions: "You will hear a tour guide talking to a group at the start of a walk. Answer the questions.",
      groups: [{ title: "Questions 11–20", listening: { voices: { Guide: "female" }, script: "Guide: Good morning, everyone, and welcome to the Old Harbour Walk. I'm Joanna, and I'll be your guide for the next two hours. Before we set off, a few practical points.\nThe walk is about three kilometres, but it's mostly flat. There is one steep section near the lighthouse, and if anyone would rather avoid it, there's a lift by the café that takes you to the same place.\nWe'll stop for a break at the halfway point, at the old fish market. It's now a food hall, and you'll have about twenty minutes there. The tickets you bought include a hot drink, but food isn't included.\nThe tour usually finishes at one o'clock at the harbour museum. Your ticket also gives you free entry to the museum for the rest of the day, so you can go back later if you like.\nNow, a little history. The harbour was built in the twelve hundreds, mainly for the wool trade, and wool remained the town's main export for about three hundred years. Later, fishing became more important, and at its peak in the eighteen nineties, over a hundred boats were based here. Today there are only a handful of fishing boats left; most of the harbour is used by leisure boats.\nAs we go round, we'll see several buildings that tell this story. Our first stop is the Customs House, where taxes on goods were collected. It's now the town library, and it has a lovely reading room on the top floor with a view over the water. After that, we'll pass the Ropewalk — a very long, narrow building where ropes for ships were made by hand. These days it's divided into artists' studios, and some of them are open to visitors on Saturdays. Then there's the Sailors' Chapel. It's small, but look out for the model ships hanging from the ceiling — they were given by local families. Finally, near the end of the walk, you'll see the old lifeboat station, which now houses a seafood restaurant.\nRight, if everyone's ready, let's begin." }, questions: [
        C("How long is the walk?", ["About two kilometres", "About four kilometres", "About three kilometres"], "C", "The walk is about three kilometres."),
        C("What can people do to avoid the steep section?", ["Take a lift near the café", "Wait at the lighthouse", "Take a short cut through the market"], "A", "There's a lift by the café that takes you to the same place."),
        C("What is included in the ticket at the food hall?", ["A snack", "A hot drink", "A full lunch"], "B", "The tickets include a hot drink, but food isn't included."),
        C("Where does the tour finish?", ["At the lighthouse", "At the fish market", "At the harbour museum"], "C", "The tour usually finishes at one o'clock at the harbour museum."),
        choose("Which TWO statements about the harbour's history are correct?", ["It was first built for the wool trade.", "Fishing was always the main activity.", "Over a hundred fishing boats were based there in the 1890s.", "It was closed for most of the twentieth century.", "It is still mainly used by fishing boats today."], ["A", "C"], "Built in the 1200s mainly for wool; over a hundred boats at the peak in the 1890s. Today most boats are leisure boats."),
        match("What is each building used for today? Choose the correct letter for each building.", ["the Customs House", "the Ropewalk", "the Sailors' Chapel", "the old lifeboat station"], ["a restaurant", "a library", "artists' studios", "a museum of ships", "a place of worship with model ships", "a ticket office"], ["B", "C", "E", "A"], "Customs House: the town library. Ropewalk: artists' studios. Sailors' Chapel: still a chapel, with model ships. Lifeboat station: a seafood restaurant.")
      ] }]
    },
    {
      partNumber: 3, title: "Section 3 · Preparing a presentation on city birds", skill: "LISTENING", instructions: "You will hear two students and their tutor discussing a presentation. Answer the questions.",
      groups: [{ title: "Questions 21–30", listening: { voices: { Tutor: "male", Hana: "female", Owen: "male" }, script: "Tutor: So, Hana, Owen — your presentation is on how birds adapt to city life. Where have you got to?\nHana: We've done most of the reading. At first we wanted to cover every kind of adaptation, but there's far too much, so we've narrowed it down to changes in behaviour rather than physical changes.\nTutor: That's wise. Twenty minutes goes very quickly. What examples are you using?\nOwen: The main one is birdsong. Several studies have found that some city birds sing at a higher pitch than birds of the same species in the countryside.\nTutor: And the explanation?\nOwen: Traffic noise is mostly low-pitched, so a higher song is easier to hear over it. Some birds also sing earlier in the morning, before the traffic starts.\nTutor: Good. Have you thought about how to present that? Audio would be much more effective than just describing it.\nHana: Yes, we've found some recordings with an open licence that we can play. We just need to check the projector in the room has speakers.\nTutor: I'd test that well in advance. Now, what's your second example?\nHana: Feeding. Some species have learned to use new food sources — for example, birds that open rubbish bins or wait near outdoor cafés.\nTutor: Be careful with that one. A few clips of a clever bird are entertaining, but they don't prove that a whole population has changed its behaviour.\nOwen: That's a fair point. We could look for a study with proper numbers instead.\nTutor: Exactly. And what about the structure?\nHana: I'll do the introduction and the part on song, and Owen will do feeding.\nOwen: And I'll do the conclusion, because I'm going to talk about what cities can do to help birds — things like planting native trees.\nTutor: And who's handling questions at the end?\nHana: Both of us, I think. Whoever knows more about the topic.\nTutor: Fine. One last thing: your slides. At the moment there's far too much text on them.\nOwen: We'll cut it down and use more photos.\nTutor: Good. And practise together at least twice — timing is where most groups lose marks." }, questions: [
        C("Why did the students narrow the topic?", ["There was too much material to cover.", "The tutor told them to.", "They could not find enough studies."], "A", "There's far too much, so we've narrowed it down to changes in behaviour."),
        C("According to Owen, why do some city birds sing at a higher pitch?", ["To attract more partners", "Because city birds are smaller", "To be heard over low-pitched traffic noise"], "C", "Traffic noise is mostly low-pitched, so a higher song is easier to hear."),
        C("What does the tutor advise about the audio recordings?", ["Avoid using them", "Test the equipment well in advance", "Ask the tutor for recordings"], "B", "I'd test that well in advance."),
        C("What concern does the tutor raise about the feeding example?", ["Video clips do not prove that a whole population has changed.", "The topic is too similar to birdsong.", "Feeding birds in cities is illegal."], "A", "A few clips… don't prove that a whole population has changed its behaviour."),
        C("What is the tutor's final piece of advice?", ["Practise together for timing", "Use fewer photos", "Add more text to the slides"], "A", "Practise together at least twice — timing is where most groups lose marks."),
        match("Who will be responsible for each part of the presentation? Choose A for Hana, B for Owen or C for both students.", ["the introduction", "the section on birdsong", "the section on feeding", "the conclusion", "answering questions"], ["Hana", "Owen", "both Hana and Owen"], ["A", "A", "B", "B", "C"], "Hana: introduction and song. Owen: feeding and the conclusion. Both: questions.")
      ] }]
    },
    {
      partNumber: 4, title: "Section 4 · Lecture: turning seawater into drinking water", skill: "LISTENING", instructions: "You will hear part of a lecture. Complete the notes. Write ONE WORD ONLY for each answer.",
      groups: [{ title: "Questions 31–40", listening: { voices: { Lecturer: "male" }, script: "Lecturer: Today we're looking at desalination: the process of removing salt from seawater so that it can be used for drinking or farming.\nThe oldest method is essentially the same as what happens in nature. Water is heated until it becomes steam, leaving the salt behind, and the steam is then cooled so that it turns back into fresh water. This is called thermal desalination. Its great disadvantage is the amount of energy needed to heat large volumes of water.\nMost new plants built in recent decades use a different method: reverse osmosis. Here, seawater is pushed at high pressure through a membrane — a very thin sheet with tiny holes. Water molecules can pass through, but most of the salt cannot. Reverse osmosis generally uses less energy than heating, but it is still energy-intensive, because of the high pressure required.\nThe membranes themselves need careful protection. Seawater contains sand, algae and other particles, which would block the membranes very quickly, so the water must be filtered before it reaches them.\nDesalination also creates a by-product called brine. This is water with a very high concentration of salt, and it is usually returned to the sea. If brine is released in one place, it can sink to the sea floor and harm the creatures living there, so engineers try to mix it with large amounts of ordinary seawater first.\nWhy, then, do countries use desalination at all? Mainly because it provides a supply of water that does not depend on rainfall. For dry coastal regions, this reliability can be worth the cost.\nThe future of the technology probably depends on two things: cheaper energy, particularly from solar power, and more efficient membranes. If both improve, desalination may become an important part of the water supply in many more parts of the world." }, questions: [
        gap("Desalination — lecture notes\nThermal method: water is turned into ___, leaving the salt behind.\nMain disadvantage: the ___ needed to heat the water.\nReverse osmosis: seawater is pushed under high ___ through a membrane.\nThe membrane lets ___ pass but blocks most of the salt.\nBefore treatment, seawater must be ___ to protect the membranes.", [["steam"], ["energy"], ["pressure"], ["water"], ["filtered"]], "Steam; energy; high pressure; water molecules pass through; the water must be filtered.", 1),
        gap("By-product: ___, which contains a very high concentration of salt.\nIf released in one place, it can harm creatures on the sea ___.\nEngineers ___ it with ordinary seawater before release.\nMain advantage: supply does not depend on ___.\nFuture improvements: cheaper ___ power and more efficient membranes.", [["brine"], ["floor", "bed"], ["mix"], ["rainfall", "rain"], ["solar"]], "Brine; it can sink to the sea floor; engineers mix it with seawater; it doesn't depend on rainfall; cheaper solar power.", 1)
      ] }]
    }
  ]
};
