import { choose, gap, match, mcq, type ExamDef } from "../types";

const C = (prompt: string, options: [string, string, string], correct: "A" | "B" | "C", explanation: string) => mcq(prompt, options, correct, explanation);

export const ieltsListening1: ExamDef = {
  key: "ielts:listening-1", batch: "ielts", slug: "ielts-listening-test-1", title: "IELTS Listening Test 1", type: "IELTS", mode: "PRACTICE", durationSeconds: 40 * 60,
  parts: [
    {
      partNumber: 1, title: "Section 1 · Course enrolment", skill: "LISTENING", instructions: "You will hear a telephone conversation about enrolling on a course. Complete the form and notes. Write NO MORE THAN TWO WORDS AND/OR A NUMBER for each answer.",
      groups: [{ title: "Questions 1–10", listening: { voices: { Receptionist: "female", Thomas: "male" }, script: "Receptionist: Good morning, Riverside Community Centre. How can I help you?\nThomas: Hello. I'm calling about the evening photography courses. I'd like to enrol on the one for beginners.\nReceptionist: Of course. Let me take a few details. What's your name, please?\nThomas: Thomas Kowalski. That's K-O-W-A-L-S-K-I.\nReceptionist: Thank you. And your address?\nThomas: Forty-two Station Road.\nReceptionist: Forty-two Station Road. And the postcode?\nThomas: B-S-7, 3-L-P.\nReceptionist: Great. Now, the beginners' course runs on two evenings. There's a Tuesday group and a Wednesday group.\nThomas: I was going to say Tuesday, but I've just remembered I have football training that night. So Wednesday, please.\nReceptionist: Wednesday it is. The standard fee is ninety-five pounds for the ten weeks, but if you book before the end of this month, it's eighty-five.\nThomas: Then I'll pay now, so the lower fee.\nReceptionist: Perfect. Let me tell you a few practical things. You'll need your own camera, of course, and please bring a tripod. The tutor uses it from the second week onwards.\nThomas: I've got one somewhere. Where are the classes held? In the main hall?\nReceptionist: The main hall is being repainted this term, so the course will be in the garden room, at the back of the building.\nThomas: And is there parking?\nReceptionist: Yes, there's a car park next door. It's free after six p.m., and the class starts at half past six, so that shouldn't be a problem.\nThomas: Good. Are there any discounts? My sister might want to join.\nReceptionist: We offer a discount for students, and for people over sixty-five, but not for family members, I'm afraid.\nThomas: She's at college, so that's fine. When does the course start?\nReceptionist: The first session is on the fourteenth of September. Not the seventh, as it says on the old leaflet.\nThomas: The fourteenth. Thanks very much." }, questions: [
        gap("Riverside Community Centre — Enrolment form\nName: Thomas ___\nAddress: ___ Station Road\nPostcode: ___\nGroup (day of the week): ___\nFee paid: £___", [["Kowalski"], ["42", "forty-two"], ["BS7 3LP", "BS73LP"], ["Wednesday"], ["85", "eighty-five"]], "Kowalski is spelled out; 42 Station Road; postcode BS7 3LP; he changes from Tuesday to Wednesday; booking early gives the £85 fee.", 2),
        gap("Notes\nBring your own camera and a ___.\nClasses take place in the ___ room.\nParking is free after ___ p.m.\nDiscounts are available for ___ and people over 65.\nThe course starts on ___ September.", [["tripod"], ["garden"], ["6", "six"], ["students"], ["14", "14th", "fourteenth"]], "Tripod from week two; the garden room because the main hall is being repainted; parking free after 6 p.m.; discount for students; start date 14 September (not the 7th).", 2)
      ] }]
    },
    {
      partNumber: 2, title: "Section 2 · Volunteering at a nature reserve", skill: "LISTENING", instructions: "You will hear a talk to new volunteers at a nature reserve. Answer the questions.",
      groups: [{ title: "Questions 11–20", listening: { voices: { Speaker: "male" }, script: "Speaker: Good morning, everyone, and welcome to Heron Lake Nature Reserve. My name is Graham, and I coordinate our volunteer programme. Thank you all for giving up your time.\nFirst, a little background. The reserve was created in 1987 on the site of an old gravel quarry. When the digging stopped, the pits filled with water, and birds started arriving almost immediately. Today we record over two hundred species every year.\nMost of you will work on Saturday mornings. We meet at the visitor centre at nine, and sessions finish at one. We provide gloves and tools, but please wear strong boots, as the paths get muddy even in summer.\nYour main tasks this season will be two. First, helping to clear the reeds around the north pond, which are spreading too fast and leave no open water for ducks. Second, repairing the wooden walkways, because several boards were damaged in the winter storms. We won't ask you to handle any birds, and bird counts are done by our trained staff.\nNow let me tell you about the different areas of the reserve, which you'll get to know well. The woodland trail is the quietest part. If you want to see woodpeckers, that's the place. The meadow is at its best in June, when it's covered in wild orchids, so please keep to the paths there. The main hide overlooks the large lake and has space for twenty people; it's where most visitors go, and it can get crowded at weekends. Finally, the children's area near the car park has a pond-dipping platform, where school groups look for small water creatures.\nOne last thing: the café in the visitor centre gives volunteers a free drink after every session, so do make use of it." }, questions: [
        C("The nature reserve was created on the site of", ["a quarry.", "a farm.", "a factory."], "A", "It was created on the site of an old gravel quarry."),
        C("How many bird species are recorded each year?", ["Over one hundred", "Over two hundred", "Over three hundred"], "B", "Today we record over two hundred species every year."),
        C("Volunteers are asked to", ["bring their own tools.", "wear strong boots.", "arrive at the car park at nine."], "B", "Please wear strong boots, as the paths get muddy. Tools are provided; they meet at the visitor centre."),
        C("Volunteer sessions finish at", ["twelve o'clock.", "two o'clock.", "one o'clock."], "C", "Sessions finish at one."),
        choose("Which TWO tasks will volunteers do this season?", ["counting birds", "clearing reeds", "building a new hide", "repairing walkways", "feeding ducks"], ["B", "D"], "Clearing the reeds around the north pond and repairing the wooden walkways. Bird counts are done by staff."),
        match("What can visitors find in each area of the reserve? Choose the correct letter for each area.", ["the woodland trail", "the meadow", "the main hide", "the children's area"], ["wild flowers in early summer", "a platform for pond dipping", "the quietest place and woodpeckers", "a café with free drinks", "a view over the large lake", "a new playground"], ["C", "A", "E", "B"], "Woodland trail: quietest, woodpeckers. Meadow: wild orchids in June. Main hide: overlooks the large lake. Children's area: pond-dipping platform.")
      ] }]
    },
    {
      partNumber: 3, title: "Section 3 · Planning a research project", skill: "LISTENING", instructions: "You will hear two students talking to their tutor about a research project. Answer the questions.",
      groups: [{ title: "Questions 21–30", listening: { voices: { Tutor: "female", Maya: "female", Leon: "male" }, script: "Tutor: Come in, Maya, Leon. So, you want to talk about your research project on cycling to campus.\nMaya: Yes. We've decided to focus on why so few students cycle, even though most of them live less than three miles away.\nTutor: Good, that's a clear question. How are you planning to collect data?\nLeon: We thought about interviews, but they take too long to transcribe. So we're going to use an online questionnaire, and then do a few short follow-up interviews with people who give interesting answers.\nTutor: Sensible. How many responses are you hoping for?\nMaya: At least two hundred. Our first idea was to send it to the whole university, but the student union said they can only share it with first-year students.\nTutor: That's a limitation you'll need to mention in your report. First-year students may behave quite differently from older students.\nLeon: We hadn't thought of that. Maybe we could also put posters in the library to reach other years.\nTutor: Worth trying. What have you found in the literature so far?\nMaya: The biggest barrier in most studies is safety, especially on busy roads. Cost comes surprisingly low, because bikes are cheap second-hand.\nTutor: And weather?\nLeon: It matters, but less than people expect. What surprised us was how important secure bike parking is. People worry about theft more than rain.\nTutor: Interesting. Now, how will you divide the work?\nMaya: I'll design the questionnaire, since I did a statistics module last year. Leon's going to write the literature review.\nLeon: And I'll contact the student union about sharing the link. We'll both do the follow-up interviews.\nTutor: And the final presentation?\nMaya: Leon's better at speaking in public, so he'll give it, but I'll make the slides.\nTutor: Sounds like a good plan. Please send me a draft of the questionnaire by Friday." }, questions: [
        C("What is the main aim of the students' research?", ["to compare cycling in different cities", "to find out why few students cycle to campus", "to measure how far students live from campus"], "B", "We've decided to focus on why so few students cycle."),
        C("Why did the students decide not to rely on interviews alone?", ["Interviews take too long to transcribe.", "Students do not like being interviewed.", "The tutor advised against them."], "A", "Interviews take too long to transcribe."),
        C("What limitation does the tutor point out?", ["Only first-year students will receive it.", "The questionnaire is too long.", "Two hundred responses are not enough."], "A", "The union can only share it with first-year students; the tutor says this is a limitation."),
        C("According to most studies, the biggest barrier to cycling is", ["cost.", "weather.", "safety."], "C", "The biggest barrier in most studies is safety."),
        C("What surprised the students in their reading?", ["the importance of secure bike parking", "the low cost of second-hand bikes", "the effect of rain"], "A", "What surprised us was how important secure bike parking is."),
        match("Who will do each task? Choose A for Maya, B for Leon or C for both students.", ["design the questionnaire", "write the literature review", "contact the student union", "carry out follow-up interviews", "give the final presentation"], ["Maya", "Leon", "both Maya and Leon"], ["A", "B", "B", "C", "B"], "Maya designs the questionnaire; Leon writes the review, contacts the union and presents; both do the interviews. (Maya makes the slides, but Leon presents.)")
      ] }]
    },
    {
      partNumber: 4, title: "Section 4 · Lecture: vertical farming", skill: "LISTENING", instructions: "You will hear part of a lecture. Complete the notes. Write ONE WORD ONLY for each answer.",
      groups: [{ title: "Questions 31–40", listening: { voices: { Lecturer: "female" }, script: "Lecturer: Today I'm going to talk about vertical farming: growing crops in stacked layers, usually indoors, under artificial light.\nThe idea is not new. In the early twentieth century, some architects imagined farms inside skyscrapers, but the technology to make them practical, especially efficient lighting, did not exist until much later. The key development was the LED lamp. LEDs produce much less heat than older lamps, which means plants can be placed very close to the light source.\nMost vertical farms today don't use soil at all. The roots sit in a shallow flow of water containing nutrients, a method known as hydroponics. Because this water is recycled, vertical farms can use up to ninety-five percent less water than traditional fields.\nWhat do they grow? At present, mainly leafy greens such as lettuce and herbs like basil. These crops grow quickly and are light, so they are cheap to move between layers. Crops such as wheat or rice take up too much space and have too low a value to make indoor farming worthwhile.\nThe advantages are clear. Farms can be built in cities, close to customers, which reduces the distance food travels and keeps it fresh. There is no need for pesticides, because insects cannot easily get in. And harvests are the same all year round, whatever the season.\nHowever, there is one major problem: energy. Lighting and climate control are expensive, and if the electricity comes from fossil fuels, the environmental benefits largely disappear. That's why several new farms are being built next to wind or solar power plants.\nFinally, a word about jobs. Vertical farms need fewer workers than traditional farms, but those workers need different skills: in data analysis and engineering rather than driving tractors." }, questions: [
        gap("Vertical farming — lecture notes\nHistory: early ideas were limited because good ___ was not available.\nLED lamps produce little ___, so plants can be close to the light.\nMethod: roots grow in water with nutrients instead of ___ (hydroponics).\nWater: up to 95% less is used because it is ___.\nCrops: mainly leafy greens and herbs such as ___.", [["lighting", "light"], ["heat"], ["soil"], ["recycled"], ["basil"]], "Efficient lighting did not exist; LEDs produce less heat; no soil (hydroponics); water is recycled; herbs like basil.", 1),
        gap("Wheat and rice are unsuitable: they need too much ___ and have low value.\nBenefit: farms can be close to customers, so food stays ___.\nNo ___ are needed because insects cannot easily get in.\nMain problem: the cost of ___ for lighting and climate control.\nWorkers need skills in data analysis and ___.", [["space"], ["fresh"], ["pesticides"], ["energy", "electricity"], ["engineering"]], "Crops take up too much space; food stays fresh; no pesticides; the problem is energy; skills in data analysis and engineering.", 1)
      ] }]
    }
  ]
};
