import { choose, gap, match, mcq, tfng, type ExamDef } from "../types";

const M = (prompt: string, options: [string, string, string, string], correct: "A" | "B" | "C" | "D", explanation: string) => mcq(prompt, options, correct, explanation);

const pencil = `The Humble Pencil

For an object that fits in a shirt pocket, the pencil has had a remarkably eventful history. Its story begins in 1564, when a large deposit of an unusually pure form of graphite was discovered near the village of Borrowdale in the north of England. Local shepherds first used the black material to mark their sheep, but it soon became clear that it was ideal for writing and drawing. Unlike lead, which had been used by the Romans to make faint grey lines, graphite left a dark mark and could be erased.

Early users simply wrapped sticks of graphite in string or sheepskin to keep their fingers clean. By the late sixteenth century, craftsmen had begun to insert the sticks into hollowed-out wooden holders, creating something close to the modern pencil. Because the Borrowdale deposit was the only known source of such pure graphite, it became extremely valuable. The mine was guarded, and at times it was flooded deliberately to prevent theft. Exports were strictly controlled, which gave English pencil makers an advantage for almost two centuries.

The situation changed during a war between Britain and France at the end of the eighteenth century. Cut off from English graphite, the French government asked the engineer Nicolas-Jacques Conté to find an alternative. In 1795 he developed a method of mixing powdered graphite with clay, shaping the mixture into rods and firing them in a kiln. This invention had two important consequences. First, lower-quality graphite could now be used, so pencils could be made almost anywhere. Second, by changing the proportion of clay, manufacturers could control the hardness of the pencil. More clay produced a harder, lighter line; less clay produced a softer, darker one. The grading system still printed on pencils today, from hard 'H' grades to soft 'B' grades, grew out of Conté's process.

Industrial production followed in the nineteenth century. Machines were developed to cut wooden slats, cut grooves into them, and glue two slats together around the graphite core. In the United States, the pencil industry grew rapidly, helped by supplies of red cedar, a soft wood that sharpens easily without splitting. The familiar yellow paint on many American pencils is said to date from the 1890s, when some manufacturers used it to suggest that their graphite came from China, a colour associated with quality and respect at the time.

Although digital devices have replaced the pencil for many tasks, billions are still produced every year. Architects and artists value the way pencil marks can be varied in darkness and smudged for shading. Pencils also work in conditions where pens fail, such as at freezing temperatures or upside down, which is why astronauts and mountaineers often carry them. For children learning to write, the slight resistance of a pencil on paper is thought by some teachers to improve control, although research on this point is limited.`;

const sleep = `Sleep and the Teenage Brain

A. Parents have long complained that teenagers stay up late and are impossible to wake in the morning. For many years this was put down to poor habits or too much screen time. Research over the past three decades, however, suggests that the change has a biological basis. During adolescence, the body releases melatonin, the hormone that makes us feel sleepy, around two hours later than in childhood. As a result, most teenagers do not feel tired until close to midnight.

B. At the same time, the amount of sleep teenagers need does not decrease. Studies suggest that adolescents require between eight and ten hours a night for good health and concentration. When school begins at eight o'clock or earlier, a student who falls asleep at midnight is likely to get only six or seven hours on a school night. Over a week, this adds up to a considerable sleep debt.

C. The effects of this debt are wide-ranging. Tired students find it harder to pay attention in class and to remember what they have learned. Sleep plays a crucial role in consolidating memories: during certain stages of sleep, the brain appears to replay and strengthen information acquired during the day. Lack of sleep has also been linked to changes in mood, reduced motivation, and a higher risk of accidents among young drivers.

D. Some schools have responded by starting the day later. In one well-known experiment, a group of secondary schools delayed their start time by fifty minutes. Over the following two years, attendance improved and students reported feeling less sleepy during lessons. Test results also rose, although researchers cautioned that other changes introduced at the same time may have contributed. Critics point out that later start times can create problems for parents' work schedules and for after-school activities.

E. Screens do make the problem worse. The blue light emitted by phones and tablets delays the release of melatonin still further, and messages or games keep the brain alert. Sleep specialists therefore recommend switching off devices at least an hour before bed. Yet they stress that removing screens alone will not fully solve the problem, because the underlying shift in body clocks remains.

F. Weekend habits matter too. Many teenagers try to catch up by sleeping until midday on Saturdays and Sundays. While this reduces tiredness in the short term, it can push the body clock even later, making Monday mornings harder still. Experts suggest that teenagers keep their wake-up time within about two hours of their weekday routine.`;

const forests = `Can Cities Learn from Forests?

For most of the twentieth century, urban planners treated the city as a machine: a system of separate parts, each designed for a single function. Residential zones were kept apart from industrial ones, water was piped away as quickly as possible, and green spaces were largely decorative. In recent years, a growing number of designers have begun to argue for a different model. Cities, they suggest, should be designed less like machines and more like forests.

The comparison is not merely poetic. A mature forest is extraordinarily efficient at managing resources. Rain is slowed by leaves, absorbed by soil, and released gradually into streams, so that floods are rare even after heavy storms. Waste from one organism becomes food for another, and the canopy shades the ground, keeping temperatures stable. Proponents of 'forest cities' believe that urban areas could achieve similar results by imitating these processes. Permeable pavements, for example, allow rainwater to soak into the ground instead of overwhelming drains, while green roofs insulate buildings and cool the surrounding air.

Critics, however, argue that the analogy can be taken too far. A forest has no need to house millions of people, provide rapid transport, or support a modern economy. Some features that make forests resilient, such as slow growth and constant competition for light, would be undesirable in a city. Moreover, many 'nature-based' projects have been judged mainly by how attractive they look rather than by whether they actually perform. A green roof that is poorly maintained, one engineer observed, may end up as little more than an expensive layer of dry grass.

Supporters accept that measurement has been a weakness, but they point to a growing body of evidence. In one European city, streets lined with trees were found to be up to four degrees cooler on summer afternoons than similar streets without them. Elsewhere, a network of rain gardens reduced the volume of water entering drains during storms by around a third. Such results, they argue, show that the approach offers practical benefits, not just aesthetic ones.

Perhaps the most important lesson from forests concerns diversity. Forests with many species tend to recover more quickly from disease or drought than plantations of a single tree. Similarly, cities that combine many different solutions — parks, wetlands, green roofs and traditional engineering — are likely to cope better with unexpected pressures than those that rely on one system. The goal, most designers now agree, is not to replace concrete with plants, but to make the two work together.`;

export const ieltsReading1: ExamDef = {
  key: "ielts:reading-1", batch: "ielts", slug: "ielts-reading-test-1", title: "IELTS Reading Test 1", type: "IELTS", mode: "PRACTICE", durationSeconds: 60 * 60,
  parts: [
    { partNumber: 1, title: "Passage 1 · The Humble Pencil", skill: "READING", instructions: "Read the passage and answer Questions 1–13. You should spend about 20 minutes on this passage.", groups: [{ title: "The Humble Pencil", passage: pencil, questions: [
      tfng("The graphite found at Borrowdale was first used by shepherds.", "True", "Local shepherds first used the black material to mark their sheep."),
      tfng("Roman writing tools produced darker lines than graphite.", "False", "Lead made faint grey lines; graphite left a dark mark."),
      tfng("The Borrowdale mine was sometimes flooded on purpose.", "True", "At times it was flooded deliberately to prevent theft."),
      tfng("English pencil makers were the first to export pencils to France.", "Not Given", "The passage mentions controlled exports but not who first exported pencils to France."),
      tfng("Conté's method made it possible to use graphite of lower quality.", "True", "Lower-quality graphite could now be used."),
      tfng("Adding more clay produces a darker line.", "False", "More clay produced a harder, lighter line."),
      gap("Early users wrapped graphite sticks in string or ___ to keep their fingers clean.", [["sheepskin"]], "…wrapped sticks of graphite in string or sheepskin.", 1),
      gap("American manufacturers used red ___ because it sharpens easily without splitting.", [["cedar"]], "Supplies of red cedar, a soft wood that sharpens easily without splitting.", 1),
      gap("Yellow paint may have been used to suggest that the graphite came from ___.", [["China"]], "To suggest that their graphite came from China.", 1),
      gap("Pencils are useful for astronauts because they work at freezing temperatures or ___ down.", [["upside"]], "Pencils work … at freezing temperatures or upside down.", 1),
      M("Why did the French government ask Conté to find an alternative?", ["English pencils had become too expensive.", "France could not obtain English graphite during a war.", "French graphite mines had closed.", "Pencil makers wanted harder pencils."], "B", "Cut off from English graphite during a war between Britain and France."),
      M("What is the writer's view of the claim that pencils improve children's writing control?", ["It is proven by research.", "It is widely rejected by teachers.", "It is not strongly supported by research.", "It applies only to younger children."], "C", "Research on this point is limited."),
      M("What is the main purpose of the passage?", ["To compare pencils with digital devices", "To describe how the pencil developed and why it is still used", "To explain how graphite is mined today", "To argue that pencils should replace pens in schools"], "B", "The passage traces the pencil's history and ends with its continuing uses.")
    ] }] },
    { partNumber: 2, title: "Passage 2 · Sleep and the Teenage Brain", skill: "READING", instructions: "Read the passage and answer Questions 14–26. You should spend about 20 minutes on this passage.", groups: [{ title: "Sleep and the Teenage Brain", passage: sleep, questions: [
      match("The passage has six paragraphs, A–F. Choose the correct heading for each paragraph from the list of headings.", ["Paragraph A", "Paragraph B", "Paragraph C", "Paragraph D", "Paragraph E", "Paragraph F"], ["A mismatch between needs and timetables", "A biological explanation for late nights", "The risk of sleeping in", "How lost sleep affects learning and safety", "A factor that makes a natural change worse", "An experiment and its limitations", "Why teenagers need less sleep than adults"], ["B", "A", "D", "F", "E", "C"], "A: melatonin is released later (biological). B: needs vs school start times. C: effects on memory, mood and accidents. D: the later-start experiment and its caveats. E: screens worsen the shift. F: weekend lie-ins push the clock later."),
      choose("Which TWO effects of the later school start are reported in paragraph D?", ["Better attendance", "Fewer car accidents", "Students felt less sleepy", "Parents found it easier to get to work", "More after-school clubs"], ["A", "C"], "Attendance improved and students reported feeling less sleepy. The other options are not reported or are the opposite of what critics say."),
      gap("Summary: In adolescence, the hormone ___ is released about two hours later than in childhood, so many teenagers do not feel sleepy until midnight. They still need eight to ten hours of sleep, which means early school starts create a sleep ___. Sleep helps the brain strengthen ___ acquired during the day. Specialists advise switching off devices an ___ before bed, and suggest that at weekends teenagers keep their ___ time close to their weekday routine.", [["melatonin"], ["debt"], ["information", "memories"], ["hour"], ["wake-up", "wake up", "waking"]], "Melatonin; sleep debt; information/memories consolidated during sleep; at least an hour before bed; wake-up time within two hours.", 1)
    ] }] },
    { partNumber: 3, title: "Passage 3 · Can Cities Learn from Forests?", skill: "READING", instructions: "Read the passage and answer Questions 27–40. You should spend about 20 minutes on this passage.", groups: [{ title: "Can Cities Learn from Forests?", passage: forests, questions: [
      M("According to the first paragraph, twentieth-century planners", ["designed cities around a single function.", "kept different city functions separate.", "used green spaces to manage water.", "modelled cities on natural systems."], "B", "Residential zones were kept apart from industrial ones; each part had a single function."),
      M("In the second paragraph, the writer mentions permeable pavements as an example of", ["a feature that imitates a forest process.", "a failed nature-based project.", "a cheap alternative to green roofs.", "a way to increase city temperatures."], "A", "Cities could achieve similar results by imitating these processes; permeable pavements let rain soak into the ground."),
      M("What does the engineer's comment about green roofs suggest?", ["Green roofs are always too expensive.", "Projects can fail if they are not maintained.", "Grass is better than other plants for roofs.", "Green roofs do not insulate buildings."], "B", "A poorly maintained green roof may end up as little more than dry grass."),
      M("What is the main point of the final paragraph?", ["Cities should replace concrete with plants.", "Single-species plantations are more productive.", "Combining different solutions makes cities more resilient.", "Forests recover slowly from disease."], "C", "Cities that combine many different solutions are likely to cope better; the goal is to make plants and concrete work together."),
      { authoring: { type: "TRUE_FALSE", variant: "YES_NO_NOT_GIVEN", prompt: "The forest comparison has a practical basis and is not only a figure of speech.", correct: "Yes" }, explanation: "The comparison is not merely poetic." },
      { authoring: { type: "TRUE_FALSE", variant: "YES_NO_NOT_GIVEN", prompt: "Critics believe cities should copy every feature of forests.", correct: "No" }, explanation: "Critics argue the analogy can be taken too far; some forest features would be undesirable." },
      { authoring: { type: "TRUE_FALSE", variant: "YES_NO_NOT_GIVEN", prompt: "Many nature-based projects have been evaluated mainly on their appearance.", correct: "Yes" }, explanation: "Many projects have been judged mainly by how attractive they look." },
      { authoring: { type: "TRUE_FALSE", variant: "YES_NO_NOT_GIVEN", prompt: "Tree-lined streets in the European city were cooler at night than in the afternoon.", correct: "Not Given" }, explanation: "Only afternoon temperatures compared with streets without trees are mentioned." },
      { authoring: { type: "TRUE_FALSE", variant: "YES_NO_NOT_GIVEN", prompt: "Most designers now agree that plants and traditional engineering should be combined.", correct: "Yes" }, explanation: "The goal, most designers now agree, is … to make the two work together." },
      match("Complete each sentence with the correct ending.", ["Rain in a mature forest", "Green roofs", "A network of rain gardens", "Forests with many species", "Supporters of forest cities"], ["reduced the water entering drains by about a third.", "is released slowly into streams.", "admit that measuring results has been a weakness.", "recover faster from drought or disease.", "insulate buildings and cool the air.", "need constant competition for light."], ["B", "E", "A", "D", "C"], "Rain is released gradually into streams; green roofs insulate and cool; rain gardens cut storm water by about a third; diverse forests recover more quickly; supporters accept that measurement has been a weakness.")
    ] }] }
  ]
};
