import { choose, gap, match, mcq, tfng, type ExamDef } from "../types";

const M = (prompt: string, options: [string, string, string, string], correct: "A" | "B" | "C" | "D", explanation: string) => mcq(prompt, options, correct, explanation);
const yn = (prompt: string, correct: "Yes" | "No" | "Not Given", explanation: string) => ({ authoring: { type: "TRUE_FALSE" as const, variant: "YES_NO_NOT_GIVEN" as const, prompt, correct }, explanation });

const bicycle = `From Running Machine to Safety Bicycle

The bicycle seems such a simple machine that it is easy to forget how long it took to develop. Its earliest ancestor appeared in 1817, when Karl Drais, a forestry official in the German city of Mannheim, demonstrated what he called a 'running machine'. It had two wheels in a line, a wooden frame and a steerable front wheel, but no pedals: the rider sat on the frame and pushed along the ground with his feet. Some historians have suggested that Drais was looking for an alternative to the horse after a series of failed harvests had made horses expensive to feed, although the evidence for this is indirect.

Drais's invention became a brief fashion among wealthy young men in Europe, but it was soon criticised as dangerous on crowded pavements, and interest faded. The decisive step came in France in the 1860s, when pedals were attached directly to the front wheel. These machines, known as velocipedes, were heavy, and with their wooden wheels and iron tyres they gave such an uncomfortable ride on cobbled streets that English speakers nicknamed them 'boneshakers'.

Because the pedals turned the front wheel directly, the only way to go faster was to make that wheel larger. The result, in the 1870s, was the high-wheeler, later called the penny-farthing after the contrast between a large and a small British coin. Its front wheel could be well over a metre across, and the rider sat almost directly above it. High-wheelers were fast and comparatively light, but mounting them required skill, and a sudden stop could throw the rider forward over the handlebars. Cycling therefore remained largely a sport for athletic young men.

The machine that changed this was the 'safety bicycle'. In 1885 the English inventor John Kemp Starley produced the Rover, which had two wheels of similar size and a chain that transferred power from the pedals to the rear wheel. Gearing allowed a smaller wheel to travel as far with each turn of the pedals as a much larger one, so the rider could sit lower, with both feet able to reach the ground. Three years later, John Boyd Dunlop, a Scottish vet living in Belfast, developed a practical air-filled tyre, originally for his son's tricycle. Combined, the chain drive and the pneumatic tyre produced a machine that was safe, comfortable and recognisably modern.

The social effects were considerable. Mass production in the 1890s made bicycles affordable to working people, who could now travel to jobs further from home. Bicycles also gave many women a new independence of movement and encouraged changes in clothing, as long skirts were replaced by more practical designs. In 1896 the American campaigner Susan B. Anthony remarked that the bicycle had done more to emancipate women than anything else in the world.`;

const forgetting = `Why Do We Forget?

A. In the 1880s, the German psychologist Hermann Ebbinghaus carried out a series of experiments on the only subject he could test at any time of day: himself. He memorised long lists of nonsense syllables, such as 'DAX' or 'BOK', which had no meaning that could help him remember them, and then measured how much he had retained after different periods of time. The result was what is now called the forgetting curve: most of what he had learned was lost within the first day, after which forgetting continued much more slowly.

B. Ebbinghaus also noticed something encouraging. When he relearned a list, it took less time than learning it the first time, even if he believed he had forgotten it completely. Some trace of the original learning remained. Furthermore, when learning was spread over several sessions rather than concentrated into one, the material was retained for much longer. This finding, known as the spacing effect, has been confirmed in hundreds of later studies.

C. Why does forgetting happen at all? One long-standing explanation is interference. New information can make older memories harder to reach, and old memories can interfere with new learning. A person who changes their phone number, for example, may find themselves recalling the old number for months. Forgetting, on this view, is often not a loss of information but a failure to retrieve it.

D. More recent research suggests that forgetting may even be useful. A memory system that kept every detail equally available would be cluttered and slow. By allowing unimportant or out-of-date information to fade, the brain may make it easier to find what we actually need. Some researchers therefore describe forgetting not as a failure but as a form of active maintenance.

E. Whatever its causes, forgetting can be slowed. One of the most effective methods is retrieval practice: actively trying to recall information, for example by testing yourself, rather than simply rereading it. Each successful act of recall appears to strengthen the memory and make it easier to retrieve in future. Students often prefer rereading because it feels easier, but that sense of ease can be misleading.

F. Sleep also plays an important part. During sleep, and particularly during its deeper stages, the brain appears to stabilise memories formed during the day. People who sleep after learning generally remember more than those who stay awake for the same length of time. Staying up all night before an examination may therefore reduce, rather than increase, what a student can recall.`;

const nightTrains = `The Return of the Night Train

For much of the twentieth century, overnight trains were a normal way to cross Europe. Passengers boarded in the evening, slept in a couchette or a private compartment, and woke up in another country. By the early twenty-first century, however, many of these services had disappeared. Low-cost airlines could carry passengers between capital cities in a couple of hours for very low fares, and new high-speed lines made daytime rail journeys faster. Night trains, with their expensive staff, specialised carriages and relatively small number of passengers per train, struggled to compete. Several national rail companies decided they were simply not worth running.

The decline did not go unchallenged. When the German railway ended its own sleeper services in 2016, the Austrian national railway took over a number of the routes under a new brand, arguing that a well-run service could attract enough passengers to survive. Its confidence was soon helped by a change in public attitudes. Growing concern about the climate impact of flying, captured in the Swedish word 'flygskam', or 'flight shame', led some travellers to look for alternatives, and night trains offered a way to cover long distances while saving a night in a hotel.

Since then, new routes have been announced across the continent, and some governments have begun to support them. Supporters argue that night trains deserve public help because they offer social and environmental benefits that ticket prices do not capture. They also point out that, unlike airports, railway stations are usually in city centres, so the total journey time from door to door may be closer to that of a flight than the timetable suggests.

Yet the revival faces practical obstacles that enthusiasm alone cannot overcome. Railways in different countries use different safety systems, electrical supplies and charging arrangements, so a single train crossing several borders must satisfy several sets of rules. Track access charges, which railway operators pay to use the lines, can make long international journeys expensive. Perhaps most seriously, there is a shortage of suitable carriages. Sleeping cars are built in small numbers and take years to order, and many older ones are close to the end of their working lives.

None of this means that the night train is a nostalgic indulgence. It does mean that its future depends less on passengers' goodwill than on decisions about infrastructure and investment. If the night train is to become more than a pleasant experience for a few, governments and operators will need to treat it as part of the transport system, not as a curiosity.`;

export const ieltsReading2: ExamDef = {
  key: "ielts:reading-2", batch: "ielts", slug: "ielts-reading-test-2", title: "IELTS Reading Test 2", type: "IELTS", mode: "PRACTICE", durationSeconds: 60 * 60,
  parts: [
    { partNumber: 1, title: "Passage 1 · From Running Machine to Safety Bicycle", skill: "READING", instructions: "Read the passage and answer Questions 1–13. You should spend about 20 minutes on this passage.", groups: [{ title: "From Running Machine to Safety Bicycle", passage: bicycle, questions: [
      tfng("Drais's running machine could be steered.", "True", "It had … a steerable front wheel."),
      tfng("Riders of the running machine used pedals on the front wheel.", "False", "It had no pedals: the rider pushed along the ground with his feet."),
      tfng("It is certain that Drais built his machine because horses had become expensive.", "False", "Some historians have suggested this, but the evidence is indirect."),
      tfng("Drais sold his running machine in several European countries.", "Not Given", "It became a fashion in Europe, but nothing is said about Drais selling it."),
      tfng("The high-wheeler was named after two British coins.", "True", "Called the penny-farthing after the contrast between a large and a small British coin."),
      tfng("Women were banned from riding high-wheelers.", "Not Given", "The passage says cycling remained largely a sport for athletic young men, not that women were banned."),
      gap("English speakers called the velocipede the '___' because of its uncomfortable ride.", [["boneshaker"]], "English speakers nicknamed them 'boneshakers'.", 1),
      gap("On the Rover, a ___ carried power from the pedals to the rear wheel.", [["chain"]], "A chain that transferred power from the pedals to the rear wheel.", 1),
      gap("Dunlop first made his air-filled tyre for his son's ___.", [["tricycle"]], "Originally for his son's tricycle.", 1),
      gap("In the 1890s, mass production made bicycles affordable, so working people could reach ___ further from home.", [["jobs"]], "Working people … could now travel to jobs further from home.", 1),
      M("Why did early high-wheelers have such a large front wheel?", ["It made mounting the bicycle easier.", "The pedals turned the front wheel directly, so a bigger wheel meant more speed.", "A large wheel made the bicycle heavier and more stable.", "Riders preferred to sit high above the road."], "B", "The only way to go faster was to make that wheel larger."),
      M("What allowed riders of the safety bicycle to sit lower?", ["A larger front wheel", "Wooden wheels", "Gearing through the chain drive", "Air-filled tyres"], "C", "Gearing allowed a smaller wheel to travel as far… so the rider could sit lower."),
      M("What does the final paragraph mainly describe?", ["Technical problems with early bicycles", "The social effects of the bicycle", "The history of bicycle racing", "How bicycles were made in factories"], "B", "The social effects were considerable: work, independence for women, clothing.")
    ] }] },
    { partNumber: 2, title: "Passage 2 · Why Do We Forget?", skill: "READING", instructions: "Read the passage and answer Questions 14–26. You should spend about 20 minutes on this passage.", groups: [{ title: "Why Do We Forget?", passage: forgetting, questions: [
      match("The passage has six paragraphs, A–F. Choose the correct heading for each paragraph from the list of headings.", ["Paragraph A", "Paragraph B", "Paragraph C", "Paragraph D", "Paragraph E", "Paragraph F"], ["Testing yourself as a learning strategy", "When old and new memories compete", "A researcher who studied his own memory", "The role of rest in keeping memories", "Why some memories last a lifetime", "Signs that learning is never entirely lost", "A possible benefit of forgetting"], ["C", "F", "B", "G", "A", "D"], "A: Ebbinghaus experimented on himself. B: relearning is faster and spacing helps. C: interference between old and new memories. D: forgetting may be useful. E: retrieval practice. F: sleep stabilises memories."),
      choose("Which TWO findings did Ebbinghaus report?", ["Relearning a list was faster than learning it the first time.", "Meaningful words were harder to remember than nonsense syllables.", "Learning spread over several sessions was remembered for longer.", "Memories were lost more quickly after the first week.", "Sleep improved his memory of the lists."], ["A", "C"], "He found relearning took less time and that spaced learning was retained longer. Forgetting slowed after the first day; sleep is discussed separately in paragraph F."),
      gap("Summary: Ebbinghaus used nonsense ___ so that meaning could not help him remember. He found that most material was forgotten within the first ___. One explanation of forgetting is ___, in which memories make each other harder to reach. Rather than rereading, learners can use ___ practice, actively trying to recall information. ___ also helps the brain stabilise new memories.", [["syllables"], ["day"], ["interference"], ["retrieval"], ["sleep"]], "Nonsense syllables; lost within the first day; interference; retrieval practice; sleep, particularly its deeper stages.", 1)
    ] }] },
    { partNumber: 3, title: "Passage 3 · The Return of the Night Train", skill: "READING", instructions: "Read the passage and answer Questions 27–40. You should spend about 20 minutes on this passage.", groups: [{ title: "The Return of the Night Train", passage: nightTrains, questions: [
      M("According to the first paragraph, why did many night trains disappear?", ["Passengers complained about the carriages.", "They could not compete with cheap flights and faster daytime trains.", "Governments banned overnight travel.", "Stations closed at night."], "B", "Low-cost airlines and new high-speed lines… night trains struggled to compete."),
      M("What happened when the German railway ended its sleeper services?", ["All night trains in Europe stopped.", "The Austrian national railway took over some routes.", "The routes were replaced by buses.", "Airlines bought the carriages."], "B", "The Austrian national railway took over a number of the routes."),
      M("Why do supporters mention the location of railway stations?", ["To show that stations are cheaper than airports", "To argue that door-to-door journey times may be closer to flying than they appear", "To explain why trains are slower", "To criticise city planning"], "B", "Stations are usually in city centres, so total journey time may be closer to that of a flight."),
      M("Which obstacle does the writer consider perhaps the most serious?", ["Different safety systems", "Track access charges", "A shortage of suitable carriages", "Passenger demand"], "C", "Perhaps most seriously, there is a shortage of suitable carriages."),
      yn("Night trains were too expensive to run mainly because of the price of fuel.", "Not Given", "Staff, specialised carriages and few passengers per train are mentioned, not fuel."),
      yn("Concern about the climate impact of flying helped the revival of night trains.", "Yes", "Growing concern about flying… led some travellers to look for alternatives."),
      yn("Ticket prices fully reflect the environmental benefits of night trains.", "No", "Supporters argue the benefits are ones that ticket prices do not capture."),
      yn("Enthusiasm from passengers is enough to make the revival succeed.", "No", "Obstacles that enthusiasm alone cannot overcome; it depends on infrastructure and investment."),
      yn("The writer believes night trains are a nostalgic indulgence.", "No", "None of this means that the night train is a nostalgic indulgence."),
      match("Complete each sentence with the correct ending.", ["Low-cost airlines", "The word 'flygskam'", "Track access charges", "Sleeping cars", "Governments and operators"], ["are built in small numbers and take years to order.", "need to treat night trains as part of the transport system.", "carried passengers between capitals quickly and cheaply.", "expresses guilt about the climate impact of flying.", "can make long international journeys expensive.", "use the same safety systems in every country."], ["C", "D", "E", "A", "B"], "Airlines offered fast, cheap flights; flygskam means flight shame; access charges raise costs; sleeping cars are built in small numbers; governments and operators must treat night trains as part of the system.")
    ] }] }
  ]
};
