import { randomUUID } from "crypto";
import { and, count, eq, inArray } from "drizzle-orm";
import type { z } from "zod";
import { AdminBlockMutationSchema, AdminContentBatchSchema, AdminCourseSchema, AdminExamPartSchema, AdminExamSchema, AdminLessonBlockSchema, AdminLessonSchema, AdminMcqQuestionSchema, AdminMediaSchema, AdminPassageSchema, AdminPublishExamSchema, AdminPublishLessonSchema, AdminVocabularySchema } from "@english4free/content-schemas";
import { createDatabase } from "@/db/client";
import { contentBatches, courseLevels, courseUnits, courses, examParts, exams, lessonBlocks, lessons, media, passages, questions, vocabulary } from "@/db/schema";
type Input<T extends z.ZodType> = z.infer<T>;
function dbOrThrow() { const db = createDatabase(); if (!db) throw new Error("DATABASE_URL is required for CMS operations"); return db; }
export async function createContentBatch(input: Input<typeof AdminContentBatchSchema>) { const db = dbOrThrow(); const id = randomUUID(); await db.insert(contentBatches).values({ id, ...input, importedAt: new Date(), status: "DRAFT" }); return { id }; }
export async function createCourseWithUnit(input: Input<typeof AdminCourseSchema>) { const db = dbOrThrow(); const courseId = randomUUID(); const levelId = randomUUID(); const unitId = randomUUID(); await db.transaction(async (tx) => { await tx.insert(courses).values({ id: courseId, slug: input.slug, title: input.title, description: input.description, contentBatchId: input.contentBatchId, status: "DRAFT" }); await tx.insert(courseLevels).values({ id: levelId, courseId, cefrLevel: input.cefrLevel, sortOrder: 1, title: input.cefrLevel }); await tx.insert(courseUnits).values({ id: unitId, courseLevelId: levelId, slug: "unit-1", title: input.unitTitle, sortOrder: 1 }); }); return { courseId, levelId, unitId }; }
export async function createLesson(input: Input<typeof AdminLessonSchema>) { const db = dbOrThrow(); const id = randomUUID(); await db.insert(lessons).values({ id, unitId: input.unitId, slug: input.slug, title: input.title, skill: input.skill, estimatedMinutes: input.estimatedMinutes, contentBatchId: input.contentBatchId, status: "DRAFT" }); return { id }; }
export async function createLessonBlock(input: Input<typeof AdminLessonBlockSchema>) { const db = dbOrThrow(); const [lesson] = await db.select({ status: lessons.status }).from(lessons).where(eq(lessons.id, input.lessonId)); if (!lesson) throw new Error("Lesson not found"); if (lesson.status !== "DRAFT") throw new Error("Only draft lessons can be edited"); const id = randomUUID(); await db.insert(lessonBlocks).values({ id, lessonId: input.lessonId, type: input.type, sortOrder: input.sortOrder, schemaVersion: input.schemaVersion, content: input.content }); return { id }; }
export async function mutateLessonBlock(input: Input<typeof AdminBlockMutationSchema>) { const db = dbOrThrow(); if (input.action === "DELETE") { const deleted = await db.delete(lessonBlocks).where(eq(lessonBlocks.id, input.blockId)).returning({ id: lessonBlocks.id }); if (!deleted.length) throw new Error("Lesson block not found"); return { id: input.blockId, deleted: true }; } const [updated] = await db.update(lessonBlocks).set({ sortOrder: input.sortOrder! }).where(eq(lessonBlocks.id, input.blockId)).returning({ id: lessonBlocks.id }); if (!updated) throw new Error("Lesson block not found"); return { id: input.blockId, sortOrder: input.sortOrder }; }
export async function publishLesson(input: Input<typeof AdminPublishLessonSchema>) { const db = dbOrThrow(); const [lesson] = await db.select({ id: lessons.id, contentBatchId: lessons.contentBatchId, courseId: courses.id, courseBatchId: courses.contentBatchId }).from(lessons).innerJoin(courseUnits, eq(lessons.unitId, courseUnits.id)).innerJoin(courseLevels, eq(courseUnits.courseLevelId, courseLevels.id)).innerJoin(courses, eq(courseLevels.courseId, courses.id)).where(eq(lessons.id, input.lessonId)); if (!lesson) throw new Error("Lesson not found"); const batchId = lesson.contentBatchId ?? lesson.courseBatchId; if (!batchId) throw new Error("Lesson needs a content batch before it can be published"); const [batch] = await db.select({ status: contentBatches.status }).from(contentBatches).where(eq(contentBatches.id, batchId)); if (batch?.status !== "PUBLISHED") throw new Error("Publish the linked content batch before publishing this lesson"); const blocks = await db.select().from(lessonBlocks).where(eq(lessonBlocks.lessonId, lesson.id)); if (!blocks.length) throw new Error("Add at least one lesson block before publishing"); for (const block of blocks) { const parsed = AdminLessonBlockSchema.safeParse({ lessonId: lesson.id, type: block.type, sortOrder: block.sortOrder, schemaVersion: block.schemaVersion, content: block.content }); if (!parsed.success) throw new Error(`Invalid ${block.type} block: ${parsed.error.issues[0]?.message}`); if (block.type === "MEDIA") { const mediaId = (block.content as { mediaId?: string }).mediaId; if (mediaId) { const [asset] = await db.select({ status: media.status }).from(media).where(eq(media.id, mediaId)); if (asset?.status !== "READY") throw new Error("Listening media must be ready before publishing"); } } } await db.transaction(async (tx) => { await tx.update(lessons).set({ status: "PUBLISHED", updatedAt: new Date() }).where(eq(lessons.id, lesson.id)); await tx.update(courses).set({ status: "PUBLISHED", updatedAt: new Date() }).where(eq(courses.id, lesson.courseId)); }); return { lessonId: lesson.id, status: "PUBLISHED" as const }; }
export async function createExamWithPart(input: Input<typeof AdminExamSchema>) { const db = dbOrThrow(); const examId = randomUUID(); const partId = randomUUID(); await db.transaction(async (tx) => { await tx.insert(exams).values({ id: examId, slug: input.slug, title: input.title, type: input.type, mode: input.mode, durationSeconds: input.durationSeconds, contentBatchId: input.contentBatchId, status: "DRAFT" }); await tx.insert(examParts).values({ id: partId, examId, partNumber: input.partNumber, title: input.partTitle, sortOrder: input.partNumber, skill: input.skill }); }); return { examId, partId }; }
export async function createExamPart(input: Input<typeof AdminExamPartSchema>) { const db = dbOrThrow(); const id = randomUUID(); const [exam] = await db.select({ id: exams.id, status: exams.status }).from(exams).where(eq(exams.id, input.examId)); if (!exam) throw new Error("Exam not found"); if (exam.status !== "DRAFT") throw new Error("Only draft exams can be edited"); const existing = await db.select({ id: examParts.id }).from(examParts).where(and(eq(examParts.examId, input.examId), eq(examParts.partNumber, input.partNumber)));
  if (existing.length) throw new Error("This exam already has that part number");
  await db.insert(examParts).values({ id, examId: input.examId, partNumber: input.partNumber, title: input.title, sortOrder: input.partNumber, skill: input.skill, instructions: input.instructions || null, durationSeconds: input.durationSeconds ?? null });
  return { id };
}
async function assertDraftExamPart(db: ReturnType<typeof dbOrThrow>, examPartId: string) { const [part] = await db.select({ id: examParts.id, status: exams.status }).from(examParts).innerJoin(exams, eq(examParts.examId, exams.id)).where(eq(examParts.id, examPartId)); if (!part) throw new Error("Exam part not found"); if (part.status !== "DRAFT") throw new Error("Only draft exams can be edited"); return part; }
export async function createPassage(input: Input<typeof AdminPassageSchema>) { const db = dbOrThrow(); await assertDraftExamPart(db, input.examPartId); const id = randomUUID(); await db.insert(passages).values({ id, ...input }); return { id }; }
export async function createMcqQuestion(input: Input<typeof AdminMcqQuestionSchema>) { const db = dbOrThrow(); await assertDraftExamPart(db, input.examPartId); if (input.passageId) { const [passage] = await db.select({ examPartId: passages.examPartId }).from(passages).where(eq(passages.id, input.passageId)); if (!passage || passage.examPartId !== input.examPartId) throw new Error("Passage must belong to the selected exam part"); } const id = randomUUID(); await db.insert(questions).values({ id, examPartId: input.examPartId, passageId: input.passageId, schemaVersion: 1, type: "MCQ", content: { prompt: input.prompt, options: input.options }, answer: { correctOptionId: input.correctOptionId }, explanation: input.explanation, tags: input.tags, status: "DRAFT" }); return { id }; }
export async function publishExam(input: Input<typeof AdminPublishExamSchema>) { const db = dbOrThrow(); const [exam] = await db.select().from(exams).where(eq(exams.id, input.examId)); if (!exam) throw new Error("Exam not found"); if (!exam.contentBatchId) throw new Error("Exam needs a content batch"); const [batch] = await db.select({ status: contentBatches.status }).from(contentBatches).where(eq(contentBatches.id, exam.contentBatchId)); if (batch?.status !== "PUBLISHED") throw new Error("Publish the linked content batch first"); const parts = await db.select({ id: examParts.id }).from(examParts).where(eq(examParts.examId, exam.id)); if (!parts.length) throw new Error("Exam needs at least one part"); for (const part of parts) { const [summary] = await db.select({ count: count() }).from(questions).where(eq(questions.examPartId, part.id)); if (!summary?.count) throw new Error("Every exam part needs at least one question"); } const partIds = parts.map((part) => part.id); await db.transaction(async (tx) => { await tx.update(questions).set({ status: "PUBLISHED", updatedAt: new Date() }).where(inArray(questions.examPartId, partIds)); await tx.update(exams).set({ status: "PUBLISHED", updatedAt: new Date() }).where(eq(exams.id, exam.id)); }); return { examId: exam.id, status: "PUBLISHED" as const }; }
export async function createVocabulary(input: Input<typeof AdminVocabularySchema>) { const db = dbOrThrow(); const id = randomUUID(); await db.insert(vocabulary).values({ id, ...input, status: "DRAFT" }); return { id }; }
export async function registerMedia(input: Input<typeof AdminMediaSchema>, owner: { userId: string | null; guestId: string | null }) { const db = dbOrThrow(); const id = randomUUID(); await db.insert(media).values({ id, ownerUserId: owner.userId, ownerGuestId: owner.guestId, ...input, status: "PENDING" }); return { id, uploadRequired: true }; }
