/** B1 example sentences (English 4 Free original). */
export const examplesB1: Record<string, string> = {
  "care|verb": "I don't care what other people think about my clothes.",
  "support|verb": "Most parents support the plan to build a new school.",
  "service|noun": "The service in this restaurant is fast and friendly.",
  "season|noun": "The rainy season in the south starts in May.",
  "president|noun": "The president gave a speech on television.",
  "series|noun": "The museum is holding a series of talks about local history.",
  "form|verb": "The students formed a group to clean the beach.",
  "development|noun": "The development of the new airport will take five years.",
  "near|adjective": "The nearest hospital is ten minutes away.",
  "current|adjective": "What is your current address?",
  "process|noun": "Applying for a visa can be a long process.",
  "main|adjective": "The main entrance is on Le Loi Street.",
  "board|verb": "Passengers can board the plane at gate 12.",
  "fight|verb": "Firefighters fight dangerous fires to protect our homes.",
  "department|noun": "She works in the marketing department.",
  "sex|noun": "Please write your name, age and sex on the form.",
  "total|adjective": "The total cost of the trip was two million dong.",
  "record|noun": "She broke the national record for the 100 metres.",
  "security|noun": "Security at the airport is very strict.",
  "industry|noun": "The tourism industry creates many jobs in Hoi An.",
  "county|noun": "They live in a quiet village in the county of Kent.",
  "present|adjective": "All the members were present at the meeting.",
  "policy|noun": "The company has a new policy on working from home.",
  "interest|verb": "History has always interested me.",
  "press|noun": "The minister refused to speak to the press.",
  "relationship|noun": "She has a good relationship with her neighbours.",
  "round|adjective": "We sat at a round table in the corner.",
  "management|noun": "Good management is important for a small business.",
  "various|adjective": "The shop sells various kinds of tea.",
  "vote|verb": "Citizens over eighteen can vote in the election.",
  "property|noun": "Please don't touch other people's property.",
  "serious|adjective": "Pollution is a serious problem in big cities.",
  "economic|adjective": "The country has had strong economic growth.",
  "complete|verb": "Please complete the form in black ink.",
  "entire|adjective": "It rained for the entire weekend.",
  "sign|verb": "Please sign your name at the bottom of the page.",
  "race|noun": "He came second in the race.",
  "legal|adjective": "Is it legal to ride a bicycle on the pavement?",
  "election|noun": "The election will take place in May.",
  "loss|noun": "The loss of his job was a shock.",
  "career|noun": "She started her career as a journalist.",
  "huge|adjective": "They live in a huge house by the lake.",
  "army|noun": "My grandfather served in the army for ten years.",
  "percent|noun": "About sixty percent of the students live on campus.",
  "standard|noun": "The hotel has a high standard of service.",
  "respect|noun": "We should treat older people with respect.",
  "pain|noun": "I have a pain in my left knee.",
  "network|noun": "The city has a good network of bus routes.",
  "potential|noun": "The coach says the young player has great potential.",
  "sort|noun": "What sort of music do you like?",
  "region|noun": "The Mekong Delta is a rich farming region.",
  "content|noun": "The content of the course is very practical.",
  "welcome|adjective": "A cup of hot tea is always welcome on a cold day.",
  "fair|noun": "We visited a book fair at the weekend.",
  "immediately|adverb": "Please call me immediately if there is a problem.",
  "search|verb": "The police searched the building for hours.",
  "global|adjective": "Climate change is a global problem.",
  "stupid|adjective": "Forgetting my passport was a stupid mistake.",
  "majority|noun": "The majority of students passed the exam.",
  "insurance|noun": "Travel insurance is a good idea for long trips.",
  "hurt|adjective": "Luckily, nobody was hurt in the accident.",
  "battle|noun": "The battle lasted for three days.",
  "defense|noun": "The castle walls were built for defense.",
  "civil|adjective": "The couple had a civil wedding at the town hall.",
  "cancer|noun": "Smoking increases the risk of cancer.",
  "administration|noun": "The school administration sent a letter to all parents.",
  "organization|noun": "She works for an international health organization.",
  "operation|noun": "My uncle needs an operation on his knee.",
  "awesome|adjective": "The view from the top was awesome!",
  "marriage|noun": "Their marriage has lasted forty years.",
  "analysis|noun": "The report includes a detailed analysis of the survey results.",
  "professor|noun": "Our professor gave an interesting lecture on economics.",
  "notice|verb": "Did you notice the new sign at the entrance?",
  "fish|verb": "My father likes to fish in the river on Sundays.",
  "disease|noun": "Clean water helps to prevent disease.",
  "reality|noun": "Living abroad was different from the reality she expected.",
  "plant|verb": "We planted three trees in the school garden.",
  "male|adjective": "Male lions have a large mane.",
  "theory|noun": "The book explains the theory of evolution in simple words.",
  "shop|verb": "I usually shop online for books.",
  "responsible|adjective": "Who is responsible for locking the office at night?",
  "otherwise|adverb": "Hurry up, otherwise we'll miss the train.",
  "holy|adjective": "The temple is a holy place for local people.",
  "eventually|adverb": "After many failures, she eventually passed her driving test.",
  "comment|noun": "Thank you for your helpful comments on my essay.",
  "block|verb": "A fallen tree blocked the road.",
  "award|verb": "She was awarded a prize for her photography.",
  "politics|noun": "He isn't interested in politics.",
  "foot|noun": "I hurt my foot while playing football.",
  "economy|noun": "Tourism is important for the local economy.",
  "murder|verb": "In the novel, the detective finds out who murdered the old man.",
  "location|noun": "The hotel is in a perfect location near the beach.",
  "interview|verb": "The company interviewed six candidates for the job.",
  "heat|verb": "Heat the milk slowly, but don't let it boil.",
  "complex|adjective": "The instructions are too complex for beginners.",
  "application|noun": "I sent my job application by email.",
  "northern|adjective": "Sa Pa is in northern Vietnam.",
  "distance|noun": "The distance from Hanoi to Hue is about 650 kilometres.",
  "channel|noun": "Which channel is the football match on?",
  "southern|adjective": "The southern coast is warm all year.",
  "engine|noun": "The car's engine makes a strange noise.",
  "demand|noun": "There is a high demand for English teachers.",
  "score|noun": "What was the final score of the match?",
  "hearing|noun": "My grandmother's hearing is not very good.",
  "weird|adjective": "I heard a weird noise outside last night.",
  "soul|noun": "Many people believe that the soul lives on after death.",
  "foundation|noun": "Workers are laying the foundation for the new building.",
  "basis|noun": "Trust is the basis of a good friendship.",
  "authority|noun": "The police have the authority to stop any vehicle.",
  "option|noun": "We have two options: take the bus or walk.",
  "obviously|adverb": "He was obviously tired after the long flight.",
  "artist|noun": "The artist painted the view from the bridge.",
  "spirit|noun": "The team played with great spirit.",
  "van|noun": "The delivery van arrived at nine o'clock.",
  "require|verb": "This job requires good computer skills.",
  "proud|adjective": "My parents are proud of my exam results.",
  "progress|noun": "You are making good progress with your English.",
  "function|noun": "What is the function of this button?",
  "eastern|adjective": "The sun rises in the eastern sky.",
  "rare|adjective": "This bird is very rare in Europe.",
  "prove|verb": "Can you prove that you were at home?",
  "length|noun": "The length of the bridge is two kilometres.",
  "journal|noun": "She writes in her journal every night.",
  "concept|noun": "The concept of time is difficult to explain to children.",
  "volume|noun": "Could you turn down the volume, please?",
  "vehicle|noun": "Only emergency vehicles can enter this street.",
  "surprise|verb": "The news surprised everyone in the office.",
  "responsibility|noun": "Looking after the garden is my responsibility.",
  "investigation|noun": "The police have started an investigation into the fire.",
  "fix|verb": "Can you fix my bicycle?",
  "cultural|adjective": "Hue has a rich cultural heritage.",
  "criminal|noun": "The police arrested the criminal at the airport.",
  "religion|noun": "People of every religion are welcome here.",
  "iron|noun": "The old bridge is made of iron.",
  "injury|noun": "He missed the match because of a knee injury.",
  "edge|noun": "Don't stand too close to the edge of the cliff.",
  "victory|noun": "The team celebrated their victory in the final.",
  "stress|noun": "Exercise helps to reduce stress.",
  "solid|adjective": "Water becomes solid when it freezes.",
  "reduce|verb": "We must reduce the amount of plastic we use."
};
