/** B2 example sentences (English 4 Free original). */
export const examplesB2: Record<string, string> = {
  "god|noun": "In Greek myths, Poseidon is the god of the sea.",
  "so-called|adjective": "The so-called shortcut added an hour to our journey.",
  "far|adjective": "They moved to a village in the far north of the country.",
  "cause|noun": "Police are still investigating the cause of the fire.",
  "saw|verb": "He sawed the old branch into small pieces for the fire.",
  "data|noun": "The app collects data about how people travel to work.",
  "community|noun": "The library is at the heart of the local community.",
  "media|noun": "The story was widely reported in the media.",
  "fire|verb": "The company fired him for repeatedly missing work.",
  "energy|noun": "Solar panels provide most of the school's energy.",
  "project|noun": "Our class is working on a project about recycling.",
  "test|verb": "Scientists tested the new vaccine on thousands of volunteers.",
  "version|noun": "The latest version of the app is much faster.",
  "minister|noun": "The education minister announced changes to the exam system.",
  "western|adjective": "The storm will reach the western coast tomorrow.",
  "conference|noun": "She presented her research at an international conference.",
  "individual|noun": "Every individual has the right to a fair trial.",
  "focus|noun": "The main focus of the meeting was the budget.",
  "fear|verb": "Many people fear losing their jobs to automation.",
  "contract|noun": "Please read the contract carefully before you sign it.",
  "stock|noun": "He invested his savings in technology stocks.",
  "master|noun": "The dog waited patiently for its master to come home.",
  "approach|verb": "As we approached the station, the train began to leave.",
  "lack|verb": "The team lacks experience, but they work very hard.",
  "doubt|verb": "I doubt that the shop will still be open at this hour.",
  "primary|adjective": "The primary reason for the delay was bad weather.",
  "mass|noun": "The mass of an object does not change on the Moon.",
  "environment|noun": "Plastic waste is a serious threat to the environment.",
  "correct|verb": "The teacher corrected the mistakes in my essay.",
  "influence|verb": "Advertising can strongly influence what children want to buy.",
  "tough|adjective": "It was a tough decision to leave my hometown.",
  "stick|noun": "The old man walked slowly with a wooden stick.",
  "roll|verb": "The ball rolled down the hill and into the river.",
  "reference|noun": "The book has a list of references at the end.",
  "parliament|noun": "The new law was approved by parliament last week.",
  "core|noun": "Remove the core before you slice the apple.",
  "classic|noun": "Pride and Prejudice is a classic of English literature.",
  "profit|noun": "The café made a small profit in its first year.",
  "crew|noun": "The film crew worked through the night.",
  "domestic|adjective": "Domestic flights leave from Terminal 1.",
  "loan|noun": "They took out a loan to open a small bakery.",
  "download|noun": "The software is available as a free download.",
  "route|noun": "The bus takes a different route on Sundays.",
  "factor|noun": "Price is an important factor when choosing a phone.",
  "fox|noun": "A fox was seen near the chicken farm last night.",
  "concern|verb": "The rising number of accidents concerns local residents.",
  "candidate|noun": "Three candidates are standing for mayor this year.",
  "urban|adjective": "Urban areas often suffer from air pollution.",
  "finance|noun": "She studied finance and now works at a bank.",
  "revenue|noun": "Tourism brings in most of the island's revenue.",
  "aircraft|noun": "The airline has ordered twenty new aircraft.",
  "struggle|verb": "Many families struggle to pay their rent.",
  "solo|adjective": "She made her first solo flight at the age of nineteen.",
  "draft|noun": "Please send me the first draft of your report by Friday.",
  "assembly|noun": "The school holds an assembly every Monday morning.",
  "territory|noun": "Wolves defend their territory from other packs.",
  "rural|adjective": "Many young people leave rural areas to work in cities.",
  "resolution|noun": "The council passed a resolution to ban plastic bags.",
  "motion|noun": "The gentle motion of the boat made me sleepy.",
  "senator|noun": "The senator voted against the new tax.",
  "plot|noun": "The plot of the film was hard to follow.",
  "load|verb": "Workers loaded the boxes onto the truck.",
  "navy|noun": "His grandfather was an officer in the navy.",
  "index|noun": "Look up the topic in the index at the back of the book.",
  "object|verb": "Local residents objected to the new parking fees.",
  "counter|noun": "Please pay at the counter near the exit.",
  "somewhat|adverb": "The results were somewhat disappointing.",
  "legislation|noun": "New legislation will protect workers' rights.",
  "interior|noun": "The interior of the old house has been completely modernised.",
  "deputy|noun": "The deputy manager will lead the meeting today.",
  "carbon|noun": "Diamonds are made of pure carbon.",
  "ban|noun": "There is a ban on smoking in all public buildings.",
  "worldwide|adjective": "The film was a worldwide success.",
  "secondary|adjective": "Price was a secondary concern; safety came first.",
  "retirement|noun": "My father plans to travel after his retirement.",
  "reform|noun": "The government is planning a reform of the tax system.",
  "portion|noun": "The portions in this restaurant are very generous.",
  "witness|noun": "A witness saw the car drive away.",
  "principal|noun": "The principal gave a speech at the graduation ceremony.",
  "decade|noun": "The city has changed a lot over the past decade.",
  "quote|noun": "The article begins with a quote from the mayor.",
  "defeat|noun": "The team suffered a heavy defeat in the final.",
  "commander|noun": "The commander ordered his soldiers to stay calm.",
  "shower|verb": "I usually shower after my morning run.",
  "gang|noun": "The police arrested members of a car theft gang.",
  "jury|noun": "The jury found the man not guilty.",
  "contemporary|adjective": "The gallery shows contemporary art from Southeast Asia.",
  "cabinet|noun": "Keep the medicine in the cabinet above the sink.",
  "province|noun": "Quang Nam province is famous for its old town.",
  "harm|noun": "A little sugar will do you no harm.",
  "clothing|noun": "Bring warm clothing for the mountain trip.",
  "shock|verb": "The news of the accident shocked the whole village.",
  "sensitive|adjective": "My teeth are sensitive to cold drinks.",
  "protest|verb": "Students protested against the rise in tuition fees.",
  "acid|noun": "Lemon juice contains a natural acid.",
  "procedure|noun": "Follow the safety procedure if the alarm rings.",
  "guarantee|verb": "The bank guaranteed the loan for the new factory.",
  "welfare|noun": "The charity works for the welfare of street children.",
  "output|noun": "The factory increased its output by twenty percent.",
  "label|noun": "Always read the label before you take any medicine.",
  "racist|noun": "The footballer was banned after fans called him a racist.",
  "odd|adjective": "It's odd that she hasn't replied to my message.",
  "priority|noun": "Safety is our top priority.",
  "institution|noun": "The university is one of the oldest institutions in the country.",
  "evolution|noun": "Darwin developed the theory of evolution.",
  "deck|noun": "He shuffled the deck and gave everyone five cards.",
  "elite|noun": "Only the elite could afford to study abroad in those days.",
  "alliance|noun": "The two parties formed an alliance before the election.",
  "translation|noun": "I read the novel in an English translation.",
  "mortgage|noun": "They needed a mortgage to buy their first home.",
  "idiot|noun": "I felt like an idiot when I locked my keys in the car.",
  "broadcast|verb": "The final will be broadcast live on national television.",
  "mill|noun": "The old mill by the river used to grind flour.",
  "enterprise|noun": "The state enterprise employs over five thousand workers.",
  "reverse|verb": "In this exercise, reverse the order of the words.",
  "programming|noun": "She learned programming at the age of twelve.",
  "hook|noun": "Hang your coat on the hook behind the door.",
  "fraud|noun": "The manager was arrested for fraud.",
  "commerce|noun": "Online commerce has grown rapidly in recent years.",
  "salary|noun": "Her salary increased after the promotion.",
  "heritage|noun": "Hoi An is protected as part of the country's heritage.",
  "headquarters|noun": "The company's headquarters are in Singapore.",
  "divorce|noun": "Their divorce was finalised last year.",
  "consent|noun": "You need your parents' consent to join the trip.",
  "wolf|noun": "A wolf was howling in the distance.",
  "lyrics|noun": "I love the melody, but I can't remember the lyrics.",
  "ambassador|noun": "The ambassador met the president to discuss trade.",
  "tail|noun": "The dog wagged its tail happily.",
  "rally|noun": "Thousands of people attended the climate rally.",
  "commonwealth|noun": "Canada and Australia are members of the Commonwealth.",
  "participation|noun": "Student participation in class discussions has improved.",
  "genius|noun": "Mozart was a musical genius.",
  "trailer|noun": "The truck was pulling a trailer full of hay.",
  "cure|verb": "The doctor said the medicine would cure the infection.",
  "component|noun": "The factory makes components for electric cars.",
  "treaty|noun": "The two countries signed a peace treaty.",
  "rocket|noun": "The rocket was launched into space this morning.",
  "psychology|noun": "She is studying child psychology at university.",
  "praise|verb": "The teacher praised the students for their hard work.",
  "mask|noun": "Doctors wear a mask during operations."
};
