/** A1 example sentences (English 4 Free original). */
export const examplesA1: Record<string, string> = {
  "time|noun": "I don't have much time before the bus leaves.",
  "get|verb": "Did you get my message this morning?",
  "people|noun": "Many people visit the old town at the weekend.",
  "new|adjective": "My sister has a new phone.",
  "now|adverb": "Let's go now, or we will be late.",
  "only|adjective": "She is the only student in the room.",
  "good|adjective": "This is a good book for beginners.",
  "first|adjective": "January is the first month of the year.",
  "see|verb": "I can see the sea from my window.",
  "know|verb": "Do you know his phone number?",
  "think|verb": "I think it will rain later.",
  "want|verb": "I want a glass of water, please.",
  "back|noun": "My back hurts after a long day at the computer.",
  "well|adjective": "I don't feel well today, so I will stay at home.",
  "go|verb": "We go to the market every Sunday.",
  "way|noun": "Is this the right way to the station?",
  "really|adverb": "The film was really good.",
  "year|noun": "My brother is ten years old.",
  "work|noun": "My mother goes to work at seven o'clock.",
  "right|adjective": "Yes, that is the right answer.",
  "day|noun": "It is a sunny day today.",
  "before|adverb": "I have seen this film before.",
  "never|adverb": "He never drinks coffee in the evening.",
  "world|noun": "She wants to travel around the world.",
  "say|verb": "What did the teacher say?",
  "great|adjective": "The concert was great!",
  "man|noun": "The man at the door is my uncle.",
  "love|noun": "Her love of music started when she was a child.",
  "use|verb": "Can I use your pen for a minute?",
  "long|adjective": "The river is very long.",
  "home|noun": "I usually get home at six o'clock.",
  "same|adjective": "We live on the same street.",
  "come|verb": "Can you come to my party on Saturday?",
  "find|verb": "I can't find my keys.",
  "better|adjective": "This coffee is better than the coffee at work.",
  "always|adverb": "She always walks to school.",
  "old|adjective": "My grandfather is old, but he is very active.",
  "help|verb": "Can you help me with my homework?",
  "own|adjective": "Each student has their own desk.",
  "thing|noun": "What is that thing on the table?",
  "game|noun": "Chess is a game for two players.",
  "school|noun": "My school is near the park.",
  "place|noun": "This café is a nice place to read.",
  "house|noun": "Their house has a small garden.",
  "again|adverb": "Can you say that again, please?",
  "show|verb": "Can you show me the way to the library?",
  "sure|adjective": "Are you sure the shop is open?",
  "put|verb": "Please put your bag under the chair.",
  "keep|verb": "You can keep this book. It's a gift.",
  "family|noun": "There are four people in my family.",
  "money|noun": "I don't have enough money for a taxi.",
  "second|adjective": "Our classroom is on the second floor.",
  "free|adjective": "Are you free on Friday evening?",
  "number|noun": "What is your phone number?",
  "left|adjective": "He writes with his left hand.",
  "play|noun": "We watched a play at the city theatre.",
  "night|noun": "It was cold last night.",
  "name|noun": "What is the name of your dog?",
  "city|noun": "Hanoi is a big city.",
  "real|adjective": "Is that a real flower or a plastic one?",
  "different|adjective": "My brother and I have different hobbies.",
  "top|noun": "We walked to the top of the hill.",
  "group|noun": "The students work in groups of four.",
  "start|noun": "I missed the start of the film.",
  "today|adverb": "What are you doing today?",
  "person|noun": "She is a very kind person.",
  "already|adverb": "I have already finished my lunch.",
  "read|verb": "I read the news every morning.",
  "point|noun": "Our team scored ten points in the game.",
  "tell|verb": "Please tell me your name.",
  "once|adverb": "I go swimming once a week.",
  "mean|verb": "What does this word mean?",
  "hard|adjective": "This exercise is hard for me.",
  "bad|adjective": "The weather is bad today.",
  "water|noun": "Drink more water when it is hot.",
  "stop|noun": "Wait for me at the bus stop.",
  "music|noun": "I listen to music on the train.",
  "small|adjective": "They live in a small flat.",
  "head|noun": "He put his hat on his head.",
  "believe|verb": "I believe you. You are always honest.",
  "job|noun": "My father has a job at the hospital.",
  "run|noun": "I go for a run every morning.",
  "party|noun": "We are having a birthday party on Sunday.",
  "order|noun": "Your order will arrive on Friday.",
  "line|noun": "Please wait in line for the tickets.",
  "later|adverb": "I'm busy now. I'll call you later.",
  "thank|verb": "I want to thank you for your help.",
  "open|adjective": "Is the bank open on Saturdays?",
  "war|noun": "My grandfather told me stories about the war.",
  "together|adverb": "We often cook dinner together.",
  "black|adjective": "She has a black cat.",
  "story|noun": "My mother tells me a story every night.",
  "face|noun": "Wash your face before breakfast.",
  "car|noun": "My uncle drives an old car.",
  "news|noun": "Did you hear the news about the storm?",
  "important|adjective": "Sleep is important for your health.",
  "hope|noun": "She never loses hope.",
  "health|noun": "Fruit and vegetables are good for your health.",
  "course|noun": "I am taking an English course this summer.",
  "information|noun": "You can find more information on our website.",
  "early|adverb": "I get up early on weekdays.",
  "book|noun": "This book has a lot of pictures.",
  "talk|verb": "We talk on the phone every evening.",
  "social|adjective": "Humans are social animals.",
  "often|adverb": "We often eat noodles for breakfast.",
  "mind|noun": "Music helps to calm my mind.",
  "hand|noun": "Raise your hand if you have a question.",
  "half|noun": "I ate half of the cake.",
  "problem|noun": "There is a problem with my computer.",
  "pay|noun": "The pay is good, but the hours are long.",
  "office|noun": "Her office is on the fifth floor.",
  "food|noun": "Vietnamese food is famous around the world.",
  "body|noun": "Exercise is good for your body.",
  "become|verb": "She wants to become a doctor.",
  "wrong|adjective": "Sorry, I think you have the wrong number.",
  "room|noun": "My room is small but bright.",
  "large|adjective": "They live in a large apartment near the river.",
  "history|noun": "I love learning about the history of my city.",
  "almost|adverb": "It's almost ten o'clock.",
  "remember|verb": "Do you remember my name?",
  "pretty|adjective": "What a pretty dress!",
  "matter|noun": "This is a private matter.",
  "girl|noun": "The girl in the red coat is my cousin.",
  "nice|adjective": "Have a nice day!",
  "friend|noun": "Nam is my best friend.",
  "close|adjective": "The hotel is close to the beach.",
  "class|noun": "There are thirty students in my class.",
  "woman|noun": "The woman at the desk can help you.",
  "wait|verb": "Please wait here for a moment.",
  "question|noun": "Can I ask a question?",
  "happy|adjective": "The children are happy because it's the holidays.",
  "watch|noun": "My watch is five minutes fast.",
  "special|adjective": "Today is a special day for our family.",
  "late|adjective": "Sorry I'm late. The traffic was terrible.",
  "ask|verb": "Ask the teacher if you don't understand.",
  "short|adjective": "It's a short walk to the station.",
  "morning|noun": "I drink tea every morning.",
  "light|adjective": "The kitchen is light because it has big windows.",
  "future|noun": "What do you want to do in the future?",
  "turn|noun": "It's your turn to choose the music."
};
