/** C1 and C2 example sentences (English 4 Free original). */
export const examplesC: Record<string, string> = {
  "coverage|noun": "Mobile coverage is poor in the mountains.",
  "wing|noun": "The bird had injured one of its wings.",
  "battery|noun": "My phone battery lasts about two days.",
  "legacy|noun": "The school is the founder's greatest legacy.",
  "mechanism|noun": "The clock's mechanism is over a hundred years old.",
  "amateur|noun": "Although he is an amateur, his photographs have won several awards.",
  "scenario|noun": "In the worst-case scenario, the project will be delayed by a year.",
  "trauma|noun": "The patient was treated for head trauma after the crash.",
  "humble|verb": "The champion was humbled by a young, unknown opponent.",
  "testament|noun": "According to his testament, the house was left to his niece.",
  "sketch|noun": "The architect showed us a rough sketch of the new library.",
  "verdict|noun": "The jury took two days to reach a verdict.",
  "peninsula|noun": "The hotel stands at the tip of a narrow peninsula.",
  "harvest|verb": "Farmers harvest the rice at the end of the rainy season.",
  "ego|noun": "Winning the award did wonders for his ego.",
  "consultation|noun": "Decisions were made without proper consultation with local residents.",
  "fossil|noun": "The children found a fossil of an ancient shell on the beach.",
  "prophet|noun": "In the old story, a prophet warned the king about the coming flood.",
  "gig|noun": "The band played a gig at a small club downtown.",
  "clan|noun": "In the Scottish Highlands, each clan had its own land.",
  "acre|noun": "The farm covers about fifty acres.",
  "exotic|adjective": "The market sells exotic fruits from all over Asia.",
  "tomb|noun": "Visitors can see the emperor's tomb outside Hue.",
  "niche|noun": "The small company found a niche making eco-friendly packaging.",
  "goose|noun": "A goose chased the children across the farmyard.",
  "premise|noun": "The whole argument rests on a false premise.",
  "injustice|noun": "She spent her career fighting injustice.",
  "carpenter|noun": "The carpenter made us a beautiful wooden table.",
  "traumatic|adjective": "Losing his home in the flood was a traumatic experience.",
  "naive|adjective": "It was naive of me to expect a quick answer from the bank.",
  "calf|noun": "The calf stayed close to its mother in the field.",
  "psychiatrist|noun": "He was referred to a psychiatrist for his anxiety.",
  "genome|noun": "Scientists have mapped the entire genome of the rice plant.",
  "purity|noun": "The purity of the water is tested every day.",
  "staple|noun": "The papers were held together with a staple.",
  "preacher|noun": "The preacher spoke to a crowd outside the church.",
  "protagonist|noun": "The protagonist of the novel is a young fisherman.",
  "refresh|verb": "Refresh the page to see the latest results.",
  "hypocrisy|noun": "Voters were angry at the hypocrisy of politicians who flew to a climate summit in private jets.",
  "anthropology|noun": "She studied anthropology and spent a year living with a mountain community.",
  "mythology|noun": "The dragon plays an important role in Vietnamese mythology.",
  "sarcasm|noun": "\"Great, another meeting,\" he said with obvious sarcasm.",
  "tailor|noun": "The tailor made him a suit in three days.",
  "pigeon|noun": "Pigeons gathered in the square, waiting for crumbs.",
  "quarry|noun": "The stone for the temple came from a nearby quarry.",
  "calorie|noun": "A can of soft drink contains about 140 calories.",
  "resilience|noun": "The resilience of the local economy surprised the experts.",
  "orchard|noun": "Behind the house there is an orchard of mango trees.",
  "aquarium|noun": "The children spent the afternoon at the city aquarium.",
  "screenplay|noun": "She wrote the screenplay for the award-winning film.",
  "intuition|noun": "My intuition told me that something was wrong.",
  "sentimental|adjective": "The watch has little value, but it's of great sentimental value to me.",
  "heroine|noun": "The heroine of the story rescues her village from the flood.",
  "conform|verb": "New buildings must conform to the safety regulations.",
  "turmoil|noun": "The country was in political turmoil after the election.",
  "parasite|noun": "The fish was infected with a parasite.",
  "boast|noun": "His boast that he could finish in an hour turned out to be true.",
  "chilly|adjective": "It gets chilly in Da Lat in the evening.",
  "allegation|noun": "The company denied all allegations of fraud.",
  "remorse|noun": "The driver showed no remorse for the accident.",
  "intellect|noun": "She was admired for her sharp intellect.",
  "blockbuster|noun": "The summer blockbuster broke box-office records.",
  "elusive|adjective": "The exact meaning of the poem remains elusive.",
  "suffice|verb": "A short email will suffice; there's no need for a formal letter.",
  "subordinate|noun": "A good manager listens to her subordinates.",
  "peacock|noun": "A peacock spread its colourful tail in the garden.",
  "psyche|noun": "The novel explores the psyche of a lonely old man.",
  "embark|verb": "Passengers embarked at the port of Hai Phong.",
  "panorama|noun": "From the tower you get a panorama of the whole city.",
  "synopsis|noun": "Read the synopsis before you decide to watch the film.",
  "otter|noun": "An otter was swimming near the riverbank.",
  "discard|verb": "Discard any food that has passed its expiry date.",
  "radiator|noun": "We hung our wet socks on the radiator.",
  "silhouette|noun": "We could see the silhouette of the mountains against the sunset.",
  "reassure|verb": "The doctor reassured her that the operation was routine.",
  "adversary|noun": "He shook hands with his old political adversary.",
  "tinker|verb": "My father loves tinkering with old radios.",
  "pendulum|noun": "The pendulum of the clock swung slowly from side to side.",
  "flatter|verb": "He flattered her by praising her cooking.",
  "concerto|noun": "The orchestra played a piano concerto by Mozart.",
  "hedgehog|noun": "A hedgehog rolled into a ball when the dog came near.",
  "firewall|noun": "The company's firewall blocks suspicious websites.",
  "itinerary|noun": "Our itinerary includes three days in Hoi An.",
  "resonate|verb": "The singer's voice resonated through the old church.",
  "rudimentary|adjective": "He has only a rudimentary knowledge of French.",
  "grapefruit|noun": "She has half a grapefruit for breakfast every day.",
  "collaborator|noun": "The two scientists were close collaborators for many years.",
  "revere|verb": "The old teacher is revered by everyone in the village.",
  "magnetism|noun": "Magnetism makes a compass needle point north.",
  "manicure|noun": "She had a manicure before the wedding.",
  "talkative|adjective": "The taxi driver was very talkative and told us about his family.",
  "crumb|noun": "There were crumbs all over the table after breakfast.",
  "honk|verb": "The drivers honked their horns in the traffic jam.",
  "taut|adjective": "Her face was taut with worry as she waited for the results.",
  "desertion|noun": "The soldier was punished for desertion.",
  "demography|noun": "Changes in demography affect the need for schools and hospitals.",
  "billiards|noun": "They played billiards after dinner.",
  "dislodge|verb": "The storm dislodged several tiles from the roof.",
  "elude|verb": "The thief eluded the police for three weeks.",
  "splatter|verb": "Mud splattered all over my new trousers.",
  "glean|verb": "After the harvest, villagers gleaned the fields for leftover rice.",
  "hibernate|verb": "Bears hibernate through the long winter.",
  "haggle|verb": "Tourists often haggle over prices at the night market.",
  "gnaw|verb": "The dog was gnawing on an old bone.",
  "somersault|noun": "The gymnast did a perfect somersault.",
  "interjection|noun": "\"Wow\" is an interjection that shows surprise.",
  "curriculum|noun": "Coding has been added to the school curriculum.",
  "ore|noun": "Iron ore is mined in the northern provinces.",
  "deficit|noun": "The government is trying to reduce the budget deficit.",
  "echo|noun": "We heard the echo of our voices in the cave.",
  "secular|adjective": "It is a secular state with no official religion.",
  "hypothesis|noun": "The experiment was designed to test the hypothesis.",
  "scroll|noun": "The museum displays an ancient scroll with poems in Chinese characters.",
  "legion|noun": "A Roman legion marched north to defend the border.",
  "commodity|noun": "Coffee is one of the country's most important export commodities.",
  "abundance|noun": "The region has an abundance of fresh seafood.",
  "proposition|noun": "Investing in solar energy is an attractive proposition for many businesses.",
  "autonomous|adjective": "The region has become an autonomous territory with its own parliament.",
  "synthesis|noun": "Her book is a synthesis of ideas from psychology and economics.",
  "notorious|adjective": "The road is notorious for traffic accidents.",
  "temper|verb": "The blacksmith tempered the steel to make it stronger.",
  "cosmic|adjective": "Astronomers study cosmic radiation from distant galaxies.",
  "abundant|adjective": "Rainfall is abundant in the central highlands.",
  "spatial|adjective": "Architects need good spatial awareness.",
  "corpse|noun": "The police found a corpse in the abandoned warehouse.",
  "solitary|adjective": "He leads a solitary life in a cabin in the woods.",
  "reconciliation|noun": "The two families finally reached a reconciliation.",
  "corpus|noun": "The dictionary is based on a corpus of two billion words.",
  "nostalgia|noun": "Old photographs fill me with nostalgia for my childhood.",
  "equilibrium|noun": "The market will eventually return to equilibrium.",
  "redundant|adjective": "Delete any redundant words to make the sentence clearer.",
  "parameter|noun": "You can change the parameters of the experiment.",
  "subsidy|noun": "Farmers receive a subsidy for growing organic crops.",
  "residue|noun": "Wash the fruit to remove any chemical residue.",
  "diligence|noun": "Her diligence was rewarded with a scholarship.",
  "accessibility|noun": "The new website was designed with accessibility in mind.",
  "locomotive|noun": "The museum has a steam locomotive from 1910.",
  "paralysis|noun": "The accident left him with paralysis in both legs.",
  "anthology|noun": "The anthology contains poems by twenty young writers.",
  "apostle|noun": "The painting shows the twelve apostles at the table.",
  "qualitative|adjective": "The study combines numbers with qualitative interviews.",
  "solitude|noun": "She enjoys the solitude of early morning walks.",
  "artifact|noun": "The museum displays artifacts from the ancient city.",
  "agile|adjective": "The goalkeeper is tall but surprisingly agile.",
  "pervasive|adjective": "The smell of smoke was pervasive after the fire.",
  "hinder|verb": "Heavy rain hindered the rescue efforts.",
  "electrode|noun": "The nurse attached electrodes to the patient's chest.",
  "palate|noun": "The spicy soup burned the roof of his palate.",
  "agility|noun": "Cats are known for their agility.",
  "disperse|verb": "The crowd slowly dispersed after the concert.",
  "collide|verb": "Two buses collided at the crossroads.",
  "mercenary|noun": "The rebels hired foreign mercenaries.",
  "hover|verb": "A helicopter hovered above the flooded village.",
  "antidote|noun": "There is no known antidote to this snake's venom.",
  "whirlwind|noun": "A whirlwind lifted leaves high into the air.",
  "meticulous|adjective": "She keeps meticulous records of every expense.",
  "jargon|noun": "The report is full of technical jargon.",
  "diligent|adjective": "He is a diligent student who never misses a class.",
  "meteorology|noun": "Advances in meteorology have made forecasts more accurate.",
  "chronology|noun": "The book presents a chronology of the war.",
  "hermit|noun": "The old hermit lived alone in a cave for forty years.",
  "fallacy|noun": "It is a fallacy that more expensive always means better.",
  "zoology|noun": "She has a degree in zoology.",
  "barometer|noun": "The barometer shows that the air pressure is falling.",
  "lark|noun": "A lark sang high above the fields.",
  "condensation|noun": "Condensation formed on the cold window.",
  "derelict|adjective": "The derelict factory has been empty for years.",
  "inert|adjective": "Helium is an inert gas.",
  "allegory|noun": "The novel is an allegory of life under a dictatorship.",
  "gout|noun": "His gout makes it painful to walk.",
  "assimilate|verb": "Many immigrants were quickly assimilated into the local community.",
  "depraved|adjective": "The film's villain is a truly depraved character.",
  "wither|verb": "The flowers withered in the heat.",
  "axiom|noun": "The proof starts from a few simple axioms.",
  "superfluous|adjective": "Remove any superfluous details from your summary.",
  "shimmer|verb": "The lake shimmered in the moonlight.",
  "coax|verb": "She coaxed the frightened cat out from under the bed.",
  "archetype|noun": "The wise old mentor is a common archetype in fairy tales.",
  "connotation|noun": "The word \"cheap\" often has a negative connotation.",
  "subsidize|verb": "The city subsidizes public transport for students.",
  "midwifery|noun": "She trained in midwifery before working in rural clinics.",
  "colloquial|adjective": "\"Gonna\" is a colloquial form of \"going to\".",
  "minefield|noun": "The area was a minefield during the war.",
  "stratosphere|noun": "The balloon rose into the stratosphere.",
  "interrogate|verb": "The police interrogated the suspect for six hours.",
  "substantiate|verb": "The journalist could not substantiate her claims.",
  "buzzard|noun": "A buzzard circled above the fields, looking for mice.",
  "surrealism|noun": "Dalí is one of the most famous painters of surrealism.",
  "prostrate|verb": "The pilgrims prostrated themselves before the altar.",
  "aghast|adjective": "She was aghast at the size of the bill.",
  "abhor|verb": "I abhor cruelty to animals.",
  "stoicism|noun": "He faced his illness with remarkable stoicism.",
  "zoologist|noun": "The zoologist studied the behaviour of wild elephants.",
  "ecotourism|noun": "Ecotourism brings income to villages near the national park.",
  "loiter|verb": "Teenagers were loitering outside the shop.",
  "dwarfism|noun": "Dwarfism can be caused by a genetic condition.",
  "laryngitis|noun": "The singer cancelled the concert because of laryngitis.",
  "interrogative|adjective": "\"Where\" and \"why\" are interrogative words.",
  "resound|verb": "Cheers resounded through the stadium.",
  "presupposition|noun": "The question contains a hidden presupposition.",
  "floe|noun": "A polar bear rested on a floe of ice.",
  "idiosyncrasy|noun": "One of his idiosyncrasies is wearing odd socks.",
  "polysyllabic|adjective": "Children often find polysyllabic words hard to spell."
};
