/** A2 example sentences (English 4 Free original). */
export const examplesA2: Record<string, string> = {
  "can|noun": "He opened a can of soup for lunch.",
  "after|adverb": "We had dinner and went for a walk after.",
  "need|verb": "I need a new pair of shoes.",
  "being|noun": "Every living being needs water.",
  "state|noun": "The state pays for primary education.",
  "part|noun": "The first part of the book is the best.",
  "company|noun": "She works for a software company in Da Nang.",
  "thought|noun": "Clear thought is difficult when you are tired.",
  "public|noun": "The museum is open to the public on Sundays.",
  "government|noun": "The government is building a new hospital.",
  "enough|adverb": "The room isn't big enough for ten people.",
  "power|noun": "The president has a lot of power.",
  "national|adjective": "Pho is a national dish in Vietnam.",
  "call|verb": "I'll call you when I arrive.",
  "actually|adverb": "I thought he was Australian, but actually he's from Canada.",
  "country|noun": "Japan is a country with many mountains.",
  "whole|adjective": "We spent the whole day at the beach.",
  "law|noun": "In many countries, the law says you must wear a helmet.",
  "area|noun": "This area is famous for its coffee.",
  "local|adjective": "We buy vegetables from the local market.",
  "single|adjective": "My cousin is thirty and still single.",
  "court|noun": "The case will go to court next month.",
  "control|noun": "The driver lost control of the car on the icy road.",
  "university|noun": "My brother studies engineering at university.",
  "research|noun": "Her research is about clean water.",
  "lost|adjective": "We got lost in the old part of the city.",
  "understand|verb": "I don't understand this question.",
  "probably|adverb": "It will probably rain this afternoon.",
  "air|noun": "The air in the mountains is fresh and cool.",
  "possible|adjective": "Is it possible to change my ticket?",
  "international|adjective": "Tan Son Nhat is an international airport.",
  "low|adjective": "The prices at this shop are very low.",
  "third|adjective": "This is my third visit to Hue.",
  "report|noun": "The manager read the report before the meeting.",
  "red|noun": "Red is my favourite colour.",
  "rather|adverb": "It's rather cold today, so take a jacket.",
  "act|noun": "Helping the old man was a kind act.",
  "quite|adverb": "The test was quite easy.",
  "political|adjective": "The newspaper has a page about political news.",
  "market|noun": "We buy fresh fish at the market every morning.",
  "final|adjective": "The final exam is in June.",
  "education|noun": "Education is free for young children in many countries.",
  "experience|noun": "She has five years of experience as a nurse.",
  "study|noun": "He spends most of his time on study.",
  "chance|noun": "This is a great chance to practise your English.",
  "road|noun": "Be careful when you cross the road.",
  "instead|adverb": "There was no bus, so we walked instead.",
  "issue|noun": "Traffic is a big issue in our city.",
  "force|noun": "The force of the wind broke the window.",
  "land|verb": "Our plane will land at eight o'clock.",
  "similar|adjective": "My bag is similar to yours.",
  "position|noun": "Check the position of the hotel on the map.",
  "include|verb": "The price includes breakfast.",
  "account|noun": "I opened a bank account last week.",
  "share|noun": "Everyone did their share of the cleaning.",
  "perfect|adjective": "The weather was perfect for a picnic.",
  "military|adjective": "He did two years of military service.",
  "common|adjective": "Nguyen is a very common family name.",
  "private|adjective": "This is a private beach for hotel guests.",
  "online|adjective": "I take an online English class every evening.",
  "hold|verb": "Please hold my coffee for a moment.",
  "center|noun": "There is a big shopping center near my house.",
  "middle|noun": "There is a fountain in the middle of the square.",
  "member|noun": "She is a member of the school choir.",
  "break|noun": "Let's take a short break.",
  "society|noun": "Older people have an important role in society.",
  "finally|adverb": "After two hours, the bus finally arrived.",
  "park|verb": "You can park your motorbike behind the building.",
  "original|adjective": "The original building was made of wood.",
  "certain|adjective": "I'm certain that I locked the door.",
  "average|adjective": "The average temperature in July is 30 degrees.",
  "value|noun": "The value of the house has doubled.",
  "source|noun": "Fish is a good source of protein.",
  "sound|noun": "I love the sound of the rain.",
  "director|noun": "The director of the company will visit our office.",
  "stuff|noun": "Can I leave my stuff here while I go shopping?",
  "stand|verb": "Please stand in line and wait.",
  "rate|noun": "The exchange rate changes every day.",
  "production|noun": "Production at the factory will increase next year.",
  "official|adjective": "English is an official language in Singapore.",
  "follow|verb": "Follow me, and I'll show you the room.",
  "evidence|noun": "The police found evidence at the scene.",
  "step|noun": "Take one step forward.",
  "model|noun": "She works as a fashion model in Paris.",
  "green|noun": "The walls are painted green.",
  "fall|verb": "Be careful not to fall on the wet floor.",
  "drive|verb": "My mother drives to work every day.",
  "trade|noun": "Trade between the two countries is growing.",
  "range|noun": "The shop sells a wide range of bicycles.",
  "style|noun": "I like the style of her new jacket.",
  "quality|noun": "The quality of the food here is excellent.",
  "hate|verb": "I hate waiting in long lines.",
  "oil|noun": "Fry the onions in a little oil.",
  "situation|noun": "The situation at the airport is getting better.",
  "perhaps|adverb": "Perhaps we should take a taxi.",
  "attack|noun": "The city was under attack for three days.",
  "staff|noun": "The hotel staff were very friendly.",
  "simple|adjective": "The instructions are simple to follow.",
  "lose|verb": "Don't lose your ticket.",
  "cover|verb": "Cover the pot and cook for ten minutes.",
  "continue|verb": "Please continue with your work.",
  "voice|noun": "She has a beautiful voice.",
  "popular|adjective": "This song is very popular with teenagers.",
  "modern|adjective": "The new library is a modern building.",
  "die|verb": "Plants die without water.",
  "crazy|adjective": "It's crazy to drive so fast in the rain.",
  "truth|noun": "Please tell me the truth.",
  "professional|adjective": "They hired a professional photographer for the wedding.",
  "offer|noun": "Thank you for your kind offer of help.",
  "mark|noun": "She got full marks in the maths test.",
  "recent|adjective": "Prices have gone up in recent years.",
  "rock|noun": "We sat on a large rock by the river.",
  "response|noun": "I sent an email but got no response.",
  "married|adjective": "My parents have been married for twenty years.",
  "recently|adverb": "I recently started learning the guitar.",
  "effect|noun": "The film uses special effects to show the storm.",
  "century|noun": "This temple was built in the eleventh century.",
  "pressure|noun": "Check the pressure in your bicycle tyres.",
  "population|noun": "The population of the city is about two million.",
  "normal|adjective": "It's normal to feel nervous before an exam.",
  "gas|noun": "Oxygen is a gas.",
  "double|adjective": "I'd like a double room for two nights.",
  "committee|noun": "The committee will meet on Monday.",
  "brown|noun": "Brown is a warm colour for a living room.",
  "association|noun": "She joined the local teachers' association.",
  "nearly|adverb": "I nearly missed the train.",
  "certainly|adverb": "I will certainly come to your wedding.",
  "beginning|noun": "Read the beginning of the story again.",
  "drop|noun": "A drop of rain fell on my face.",
  "contact|noun": "Children should have contact with nature.",
  "significant|adjective": "This is a significant day in our history.",
  "nature|noun": "We spent the weekend enjoying nature in the mountains.",
  "manager|noun": "Please speak to the manager about your complaint.",
  "episode|noun": "I watched the first episode of the new series.",
  "wide|adjective": "The road is wide enough for two buses.",
  "train|verb": "She trains at the gym three times a week.",
  "knowledge|noun": "His knowledge of history is impressive.",
  "secretary|noun": "The secretary will send you the documents.",
  "product|noun": "This product is made in Vietnam.",
  "opportunity|noun": "The job is a good opportunity to learn new skills."
};
