import { randomUUID } from "node:crypto";
import { and, asc, desc, eq, or } from "drizzle-orm";
import { McqContentSchema } from "@english4free/content-schemas";
import { createDatabase } from "@/db/client";
import { attemptAnswers, attempts, examParts, exams, passages, questions } from "@/db/schema";
import { appendProgressEvent } from "@/modules/progress/repository";
import type { AttemptActor, SavedAnswer } from "@/modules/attempts/types";

function dbOrThrow() { const db = createDatabase(); if (!db) throw new Error("DATABASE_URL is required for the shared exam engine"); return db; }
function owner(actor: AttemptActor) { return actor.userId ? or(eq(attempts.userId, actor.userId), eq(attempts.guestId, actor.guestId)) : eq(attempts.guestId, actor.guestId); }
export function isAttemptExpired(expiresAt: Date | null, now = new Date()) { return Boolean(expiresAt && expiresAt <= now); }
export function scoreStoredAnswers(questionRows: Array<{ id: string; answer: unknown; explanation: string | null }>, saved: Array<{ questionId: string; selectedOptionId: string }>) { const answerMap = new Map(saved.map((item) => [item.questionId, item.selectedOptionId])); const results = questionRows.map((item) => { const correctOptionId = (item.answer as { correctOptionId: string }).correctOptionId; const selectedOptionId = answerMap.get(item.id) ?? null; return { questionId: item.id, selectedOptionId, correctOptionId, correct: selectedOptionId === correctOptionId, explanation: item.explanation }; }); return { rawScore: results.filter((item) => item.correct).length, results }; }
export async function getPublicExamBySlug(slug: string) { const db = dbOrThrow(); const [exam] = await db.select().from(exams).where(and(eq(exams.slug, slug), eq(exams.status, "PUBLISHED"))); if (!exam) return null; const partRows = await db.select().from(examParts).where(eq(examParts.examId, exam.id)).orderBy(asc(examParts.sortOrder)); const parts = await Promise.all(partRows.map(async (part) => { const passageRows = await db.select().from(passages).where(eq(passages.examPartId, part.id)).orderBy(asc(passages.sortOrder)); const questionRows = await db.select({ id: questions.id, type: questions.type, schemaVersion: questions.schemaVersion, content: questions.content, passageId: questions.passageId }).from(questions).where(and(eq(questions.examPartId, part.id), eq(questions.status, "PUBLISHED"))).orderBy(asc(questions.createdAt)); return { id: part.id, partNumber: part.partNumber, title: part.title, instructions: part.instructions, skill: part.skill, metadata: part.metadata as Record<string, unknown>, passages: passageRows.map((item) => ({ id: item.id, title: item.title, content: item.content })), questions: questionRows.map((item) => ({ ...item, content: McqContentSchema.parse(item.content) })) }; })); return { id: exam.id, slug: exam.slug, title: exam.title, type: exam.type, mode: exam.mode as "PRACTICE" | "MINI_TEST" | "FULL_MOCK", durationSeconds: exam.durationSeconds, parts, totalQuestions: parts.reduce((sum, part) => sum + part.questions.length, 0) }; }
export async function startOrResumeExam(slug: string, actor: AttemptActor) { const db = dbOrThrow(); const exam = await getPublicExamBySlug(slug); if (!exam) throw new Error("Exam not found"); const [active] = await db.select().from(attempts).where(and(eq(attempts.examId, exam.id), eq(attempts.status, "IN_PROGRESS"), owner(actor))).orderBy(desc(attempts.startedAt)).limit(1); const now = new Date(); if (active && (!active.expiresAt || active.expiresAt > now)) { const answers = await db.select({ questionId: attemptAnswers.questionId, selectedOptionId: attemptAnswers.selectedOptionId }).from(attemptAnswers).where(eq(attemptAnswers.attemptId, active.id)); return { attempt: { ...active, answers }, exam, resumed: true }; } if (active) await db.update(attempts).set({ status: "EXPIRED", updatedAt: now }).where(eq(attempts.id, active.id)); const id = randomUUID(); const expiresAt = new Date(now.getTime() + exam.durationSeconds * 1000); await db.insert(attempts).values({ id, examId: exam.id, userId: actor.userId, guestId: actor.guestId, status: "IN_PROGRESS", startedAt: now, expiresAt, totalQuestions: exam.totalQuestions }); await appendProgressEvent({ userId: actor.userId, guestId: actor.guestId, type: "EXAM_STARTED", skill: null, sourceType: "EXAM_ATTEMPT", sourceId: id, idempotencyKey: `exam:${id}:started`, metadata: { examId: exam.id, mode: exam.mode } }); return { attempt: { id, examId: exam.id, userId: actor.userId, guestId: actor.guestId, status: "IN_PROGRESS" as const, startedAt: now, expiresAt, submittedAt: null, rawScore: null, totalQuestions: exam.totalQuestions, answers: [] }, exam, resumed: false }; }
async function getOwnedAttempt(attemptId: string, actor: AttemptActor) { const db = dbOrThrow(); const [attempt] = await db.select().from(attempts).where(and(eq(attempts.id, attemptId), owner(actor))); if (!attempt) throw new Error("Attempt not found"); return attempt; }
export async function saveExamAnswers(attemptId: string, actor: AttemptActor, answers: SavedAnswer[]) { const db = dbOrThrow(); const attempt = await getOwnedAttempt(attemptId, actor); if (attempt.status !== "IN_PROGRESS") throw new Error("Attempt is not editable"); if (attempt.expiresAt && attempt.expiresAt <= new Date()) { await db.update(attempts).set({ status: "EXPIRED", updatedAt: new Date() }).where(eq(attempts.id, attempt.id)); throw new Error("Attempt has expired"); } const allowedRows = await db.select({ id: questions.id, content: questions.content }).from(questions).innerJoin(examParts, eq(questions.examPartId, examParts.id)).where(and(eq(examParts.examId, attempt.examId), eq(questions.status, "PUBLISHED"))); const allowed = new Map(allowedRows.map((row) => [row.id, McqContentSchema.parse(row.content)])); for (const answer of answers) { const content = allowed.get(answer.questionId); if (!content?.options.some((option) => option.id === answer.selectedOptionId)) throw new Error("Invalid answer for this exam"); await db.insert(attemptAnswers).values({ attemptId, questionId: answer.questionId, selectedOptionId: answer.selectedOptionId }).onConflictDoUpdate({ target: [attemptAnswers.attemptId, attemptAnswers.questionId], set: { selectedOptionId: answer.selectedOptionId, updatedAt: new Date() } }); } return { attemptId, savedAnswers: (await db.select().from(attemptAnswers).where(eq(attemptAnswers.attemptId, attemptId))).length }; }
export async function submitExamAttempt(attemptId: string, actor: AttemptActor, submittedAnswers: SavedAnswer[]) { const db = dbOrThrow(); let attempt = await getOwnedAttempt(attemptId, actor); if (attempt.status === "EXPIRED") throw new Error("Attempt has expired"); if (attempt.status === "IN_PROGRESS") { await saveExamAnswers(attemptId, actor, submittedAnswers); if (attempt.expiresAt && attempt.expiresAt <= new Date()) throw new Error("Attempt has expired"); const questionRows = await db.select({ id: questions.id, answer: questions.answer, explanation: questions.explanation }).from(questions).innerJoin(examParts, eq(questions.examPartId, examParts.id)).where(and(eq(examParts.examId, attempt.examId), eq(questions.status, "PUBLISHED"))); const saved = await db.select().from(attemptAnswers).where(eq(attemptAnswers.attemptId, attemptId)); const answerMap = new Map(saved.map((item) => [item.questionId, item.selectedOptionId])); const rawScore = questionRows.filter((item) => (item.answer as { correctOptionId?: string }).correctOptionId === answerMap.get(item.id)).length; const submittedAt = new Date(); await db.update(attempts).set({ status: "SUBMITTED", rawScore, submittedAt, updatedAt: submittedAt }).where(and(eq(attempts.id, attemptId), eq(attempts.status, "IN_PROGRESS"))); attempt = (await getOwnedAttempt(attemptId, actor)); }
  const questionRows = await db.select({ id: questions.id, answer: questions.answer, explanation: questions.explanation }).from(questions).innerJoin(examParts, eq(questions.examPartId, examParts.id)).where(and(eq(examParts.examId, attempt.examId), eq(questions.status, "PUBLISHED"))); const saved = await db.select().from(attemptAnswers).where(eq(attemptAnswers.attemptId, attemptId)); const answerMap = new Map(saved.map((item) => [item.questionId, item.selectedOptionId])); const results = questionRows.map((item) => { const correctOptionId = (item.answer as { correctOptionId: string }).correctOptionId; const selectedOptionId = answerMap.get(item.id) ?? null; return { questionId: item.id, selectedOptionId, correctOptionId, correct: selectedOptionId === correctOptionId, explanation: item.explanation }; }); const [exam] = await db.select().from(exams).where(eq(exams.id, attempt.examId)); await appendProgressEvent({ userId: actor.userId, guestId: actor.guestId, type: "EXAM_COMPLETED", skill: null, sourceType: "EXAM_ATTEMPT", sourceId: attempt.id, idempotencyKey: `exam:${attempt.id}:completed`, metadata: { examId: attempt.examId, rawScore: attempt.rawScore, mode: exam?.mode } }); return { attempt, results };
}
