import Link from "next/link";
import { notFound } from "next/navigation";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Eyebrow, Section } from "@/components/ui/section";
import { getLocale, getMessages } from "@/lib/i18n";
const sections = ["learn", "toeic", "ielts", "vocabulary", "grammar", "pronunciation", "dashboard", "about", "blog"] as const; type SectionName = (typeof sections)[number];
export function generateStaticParams() { return sections.map((section) => ({ section })); }
export default async function SectionPage({ params }: { params: Promise<{ section: string }> }) { const { section } = await params; if (!sections.includes(section as SectionName)) notFound(); const messages = getMessages(await getLocale()); const localized: Record<SectionName, { title: string; text: string }> = { learn: { title: messages.nav.learn, text: messages.home.levelsDescription }, toeic: { title: "TOEIC", text: messages.home.examDescription }, ielts: { title: "IELTS", text: messages.common.comingSoon }, vocabulary: { title: messages.nav.vocabulary, text: messages.home.levelsDescription }, grammar: { title: messages.nav.grammar, text: messages.home.levelsDescription }, pronunciation: { title: messages.nav.pronunciation, text: messages.home.skillsDescription }, dashboard: { title: messages.common.dashboard, text: messages.common.comingSoon }, about: { title: messages.common.about, text: messages.brandTagline }, blog: { title: messages.common.blog, text: messages.common.comingSoon } }; const content = localized[section as SectionName]; return <Section className="py-20 sm:py-28"><Eyebrow>{messages.home.eyebrow}</Eyebrow><h1 className="mt-5 font-serif text-5xl font-bold tracking-tight sm:text-6xl">{content.title}</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-muted">{content.text}</p><Card className="mt-12 max-w-2xl"><p className="text-sm font-bold text-brand">{messages.common.comingSoon}</p><p className="mt-3 leading-7 text-muted">{content.text}</p>{section === "toeic" ? <Link className="mt-7 inline-flex" href="/toeic/practice/part-5"><Button>TOEIC Part 5</Button></Link> : <Link className="mt-7 inline-flex" href="/"><Button variant="secondary">{messages.common.explore}</Button></Link>}</Card></Section>; }
