import { cookies } from "next/headers";
import { locales, localeCookieName, type Locale } from "./locale";
export { locales, localeCookieName, type Locale };

const messages = {
  vi: {
    brandTagline: "Học tiếng Anh miễn phí, có lộ trình.",
    nav: {"learn": "Học", "skills": "Kỹ năng", "toeic": "TOEIC", "ielts": "IELTS", "vocabulary": "Từ vựng", "grammar": "Ngữ pháp", "pronunciation": "Phát âm", "today": "Hôm nay", "mistakes": "Sổ lỗi sai", "path": "Lộ trình", "practice": "Luyện tập", "examPrep": "Luyện thi"},
    common: { login: "Đăng nhập", logout: "Đăng xuất", signedIn: "Đã đăng nhập", dashboard: "Tiến độ", start: "Bắt đầu học", menu: "Mở menu", close: "Đóng menu", language: "Ngôn ngữ", explore: "Khám phá", skipContent: "Bỏ qua đến nội dung", primaryNavigation: "Điều hướng chính", mobileNavigation: "Điều hướng di động", about: "Giới thiệu", privacy: "Quyền riêng tư", terms: "Điều khoản" },
    operability: { loading: "Đang tải…", saving: "Đang lưu…", requestFailed: "Thao tác chưa hoàn tất. Hãy thử lại.", noData: "Chưa có dữ liệu để hiển thị.", unavailable: "Tính năng này hiện chưa sẵn sàng." },
    dashboard: { eyebrow: "Tiến độ", title: "Tiến độ học của bạn", xp: "XP", streak: "Chuỗi ngày", activities: "Hoạt động", days: "ngày", skillActivity: "Hoạt động theo kỹ năng", emptyTitle: "Chưa có hoạt động học", emptyText: "Hãy hoàn thành một bài luyện hoặc ôn một thẻ từ để bắt đầu theo dõi tiến độ." },
    home: {"eyebrow": "Miễn phí · Học bằng tiếng Việt", "title": "Một lộ trình tiếng Anh rõ ràng, dành cho bạn.", "description": "Làm bài xếp lớp 20 câu, nhận lộ trình A1–C2 đúng trình độ, rồi luyện đủ bốn kỹ năng, từ vựng và đề TOEIC, IELTS. Hoàn toàn miễn phí.", "startPlan": "Bắt đầu học", "todayPlan": "Học tiếp", "viewPath": "Xem lộ trình", "trust": ["Không quảng cáo", "Không cần đăng ký để bắt đầu", "Giao diện tiếng Việt và tiếng Anh"], "previewLesson": "Bài học", "previewWord": "Thẻ từ vựng", "previewQuestion": "Câu hỏi luyện tập", "minutes": "phút", "stats": {"lessons": "bài học theo lộ trình", "words": "từ vựng có IPA và nghĩa tiếng Việt", "examQuestions": "câu hỏi luyện thi TOEIC và IELTS", "topics": "chủ đề luyện Nói và Viết"}, "stepsEyebrow": "Cách học", "stepsTitle": "Bắt đầu trong ba bước", "steps": [{"title": "Làm bài xếp lớp", "text": "20 câu Ngữ pháp, Từ vựng, Đọc và Nghe, độ khó tự điều chỉnh theo câu trả lời. Khoảng 10 phút."}, {"title": "Học theo lộ trình", "text": "Mỗi trình độ chia thành các chủ đề. Nút Học tiếp luôn đưa bạn đến bài kế tiếp."}, {"title": "Ôn tập và luyện thi", "text": "Ôn từ vựng đúng lúc sắp quên, luyện lại câu sai và làm đề TOEIC, IELTS khi sẵn sàng."}], "featuresEyebrow": "Có gì trong English 4 Free", "featuresTitle": "Mọi thứ để học đều đặn mỗi ngày", "features": {"path": {"title": "Lộ trình A1–C2", "text": "Bài Ngữ pháp, Nghe, Đọc, Nói và Viết sắp xếp theo chủ đề."}, "listenRead": {"title": "Nghe và Đọc", "text": "Hội thoại có ghi âm và bài đọc theo từng trình độ, kèm câu hỏi."}, "speakWrite": {"title": "Nói và Viết", "text": "Ghi âm, viết theo chủ đề với câu gợi ý và nhận nhận xét từ AI."}, "vocab": {"title": "Từ vựng và phát âm", "text": "Thẻ ghi nhớ ôn lặp lại, bảng IPA và các cặp âm dễ nhầm."}, "exams": {"title": "Luyện thi TOEIC, IELTS", "text": "Luyện từng phần, bài thi ngắn và đề thi thử TOEIC 200 câu."}, "mistakes": {"title": "Sổ lỗi sai và trợ giảng", "text": "Câu sai được lưu lại để luyện; trợ giảng AI giải thích từng câu."}}, "ctaTitle": "Khoảng 10 phút để biết trình độ của bạn", "ctaText": "Làm bài xếp lớp và nhận lộ trình học riêng ngay hôm nay.", "ctaReturningTitle": "Tiếp tục lộ trình của bạn", "ctaReturningText": "Bài học tiếp theo đã sẵn sàng trong mục Hôm nay.", "progressEyebrow": "Tiến độ", "progressTitle": "Tiến độ học của bạn", "viewDetail": "Xem chi tiết", "vocabularyLearned": "Từ vựng đã học", "dayStreak": "Chuỗi ngày học", "streakNote": "*Chuỗi ngày mới bắt đầu lúc 0h giờ Việt Nam", "heatmapTitle": "Hoạt động 20 tuần gần đây", "few": "Ít", "many": "Nhiều", "activeDays": "ngày học"},
    learning: { eyebrow: "Lộ trình CEFR", title: "Học tiếng Anh theo từng bước nhỏ", description: "Chọn trình độ, hoàn thành bài học ngắn, rồi ôn từ vựng đúng thời điểm.", continue: "Tiếp tục học", units: "chủ đề", lessons: "bài học", minutes: "phút", startLesson: "Bắt đầu bài học", lessonComplete: "Đã hoàn thành", lessonProgress: "Tiến độ bài học", vocabularyTitle: "Từ vựng CEFR", vocabularyDescription: "Từ vựng theo trình độ CEFR; mỗi từ được hẹn ôn lại đúng lúc bạn sắp quên.", reviewNow: "Ôn ngay", noCards: "Bạn đã ôn hết các từ đến hạn ở trình độ này.", saveFailed: "Chưa lưu được kết quả ôn. Hãy thử lại.", dueSummary: "{due} từ đến hạn ôn · {new} từ mới · {later} từ sẽ quay lại sau", again: "Chưa nhớ", hard: "Khó", good: "Tốt", easy: "Dễ", nextCard: "Thẻ tiếp theo", reviewed: "Đã ôn", source: "Nguồn dữ liệu" }
    , pronunciation: { eyebrow: "Phát âm", title: "Nghe kỹ, nói rõ, luyện đều.", description: "Làm chủ từng âm IPA, phân biệt minimal pairs và luyện shadowing với bản ghi âm của chính bạn.", ipa: "Bảng IPA", minimalPairs: "Cặp âm dễ nhầm", shadowing: "Shadowing", record: "Bắt đầu ghi âm", stop: "Dừng ghi âm", recording: "Đang ghi âm", playback: "Nghe lại bản ghi", targetPlayback: "Nghe câu mẫu", unsupported: "Trình duyệt này không hỗ trợ ghi âm.", permissionDenied: "Không thể truy cập microphone. Hãy cấp quyền rồi thử lại.", ready: "Sẵn sàng để luyện", retry: "Ghi âm lại", transcript: "Bản ghi lời nói", analysisPending: "Nghe câu mẫu, ghi âm rồi nghe lại để tự so sánh nhịp, trọng âm và các âm cần chú ý.", target: "Câu mẫu", tip: "Mẹo luyện tập" }
    , ielts: { eyebrow: "IELTS Academic", title: "Luyện IELTS theo đúng kỹ năng và tiêu chí chấm.", description: "Luyện đủ bốn kỹ năng Listening, Reading, Writing và Speaking theo đúng dạng đề thi.", writing: "Writing", speaking: "Speaking", writingTitle: "IELTS Writing", writingDescription: "Chọn một đề Task 1 (mô tả biểu đồ, 150 từ) hoặc Task 2 (bài luận, 250 từ). Lưu nháp bất cứ lúc nào; khi nộp, bạn nhận nhận xét theo bốn tiêu chí chấm (không phải band chính thức).", writingPrompt: "Some people believe that technology makes people less social. To what extent do you agree or disagree?", speakingTitle: "IELTS Speaking", speakingDescription: "Chọn một bộ đề gồm Part 1, cue card Part 2 và câu hỏi thảo luận Part 3. Nhấn để nói; bạn sẽ nhận bản chép lời và nhận xét để luyện tiếp (không phải band chính thức).", speakingPrompt: "Tell me about a skill you would like to learn." }
    , onboarding: { eyebrow: "Bắt đầu", title: "Cùng thiết lập lộ trình của bạn", description: "Vài câu hỏi ngắn để chúng tôi gợi ý đúng việc cần làm mỗi ngày.", goalStep: "Mục tiêu của bạn là gì?", goalCommunication: "Giao tiếp hằng ngày", goalToeic: "Luyện thi TOEIC", goalIelts: "Luyện thi IELTS", minutesStep: "Bạn muốn học bao nhiêu phút mỗi ngày?", minutes: "phút/ngày", levelStep: "Trình độ hiện tại của bạn?", levelSelfHint: "Chọn trình độ bạn nghĩ mình đang có rồi hoàn tất, hoặc làm bài xếp lớp: bài kiểm tra sẽ bắt đầu từ trình độ bạn chọn (mặc định B1).", takePlacement: "Làm bài kiểm tra xếp lớp", useSelfLevel: "Dùng trình độ này", placementTitle: "Bài kiểm tra xếp lớp", placementIntro: "Khoảng 20 câu cho Ngữ pháp, Từ vựng, Đọc và Nghe. Độ khó tự điều chỉnh theo câu trả lời của bạn, nên cứ chọn đáp án bạn thấy đúng nhất, không cần đoán.", placementProgress: "Câu {current}/{total}", placementStarting: "Đang chuẩn bị bài kiểm tra…", placementError: "Không tải được câu hỏi. Hãy thử lại.", listen: "Nghe", listenHint: "Nghe đoạn ghi âm rồi trả lời câu hỏi.", quit: "Thoát bài kiểm tra", skills: { GRAMMAR: "Ngữ pháp", VOCABULARY: "Từ vựng", READING: "Đọc", LISTENING: "Nghe", SPEAKING: "Nói", WRITING: "Viết" }, selfTitle: "Nói và Viết: tự đánh giá", selfIntro: "Hai kỹ năng này chưa chấm tự động được. Chọn câu mô tả đúng nhất khả năng hiện tại của bạn.", seeResult: "Xem kết quả", back: "Quay lại", next: "Tiếp tục", finish: "Hoàn tất", submitting: "Đang lưu…", resultLevel: "Trình độ đề xuất", resultBySkill: "Trình độ theo kỹ năng", resultScore: "Trả lời đúng {correct}/{total} câu", resultSelfNote: "Nói và Viết theo tự đánh giá", startLearning: "Bắt đầu học", errorSave: "Chưa lưu được. Hãy thử lại." }
    , today: {"eyebrow": "Hôm nay", "title": "Hôm nay", "greeting": "Việc nên làm hôm nay, theo lộ trình và mục tiêu của bạn.", "continueLabel": "Học tiếp", "continueHint": "Bài kế tiếp trong lộ trình", "allDone": "Bạn đã học hết các bài trong lộ trình. Hãy ôn từ vựng, luyện lại lỗi sai hoặc luyện thi.", "openPath": "Xem lộ trình", "minutesTitle": "Mục tiêu hôm nay", "minutesProgress": "{done}/{goal} phút", "minutesDone": "Bạn đã đạt mục tiêu hôm nay!", "minutesNote": "Ước tính từ các hoạt động đã làm hôm nay.", "vocabularyTitle": "Từ vựng đến hạn ôn", "vocabularyDue": "{count} từ cần ôn hôm nay", "vocabularyNone": "Không có từ nào đến hạn. Hãy học thêm từ mới.", "reviewNow": "Ôn ngay", "learnVocabulary": "Học từ mới", "mistakesTitle": "Sổ lỗi sai", "mistakesDue": "{count} câu cần luyện lại", "mistakesNone": "Không có lỗi nào cần luyện. Làm tốt lắm!", "practiceMistakes": "Luyện lại", "weakTitle": "Kỹ năng nên luyện", "weakText": "Theo bài xếp lớp, {skill} của bạn đang ở mức {level}, thấp nhất trong các kỹ năng.", "weakAction": "Luyện {skill}", "weakNone": "Làm bài xếp lớp để biết kỹ năng nào nên luyện thêm.", "takePlacement": "Làm bài xếp lớp", "examTitle": "Luyện thi", "practiceExam": "Luyện đề", "allExams": "Tất cả đề", "levelLabel": "Trình độ", "goalLabel": "Mục tiêu", "goalCommunication": "Giao tiếp", "goalToeic": "TOEIC", "goalIelts": "IELTS", "profileLink": "Hồ sơ học tập", "emptyTitle": "Bạn chưa thiết lập lộ trình", "emptyText": "Trả lời vài câu hỏi ngắn và làm bài xếp lớp để nhận gợi ý học mỗi ngày.", "setup": "Bắt đầu"}
    , mistakes: { eyebrow: "Ôn tập", title: "Sổ lỗi sai", description: "Những câu bạn từng làm sai trong bài học và đề thi, gom lại để luyện cho đến khi thành thạo.", emptyTitle: "Chưa có lỗi nào", emptyText: "Khi bạn làm sai một câu trong bài học hoặc đề thi, câu đó sẽ xuất hiện ở đây để luyện lại.", allSkills: "Tất cả", grammarOnly: "Ngữ pháp", count: "{count} câu cần luyện", timesWrong: "Sai {count} lần", sourceLesson: "Bài học", sourceExam: "Đề thi", practice: "Luyện lại", check: "Kiểm tra", next: "Câu tiếp theo", correct: "Chính xác! Đã xoá khỏi sổ lỗi.", incorrect: "Chưa đúng.", correctAnswer: "Đáp án đúng", finished: "Đã luyện xong các câu sai. Quay lại sổ để xem còn câu nào.", backToList: "Về danh sách" }
    , wordbook: { add: "Thêm vào sổ từ", added: "Đã thêm", adding: "Đang thêm…", already: "Đã có trong sổ", lessonTitle: "Từ mới trong bài", lessonDescription: "Lưu những từ bạn muốn nhớ. Chúng sẽ có trong lượt ôn từ vựng tiếp theo.", review: "Ôn sổ từ", dueDeck: "Đến hạn ôn", dueDeckSummary: "{due} từ trong sổ từ đang đến hạn ôn", dueDeckEmpty: "Chưa có từ nào đến hạn ôn. Thêm từ vào sổ từ khi học bài, hoặc chọn một trình độ để học từ mới." }
    , review: { modeLabel: "Kiểu ôn", recognition: "Nhận diện", typing: "Gõ lại", dictation: "Nghe & viết", show: "Xem nghĩa", typePrompt: "Gõ từ tiếng Anh", listenPrompt: "Nghe rồi gõ lại từ", play: "Nghe lại", check: "Kiểm tra", correctIs: "Đáp án", correct: "Chính xác", incorrect: "Chưa đúng" }
    , aiTutor: { ask: "Hỏi trợ giảng AI", thinking: "Đang nghĩ…", next: "Tiếp theo", you: "Bạn", tutor: "Trợ giảng", send: "Gửi", followUpPlaceholder: "Hỏi thêm về câu này", aiFeedback: "Nhận xét luyện tập từ AI", officialExplanation: "Lời giải chính thức", unavailable: "Trợ giảng tạm thời không khả dụng." }
    , assistant: { title: "Trợ giảng AI", open: "Mở trợ giảng AI", close: "Đóng", welcome: "Xin chào {name}! Mình là trợ giảng AI của English 4 Free. Hỏi mình một câu tiếng Anh hoặc cách dùng web nhé.", placeholder: "Hỏi về tiếng Anh hoặc website…", send: "Gửi", thinking: "Đang trả lời…", unavailable: "Trợ giảng tạm nghỉ, bạn thử lại sau nhé.", rateLimited: "Bạn hỏi hơi nhanh — nghỉ một chút rồi hỏi tiếp nhé.", friend: "bạn" }
    , pathPage: {"eyebrow": "Lộ trình", "title": "Lộ trình học", "description": "Mỗi trình độ gồm nhiều chủ đề với bài Ngữ pháp, Nghe, Đọc, Nói và Viết. Bạn có thể học bất kỳ bài nào; nút Học tiếp luôn đưa bạn đến bài kế tiếp.", "yourLevel": "Trình độ của bạn", "progress": "{done}/{total} bài đã học", "continue": "Học tiếp", "levelDone": "Bạn đã học hết trình độ này. Tuyệt vời!", "statusDone": "Đã học", "statusCurrent": "Bài tiếp theo", "statusTodo": "Chưa học", "vocabularyTitle": "Từ vựng {level}", "vocabularyText": "Học và ôn từ vựng trình độ {level} bằng thẻ ghi nhớ, song song với các bài học.", "vocabularyAction": "Mở từ vựng", "empty": "Chưa có bài học nào ở trình độ này."}
    , practice: {"eyebrow": "Luyện tập", "title": "Luyện tập theo kỹ năng", "description": "Chọn một kỹ năng để luyện riêng, bên cạnh lộ trình.", "suggested": "Nên luyện", "items": {"LISTENING": "Hội thoại và bài nói theo trình độ A1–C2.", "READING": "Đoạn văn theo trình độ, có câu hỏi đọc hiểu.", "SPEAKING": "Nói theo chủ đề, ghi âm và nhận nhận xét.", "WRITING": "Viết theo chủ đề với câu gợi ý và nhận xét.", "VOCABULARY": "Thẻ ghi nhớ và sổ từ, ôn theo lịch lặp lại.", "GRAMMAR": "Các chủ điểm ngữ pháp từ A1 đến C2.", "PRONUNCIATION": "Bảng IPA, cặp âm dễ nhầm và luyện nói đuổi.", "MISTAKES": "Luyện lại những câu bạn đã làm sai."}}
    , examPrep: {"eyebrow": "Luyện thi", "title": "Luyện thi TOEIC và IELTS", "description": "Luyện từng phần, làm bài thi ngắn hoặc thi thử đầy đủ. Đáp án được tự động lưu, bạn có thể dừng và làm tiếp bất cứ lúc nào.", "history": "Lịch sử làm đề", "toeicText": "Nghe và Đọc, Part 1–7, thang điểm 10–990.", "ieltsText": "Listening, Reading, Writing và Speaking, thang band 0–9.", "writingSpeaking": "Luyện Writing và Speaking IELTS", "empty": "Chưa có đề nào được công bố."}
    , account: {"menu": "Tài khoản", "guest": "Khách", "progress": "Tiến độ", "profile": "Hồ sơ học tập", "guestNote": "Tiến độ đang được lưu trên trình duyệt này. Đăng nhập để giữ lâu dài."}
    , profilePage: {"eyebrow": "Tài khoản", "title": "Hồ sơ học tập", "levelTitle": "Trình độ hiện tại", "fromPlacement": "Theo bài xếp lớp ({score}/{total} câu đúng)", "fromSelf": "Bạn tự chọn trình độ", "skillsTitle": "Trình độ theo kỹ năng", "skillsNone": "Làm bài xếp lớp để biết trình độ của từng kỹ năng.", "retake": "Làm lại bài xếp lớp", "planTitle": "Mục tiêu và thời gian học", "goal": "Mục tiêu", "minutes": "Số phút mỗi ngày", "save": "Lưu thay đổi", "saving": "Đang lưu…", "saved": "Đã lưu.", "saveFailed": "Chưa lưu được. Hãy thử lại.", "emptyTitle": "Bạn chưa có hồ sơ học tập", "emptyText": "Hoàn tất phần thiết lập để có hồ sơ và lộ trình riêng.", "setup": "Bắt đầu"}
  },
  en: {
    brandTagline: "Free English learning, with a clear path.",
    nav: {"learn": "Learn", "skills": "Skills", "toeic": "TOEIC", "ielts": "IELTS", "vocabulary": "Vocabulary", "grammar": "Grammar", "pronunciation": "Pronunciation", "today": "Today", "mistakes": "Mistakes", "path": "Path", "practice": "Practice", "examPrep": "Exam prep"},
    common: { login: "Log in", logout: "Log out", signedIn: "Signed in", dashboard: "Progress", start: "Start learning", menu: "Open menu", close: "Close menu", language: "Language", explore: "Explore", skipContent: "Skip to content", primaryNavigation: "Primary navigation", mobileNavigation: "Mobile navigation", about: "About", privacy: "Privacy", terms: "Terms" },
    operability: { loading: "Loading…", saving: "Saving…", requestFailed: "The action could not be completed. Please try again.", noData: "There is no data to display yet.", unavailable: "This feature is not available yet." },
    dashboard: { eyebrow: "Dashboard", title: "Your learning progress", xp: "XP", streak: "Streak", activities: "Activities", days: "days", skillActivity: "Skill activity", emptyTitle: "No learning activity yet", emptyText: "Complete a practice activity or review a vocabulary card to start tracking your progress." },
    home: {"eyebrow": "Free · Made for Vietnamese learners", "title": "A clear English-learning path, made for you.", "description": "Take a 20-question placement test, get an A1–C2 path at your level, then practise all four skills, vocabulary and TOEIC or IELTS exams. Completely free.", "startPlan": "Get started", "todayPlan": "Continue learning", "viewPath": "View the path", "trust": ["No ads", "No sign-up needed to start", "Vietnamese and English interface"], "previewLesson": "Lesson", "previewWord": "Flashcard", "previewQuestion": "Practice question", "minutes": "min", "stats": {"lessons": "lessons on the path", "words": "words with IPA and Vietnamese meanings", "examQuestions": "TOEIC and IELTS practice questions", "topics": "speaking and writing topics"}, "stepsEyebrow": "How it works", "stepsTitle": "Get started in three steps", "steps": [{"title": "Take the placement test", "text": "20 questions on Grammar, Vocabulary, Reading and Listening that adapt to your answers. About 10 minutes."}, {"title": "Follow your path", "text": "Each level is split into topics. Continue always takes you to the next lesson."}, {"title": "Review and practise exams", "text": "Review words just before you forget them, re-practise mistakes and try TOEIC or IELTS when you are ready."}], "featuresEyebrow": "What's inside", "featuresTitle": "Everything you need to study every day", "features": {"path": {"title": "A1–C2 path", "text": "Grammar, Listening, Reading, Speaking and Writing lessons grouped by topic."}, "listenRead": {"title": "Listening and Reading", "text": "Recorded conversations and texts for every level, with questions."}, "speakWrite": {"title": "Speaking and Writing", "text": "Record yourself, write on a topic with sentence frames and get AI feedback."}, "vocab": {"title": "Vocabulary and pronunciation", "text": "Spaced-repetition flashcards, the IPA chart and minimal pairs."}, "exams": {"title": "TOEIC and IELTS practice", "text": "Part practice, mini tests and a 200-question TOEIC mock test."}, "mistakes": {"title": "Mistake notebook and tutor", "text": "Wrong answers are saved to practise again; the AI tutor explains each one."}}, "ctaTitle": "About 10 minutes to find your level", "ctaText": "Take the placement test and get your own learning path today.", "ctaReturningTitle": "Continue your path", "ctaReturningText": "Your next lesson is ready in Today.", "progressEyebrow": "Learning progress", "progressTitle": "Your learning progress", "viewDetail": "View details", "vocabularyLearned": "Vocabulary learned", "dayStreak": "Day streak", "streakNote": "*A new streak starts at midnight, Vietnam time", "heatmapTitle": "Activity in the last 20 weeks", "few": "Less", "many": "More", "activeDays": "active days"},
    learning: { eyebrow: "CEFR pathway", title: "Build English one small step at a time", description: "Choose your level, finish short lessons, then review vocabulary at the right time.", continue: "Continue learning", units: "units", lessons: "lessons", minutes: "min", startLesson: "Start lesson", lessonComplete: "Completed", lessonProgress: "Lesson progress", vocabularyTitle: "CEFR vocabulary", vocabularyDescription: "Vocabulary by CEFR level; each word comes back for review just before you are likely to forget it.", reviewNow: "Review now", noCards: "You have reviewed every due word at this level.", saveFailed: "Your review was not saved. Please try again.", dueSummary: "{due} due for review · {new} new · {later} scheduled for later", again: "Again", hard: "Hard", good: "Good", easy: "Easy", nextCard: "Next card", reviewed: "Reviewed", source: "Data source" }
    , pronunciation: { eyebrow: "Pronunciation", title: "Listen closely, speak clearly, practise often.", description: "Master IPA sounds, distinguish minimal pairs, and practise shadowing with your own recording.", ipa: "IPA chart", minimalPairs: "Minimal pairs", shadowing: "Shadowing", record: "Start recording", stop: "Stop recording", recording: "Recording", playback: "Play your recording", targetPlayback: "Play target sentence", unsupported: "Your browser does not support audio recording.", permissionDenied: "Microphone access was unavailable. Allow it and try again.", ready: "Ready to practise", retry: "Record again", transcript: "Speech transcript", analysisPending: "Play the target, record yourself, then listen back to compare rhythm, stress and the focus sounds.", target: "Target sentence", tip: "Practice tip" }
    , ielts: { eyebrow: "IELTS Academic", title: "Practise IELTS by skill and scoring criterion.", description: "Practise Listening, Reading, Writing and Speaking in the format of the real test.", writing: "Writing", speaking: "Speaking", writingTitle: "IELTS Writing", writingDescription: "Choose a Task 1 (describe a figure, 150 words) or Task 2 (essay, 250 words) prompt. Save drafts at any time; when you submit, you receive feedback on the four assessment criteria (not an official band).", writingPrompt: "Some people believe that technology makes people less social. To what extent do you agree or disagree?", speakingTitle: "IELTS Speaking", speakingDescription: "Choose a set with Part 1 questions, a Part 2 cue card and Part 3 discussion questions. Push to talk; you receive a transcript and feedback to practise again (not an official band).", speakingPrompt: "Tell me about a skill you would like to learn." }
    , onboarding: { eyebrow: "Get started", title: "Let's set up your path", description: "A few short questions so we can suggest exactly what to do each day.", goalStep: "What is your goal?", goalCommunication: "Everyday communication", goalToeic: "TOEIC preparation", goalIelts: "IELTS preparation", minutesStep: "How many minutes do you want to study each day?", minutes: "min/day", levelStep: "What is your current level?", levelSelfHint: "Choose the level you think you have and finish, or take the placement test: it starts at the level you choose (B1 by default).", takePlacement: "Take the placement test", useSelfLevel: "Use this level", placementTitle: "Placement test", placementIntro: "About 20 questions on Grammar, Vocabulary, Reading and Listening. The difficulty adapts to your answers, so just pick the answer you think is best; there is no need to guess.", placementProgress: "Question {current}/{total}", placementStarting: "Preparing the test…", placementError: "Could not load the question. Please try again.", listen: "Listen", listenHint: "Listen to the recording, then answer the question.", quit: "Leave the test", skills: { GRAMMAR: "Grammar", VOCABULARY: "Vocabulary", READING: "Reading", LISTENING: "Listening", SPEAKING: "Speaking", WRITING: "Writing" }, selfTitle: "Speaking and Writing: self-assessment", selfIntro: "These two skills cannot be scored automatically yet. Choose the statement that best describes what you can do now.", seeResult: "See my result", back: "Back", next: "Continue", finish: "Finish", submitting: "Saving…", resultLevel: "Suggested level", resultBySkill: "Level by skill", resultScore: "{correct}/{total} questions correct", resultSelfNote: "Speaking and Writing are self-assessed", startLearning: "Start learning", errorSave: "Could not save. Please try again." }
    , today: {"eyebrow": "Today", "title": "Today", "greeting": "What to do today, based on your path and goal.", "continueLabel": "Continue", "continueHint": "Next lesson on your path", "allDone": "You've finished every lesson on the path. Review vocabulary, practise your mistakes or try an exam.", "openPath": "View path", "minutesTitle": "Today's goal", "minutesProgress": "{done}/{goal} min", "minutesDone": "You reached today's goal!", "minutesNote": "Estimated from what you did today.", "vocabularyTitle": "Vocabulary due", "vocabularyDue": "{count} words to review today", "vocabularyNone": "Nothing due. Learn some new words.", "reviewNow": "Review now", "learnVocabulary": "Learn new words", "mistakesTitle": "Mistake notebook", "mistakesDue": "{count} questions to re-practise", "mistakesNone": "No mistakes to practise. Great work!", "practiceMistakes": "Practise", "weakTitle": "Skill to practise", "weakText": "Your placement test puts your {skill} at {level}, your lowest skill.", "weakAction": "Practise {skill}", "weakNone": "Take the placement test to find out which skill needs more practice.", "takePlacement": "Take the placement test", "examTitle": "Exam practice", "practiceExam": "Practise", "allExams": "All exams", "levelLabel": "Level", "goalLabel": "Goal", "goalCommunication": "Communication", "goalToeic": "TOEIC", "goalIelts": "IELTS", "profileLink": "Learning profile", "emptyTitle": "You haven't set up a path yet", "emptyText": "Answer a few quick questions and take the placement test to get daily suggestions.", "setup": "Get started"}
    , mistakes: { eyebrow: "Review", title: "Mistake notebook", description: "Questions you got wrong in lessons and exams, gathered so you can practise them until they stick.", emptyTitle: "No mistakes yet", emptyText: "When you miss a question in a lesson or exam, it will appear here to practise again.", allSkills: "All", grammarOnly: "Grammar", count: "{count} to practise", timesWrong: "Missed {count} times", sourceLesson: "Lesson", sourceExam: "Exam", practice: "Practise", check: "Check", next: "Next question", correct: "Correct! Removed from your notebook.", incorrect: "Not correct.", correctAnswer: "Correct answer", finished: "You've practised every mistake. Head back to see what remains.", backToList: "Back to list" }
    , wordbook: { add: "Add to wordbook", added: "Added", adding: "Adding…", already: "Already saved", lessonTitle: "New words in this lesson", lessonDescription: "Save the words you want to remember. They join your next vocabulary review.", review: "Review my wordbook", dueDeck: "Due for review", dueDeckSummary: "{due} words in your wordbook are due for review", dueDeckEmpty: "No words are due yet. Save words to your wordbook while you study, or choose a level to learn new words." }
    , review: { modeLabel: "Review mode", recognition: "Recognition", typing: "Type it", dictation: "Listen & write", show: "Show meaning", typePrompt: "Type the English word", listenPrompt: "Listen, then type the word", play: "Play again", check: "Check", correctIs: "Answer", correct: "Correct", incorrect: "Not correct" }
    , aiTutor: { ask: "Ask AI Tutor", thinking: "Thinking…", next: "Next", you: "You", tutor: "Tutor", send: "Send", followUpPlaceholder: "Ask a follow-up about this question", aiFeedback: "AI practice feedback", officialExplanation: "Official explanation", unavailable: "Tutor service unavailable" }
    , assistant: { title: "AI Tutor", open: "Open AI Tutor", close: "Close", welcome: "Hi {name}! I'm the AI tutor. Welcome to English 4 Free. How can i help you ?", placeholder: "Just ask me ...", send: "Send", thinking: "Replying…", unavailable: "The tutor is taking a break — please try again soon.", rateLimited: "That's a lot of questions fast — take a short break and try again.", friend: "there" }
    , pathPage: {"eyebrow": "Path", "title": "Learning path", "description": "Each level has topics with Grammar, Listening, Reading, Speaking and Writing lessons. Take any lesson you like; Continue always takes you to the next one.", "yourLevel": "Your level", "progress": "{done}/{total} lessons done", "continue": "Continue", "levelDone": "You've finished this level. Well done!", "statusDone": "Done", "statusCurrent": "Up next", "statusTodo": "Not started", "vocabularyTitle": "{level} vocabulary", "vocabularyText": "Learn and review {level} words with flashcards alongside the lessons.", "vocabularyAction": "Open vocabulary", "empty": "There are no lessons at this level yet."}
    , practice: {"eyebrow": "Practice", "title": "Practise by skill", "description": "Pick a skill to practise on its own, alongside your path.", "suggested": "Suggested", "items": {"LISTENING": "Conversations and talks by level, A1–C2.", "READING": "Texts by level with comprehension questions.", "SPEAKING": "Speak on a topic, record yourself and get feedback.", "WRITING": "Write on a topic with sentence frames and feedback.", "VOCABULARY": "Flashcards and your word book, with spaced review.", "GRAMMAR": "Grammar topics from A1 to C2.", "PRONUNCIATION": "IPA chart, minimal pairs and shadowing.", "MISTAKES": "Re-practise the questions you got wrong."}}
    , examPrep: {"eyebrow": "Exam prep", "title": "TOEIC and IELTS practice", "description": "Practise individual parts, take mini tests or a full mock test. Answers save automatically, so you can stop and continue at any time.", "history": "Exam history", "toeicText": "Listening and Reading, Parts 1–7, scored 10–990.", "ieltsText": "Listening, Reading, Writing and Speaking, band 0–9.", "writingSpeaking": "IELTS Writing and Speaking practice", "empty": "No exams have been published yet."}
    , account: {"menu": "Account", "guest": "Guest", "progress": "Progress", "profile": "Learning profile", "guestNote": "Your progress is saved in this browser. Log in to keep it."}
    , profilePage: {"eyebrow": "Account", "title": "Learning profile", "levelTitle": "Current level", "fromPlacement": "From the placement test ({score}/{total} correct)", "fromSelf": "Chosen by you", "skillsTitle": "Level by skill", "skillsNone": "Take the placement test to see your level in each skill.", "retake": "Retake the placement test", "planTitle": "Goal and study time", "goal": "Goal", "minutes": "Minutes per day", "save": "Save changes", "saving": "Saving…", "saved": "Saved.", "saveFailed": "Could not save. Please try again.", "emptyTitle": "You don't have a learning profile yet", "emptyText": "Finish the setup to get your own profile and path.", "setup": "Get started"}
  }
} as const;

export type Messages = (typeof messages)[Locale];

export function isLocale(value: string | undefined): value is Locale {
  return Boolean(value && locales.includes(value as Locale));
}

export async function getLocale(): Promise<Locale> {
  const value = (await cookies()).get(localeCookieName)?.value;
  return isLocale(value) ? value : "vi";
}

export function getMessages(locale: Locale): Messages {
  return messages[locale];
}
