import { cookies } from "next/headers";

export const locales = ["vi", "en"] as const;
export type Locale = (typeof locales)[number];
export const localeCookieName = "e4f-locale";

const messages = {
  vi: {
    brandTagline: "Học tiếng Anh miễn phí, có lộ trình.",
    nav: { learn: "Học", skills: "Kỹ năng", toeic: "TOEIC", ielts: "IELTS", vocabulary: "Từ vựng", grammar: "Ngữ pháp", pronunciation: "Phát âm", today: "Hôm nay", mistakes: "Sổ lỗi sai" },
    common: { login: "Đăng nhập", logout: "Đăng xuất", signedIn: "Đã đăng nhập", dashboard: "Tiến độ", start: "Bắt đầu học", menu: "Mở menu", close: "Đóng menu", language: "Ngôn ngữ", explore: "Khám phá", skipContent: "Bỏ qua đến nội dung", primaryNavigation: "Điều hướng chính", mobileNavigation: "Điều hướng di động", about: "Giới thiệu", privacy: "Quyền riêng tư" },
    operability: { loading: "Đang tải…", saving: "Đang lưu…", requestFailed: "Thao tác chưa hoàn tất. Hãy thử lại.", noData: "Chưa có dữ liệu để hiển thị.", unavailable: "Tính năng này hiện chưa sẵn sàng." },
    toeicPractice: { loading: "Đang chuẩn bị bài luyện TOEIC Part 5…", startFailed: "Không thể bắt đầu bài luyện.", saveFailed: "Không thể tự động lưu đáp án. Hãy thử lại.", submitFailed: "Không thể nộp bài. Hãy thử lại.", label: "TOEIC · Luyện tập", answered: "Đã trả lời", saving: "Đang lưu", saved: "Đã tự động lưu", question: "Câu", correct: "Đúng.", incorrect: "Chưa đúng.", result: "Kết quả", review: "Hãy xem giải thích bên dưới từng câu để ôn lại.", submit: "Nộp bài" },
    dashboard: { eyebrow: "Tiến độ", title: "Tiến độ học của bạn", xp: "XP", streak: "Chuỗi ngày", activities: "Hoạt động", days: "ngày", skillActivity: "Hoạt động theo kỹ năng", emptyTitle: "Chưa có hoạt động học", emptyText: "Hãy hoàn thành một bài luyện hoặc ôn một thẻ từ để bắt đầu theo dõi tiến độ." },
    home: {
      eyebrow: "English 4 Free", title: "Một lộ trình tiếng Anh rõ ràng, dành cho bạn.",
      description: "Học từ A1 đến C2, luyện TOEIC và IELTS, phát triển đủ bốn kỹ năng — hoàn toàn miễn phí.",
      secondary: "Luyện thi TOEIC & IELTS", levelsTitle: "Học đúng trình độ hiện tại", levelsDescription: "Các bài học ngắn, thực hành đều đặn và tiến độ dễ theo dõi.",
      skillsTitle: "Bốn kỹ năng, một hành trình", skillsDescription: "Nghe, nói, đọc và viết kết nối trong từng bài học thay vì học rời rạc.",
      examTitle: "Luyện thi có chiến lược", examDescription: "Luyện từng Part TOEIC, làm mini test và thi thử — nhận kết quả ngay và xem lời giải cho từng câu.", examAction: "Luyện TOEIC", vocabularyDescription: "Học từ theo trình độ CEFR và ôn lại đúng lúc sắp quên với thẻ ghi nhớ.",
      current: "Đang có", free: "Miễn phí", level: "Trình độ",
      progressEyebrow: "Tiến độ", progressTitle: "Tiến độ học của bạn", viewDetail: "Xem chi tiết",
      vocabularyLearned: "Từ vựng đã học", dayStreak: "Chuỗi ngày học", streakNote: "*Chuỗi ngày mới bắt đầu lúc 0h giờ Việt Nam",
      heatmapTitle: "Hoạt động 20 tuần gần đây", few: "Ít", many: "Nhiều", activeDays: "ngày học",
      startPlan: "Thiết lập lộ trình", todayPlan: "Hôm nay học gì"
    },
    learning: { eyebrow: "Lộ trình CEFR", title: "Học tiếng Anh theo từng bước nhỏ", description: "Chọn trình độ, hoàn thành bài học ngắn, rồi ôn từ vựng đúng thời điểm.", continue: "Tiếp tục học", units: "chủ đề", lessons: "bài học", minutes: "phút", startLesson: "Bắt đầu bài học", lessonComplete: "Đã hoàn thành", lessonProgress: "Tiến độ bài học", vocabularyTitle: "Từ vựng CEFR", vocabularyDescription: "Từ vựng theo trình độ CEFR; mỗi từ được hẹn ôn lại đúng lúc bạn sắp quên.", reviewNow: "Ôn ngay", noCards: "Bạn đã ôn hết các từ đến hạn ở trình độ này.", saveFailed: "Chưa lưu được kết quả ôn. Hãy thử lại.", dueSummary: "{due} từ đến hạn ôn · {new} từ mới · {later} từ sẽ quay lại sau", again: "Chưa nhớ", hard: "Khó", good: "Tốt", easy: "Dễ", nextCard: "Thẻ tiếp theo", reviewed: "Đã ôn", source: "Nguồn dữ liệu" }
    , pronunciation: { eyebrow: "Phát âm", title: "Nghe kỹ, nói rõ, luyện đều.", description: "Làm chủ từng âm IPA, phân biệt minimal pairs và luyện shadowing với bản ghi âm của chính bạn.", ipa: "Bảng IPA", minimalPairs: "Cặp âm dễ nhầm", shadowing: "Shadowing", record: "Bắt đầu ghi âm", stop: "Dừng ghi âm", recording: "Đang ghi âm", playback: "Nghe lại bản ghi", targetPlayback: "Nghe câu mẫu", unsupported: "Trình duyệt này không hỗ trợ ghi âm.", permissionDenied: "Không thể truy cập microphone. Hãy cấp quyền rồi thử lại.", ready: "Sẵn sàng để luyện", retry: "Ghi âm lại", transcript: "Bản ghi lời nói", analysisPending: "Nghe câu mẫu, ghi âm rồi nghe lại để tự so sánh nhịp, trọng âm và các âm cần chú ý.", target: "Câu mẫu", tip: "Mẹo luyện tập" }
    , ielts: { eyebrow: "IELTS Academic", title: "Luyện IELTS theo đúng kỹ năng và tiêu chí chấm.", description: "Luyện đủ bốn kỹ năng Listening, Reading, Writing và Speaking theo đúng dạng đề thi.", writing: "Writing", speaking: "Speaking", writingTitle: "IELTS Writing", writingDescription: "Chọn một đề Task 1 (mô tả biểu đồ, 150 từ) hoặc Task 2 (bài luận, 250 từ). Lưu nháp bất cứ lúc nào; khi nộp, bạn nhận nhận xét theo bốn tiêu chí chấm (không phải band chính thức).", writingPrompt: "Some people believe that technology makes people less social. To what extent do you agree or disagree?", speakingTitle: "IELTS Speaking", speakingDescription: "Chọn một bộ đề gồm Part 1, cue card Part 2 và câu hỏi thảo luận Part 3. Nhấn để nói; bạn sẽ nhận bản chép lời và nhận xét để luyện tiếp (không phải band chính thức).", speakingPrompt: "Tell me about a skill you would like to learn." }
    , onboarding: { eyebrow: "Bắt đầu", title: "Cùng thiết lập lộ trình của bạn", description: "Vài câu hỏi ngắn để chúng tôi gợi ý đúng việc cần làm mỗi ngày.", goalStep: "Mục tiêu của bạn là gì?", goalCommunication: "Giao tiếp hằng ngày", goalToeic: "Luyện thi TOEIC", goalIelts: "Luyện thi IELTS", levelStep: "Trình độ hiện tại của bạn?", levelSelfHint: "Tự chọn trình độ, hoặc làm bài kiểm tra ngắn để chúng tôi đề xuất.", takePlacement: "Làm bài kiểm tra xếp lớp", skipPlacement: "Tôi tự chọn trình độ", minutesStep: "Bạn muốn học bao nhiêu phút mỗi ngày?", minutes: "phút/ngày", placementTitle: "Bài kiểm tra xếp lớp", placementIntro: "18 câu, độ khó tăng dần. Chọn đáp án đúng nhất.", placementProgress: "Câu {current}/{total}", back: "Quay lại", next: "Tiếp tục", finish: "Hoàn tất", submitting: "Đang lưu…", resultLevel: "Trình độ đề xuất", startLearning: "Bắt đầu học", errorSave: "Chưa lưu được. Hãy thử lại." }
    , today: { eyebrow: "Hôm nay", title: "Hôm nay học gì", greeting: "Đây là gợi ý cho hôm nay.", nextLessonTitle: "Bài học tiếp theo", noLesson: "Bạn đã hoàn thành mọi bài học ở trình độ này.", startLesson: "Vào học", vocabularyTitle: "Từ vựng đến hạn ôn", vocabularyDue: "{count} từ cần ôn hôm nay", vocabularyNone: "Không có từ nào đến hạn. Hãy học thêm từ mới.", reviewNow: "Ôn ngay", learnVocabulary: "Học từ mới", examTitle: "Luyện thi", goalMinutes: "Mục tiêu: {minutes} phút hôm nay", levelLabel: "Trình độ", goalLabel: "Mục tiêu", practiceExam: "Luyện đề", redo: "Cập nhật lộ trình", goalCommunication: "Giao tiếp", goalToeic: "TOEIC", goalIelts: "IELTS", emptyTitle: "Bạn chưa thiết lập lộ trình", emptyText: "Trả lời vài câu hỏi ngắn để nhận gợi ý học mỗi ngày.", setup: "Thiết lập lộ trình", mistakesTitle: "Sổ lỗi sai", mistakesDue: "{count} câu cần luyện lại", mistakesNone: "Không có lỗi nào cần luyện. Làm tốt lắm!", practiceMistakes: "Luyện lại" }
    , mistakes: { eyebrow: "Ôn tập", title: "Sổ lỗi sai", description: "Những câu bạn từng làm sai trong bài học và đề thi, gom lại để luyện cho đến khi thành thạo.", emptyTitle: "Chưa có lỗi nào", emptyText: "Khi bạn làm sai một câu trong bài học hoặc đề thi, câu đó sẽ xuất hiện ở đây để luyện lại.", allSkills: "Tất cả", grammarOnly: "Ngữ pháp", count: "{count} câu cần luyện", timesWrong: "Sai {count} lần", sourceLesson: "Bài học", sourceExam: "Đề thi", practice: "Luyện lại", check: "Kiểm tra", next: "Câu tiếp theo", correct: "Chính xác! Đã xoá khỏi sổ lỗi.", incorrect: "Chưa đúng.", correctAnswer: "Đáp án đúng", finished: "Đã luyện xong các câu sai. Quay lại sổ để xem còn câu nào.", backToList: "Về danh sách" }
    , wordbook: { add: "Thêm vào sổ từ", added: "Đã thêm", adding: "Đang thêm…", already: "Đã có trong sổ" }
    , review: { modeLabel: "Kiểu ôn", recognition: "Nhận diện", typing: "Gõ lại", dictation: "Nghe & viết", show: "Xem nghĩa", typePrompt: "Gõ từ tiếng Anh", listenPrompt: "Nghe rồi gõ lại từ", play: "Nghe lại", check: "Kiểm tra", correctIs: "Đáp án", correct: "Chính xác", incorrect: "Chưa đúng" }
    , aiTutor: { ask: "Hỏi trợ giảng AI", thinking: "Đang nghĩ…", next: "Tiếp theo", you: "Bạn", tutor: "Trợ giảng", send: "Gửi", followUpPlaceholder: "Hỏi thêm về câu này", aiFeedback: "Nhận xét luyện tập từ AI", officialExplanation: "Lời giải chính thức", unavailable: "Trợ giảng tạm thời không khả dụng." }
    , assistant: { title: "Trợ giảng AI", open: "Mở trợ giảng AI", close: "Đóng", welcome: "Xin chào {name}! Mình là trợ giảng AI của English 4 Free. Hỏi mình một câu tiếng Anh hoặc cách dùng web nhé.", placeholder: "Hỏi về tiếng Anh hoặc website…", send: "Gửi", thinking: "Đang trả lời…", unavailable: "Trợ giảng tạm nghỉ, bạn thử lại sau nhé.", rateLimited: "Bạn hỏi hơi nhanh — nghỉ một chút rồi hỏi tiếp nhé.", friend: "bạn" }
  },
  en: {
    brandTagline: "Free English learning, with a clear path.",
    nav: { learn: "Learn", skills: "Skills", toeic: "TOEIC", ielts: "IELTS", vocabulary: "Vocabulary", grammar: "Grammar", pronunciation: "Pronunciation", today: "Today", mistakes: "Mistakes" },
    common: { login: "Log in", logout: "Log out", signedIn: "Signed in", dashboard: "Progress", start: "Start learning", menu: "Open menu", close: "Close menu", language: "Language", explore: "Explore", skipContent: "Skip to content", primaryNavigation: "Primary navigation", mobileNavigation: "Mobile navigation", about: "About", privacy: "Privacy" },
    operability: { loading: "Loading…", saving: "Saving…", requestFailed: "The action could not be completed. Please try again.", noData: "There is no data to display yet.", unavailable: "This feature is not available yet." },
    toeicPractice: { loading: "Preparing TOEIC Part 5 practice…", startFailed: "Could not start the practice.", saveFailed: "Could not save your answer automatically. Please try again.", submitFailed: "Could not submit your answers. Please try again.", label: "TOEIC · Practice", answered: "Answered", saving: "Saving", saved: "Saved automatically", question: "Question", correct: "Correct.", incorrect: "Not correct.", result: "Result", review: "Review the explanation under each question.", submit: "Submit" },
    dashboard: { eyebrow: "Dashboard", title: "Your learning progress", xp: "XP", streak: "Streak", activities: "Activities", days: "days", skillActivity: "Skill activity", emptyTitle: "No learning activity yet", emptyText: "Complete a practice activity or review a vocabulary card to start tracking your progress." },
    home: {
      eyebrow: "English 4 Free", title: "A clear English-learning path, made for you.",
      description: "Learn from A1 to C2, practise TOEIC and IELTS, and develop all four skills — completely free.",
      secondary: "Practise TOEIC & IELTS", levelsTitle: "Learn at the right level", levelsDescription: "Short lessons, steady practice, and progress that is easy to follow.",
      skillsTitle: "Four skills, one journey", skillsDescription: "Listening, speaking, reading and writing belong together in every lesson.",
      examTitle: "Practise exams with purpose", examDescription: "Practise TOEIC parts, mini tests and mock tests — get your result instantly and review every explanation.", examAction: "TOEIC practice", vocabularyDescription: "Learn words by CEFR level and review them with flashcards just before you forget.",
      current: "Available now", free: "Free", level: "Level",
      progressEyebrow: "Learning progress", progressTitle: "Your learning progress", viewDetail: "View details",
      vocabularyLearned: "Vocabulary learned", dayStreak: "Day streak", streakNote: "*A new streak starts at midnight, Vietnam time",
      heatmapTitle: "Activity in the last 20 weeks", few: "Less", many: "More", activeDays: "active days",
      startPlan: "Set up your path", todayPlan: "What to learn today"
    },
    learning: { eyebrow: "CEFR pathway", title: "Build English one small step at a time", description: "Choose your level, finish short lessons, then review vocabulary at the right time.", continue: "Continue learning", units: "units", lessons: "lessons", minutes: "min", startLesson: "Start lesson", lessonComplete: "Completed", lessonProgress: "Lesson progress", vocabularyTitle: "CEFR vocabulary", vocabularyDescription: "Vocabulary by CEFR level; each word comes back for review just before you are likely to forget it.", reviewNow: "Review now", noCards: "You have reviewed every due word at this level.", saveFailed: "Your review was not saved. Please try again.", dueSummary: "{due} due for review · {new} new · {later} scheduled for later", again: "Again", hard: "Hard", good: "Good", easy: "Easy", nextCard: "Next card", reviewed: "Reviewed", source: "Data source" }
    , pronunciation: { eyebrow: "Pronunciation", title: "Listen closely, speak clearly, practise often.", description: "Master IPA sounds, distinguish minimal pairs, and practise shadowing with your own recording.", ipa: "IPA chart", minimalPairs: "Minimal pairs", shadowing: "Shadowing", record: "Start recording", stop: "Stop recording", recording: "Recording", playback: "Play your recording", targetPlayback: "Play target sentence", unsupported: "Your browser does not support audio recording.", permissionDenied: "Microphone access was unavailable. Allow it and try again.", ready: "Ready to practise", retry: "Record again", transcript: "Speech transcript", analysisPending: "Play the target, record yourself, then listen back to compare rhythm, stress and the focus sounds.", target: "Target sentence", tip: "Practice tip" }
    , ielts: { eyebrow: "IELTS Academic", title: "Practise IELTS by skill and scoring criterion.", description: "Practise Listening, Reading, Writing and Speaking in the format of the real test.", writing: "Writing", speaking: "Speaking", writingTitle: "IELTS Writing", writingDescription: "Choose a Task 1 (describe a figure, 150 words) or Task 2 (essay, 250 words) prompt. Save drafts at any time; when you submit, you receive feedback on the four assessment criteria (not an official band).", writingPrompt: "Some people believe that technology makes people less social. To what extent do you agree or disagree?", speakingTitle: "IELTS Speaking", speakingDescription: "Choose a set with Part 1 questions, a Part 2 cue card and Part 3 discussion questions. Push to talk; you receive a transcript and feedback to practise again (not an official band).", speakingPrompt: "Tell me about a skill you would like to learn." }
    , onboarding: { eyebrow: "Get started", title: "Let's set up your path", description: "A few short questions so we can suggest exactly what to do each day.", goalStep: "What is your goal?", goalCommunication: "Everyday communication", goalToeic: "TOEIC preparation", goalIelts: "IELTS preparation", levelStep: "What is your current level?", levelSelfHint: "Choose your level, or take a short test and we'll suggest one.", takePlacement: "Take the placement test", skipPlacement: "I'll choose my level", minutesStep: "How many minutes do you want to study each day?", minutes: "min/day", placementTitle: "Placement test", placementIntro: "18 questions, increasing difficulty. Choose the best answer.", placementProgress: "Question {current}/{total}", back: "Back", next: "Continue", finish: "Finish", submitting: "Saving…", resultLevel: "Suggested level", startLearning: "Start learning", errorSave: "Could not save. Please try again." }
    , today: { eyebrow: "Today", title: "What to learn today", greeting: "Here's your plan for today.", nextLessonTitle: "Next lesson", noLesson: "You've completed every lesson at this level.", startLesson: "Start", vocabularyTitle: "Vocabulary due", vocabularyDue: "{count} words to review today", vocabularyNone: "Nothing due. Learn some new words.", reviewNow: "Review now", learnVocabulary: "Learn new words", examTitle: "Exam practice", goalMinutes: "Goal: {minutes} minutes today", levelLabel: "Level", goalLabel: "Goal", practiceExam: "Practise", redo: "Update path", goalCommunication: "Communication", goalToeic: "TOEIC", goalIelts: "IELTS", emptyTitle: "You haven't set up a path yet", emptyText: "Answer a few quick questions to get daily suggestions.", setup: "Set up my path", mistakesTitle: "Mistake notebook", mistakesDue: "{count} questions to re-practise", mistakesNone: "No mistakes to practise. Great work!", practiceMistakes: "Practise" }
    , mistakes: { eyebrow: "Review", title: "Mistake notebook", description: "Questions you got wrong in lessons and exams, gathered so you can practise them until they stick.", emptyTitle: "No mistakes yet", emptyText: "When you miss a question in a lesson or exam, it will appear here to practise again.", allSkills: "All", grammarOnly: "Grammar", count: "{count} to practise", timesWrong: "Missed {count} times", sourceLesson: "Lesson", sourceExam: "Exam", practice: "Practise", check: "Check", next: "Next question", correct: "Correct! Removed from your notebook.", incorrect: "Not correct.", correctAnswer: "Correct answer", finished: "You've practised every mistake. Head back to see what remains.", backToList: "Back to list" }
    , wordbook: { add: "Add to wordbook", added: "Added", adding: "Adding…", already: "Already saved" }
    , review: { modeLabel: "Review mode", recognition: "Recognition", typing: "Type it", dictation: "Listen & write", show: "Show meaning", typePrompt: "Type the English word", listenPrompt: "Listen, then type the word", play: "Play again", check: "Check", correctIs: "Answer", correct: "Correct", incorrect: "Not correct" }
    , aiTutor: { ask: "Ask AI Tutor", thinking: "Thinking…", next: "Next", you: "You", tutor: "Tutor", send: "Send", followUpPlaceholder: "Ask a follow-up about this question", aiFeedback: "AI practice feedback", officialExplanation: "Official explanation", unavailable: "Tutor service unavailable" }
    , assistant: { title: "AI Tutor", open: "Open AI Tutor", close: "Close", welcome: "Hi {name}! I'm the AI tutor. Welcome to English 4 Free. How can i help you ?", placeholder: "Just ask me ...", send: "Send", thinking: "Replying…", unavailable: "The tutor is taking a break — please try again soon.", rateLimited: "That's a lot of questions fast — take a short break and try again.", friend: "there" }
  }
} as const;

export type Messages = (typeof messages)[Locale];

export function isLocale(value: string | undefined): value is Locale {
  return Boolean(value && locales.includes(value as Locale));
}

export async function getLocale(): Promise<Locale> {
  const value = (await cookies()).get(localeCookieName)?.value;
  return isLocale(value) ? value : "vi";
}

export function getMessages(locale: Locale): Messages {
  return messages[locale];
}
