import type { Locale } from "./i18n";

export type WritingTopic = { id: string; title: string; prompt: string; suggestions: string[]; advanced: string[] };
export type WritingCategory = { id: string; title: string; note: string; topics: WritingTopic[] };

type Text = { vi: string; en: string };
type TopicSource = { id: string; title: Text; prompt: Text; suggestions: string[]; advanced: string[] };
type CategorySource = { id: string; title: Text; words: string; topics: TopicSource[] };

const t = (id: string, vi: string, en: string, promptVi: string, promptEn: string, suggestions: string[], advanced: string[]): TopicSource => ({ id, title: { vi, en }, prompt: { vi: promptVi, en: promptEn }, suggestions, advanced });

/**
 * Free-writing topics grouped by text type, each group with a suggested length. Topic
 * ids are stored as the submission promptId (`free-write:<id>`), so keep them stable —
 * renaming one detaches its saved drafts. Sentence frames are English and shared by
 * both interface languages: four basic ones and two more advanced (B2–C1) ones.
 */
const categories: CategorySource[] = [
  { id: "messages", title: { vi: "Tin nhắn & email thân mật", en: "Messages & informal emails" }, words: "60–100", topics: [
    t("invite-friend", "Mời bạn đi chơi", "Invite a friend", "Viết email mời một người bạn tham gia một sự kiện cuối tuần.", "Write an email inviting a friend to an event this weekend.", ["Hi ___, are you free on ___?", "There's a ___ at ___ and I thought of you.", "We could meet at ___ at ___.", "Let me know by ___ if you can come!"], ["I've been meaning to ask you for ages — would you fancy ___?", "No pressure if you're busy, but it would be great to catch up."]),
    t("thank-you-note", "Lời cảm ơn", "A thank-you note", "Viết thư cảm ơn ai đó đã tặng quà hoặc giúp đỡ bạn.", "Write a note thanking someone for a gift or for their help.", ["Thank you so much for ___.", "It was really kind of you to ___.", "I've already ___ with it.", "I hope I can return the favour soon."], ["I can't tell you how much it meant to me that you ___.", "Without your help, I'd never have managed to ___."]),
    t("apologise-friend", "Xin lỗi bạn", "Say sorry to a friend", "Viết tin nhắn xin lỗi vì đã lỡ hẹn với bạn.", "Write a message apologising for missing a meeting with a friend.", ["I'm really sorry I didn't ___.", "The reason was that ___.", "I should have ___.", "Can we meet ___ instead?"], ["I completely understand if you were annoyed — I would have been too.", "Let me make it up to you: ___ is on me."]),
    t("share-news", "Kể tin vui", "Share your news", "Viết email kể cho bạn nghe một tin vui gần đây của bạn.", "Write an email telling a friend some good news.", ["Guess what? I've just ___!", "It happened when ___.", "I'm so excited because ___.", "What's new with you?"], ["I still can't quite believe that ___.", "It's been a long road, but all the effort finally paid off."]),
    t("ask-for-advice", "Xin lời khuyên", "Ask for advice", "Viết email hỏi một người bạn xin lời khuyên về một vấn đề của bạn.", "Write to a friend asking for advice about a problem.", ["I need your advice about ___.", "The problem is that ___.", "I'm not sure whether to ___ or ___.", "What would you do if you were me?"], ["I've been going back and forth on this for weeks.", "You always see things more clearly than I do, so ___."]),
    t("decline-invitation", "Từ chối lời mời", "Decline an invitation", "Viết tin nhắn từ chối lịch sự một lời mời và đề nghị hẹn dịp khác.", "Politely decline an invitation and suggest another time.", ["Thanks a lot for inviting me to ___.", "Unfortunately, I can't come because ___.", "I hope you have a great time.", "How about ___ another day?"], ["I'd have loved to come, but I've already committed to ___.", "Please count me in next time — I'd hate to miss another one."])
  ] },
  { id: "formal", title: { vi: "Email & thư trang trọng", en: "Formal emails & letters" }, words: "120–180", topics: [
    t("complaint-email", "Email khiếu nại", "A complaint email", "Viết email khiếu nại về một sản phẩm hoặc dịch vụ không như mong đợi.", "Write an email complaining about a product or service.", ["I am writing to complain about ___.", "On ___, I bought/ordered ___.", "Unfortunately, ___.", "I would like you to ___."], ["I trust you will look into this matter and respond within ___ days.", "Should the problem not be resolved, I will have no choice but to ___."]),
    t("job-application", "Xin việc bán thời gian", "Apply for a part-time job", "Viết email ứng tuyển một công việc bán thời gian.", "Write an email applying for a part-time job.", ["I am writing to apply for the position of ___.", "I have experience in ___.", "I am available ___.", "I look forward to hearing from you."], ["I believe my experience in ___ makes me a strong fit for this role.", "I would welcome the opportunity to discuss how I could contribute to ___."]),
    t("request-information", "Hỏi thông tin khoá học", "Request information", "Viết email hỏi thông tin về một khoá học (thời gian, học phí, trình độ).", "Write an email asking for information about a course.", ["I am interested in your ___ course.", "Could you tell me ___?", "I would also like to know whether ___.", "Thank you in advance for your help."], ["I would be grateful if you could clarify ___.", "Given my current level, I am unsure whether ___ would be suitable."]),
    t("letter-to-editor", "Thư gửi báo địa phương", "Letter to a local newspaper", "Viết thư gửi báo địa phương về một vấn đề ở khu bạn sống.", "Write a letter to a local newspaper about a problem in your area.", ["I am writing to draw attention to ___.", "This has caused ___.", "Many residents feel ___.", "I suggest that ___."], ["It is high time the authorities took action on ___.", "While I appreciate that ___, this cannot justify ___."]),
    t("change-booking", "Đổi lịch đặt chỗ", "Change a booking", "Viết email đề nghị đổi ngày đặt phòng khách sạn.", "Write an email asking to change a hotel booking.", ["I have a booking for ___ from ___ to ___.", "Due to ___, I need to change the dates.", "Would it be possible to ___?", "Please let me know if there is any extra charge."], ["I apologise for any inconvenience this may cause.", "If the new dates are unavailable, I would appreciate it if you could suggest ___."])
  ] },
  { id: "describe", title: { vi: "Miêu tả", en: "Description" }, words: "100–150", topics: [
    t("describe-person", "Một người quan trọng", "An important person", "Miêu tả một người quan trọng với bạn.", "Describe a person who is important to you.", ["The person I want to describe is ___.", "He/She is ___ and ___.", "What I like most about him/her is ___.", "He/She has taught me ___."], ["What strikes you first about him/her is ___.", "It is hard to imagine my life without ___."]),
    t("describe-place", "Một nơi bạn yêu thích", "A place you love", "Miêu tả một nơi bạn yêu thích và cảm giác khi ở đó.", "Describe a place you love and how it makes you feel.", ["My favourite place is ___.", "It is located ___.", "You can see/hear ___.", "I feel ___ when I'm there."], ["There is something almost magical about ___ at dawn.", "Whenever I need to clear my head, I find myself drawn back to ___."]),
    t("describe-object", "Một đồ vật ý nghĩa", "A meaningful object", "Miêu tả một đồ vật có ý nghĩa với bạn.", "Describe an object that means a lot to you.", ["The object I treasure most is ___.", "It is made of ___ and ___.", "I got it ___.", "It is special because ___."], ["It may look ordinary, but it carries memories of ___.", "I would be heartbroken if I ever lost it."]),
    t("describe-festival", "Một lễ hội", "A festival", "Miêu tả một lễ hội hoặc dịp lễ ở nơi bạn sống.", "Describe a festival or celebration where you live.", ["___ is celebrated every year in ___.", "People usually ___.", "The streets are ___.", "My favourite part is ___."], ["The festival is rooted in ___, which explains why ___.", "Beyond the celebrations, it is a time for families to ___."]),
    t("perfect-day", "Một ngày hoàn hảo", "Your perfect day", "Miêu tả một ngày hoàn hảo theo ý bạn.", "Describe your idea of a perfect day.", ["My perfect day would start with ___.", "In the afternoon, I would ___.", "I'd spend the evening ___.", "It would be perfect because ___."], ["Ideally, the day would strike a balance between ___ and ___.", "It wouldn't need to be extravagant — just ___."]),
    t("describe-photo", "Miêu tả một bức ảnh", "Describe a photo", "Chọn một bức ảnh bạn thích và miêu tả chi tiết.", "Choose a photo you like and describe it in detail.", ["In this photo, you can see ___.", "In the foreground, there is ___.", "In the background, ___.", "The photo makes me feel ___."], ["The photographer seems to have captured the moment just as ___.", "What makes the image so striking is the contrast between ___ and ___."])
  ] },
  { id: "stories", title: { vi: "Kể chuyện", en: "Stories" }, words: "120–180", topics: [
    t("unexpected-day", "Một ngày không như dự định", "A day that went wrong", "Kể về một ngày mọi thứ không diễn ra như kế hoạch.", "Write about a day when nothing went to plan.", ["It started as a normal ___.", "Suddenly, ___.", "Then things got worse when ___.", "In the end, ___."], ["Little did I know that the day would end with ___.", "Looking back, I can laugh about it, but at the time ___."]),
    t("got-lost", "Lần bị lạc", "A time you got lost", "Kể về một lần bạn bị lạc đường.", "Write about a time you got lost.", ["I was on my way to ___.", "I took a wrong turn and ___.", "I felt ___.", "Finally, ___ helped me."], ["The more I walked, the more unfamiliar everything became.", "By the time I realised my mistake, ___."]),
    t("first-time", "Lần đầu tiên", "A first time", "Kể về lần đầu tiên bạn làm một việc gì đó.", "Write about the first time you did something.", ["The first time I ___ was ___.", "Before it started, I felt ___.", "The most difficult part was ___.", "Afterwards, I ___."], ["Nothing could have prepared me for ___.", "It turned out to be the first of many ___."]),
    t("helped-stranger", "Giúp một người lạ", "Helping a stranger", "Kể về một lần bạn giúp một người lạ (hoặc được người lạ giúp).", "Write about a time you helped a stranger or a stranger helped you.", ["One day, I saw ___.", "He/She needed ___.", "I decided to ___.", "It made me realise ___."], ["It was only a small gesture, yet it ___.", "I often wonder what became of ___."]),
    t("story-ending", "Truyện với câu kết cho sẵn", "A story with a given ending", "Viết một câu chuyện kết thúc bằng câu: \"...and I never saw it again.\"", "Write a story that ends with: \"...and I never saw it again.\"", ["It all began when ___.", "I noticed ___.", "Without thinking, I ___.", "...and I never saw it again."], ["At first, it seemed like an ordinary ___, but ___.", "To this day, I can't explain how ___."]),
    t("kindness-received", "Một lần được giúp đỡ", "Kindness you received", "Kể về một hành động tử tế bạn từng nhận được.", "Write about an act of kindness you received.", ["I was having a difficult time because ___.", "Then ___ offered to ___.", "I was surprised because ___.", "Since then, I ___."], ["It taught me that kindness often comes from the people you least expect.", "I've tried to pass that kindness on by ___."])
  ] },
  { id: "opinion", title: { vi: "Nêu ý kiến", en: "Opinion essays" }, words: "150–250", topics: [
    t("homework", "Có nên bỏ bài tập về nhà?", "Should homework be banned?", "Học sinh có nên được miễn bài tập về nhà không? Nêu ý kiến của bạn.", "Should homework be banned? Give your opinion.", ["In my opinion, homework should ___.", "Firstly, ___.", "Secondly, ___.", "In conclusion, ___."], ["While homework can reinforce learning, excessive amounts may ___.", "A more balanced approach would be to ___."]),
    t("school-uniforms", "Đồng phục học sinh", "School uniforms", "Học sinh có nên mặc đồng phục không?", "Should students wear school uniforms?", ["I believe that students should/shouldn't ___.", "One reason is that ___.", "Another reason is ___.", "Therefore, ___."], ["Advocates claim uniforms promote equality, yet they may also ___.", "On balance, I am convinced that ___."]),
    t("phones-in-school", "Điện thoại ở trường", "Phones in school", "Có nên cấm điện thoại trong trường học?", "Should mobile phones be banned in schools?", ["Many people think ___.", "However, I feel that ___.", "For example, ___.", "To sum up, ___."], ["A blanket ban seems excessive when phones can also ___.", "Clear rules, rather than prohibition, would ___."]),
    t("online-friends", "Bạn bè trên mạng", "Online friends", "Bạn bè trên mạng có thể là bạn thật sự không?", "Can online friends be real friends?", ["Some people believe ___.", "In my view, ___.", "This is because ___.", "Overall, ___."], ["Friendship depends less on where it began than on ___.", "That said, online friendships may lack ___."]),
    t("fast-fashion", "Thời trang nhanh", "Fast fashion", "Chúng ta có nên mua ít quần áo hơn không?", "Should we buy fewer clothes?", ["Nowadays, people buy ___.", "I think we should ___.", "This would help ___.", "In conclusion, ___."], ["The true cost of cheap clothing is often borne by ___.", "Consumers alone cannot solve the problem unless ___."]),
    t("four-day-week", "Tuần làm việc 4 ngày", "A four-day work week", "Các công ty có nên chuyển sang tuần làm việc 4 ngày?", "Should companies switch to a four-day work week?", ["A four-day week would mean ___.", "The main advantage is ___.", "However, ___.", "I believe that ___."], ["Early trials suggest that productivity ___, although ___.", "Whether it works may depend largely on ___."])
  ] },
  { id: "pros-cons", title: { vi: "Lợi ích & bất lợi", en: "Advantages & disadvantages" }, words: "150–250", topics: [
    t("city-life", "Sống ở thành phố", "Living in a big city", "Nêu lợi ích và bất lợi của việc sống ở thành phố lớn.", "Discuss the advantages and disadvantages of living in a big city.", ["Living in a big city has several advantages.", "For instance, ___.", "On the other hand, ___.", "Overall, ___."], ["The very things that make cities exciting can also make them ___.", "Whether the benefits outweigh the drawbacks depends on ___."]),
    t("studying-abroad", "Du học", "Studying abroad", "Nêu lợi ích và bất lợi của việc du học.", "Discuss the pros and cons of studying abroad.", ["Studying abroad can help students ___.", "Another benefit is ___.", "However, students may face ___.", "In conclusion, ___."], ["Beyond academic benefits, living abroad forces students to ___.", "The financial and emotional costs should not be underestimated."]),
    t("working-from-home", "Làm việc tại nhà", "Working from home", "Nêu ưu và nhược điểm của làm việc tại nhà.", "Discuss the advantages and disadvantages of working from home.", ["Working from home saves ___.", "People can also ___.", "On the downside, ___.", "To conclude, ___."], ["The flexibility comes at a price: the boundary between ___ and ___ blurs.", "A hybrid arrangement may offer the best of both worlds."]),
    t("social-media-teens", "Mạng xã hội với tuổi teen", "Social media for teenagers", "Mạng xã hội mang lại lợi ích và tác hại gì cho thanh thiếu niên?", "What are the benefits and risks of social media for teenagers?", ["Social media allows teenagers to ___.", "It can also ___.", "However, it may lead to ___.", "Therefore, parents should ___."], ["Used thoughtfully, social media can ___; used carelessly, it can ___.", "The key lies not in banning it but in ___."]),
    t("tourism-effects", "Ảnh hưởng của du lịch", "Effects of tourism", "Du lịch mang lại lợi ích và tác hại gì cho địa phương?", "What are the benefits and drawbacks of tourism for local communities?", ["Tourism brings ___ to local areas.", "It also creates ___.", "On the other hand, ___.", "In summary, ___."], ["Tourism can be a lifeline for local economies, yet it can also ___.", "Careful planning is needed to ensure that ___."]),
    t("ai-in-education", "AI trong giáo dục", "AI in education", "Trí tuệ nhân tạo có lợi và có hại gì cho việc học?", "What are the advantages and disadvantages of AI in education?", ["AI tools can help students ___.", "Teachers can use them to ___.", "However, there is a risk that ___.", "Overall, ___."], ["AI is most valuable when it supports, rather than replaces, ___.", "There is a real danger that students will ___ instead of ___."])
  ] },
  { id: "problem-solution", title: { vi: "Vấn đề & giải pháp", en: "Problems & solutions" }, words: "150–250", topics: [
    t("traffic", "Tắc đường", "Traffic jams", "Nêu nguyên nhân tắc đường ở thành phố và đề xuất giải pháp.", "Explain the causes of traffic jams in cities and suggest solutions.", ["Traffic jams are a serious problem in ___.", "One main cause is ___.", "One solution would be to ___.", "If ___, traffic would improve."], ["The problem is compounded by ___.", "No single measure will suffice; what is needed is ___."]),
    t("plastic-waste", "Rác thải nhựa", "Plastic waste", "Làm sao giảm rác thải nhựa? Nêu vấn đề và giải pháp.", "How can we reduce plastic waste? Describe the problem and solutions.", ["Plastic waste harms ___.", "This happens because ___.", "Individuals can ___.", "Governments should ___."], ["Unless producers are held accountable, ___.", "Small everyday changes, multiplied across millions of people, can ___."]),
    t("student-stress", "Áp lực học tập", "Student stress", "Nêu nguyên nhân áp lực học tập của học sinh và cách giảm bớt.", "Why are students stressed, and what can be done about it?", ["Many students feel stressed because ___.", "This can lead to ___.", "Schools could ___.", "Students themselves can ___."], ["The pressure to ___ has intensified in recent years.", "Tackling the root causes means rethinking ___."]),
    t("screen-time", "Thời gian dùng màn hình", "Too much screen time", "Trẻ em dùng màn hình quá nhiều: vấn đề và giải pháp.", "Children spend too much time on screens. Discuss the problem and solutions.", ["Children today spend ___ on screens.", "This can affect ___.", "Parents can ___.", "Schools can also ___."], ["The challenge is not screens themselves but ___.", "Setting an example is arguably more effective than ___."]),
    t("lonely-elderly", "Người già cô đơn", "Loneliness among older people", "Nhiều người già sống cô đơn. Chúng ta có thể làm gì?", "Many older people live alone and feel lonely. What can be done?", ["Many older people feel lonely because ___.", "This affects their ___.", "Communities could ___.", "Young people can help by ___."], ["Loneliness is often described as a hidden epidemic, since ___.", "Intergenerational projects have shown that ___."])
  ] },
  { id: "reviews", title: { vi: "Đánh giá & review", en: "Reviews" }, words: "100–180", topics: [
    t("review-film", "Review phim", "A film review", "Viết bài review một bộ phim bạn đã xem gần đây.", "Write a review of a film you have seen recently.", ["___ is a ___ film directed by ___.", "The story is about ___.", "The best thing about it is ___.", "I would recommend it to ___."], ["The film succeeds in ___, although it occasionally ___.", "It lingers in the mind long after ___."]),
    t("review-book", "Review sách", "A book review", "Viết bài review một cuốn sách bạn thích.", "Write a review of a book you enjoyed.", ["___ was written by ___.", "It tells the story of ___.", "I liked the way ___.", "Overall, I'd give it ___ out of five."], ["What sets this book apart is ___.", "Readers who enjoy ___ will find it hard to put down."]),
    t("review-restaurant", "Review nhà hàng / quán ăn", "A restaurant review", "Viết review một quán ăn hoặc quán cà phê bạn từng đến.", "Write a review of a restaurant or café you visited.", ["I recently visited ___.", "The food was ___.", "The service was ___.", "Prices are ___."], ["The menu offers a clever twist on ___.", "My only criticism would be ___."]),
    t("review-app", "Review ứng dụng", "An app review", "Viết review một ứng dụng bạn dùng thường xuyên.", "Write a review of an app you use often.", ["I have been using ___ for ___.", "It helps me ___.", "One problem is ___.", "I would rate it ___."], ["It is intuitive enough for beginners, yet ___.", "If the developers ___, it would be close to perfect."]),
    t("review-product", "Review sản phẩm", "A product review", "Viết review một sản phẩm bạn đã mua.", "Write a review of a product you bought.", ["I bought ___ because ___.", "It works ___.", "What I like is ___.", "However, ___."], ["For the price, it delivers far more than I expected.", "It falls short when it comes to ___."])
  ] },
  { id: "reports", title: { vi: "Báo cáo & tóm tắt", en: "Reports & summaries" }, words: "120–200", topics: [
    t("class-survey", "Báo cáo khảo sát lớp", "A class survey report", "Viết báo cáo kết quả một khảo sát nhỏ trong lớp (ví dụ về thói quen đọc sách).", "Write a report on a small class survey (e.g. reading habits).", ["The aim of this report is to ___.", "We asked ___ students about ___.", "Most students said ___.", "We recommend that ___."], ["The findings suggest a clear link between ___ and ___.", "It is worth noting that a significant minority ___."]),
    t("school-event", "Báo cáo sự kiện ở trường", "A school event report", "Viết báo cáo về một sự kiện đã diễn ra ở trường.", "Write a report about an event held at your school.", ["The event took place on ___.", "About ___ people attended.", "The most popular activity was ___.", "Next time, we should ___."], ["Overall, the event was a success, although ___.", "Feedback from participants indicated that ___."]),
    t("field-trip", "Báo cáo chuyến đi thực tế", "A field trip report", "Viết báo cáo về một chuyến đi thực tế hoặc tham quan.", "Write a report on a field trip or visit.", ["The purpose of the trip was ___.", "We visited ___.", "Students learned ___.", "I recommend that ___."], ["The trip provided a valuable opportunity to ___.", "In future, more time should be allocated to ___."]),
    t("summarise-article", "Tóm tắt một bài báo", "Summarise an article", "Tóm tắt một bài báo bạn đọc gần đây và nêu nhận xét ngắn.", "Summarise an article you read recently and add a short comment.", ["The article is about ___.", "The writer argues that ___.", "He/She gives examples such as ___.", "In my opinion, ___."], ["The central claim rests on ___, which is ___.", "While the argument is persuasive, it overlooks ___."]),
    t("improve-facility", "Đề xuất cải thiện cơ sở vật chất", "Improving a facility", "Viết báo cáo đề xuất cải thiện thư viện hoặc căng-tin trường bạn.", "Write a report suggesting improvements to your school library or canteen.", ["This report looks at ___.", "At present, ___.", "Students would like ___.", "I recommend ___."], ["Implementing these changes would not only ___ but also ___.", "Priority should be given to ___."])
  ] },
  { id: "reflection", title: { vi: "Suy ngẫm cá nhân", en: "Personal reflection" }, words: "100–180", topics: [
    t("goal-achieved", "Một mục tiêu đã đạt được", "A goal you achieved", "Viết về một mục tiêu bạn đã đạt được và bạn đã làm thế nào.", "Write about a goal you achieved and how you did it.", ["My goal was to ___.", "To achieve it, I ___.", "The hardest part was ___.", "I learned that ___."], ["There were moments when giving up seemed like the easier option.", "Achieving it gave me the confidence to ___."]),
    t("lesson-from-failure", "Bài học từ thất bại", "A lesson from failure", "Viết về một thất bại và bài học bạn rút ra.", "Write about a failure and what it taught you.", ["I once failed ___.", "At first, I felt ___.", "Then I realised ___.", "Now I ___."], ["In hindsight, the failure was a blessing in disguise.", "It forced me to confront ___."]),
    t("future-self", "Thư gửi bản thân tương lai", "A letter to your future self", "Viết lá thư gửi chính bạn 10 năm sau.", "Write a letter to yourself in ten years' time.", ["Dear future me, ___.", "Right now, I am ___.", "I hope that you ___.", "Please remember ___."], ["I wonder whether you still ___.", "Whatever you have become, I hope you have not forgotten ___."]),
    t("changed-mind", "Khi bạn thay đổi suy nghĩ", "Changing your mind", "Viết về một lần bạn thay đổi quan điểm về điều gì đó.", "Write about a time you changed your mind about something.", ["I used to think ___.", "Then I ___.", "This made me realise ___.", "Now I believe ___."], ["It took ___ to make me question what I had always assumed.", "Changing my mind was humbling, but ___."]),
    t("gratitude", "Điều bạn biết ơn", "Something you're grateful for", "Viết về một điều bạn cảm thấy biết ơn trong cuộc sống.", "Write about something you are grateful for.", ["I am grateful for ___.", "It matters to me because ___.", "Without it, ___.", "I show my thanks by ___."], ["It is easy to take ___ for granted until ___.", "Gratitude, I have found, changes the way I ___."])
  ] },
  { id: "creative", title: { vi: "Sáng tạo", en: "Creative writing" }, words: "100–200", topics: [
    t("dialogue", "Viết một đoạn hội thoại", "Write a dialogue", "Viết đoạn hội thoại giữa hai người bạn lên kế hoạch cho một chuyến đi.", "Write a dialogue between two friends planning a trip.", ["A: What do you think about going to ___?", "B: That sounds ___, but ___.", "A: How about ___ instead?", "B: OK, let's ___!"], ["A: I know it's a long shot, but hear me out.", "B: Fair enough — as long as we ___."]),
    t("diary-2050", "Nhật ký năm 2050", "A diary entry from 2050", "Viết một trang nhật ký của bạn vào năm 2050.", "Write a diary entry from the year 2050.", ["Today I woke up and ___.", "People now ___.", "The strangest thing is ___.", "I miss ___."], ["It's hard to believe that people once had to ___.", "For all the progress, some things never change: ___."]),
    t("superpower", "Nếu có siêu năng lực", "If you had a superpower", "Nếu có một siêu năng lực, bạn sẽ chọn gì và làm gì với nó?", "If you could have one superpower, what would it be and why?", ["If I had a superpower, I would choose ___.", "I would use it to ___.", "The first thing I'd do is ___.", "The only problem would be ___."], ["Tempting as ___ may be, I would choose ___ because ___.", "With such power would come the responsibility to ___."]),
    t("invent-product", "Quảng cáo một phát minh", "Advertise an invention", "Tự nghĩ ra một sản phẩm và viết quảng cáo cho nó.", "Invent a product and write an advertisement for it.", ["Introducing ___!", "It helps you ___.", "It's easy to use: just ___.", "Get yours today for only ___!"], ["Tired of ___? Say goodbye to ___ forever.", "Designed with ___ in mind, it ___."]),
    t("postcard-from-space", "Bưu thiếp từ không gian", "A postcard from space", "Viết bưu thiếp gửi gia đình từ một chuyến du lịch vũ trụ.", "Write a postcard to your family from a trip to space.", ["Greetings from ___!", "From here, the Earth looks ___.", "Every day we ___.", "I can't wait to ___."], ["Nothing prepared me for the silence of ___.", "Seeing Earth from above makes you realise how ___."])
  ] },
  { id: "academic", title: { vi: "Nghị luận học thuật", en: "Academic essays" }, words: "250+", topics: [
    t("free-university", "Đại học miễn phí", "Free university education", "Giáo dục đại học có nên miễn phí cho mọi người không?", "Should university education be free for everyone?", ["Some argue that university should be free because ___.", "Others believe that ___.", "In my view, ___.", "In conclusion, ___."], ["Although free tuition widens access, it raises the question of who ___.", "A more sustainable model might combine ___ with ___."]),
    t("arts-vs-sport", "Tiền công cho nghệ thuật hay thể thao", "Public money: arts or sport?", "Chính phủ nên ưu tiên chi tiền cho nghệ thuật hay thể thao?", "Should governments spend more on the arts or on sport?", ["Governments have limited budgets, so ___.", "Supporters of the arts argue ___.", "Sport, on the other hand, ___.", "On balance, ___."], ["Framing the issue as a choice between the two may be misleading, since ___.", "Both contribute to public well-being, albeit in different ways."]),
    t("technology-jobs", "Công nghệ và việc làm", "Technology and jobs", "Công nghệ đang tạo ra hay lấy đi nhiều việc làm hơn?", "Is technology creating more jobs than it destroys?", ["Technology has replaced many jobs such as ___.", "At the same time, it has created ___.", "The main challenge is ___.", "Therefore, ___."], ["History suggests that technological change tends to ___, at least in the long run.", "The transition, however, is rarely painless for ___."]),
    t("climate-responsibility", "Trách nhiệm với khí hậu", "Who is responsible for climate action?", "Chống biến đổi khí hậu là trách nhiệm của cá nhân hay chính phủ?", "Is tackling climate change the responsibility of individuals or governments?", ["Some people believe individuals should ___.", "Others argue that governments ___.", "I believe that ___.", "In conclusion, ___."], ["Individual choices matter, but they are shaped by systems that only governments can ___.", "Placing the burden on individuals risks ___."]),
    t("globalisation-culture", "Toàn cầu hoá và văn hoá", "Globalisation and local culture", "Toàn cầu hoá có đe doạ bản sắc văn hoá địa phương không?", "Does globalisation threaten local cultures?", ["Globalisation means ___.", "It can threaten local culture by ___.", "However, it can also ___.", "Overall, ___."], ["Culture is not static; it has always evolved through ___.", "The real risk is not change itself but ___."]),
    t("ageing-population", "Dân số già", "An ageing population", "Dân số già hoá mang lại thách thức gì và xã hội nên ứng phó ra sao?", "What challenges does an ageing population bring, and how should societies respond?", ["In many countries, people are living longer.", "This puts pressure on ___.", "One solution is to ___.", "In conclusion, ___."], ["Rather than viewing older people as a burden, societies could ___.", "Policies such as ___ could ease the strain on ___."])
  ] }
];

export function getWritingCategories(locale: Locale): WritingCategory[] {
  return categories.map((category) => ({
    id: category.id,
    title: category.title[locale],
    note: locale === "vi" ? `Độ dài gợi ý: ${category.words} từ` : `Suggested length: ${category.words} words`,
    topics: category.topics.map((topic) => ({ id: topic.id, title: topic.title[locale], prompt: topic.prompt[locale], suggestions: topic.suggestions, advanced: topic.advanced }))
  }));
}
